http4s/http4s

core/src/main/scala/org/http4s/EntityDecoder.scala, core/src/test/scala/org/http4s/EntityDecoderSpec.scala
=> Add `flatMapR` method to EntityDecoder

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala, argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala, core/src/main/scala/org/http4s/EntityDecoder.scala, core/src/main/scala/org/http4s/Message.scala, core/src/test/scala/org/http4s/EntityDecoderSpec.scala, examples/src/main/scala/com/example/http4s/ExampleService.scala, examples/src/main/scala/com/example/http4s/ScienceExperiments.scala, scala-xml/src/main/scala/scalaxml/ElemInstances.scala, scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala, server/src/test/scala/org/http4s/server/middleware/EntityLimiterSpec.scala
=> Add entity codec instances for Argonaut codecs.

core/src/main/scala/org/http4s/QueryParam.scala, core/src/test/scala/org/http4s/QueryParamCodecSpec.scala, core/src/test/scala/org/http4s/UriSpec.scala
issue #187
It can cause problems with Strings
=> Remove Char QueryParamEncoder

blaze-core/src/main/scala/org/http4s/blaze/Http1Stage.scala
The old method would build up a 'linked list of Promises' on a long body, which can cause problems for really long messages.
It may be worth it to shutdown the stage after dumping a certain amount of body.
=> blaze Http1Stage drainBody rework

build.sbt, examples/blaze/examples-blaze.sbt, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/ClientExample.scala, src/jekyll/index.md
The client seems to be popular, and we should probably add some info on how to use it.
=> Add client example to project and to site

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
Trivial fix. This is my first PR, so let me know if I should be doing anything differently. :)
=> Use created `threadPool` in `JettyBuilder`.

README.md
I also think we should advertise gitter while maintaining the irc as a
'scratch pad' for off topic/tangential discussion.
=> These are popular

core/src/main/scala/org/http4s/StaticFile.scala
=> Alter StaticFile.fromURL so it doesn't rely on StaticFile.fromFile. 

core/src/main/scala/org/http4s/headers/Allow.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala, core/src/main/scala/org/http4s/util/Renderable.scala, core/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
Also fixed a bug in ```Writer.addStrings```
=> Add an Allow header and parser.

blaze-server/src/test/scala/org/http4s/server/blaze/Http4sHttp1ServerStageSpec.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala, examples/src/main/scala/com/example/http4s/ExampleService.scala, examples/src/main/scala/com/example/http4s/ScienceExperiments.scala, project/Http4sBuild.scala
=> Upgrade to scalaz-stream-0.7a.

.gitignore, blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala, blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
This fixes it against master. I'm happy to write one for the 0.6.x branch if needed.
=> Issue 240 fix host header handling

core/src/main/scala/org/http4s/headers/User-Agent.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala, core/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
=> Add User-Agent header type and parser

build.sbt, load-test/load-test.sbt, load-test/src/test/scala/org/http4s/load/DemoSimulation.scala, project/Http4sBuild.scala, project/plugins.sbt
load test can be run with:
```
sbt
project load-test
gatling:testOnly org.http4s.load.DemoSimulation
```
html report is output at load-test/target/gatling
=> add load-test module

server/src/main/scala/org/http4s/server/middleware/CORS.scala, server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala
This starts to address issue #218
@rossabaker please help me clean this up a bit.
=> Implement CORS middleware

dsl/src/main/scala/org/http4s/dsl/package.scala, examples/src/main/scala/com/example/http4s/ExampleService.scala
It was endinging ResponseGenerator instead of EmptyResponseGenerator
see comment by @chris-martin in issue #234
=> Fix the MethodNotAllowed response generator in dsl

dsl/src/main/scala/org/http4s/dsl/Path.scala, dsl/src/test/scala/org/http4s/dsl/PathInHttpServiceSpec.scala
This will allow applicative processing of parameters wihtin services. In
particular, this allows graceful handling of missing or invalid
parameter values.
=> Add QueryParamMatcher that returns ValidationNel

CHANGELOG.md
I hope to do a 0.7.0 release today. Is anything significant missing from the change log?
=> Update changelog in prep for 0.7.0 release

core/src/main/scala/org/http4s/parser/AuthorizationHeader.scala, core/src/test/scala/org/http4s/parser/AuthorizationHeaderSpec.scala
Closes #226 
Thanks @toby5box for the bug report.
=> Fix Oauth2 Authorization header parser

core/src/main/scala/org/http4s/HeaderKey.scala, core/src/main/scala/org/http4s/Headers.scala
Make a few things final and cleanup the way headers are found from ````Headers````.
Closes #222
=> Small cleanup of HeaderKey and Headers

core/src/main/scala/org/http4s/UrlForm.scala
Also dry out the last phase, conversion of the sequence of pairs to a 'multimap'.
=> Make UrlForm.decodeString public

core/src/main/scala/org/http4s/StaticFile.scala, core/src/main/scala/org/http4s/headers/Content-Range.scala, server/src/main/scala/org/http4s/server/staticcontent/FileService.scala, server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala, server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala, server/src/main/scala/org/http4s/server/staticcontent/package.scala, server/src/test/resources/testresource.txt, server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/ResourceServiceSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/StaticContentShared.scala
the server package `staticcontent` provides some tools for serving up
static content from either a resource or from a file.
* Configuration allows for caching (only one very basic example right now).
* Some support for Range headers.
=> Add support of static content

jetty/src/main/java/org/http4s/server/jetty/InstrumentedHandler.java, jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
=> Use patched InstrumentedHandler for Jetty.

server/src/main/scala/org/http4s/server/staticcontent/CacheStrategy.scala, server/src/main/scala/org/http4s/server/staticcontent/FileService.scala, server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala, server/src/main/scala/org/http4s/server/staticcontent/NoopCacheStrategy.scala, server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala, server/src/main/scala/org/http4s/server/staticcontent/package.scala
* Moved some of the CacheStrategy types into their own file
* Added lots of doc strings
* Used a ConcurrentHashMap instead of synchronizing on a HashMap
This PR should be binary compatible.
This PR also represents a conscious effort to do a better job documenting things.
=> Cleanup staticcontent package

src/jekyll/_layouts/default.html
=> Update the links to the scaladocs

server/src/main/scala/org/http4s/server/middleware/GZip.scala
=> Honor the buffer size in gzip middleware; use streamz's default.

examples/src/main/scala/com/example/http4s/ScienceExperiments.scala, servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
=> Handle service exceptions in servlet backends.

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
closes #338
URITranslation is an ineffective strategy for mouting in blaze.
Allow fall through behavior by making sure we got a result.
This is not automatically tested and hopefully will be addressed by issue #342.
=> Fix blaze mount problem

server/src/main/scala/org/http4s/server/middleware/CORS.scala
Here is the CORS change on the release branch
=> Do not apply CORS headers and inform of unsuccessful responses

server/src/main/scala/org/http4s/server/package.scala
=> Add Service.const and allow lifting of Option[Task[B]] into PartialService

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
Before this commit, all ParserExceptions were considerd 'BadRequest' which is not actually true. This PR fixes that behavior and consolidates code for rendering InternalServerError responses at the blaze level.
=> Cleanup some exception handling in Http1ServerStage

build.sbt, client/src/main/scala/org/http4s/client/oauth1/oauth1.scala, core/src/main/scala/org/http4s/Credentials.scala, project/Http4sBuild.scala
I love it when we can drop a dependency.
=> Remove iharder base64 in favor of java8 base64

.travis.yml
=> Explicitly pull sbt-launcher to work around Travis issue.

core/src/main/scala/org/http4s/Message.scala, server/src/main/scala/org/http4s/server/middleware/VirtualHost.scala, server/src/test/scala/org/http4s/server/middleware/VirtualHostSpec.scala
Enables mounting multiple websites on the same server.
=> Add a Virtual Host middleware

blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
Some of these tests were failing on travis sporadically, likely due to unnecessarily strict timeouts. The timeouts have been increased to much longer time, but not infinite just in case the backend fails and we don't want to wait forever.
Also cleaned up some redundent objects.
=> Don't use a short duration on tests that don't test timeout

core/src/main/scala/org/http4s/Uri.scala, core/src/test/scala/org/http4s/UriSpec.scala
I find this one kind of useful
=> add / method on Uri

build.sbt, docs/src/jekyll/index.md, docs/src/test/scala/org/http4s/docs/AsynchronousExample.scala, docs/src/test/scala/org/http4s/docs/CompositionExample.scala
This may be replaced by rossabakers 'Tut' work. On the other hand, maybe not.
=> Require the examples on the site to compile

core/src/main/scala/org/http4s/StaticFile.scala
call with f.isFile before require
=> Optimizes #380 by replacing redundant f.exists()

jetty/src/main/scala/org/http4s/server/jetty/InstrumentedConnectionFactory.scala, jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
=> Work around metrics incompatibility with Jetty 9.3.

examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala, examples/src/main/scala/com/example/http4s/ExampleService.scala, examples/src/main/twirl/com/example/http4s/index.scala.html
* little fixes which was intruded in http4s/http4s@7c55dc4b04c75a40
* remove link 'short-sum' - endpoint was removed
* update digest link - endpoint is now '/auth/protected'
* fix metrics endpoint - add missing slash
* fix spelling
* fix comment
=> fix examples

CHANGELOG.md, blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientReceiver.scala, blaze-core/src/main/scala/org/http4s/blaze/util/ProcessWriter.scala, blaze-core/src/test/scala/org/http4s/blaze/TestHead.scala
These commits could use a review, then a release, and then they should be merged into master and cherry picked into 0.8.x for a release.
cc @dchenbecker @jdegoes
=> Release 0.9.3

.gitignore, server/src/main/scala/org/http4s/server/Fallthrough.scala, server/src/main/scala/org/http4s/server/Router.scala, server/src/main/scala/org/http4s/server/package.scala, server/src/main/scala/org/http4s/server/staticcontent/FileService.scala, server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala, server/src/main/scala/org/http4s/server/staticcontent/package.scala, server/src/main/scala/org/http4s/server/syntax/Service.scala, server/src/test/scala/org/http4s/server/HttpServiceSpec.scala, server/src/test/scala/org/http4s/server/RouterSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/ResourceServiceSpec.scala
A work in progress; servers need to be aware of the fallthrough just like bryce's take.
=> Present the Fallthrough typeclass as an alternative to PartialService

build.sbt
I'm tired of having to restart sbt every time I want to try something new.
=> Add sbt revolver settings to the blaze examples

server/src/main/scala/org/http4s/server/middleware/CORS.scala
resolves #421
retarget of #422 to `release-0.10.1`
=> CORS: comma delimit Access-Control-Allow-Methods header values

server/src/main/scala/org/http4s/server/Fallthrough.scala, server/src/main/scala/org/http4s/server/package.scala, server/src/test/scala/org/http4s/server/HttpServiceSpec.scala, server/src/test/scala/org/http4s/server/RouterSpec.scala
I believe this addresses #416. It attempts to address the shortcomings of PR #418.
=> Modify default 'fallthrough' behavior.

core/src/main/scala/org/http4s/StaticFile.scala, core/src/test/scala/org/http4s/StaticFileSpec.scala
=> StaticFile.fromFile — handle empty file

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala, blaze-client/src/main/scala/org/http4s/client/blaze/PooledHttp1Client.scala, blaze-client/src/main/scala/org/http4s/client/blaze/SimpleHttp1Client.scala
issue #432
This is useful for self signed certificates.
Authentication is enabled by default.
=> Add ability to disable enpoint authentication

docs/src/jekyll/_layouts/default.html
=> Fix site links to API docs

build.sbt
=> Add source links to generated scaladocs

build.sbt, jetty/src/test/scala/org/http4s/server/jetty/Issue454.scala, servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
=> Await last write before completing the async context.

project/Http4sBuild.scala
This resolves an eviction notice with scalaz-stream-0.7.
=> Upgrade jawn-streamz to 0.6.0.

blaze-client/src/main/scala/org/http4s/client/blaze/ClientTimeoutStage.scala, blaze-core/src/test/scala/org/http4s/blaze/TestHead.scala
Problem: When a client timeouts, the tail stage (the parser) will receive a TimeoutException, as it should. The problem is that the Exception is then pushed out to the head stage making a lot of noise along the way.
Solution: The ClientTimeoutStage should inspect outbound Error commands for a TimeoutException that it has generated and swallow it, sending a Disconnect command instead to sanely shutdown the pipeline.
=> ClientTimeoutStage will swallow its own TimeoutException's

servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
Closes #459
Classic stack unsafe scalaz.concurrent.Task.async bug.
=> Fix stack safety issue on servlet asyncIO.

blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala
TimeoutException's currently make a lot of noise. This PR attempts to filter them out from the logger process on the blaze-client as they will already be logged.
=> Clean out some noise from TimeoutException's

servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
=> Log an error message if packets are dropped

blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
closes #484
Problem: Spec "Handle routes that ignores the body for non-chunked" didn't actually ignore its body: it echoed it. Test "Handle routes that consumes the full request body for non-chunked" echoed the body, it did not consume it.
Solution: One test was repurposed and the other renamed to be more clear about what it does.
=> Replace duplicate test and bring test behavior more in line with its title

core/src/main/scala/org/http4s/Query.scala, core/src/test/scala/org/http4s/QuerySpec.scala, core/src/test/scala/org/http4s/TestInstances.scala, core/src/test/scala/org/http4s/UriSpec.scala
=> Encode query keys.

CONTRIBUTING.md, docs/src/jekyll/community.md, docs/src/jekyll/conduct.md
This proposal is not in response to any incident.  Our community has a track record of being kind and civil, and I'm proud of that.  However, the time has come:
1. We are growing, and we should be prepared for the growing pains.
2. We don't know who might have been reluctant to contribute in the past for lack of an explicit policy.
=> Establish the http4s Code of Conduct.

client/src/main/scala/org/http4s/client/Client.scala, core/src/main/scala/org/http4s/MediaType.scala, core/src/main/scala/org/http4s/headers/Accept.scala, core/src/main/scala/org/http4s/parser/AcceptHeader.scala, core/src/test/scala/org/http4s/parser/AcceptHeaderSpec.scala, core/src/test/scala/org/http4s/parser/MediaRangeSpec.scala, dsl/src/test/scala/org/http4s/dsl/ResponseGeneratorSpec.scala
Not finished, still a few failing tests, but posting to get early feedback
=> [SI-527] Remove QValue from MediaRange and MediaType

project/build.properties
For an undiagnosed reason I was getting this error attempting to start `sbt` with a pristine copy of `http4s` on the master branch:
```
/Users/JR/Dropbox/http4s/build.sbt:414: error: not found: value specs2Core
specs2Core,
^
/Users/JR/Dropbox/http4s/build.sbt:36: error: not found: value macroParadiseSetting
macroParadiseSetting
^
/Users/JR/Dropbox/http4s/build.sbt:132: error: value argonaut is not a member of object Http4sBuild
Http4sBuild.argonaut,
^
/Users/JR/Dropbox/http4s/build.sbt:253: error: not found: value circeGeneric
circeGeneric,
^
/Users/JR/Dropbox/http4s/build.sbt:267: error: not found: value macroParadiseSetting
macroParadiseSetting,
^
sbt.compiler.EvalException: Type error in expression
at sbt.compiler.Eval.checkError(Eval.scala:384)
at …
```
=> Upgrade sbt to 0.13.11

bin/travis, build.sbt, project/Http4sBuild.scala, project/plugins.sbt
If this helps identify areas of the code that need more attention, great.  If not, 100% of our money back.
Disclaimers:
* We prefer types to tests where possible.
* This is a tool, not a cudgel.
Fixes #62.
=> Create and publish scoverage reports

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala, client/src/main/scala/org/http4s/client/BasicManager.scala, client/src/main/scala/org/http4s/client/ConnectionManager.scala, client/src/main/scala/org/http4s/client/PoolManager.scala
Closes #571
Otherwise we have an infinite loop for a connection that never connects.
This was quick so take a careful look before merging. That said, it was pretty simple.
=> Add mechanism to force a fresh connection

blaze-core/src/main/scala/org/http4s/blaze/util/Http2Writer.scala, blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala, project/Http4sBuild.scala
Hopefully this is over with for now.
I'll merge this sooner than later if nobody objects: it shouldn't be controversial and the build is currently broken without it.
=> Fix the build from blaze-snapshot changes.

bin/travis, build.sbt, project/Http4sBuild.scala, project/plugins.sbt
Bonus fix: run report against the correct Scalaz cross build.
=> Fix MiMa reports for Java8 binaries.

README.md, docs/src/site/_layouts/default.html, docs/src/site/community/index.md, docs/src/site/index.md
* Replaces our code of conduct with theirs to reduce copypasta.
* Mention the new affiliation in the README and various points of the
site.
=> Joining Typelevel as an incubator project

core/src/main/scala/org/http4s/MessageFailure.scala, core/src/test/scala/org/http4s/EntityDecoderSpec.scala
I don't know if the test code can be simplified but hopefully it shows what's the intention with this feature.
cc @rossabaker
=> Added the possibility to specify custom responses to MessageBodyFailures

codecov.yml
I want codecov for advice, not for another hoop all commits must jump through.
=> Make codecov a little less scolding

dsl/src/main/scala/org/http4s/dsl/Path.scala, dsl/src/test/scala/org/http4s/dsl/PathSpec.scala
Was this working as intended and perhaps poorly documented or is this PR a bugfix?
=> The Path extractor for Long now supports negative numbers

core/src/main/scala/org/http4s/Status.scala
=> pass the reason string when setting the Status for a successful ParseResult

CHANGELOG.md, blaze-core/src/main/scala/org/http4s/blaze/util/ChunkProcessWriter.scala, blaze-core/src/main/scala/org/http4s/blaze/util/IdentityWriter.scala, build.sbt, core/src/main/scala/org/http4s/EntityEncoder.scala, core/src/main/scala/org/http4s/multipart/MultipartParser.scala, core/src/main/scala/org/http4s/util/package.scala, project/Http4sBuild.scala, server/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
This will bring in scodec-bits-1.1, and make us compatible with
remotely again.
Fixes #632
=> Upgrade to scalaz-stream-0.8.2

docs/src/main/tut/dsl.md
Change referenced in issue [#649](https://github.com/http4s/http4s/issues/649)
=> Add Testing Section to dsl.md

blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala, blaze-client/src/test/scala/org/http4s/client/blaze/ExternalBlazeHttp1ClientSpec.scala, blaze-core/src/main/scala/org/http4s/blaze/Http1Stage.scala, blaze-core/src/main/scala/org/http4s/blaze/util/BodylessWriter.scala, blaze-core/src/main/scala/org/http4s/blaze/util/ProcessWriter.scala, blaze-core/src/test/scala/org/http4s/blaze/util/DumpingWriter.scala, blaze-core/src/test/scala/org/http4s/blaze/util/ProcessWriterSpec.scala, client/src/main/scala/org/http4s/client/middleware/Retry.scala, client/src/test/scala/org/http4s/client/middleware/RetrySpec.scala, core/src/main/scala/org/http4s/DecodeResult.scala, core/src/main/scala/org/http4s/EntityDecoder.scala, core/src/main/scala/org/http4s/StaticFile.scala, core/src/main/scala/org/http4s/package.scala, core/src/main/scala/org/http4s/util/CaseInsensitiveString.scala, core/src/main/scala/org/http4s/util/String.scala, core/src/main/scala/org/http4s/util/option.scala
These are uninteresting cleanups that came out of experimentation on #390.  Separated out, as they're all anticipated to be uncontroversial and positive.
=> Miscellaneous, boring cleanups

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
Create the SSL engine with the peer host and peer port info, to "provide
hints for internal session reuse strategy," regardless of whether
endpoint authentication is enabled.
In so doing, we eliminate a case.
=> Simplify creation of SSLEngine in blaze-client

.travis.yml, bin/publish, project/Http4sBuild.scala
=> Dependency patch upgrades in advance of 0.14.3 release

codecov.yml, project/build.properties
Bonus: this one is actually valid.
=> Reconfigure codecov

core/src/main/scala/org/http4s/headers/X-B3-Flags.scala, core/src/main/scala/org/http4s/headers/X-B3-ParentSpanId.scala, core/src/main/scala/org/http4s/headers/X-B3-Sampled.scala, core/src/main/scala/org/http4s/headers/X-B3-SpanId.scala, core/src/main/scala/org/http4s/headers/X-B3-TraceId.scala, core/src/main/scala/org/http4s/headers/package.scala, core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala, core/src/main/scala/org/http4s/parser/ZipkinHeader.scala, core/src/test/scala/org/http4s/TestInstances.scala, core/src/test/scala/org/http4s/headers/ZipkinHeaderSpec.scala
@rossabaker - adds parsers for Zipkin headers
=> add zipkin headers

dsl/src/main/scala/org/http4s/dsl/Path.scala, dsl/src/test/scala/org/http4s/dsl/PathSpec.scala
Thanks to @dbousamra for reporting this.
=> Fix tail of empty list in /: extractor

core/src/main/scala/org/http4s/Fallthrough.scala, core/src/main/scala/org/http4s/Service.scala
This changed in master, but I'd rather not mislead people now.
=> Fix some incorrect scaladoc

server/src/main/scala/org/http4s/server/middleware/Metrics.scala
These happen in HEAD requests.
/cc @sgalkin-zenefits
=> Don't treat Killed responses as abnormal termination

build.sbt
See scoverage/sbt-coverage#153.
=> Don't include scoverage dependencies in POM

core/src/main/scala/org/http4s/util/UrlCoding.scala, core/src/test/scala/org/http4s/util/UrlCodingSpec.scala
=> Don't uppercase hex digits after encoded '%'

server/src/main/scala/org/http4s/server/middleware/Timeout.scala
This is an attempt to fix #726.
=> Allow custom scheduler for timeout middleware

circe/src/test/scala/org/http4s/circe/CirceSpec.scala, core/src/test/scala/org/http4s/EntityEncoderSpec.scala, project/Http4sBuild.scala
For some reason the `beRight` matcher didn't work.
Part of #661
=> Port Circe module to fs2

json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala, json4s/src/test/scala/org/http4s/json4s/Json4sSpec.scala, project/Http4sBuild.scala
json4s, json4s-jackson and json4s-native all compiles and tests with cats/fs2.
Part of #661
=> Port json4s module to fs2

twirl/src/test/scala/org/http4s/twirl/TwirlSpec.scala
=> Port twirl module to fs2

core/src/test/scala/org/http4s/EntityEncoderSpec.scala, scala-xml/src/main/scala/scalaxml/ElemInstances.scala, scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala
=> Port scala-xml module to fs2

project/plugins.sbt
This should resolve the ArrayIndexOutOfBoundsExceptions on Travis.
=> Upgrade sbt-mima-plugin

argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala, build.sbt, core/src/test/scala/org/http4s/EntityEncoderSpec.scala, project/Http4sBuild.scala
=> Port Argonaut module to fs2

build.sbt, project/build.properties
Bump version and fix deprecation warnings.
=> Update sbt to 0.13.13

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala, jetty/src/test/scala/org/http4s/server/jetty/Issue454.scala, servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala, servlet/src/main/scala/org/http4s/servlet/ServletIo.scala, servlet/src/main/scala/org/http4s/servlet/package.scala, servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala, tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
Ports the servlet, tomcat and jetty modules to fs2/cats.
The modules compile and the tests pass, but there a few `TODO fs2 port` in there.
Part of #661
=> More fs2/cats porting

docs/src/main/tut/client.md, docs/src/main/tut/dsl.md, docs/src/main/tut/entity.md, docs/src/main/tut/index.md, docs/src/main/tut/service.md
=> Documentation on client and EntityDecoder/Encoder

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala, argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala, circe/src/main/scala/org/http4s/circe/CirceInstances.scala, circe/src/test/scala/org/http4s/circe/CirceSpec.scala, docs/src/main/tut/index.md, docs/src/main/tut/uri.md, json4s-native/src/main/scala/org/http4s/json4s/native/Json4sNativeInstances.scala, json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala, json4s/src/test/scala/org/http4s/json4s/Json4sSpec.scala
Extends #768 with the missing circe and json4s implementations.
=> Uri parsing connectors

testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala, tests/src/test/scala/org/http4s/UriSpec.scala
The pending test in UriSpec is a separate issue, but no longer throws an
exception.
=> timesBetween needs to be a Monoid, because it can make empty lists

.travis.yml, build.sbt
=> scala 2.12.1, scalaz-7.2.8

core/src/main/scala/org/http4s/package.scala
Update javadoc on `AuthedService.empty`. Part 1/2 for #808.
=> Documentation Fix

core/src/main/scala/org/http4s/package.scala
empty defined with the wrong type (`HttpService`); updated to `AuthedService[T]`. Part 2/2 for #808.
=> `AuthedService.empty` Update

docs/src/hugo/layouts/partials/nav.html
Github link was linking to twitter instead.
=> Corrected github link.

docs/src/main/tut/auth.md, docs/src/main/tut/client.md, docs/src/main/tut/entity.md, docs/src/main/tut/index.md, docs/src/main/tut/json.md, docs/src/main/tut/service.md, docs/src/main/tut/static.md, docs/src/main/tut/streaming.md, docs/src/main/tut/uri.md
Updated links to new document format and scaladoc location.
=> Fix markdown links

docs/src/main/tut/dsl.md, docs/src/main/tut/entity.md, docs/src/main/tut/middleware.md, docs/src/main/tut/streaming.md
Fixed a few missing links and changed some wording.
Also, my editor removed some whitespace.
=> Documentation Changes

server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala
Hi, I've had a crack at porting server-metrics over to fs2. The changes don't seem to be too difficult. I noticed that there was a comment regarding `onHalt` behaviour but I think `onError` handles the case that we want to use. It also didn't seem necessary to update the request body as it didn't seem to need any modifications.
Please let me know if there's anything that doesn't look right, or if the changes don't look correct.
=> Update server-metrics to use fs2

build.sbt
for compatibility with the 2.13 community build (yes, there already
is one!)
=> tweak build to support Scala 2.13

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala, examples/src/main/scala/com/example/http4s/ssl/SslExample.scala, jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala, server/src/main/scala/org/http4s/server/ServerBuilder.scala, server/src/main/scala/org/http4s/server/package.scala, tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
Please advise on formatting rules. I notice some whitespace moving around. Tried to keep IntelliJ from wreaking too much havoc on the current layout but some snuck in anyhow.
=> Allow Blaze & Jetty to be configured with custom SSLContext

docs/src/main/tut/client.md, docs/src/main/tut/cors.md, docs/src/main/tut/dsl.md, docs/src/main/tut/entity.md, docs/src/main/tut/gzip.md, docs/src/main/tut/json.md, docs/src/main/tut/middleware.md
Updates tut Documentation for Scalaz 7.2. 
Partial coverage of #829
=> Transfer Documentation to unsafePerformSync

client/src/main/scala/org/http4s/client/Client.scala
Something I just came across. Renames method _interruptable_ to _interruptible_
=> Small typo fix

docs/src/hugo/content/versions.md
Becomes true after #879 gets merged.
=> List 0.16 snapshots, including cats

core/src/main/scala/org/http4s/EntityEncoder.scala, core/src/main/scala/org/http4s/ServerSentEvent.scala, core/src/main/scala/org/http4s/package.scala, testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala, tests/src/test/scala/org/http4s/ServerSentEventSpec.scala
I kept the code close to the scalaz-stream version so the diffs should be easy to review. fixes #872
=> port SSE support to cats/fs2

core/src/main/scala/org/http4s/EntityEncoder.scala
Looking through the code i found this funny comment and thought i give it a try :smile:
=> simplify sourceEncoder.toEntity

core/src/main/scala/org/http4s/StaticFile.scala, tests/src/test/scala/org/http4s/StaticFileSpec.scala
This is my attempt to port `StaticFile.fileToBody` to fs2. The solution is closely based on `fs2` code to read files, adapted to read portion of files
The test suite has been expanded to cover some extra cases and to ensure the fs2-based solution is correct
Fixes #886
=> StaticFile.fileToBody

client/src/main/scala/org/http4s/client/ConnectionManager.scala, client/src/main/scala/org/http4s/client/PoolManager.scala
Just a basic reimplementation of the PoolManager. Lots of internal cheating(unsafeRun), but no more than before.
=> Basic Reimplementation of PoolManager

core/src/main/scala/org/http4s/util/CaseInsensitiveString.scala, testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala, tests/src/test/scala/org/http4s/util/CaseInsensitiveStringSpec.scala
- no more lazy folded form
- record hash code in a var, similar to our optimistic scheme for parsed headers
- provide all the right Scalaz instances
- for giggles, make it as StringLike as we can
=> CaseInsensitiveString improvements

build.sbt
Cargoculted from the parboiled2 build.
=> Filter duplicate entries in scaladoc jar

build.sbt, docs/src/main/tut/json.md, project/Http4sBuild.scala
This should improve the reliability of Travis.
Fixes #817
=> Remove Github API dependency in JSON tut

CONTRIBUTING.md
Fixed a couple markdown links and trimmed a few more words
to make things a bit less wordy.
=> Minor improvements to contributors guide

build.sbt, docs/src/main/tut/json.md, project/Http4sBuild.scala
Merges #936 Changes into Master Branch.
=> Merge release-0.15.x to Master - 2

docs/src/hugo/content/adopters.md
A simple demo app (http4s, argonaut, doobie)
=> Add 0x7e.xyz

.travis.yml, build.sbt
Master got this change as some point but cats missed out.
=> Cats - Updated Scala Version in Travis to 2.12.1

docs/src/main/tut/static.md, server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala, server/src/main/scala/org/http4s/server/staticcontent/package.scala, server/src/test/resources/META-INF/resources/webjars/test-lib/1.0.0/sub/testresource.txt, server/src/test/resources/META-INF/resources/webjars/test-lib/1.0.0/testresource.txt, server/src/test/scala/org/http4s/server/staticcontent/StaticContentShared.scala, server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceFilterSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceSpec.scala
Here's my implementation for the Webjar support  (#959) - let me know what you think!
=> Fix #959 - Add Webjar support

CONTRIBUTING.md
- ~~Cut some of the fluff.~~
- ~~Get branching strategy up near the top.~~
- Make plea for more public adopters.  I know you're out there.
=> Refactor the contributing guide

.travis.yml
This one lints.  Maybe it even works.
=> Fix the Travis-Gitter integration

core/src/main/scala/org/http4s/headers/Retry-After.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala, core/src/main/scala/org/http4s/util/Renderable.scala, testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala, tests/src/test/scala/org/http4s/headers/RetryAfterSpec.scala
=> Implement Retry-After Header

bin/travis
=> Check TRAVIS_REPO_SLUG is correct when publishing

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
Yeah, let's just put this behind us...
=> Fix Server Default to Run As Daemon Threads

build.sbt
Unique Publish to not override master docs.
=> Update build.sbt with unique publish for cats

bin/travis
Should be good for a merge train.
=> Added Cats Branch to Travis Publish

docs/src/hugo/content/versions.md, docs/src/hugo/layouts/index.html, docs/src/hugo/layouts/partials/head.html, docs/src/hugo/layouts/partials/nav-docs.html, docs/src/hugo/layouts/partials/nav.html, docs/src/hugo/layouts/single.html
So I yanked all of these over. I believe everything looks in order.
=> 0.15.x menu updates

docs/src/hugo/content/versions.md
Looks right to me. Targets 0.15.x Adds the new `0.16` and updates to `0.15.6`
=> Retarget - Add 0.15.6[a]

bin/travis, build.sbt
Was looking for a SCALAZ_VERSION to publish. I believe this should get it to actually publish.
=> Cats Site Mappings

docs/src/hugo/content/versions.md
We can bounce this forward and remove our duplicates.
=> Fixed Duplicate Cats Version

project/Http4sGhPages.scala
Fixes #1023.  This is the one-line band-aid in lieu of a more proper fix via #972.
=> Don't clobber master documentation when publishing cats

docs/src/main/tut/service.md
for better discovery chance by search
=> chained -> combined

README.md
I couldn't decide on a good spot for it previously, because the logo they sent me was really big compared to anything else we had up.  And then I forgot.  Proposing this for now (copied from fs2), and am fine with alternatives.
=> Finally moving on open-source YourKit license

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
More is coming, but this cleans things up a bit in a compatible manner.
=> Refactor creation of blaze servers

docs/src/hugo/layouts/partials/nav-docs.html
Things like this happen on airplanes.
=> Update versions in nav dropdown

bin/travis
=> Build 0.15 docs from Scala 2.12

build.sbt, project/Http4sGhPages.scala
Fixes the 0.17 problems of #1061
=> Publish cats scaladoc without the -cats suffix

core/src/main/scala/org/http4s/headers/Referer.scala, core/src/main/scala/org/http4s/parser/Http4sHeaderParser.scala, core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala, core/src/main/scala/org/http4s/parser/LocationHeader.scala, core/src/main/scala/org/http4s/parser/RefererHeader.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala, core/src/main/scala/org/http4s/parser/UriHeaderParser.scala, tests/src/test/scala/org/http4s/headers/RefererSpec.scala, tests/src/test/scala/org/http4s/parser/LocationHeaderSpec.scala
This PR implements the `Referer` header and abstracts some common code for `Uri1` parsing used by `Location`
=> Referer header

build.sbt, core/src/main/scala/org/http4s/util/StreamApp.scala, docs/src/main/tut/client.md, docs/src/main/tut/service.md, docs/src/main/tut/streaming.md, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala, examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala, examples/src/main/scala/com/example/http4s/ssl/SslExample.scala, examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala, server/src/main/scala/org/http4s/server/Server.scala, server/src/main/scala/org/http4s/server/ServerApp.scala, server/src/main/scala/org/http4s/server/ServerBuilder.scala
This one got a little chewier than most merges, so I'm putting it through review.
=> Merge #1068 to cats

CHANGELOG.md, server/src/main/scala/org/http4s/server/ServerApp.scala
=> Terminate ServerApp when the server fails to start up

.travis.yml, CHANGELOG.md, project/Http4sBuild.scala
* async-http-client-2.0.31
* jetty-9.3.18.v20170406
* json4s-3.5.1
* metrics-core-3.1.4
* scalacheck-1.13.5
* scalaz-7.1.12 or scalaz-7.2.10
* tomcat-8.0.43
=> As long as we're here, let's upgrade some dependencies

CONTRIBUTING.md
=> add markdown link for the release-0.16.x branch

project/Http4sPlugin.scala
=> Upgrade Tomcat Version to 8.5.13

tests/src/test/scala/org/http4s/util/ProcessAppSpec.scala
Small Testing Suite. Pulling against current release-0.16 and will rebase once the fixes have been incorporated for compliance.
=> ProcessApp Tests

server/src/main/scala/org/http4s/server/middleware/Timeout.scala, server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
* Simplified the way timeout responses are generated.  Uses `Task.schedule` instead of `task.after`, because the latter doesn't pass along the provided scheduler.
* Asserts that the service response gets a chance to clean up even if it loses
* Documents that this happens
* Removes `Thread.sleep` in the specs, which can't be healthy for Travis
* Reduces some timeouts to make this spec run faster.  If we start to see intermittent issues in Travis, like #1098, we should turn this back up.
=> Clean up timeout scaladoc and spec

CHANGELOG.md, blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
=> Set secure request attribute correctly in blaze-server

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
Suggested by @bfritz in #1106.
=> Update HTTP/2 fallback warning

server/src/test/scala/org/http4s/server/middleware/authentication/AuthMiddlewareSpec.scala
For what is worth this is a small test to verify that `AuthMiddleware` behaves correctly when another type of error is produced, e.g. method incorrect
=> Check for AuthMiddleware behavior on non-auth errors

server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala, server/src/test/scala/org/http4s/server/staticcontent/ResourceServiceSpec.scala
=> Make ResourceService respect If-Modified-Since (0.15)

build.sbt, docs/src/main/tut/methods.md, docs/src/main/tut/verbs.md
=> Added Service example with a few different verbs

CHANGELOG.md, core/src/main/scala/org/http4s/util/ProcessApp.scala, docs/src/main/tut/service.md, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala, examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala, examples/src/main/scala/com/example/http4s/ssl/SslExample.scala, examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala, tests/src/test/scala/org/http4s/util/ProcessAppSpec.scala
=> Exit with -1 when a ProcessApp fails

docs/src/main/tut/index.md
This one compiles.  See http4s/http4s.g8#15.
Fixes #1117.
=> Use 0.17 branch of g8 template in 0.17

docs/src/main/tut/methods.md
Addresses the build failure in https://travis-ci.org/http4s/http4s/jobs/223382540.
=> Stand back. I ran tut in my head.

circe/src/main/scala/org/http4s/circe/CirceInstances.scala
=> Circe EntityEncoder without intermediate String allocation

blaze-core/src/main/scala/org/http4s/blaze/websocket/Http4sWSStage.scala, blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala, blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketSupport.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala, server/src/main/scala/org/http4s/server/websocket/package.scala
This has been a long time in the oven being a lot harder for me as I had anticipated. I started with the example and worked my way back porting `Http4sWSStage`
Still I'm a bit unsure about some of the details and added some **RFC** (Request for comment) entries in the code
I'd like at some moment to add unit tests as test were done manually using `wscat`
Fixes #868
=> Port websockets support to fs2-cats

CHANGELOG.md, project/Http4sPlugin.scala
Too new for 0.15.x, ready for 0.16.0-M2.
=> Upgrade to jetty-9.4.4 and tomcat-8.5.14

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
Should fix compile on master branch after #1146 and #1151 collided during merge.
=> fix AHC imports after `org.http4s.batteries` removed

build.sbt
Link to different branches from scaladoc source links
If the current git commit has a tag, link to the git tag of the current version.
If the current git commit has no tag and the current branch is master, link to the master branch.
If the current git commit has no tag and the current branch is not master, link to the current git commit.
Inspired by https://github.com/typelevel/cats-effect/blob/master/build.sbt#L35-L40
=> Update scaladoc source links

project/Http4sBuild.scala
If at first you fail to patch the code from the hot tub, increase the font size and try again.
=> Upgrade blaze

docs/src/main/tut/index.md
Fixes #1169 
If you could confirm that this is the correct command. @brinklec
=> Fix sbt new docs for Windows

docs/src/main/tut/middleware.md
Kleisli is mentioned in service, and dsl is where we discuss testing without a server. This could lead to confusion so this is hopefully more clear.
Fixes #1170
=> Fix Documentation Wording and Links for Clarity

examples/src/main/scala/com/example/http4s/ExampleService.scala, examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
Most are completed, some are being tricky, and a few are just painful to port.
Round 1
Refs #866
=> Fix Most Science Experiments

server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala, server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceSpec.scala
Previously, it threw a MatchError. *spit*
/cc @ZizhengTai
=> WebjarService should pass on unmatched methods

testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
I turned on monitor watching in yourkit.  On my laptop, we blocked threads on `genStandardMethod` hundreds of times.  All of these lazy values could be locking test suites.
If we go this route, we have to be careful about the ordering of the values.  In a trait, scalac doesn't flag questionable forward references.
=> Remove laziness from arbitraries

scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala
Just the test improvement we discussed in #1214
=> Use testPool for ScalaXMLSpec parrallel test

.travis.yml, bin/publishCentral.sh, bin/publishSite.sh, bin/setup.sh, bin/specialTest.sh, bin/test.sh
- Some cleanups from 0.15.x
- Don't think we need the watch dog anymore
- Simplify sbt options
=> 0.16.x build improvements

core/src/main/scala/org/http4s/Status.scala, docs/src/main/tut/auth.md, docs/src/main/tut/client.md, docs/src/main/tut/cors.md, docs/src/main/tut/dsl.md, docs/src/main/tut/entity.md, docs/src/main/tut/gzip.md, docs/src/main/tut/json.md, docs/src/main/tut/methods.md, docs/src/main/tut/middleware.md, docs/src/main/tut/service.md, docs/src/main/tut/static.md, docs/src/main/tut/streaming.md
All tut blocks now compile with fs2-0.10. The actual documentation will need an overhaul at some point.
I had to update `ResponseClass.unapply` to make it work.
=> FS2 0.10: Update docs so they compile

bin/setup.sh
Never would publish due to logic error
Fixes #1229
=> Fix Elif Logic

core/src/main/scala/org/http4s/Uri.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExampleWithRedirect.scala, examples/src/main/scala/com/example/http4s/ssl/SslExampleWithRedirect.scala, tests/src/test/scala/org/http4s/UriSpec.scala
I had to augment my main project to automatically redirect http to https and I thought it would be a good example for http4s
Do you think this could be of interest in general? Should I add some documentation?
=> Example of a site with automatic http to https redirects

core/src/main/scala/org/http4s/MessageFailure.scala, core/src/main/scala/org/http4s/headers/Age.scala, core/src/main/scala/org/http4s/headers/Retry-After.scala, core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala, core/src/main/scala/org/http4s/util/Renderable.scala, testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala, tests/src/test/scala/org/http4s/headers/AgeSpec.scala
Simple implementation of the header `Age`
=> Implementation of the Age header

bin/publishSite.sh
=> Merge Conflict Made It Upstream

project/Http4sPlugin.scala
=> FS2 0.10: Update fs2 to 0.10.0-M3

docs/src/hugo/content/standards.md
We've been talking a lot about making the model more consistent.  Here's a start on explaining it.
=> Coding standards

core/src/main/scala/org/http4s/headers/Content-Length.scala
Minimal fix to the `Content-Length` update
=> Avoid creating an anonymous class on the zero method

project/Http4sPlugin.scala
Our problem on #1274 looks vaguely like https://github.com/AsyncHttpClient/async-http-client/commit/ff85849cf0d14358a8b69003ef7c48399d070230, and this is an easy solution if it works.
Can't reproduce locally, so 🤞 .
=> Upgrade to async-http-client-2.0.33

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
Calling `ReactiveStreamsBodyGenerator` on an empty body is leaving a single response handler without calling `onComplete`, which seems like it could reasonably cause the misery observed in #1274.
=> Don't use ReactiveStreamsBodyGenerator if we don't have a body

docs/src/hugo/content/adopters.md
=> Add http4sbin project example.

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala, blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala, blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala, client/src/main/scala/org/http4s/client/impl/RequestGenerator.scala, core/src/main/scala/org/http4s/Message.scala, core/src/main/scala/org/http4s/StaticFile.scala, core/src/main/scala/org/http4s/headers/Content-Length.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala, dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala, dsl/src/test/scala/org/http4s/dsl/ResponseGeneratorSpec.scala, examples/src/main/scala/com/example/http4s/ExampleService.scala, server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala, server/src/main/scala/org/http4s/server/middleware/Jsonp.scala, testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala, tests/src/test/scala/org/http4s/HeaderSpec.scala, tests/src/test/scala/org/http4s/HeadersSpec.scala, tests/src/test/scala/org/http4s/ResponderSpec.scala, tests/src/test/scala/org/http4s/headers/ContentLengthSpec.scala, tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
Includes subsequent fix in #1263.
=> Backport #1244: improvements to Content-Length

bin/publishCentral.sh, bin/publishSite.sh, bin/setup.sh, bin/specialTest.sh, bin/test.sh
This should work, I have also integrated the `set -e` positioning. This fails due to the tut changes from #1301
=> Tut CI Integration

dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala, dsl/src/main/scala/org/http4s/dsl/package.scala, dsl/src/test/scala/org/http4s/dsl/ResponseGeneratorSpec.scala
* Backports #1298 
* Fixes #1308
I'm a little concerned this leaves us more exposed to #1302.
=> Empty response generators

server/src/main/scala/org/http4s/server/middleware/Logger.scala, server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala, server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala, server/src/test/scala/org/http4s/server/middleware/LoggerSpec.scala
Less Gobble Gobble, more Enjoying the Logging.
Continuation Reference of #1250
=> Stop Logger Middleware Eating Body

core/src/main/scala/org/http4s/multipart/Multipart.scala, tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala
=> Backport #1315: fix Part.name

core/src/main/scala/org/http4s/Headers.scala, core/src/main/scala/org/http4s/Message.scala, tests/src/test/scala/org/http4s/MessageSpec.scala
=> Stop Leaking Secrets in Request and Response toString

server/src/main/scala/org/http4s/server/middleware/Logger.scala, server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala, server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
A bit long when switching from `redactWhen` to `redactHeadersWhen`.
=> Added Header Redaction to Logger

CHANGELOG.md
Missing async-http-client and month
=> Fix Issues with RC Changelog

blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala, blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala
I think I broke this in #1332.
=> Fix intermittent failure related to TickWheelExecutor shutdown

core/src/main/scala/org/http4s/util/StreamApp.scala, server/src/main/scala/org/http4s/server/ServerBuilder.scala, tests/src/test/scala/org/http4s/util/StreamAppSpec.scala
I changed `ServerBuilder.serve` back to something that makes sense.
There's also yet another attempt at refactoring `StreamApp`. It tests and I have checked it in a small example app as well.
=> [0.18] Refactor StreamApp and fix ServerBuilder.serve

core/src/main/scala/org/http4s/syntax/ServiceSyntax.scala
I think this is very convenient for testing. If only for migration purposes alone.
=> Add syntax to make a `HttpService` "total"

CHANGELOG.md, project/Http4sPlugin.scala
Release notes sloppily intertwined because I hopped branches too fast. 🤷‍♂️
=> Upgrade to blaze-0.12.7

.travis.yml, CHANGELOG.md, bin/publish, blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala, blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala, core/src/main/scala/org/http4s/QueryParam.scala, core/src/main/scala/org/http4s/syntax/ServiceSyntax.scala, project/Http4sPlugin.scala, server/src/test/scala/org/http4s/server/middleware/UrlFormLifterSpec.scala
Catches up to everything that will be in 0.16.0-RC2.
=> Prepare for 0.17.0-RC2

blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala
Related to @rossabaker comments on #1346
=> Fix Running Threads in BlazeServerSpec

core/src/main/scala/org/http4s/EntityEncoder.scala, tests/src/test/scala/org/http4s/EntityEncoderSpec.scala
The existing `EntityEncoder[Byte]` is inefficient.  This replacement encoder preserves chunking of the provided or contramapped stream.
=> Replace EntityEncoder[Byte] with EntityEncoder[EntityBody]

project/Http4sPlugin.scala
Security fix.  Might as well grab it while we're here.
=> Upgrade to async-http-client-2.0.35

client/src/main/scala/org/http4s/client/middleware/Retry.scala, client/src/main/scala/org/http4s/client/middleware/package.scala, client/src/test/scala/org/http4s/client/middleware/RetrySpec.scala
=> Implement a retry policy for client retry middleware

examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
Uncommented and ported to work with cats-effect
=> Restore blaze metrics example

parboiled2/src/main/scala/org/http4s/internal/parboiled2/Parser.scala, parboiled2/src/test/scala/org/http4s/internal/parboiled2/BasicSpec.scala
Decided to see if it had changed much. It hasn't, but it's easier to stay current.
=> Sync parboiled to d7ad77a5077

examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeHttp2Example.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExample.scala
Ported the 2 remaining examples to Cats
- This is minor but it _should_ close out #866 unless I am missing something
=> Port remaining examples to Cats.

server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala
=> Fix AutoSlash middleware when a service is mounted prefixed

core/src/main/scala/org/http4s/Message.scala, tests/src/test/scala/org/http4s/MessageSpec.scala
Resolves #681 
- Not the biggest fan of the names but I can't think of anything better
=> Added convenience method to Request for X-Forward-For

server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
=> Increase timeout in timeout spec by a factor 5000

server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala
We weren't attaching the update code to the request body, so no metrics were being captured.
There was, and is, no unit test for this. :(  I did test it manually.
=> Fix metrics middleware

.jvmopts
A response to https://travis-ci.org/http4s/http4s/jobs/276690688
=> Travis JVM options tweak

bin/publishCentral.sh
Hard to test without merging it, but I think this will get @cranst0n unblocked.
=> Turn coverage off before publishing

server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
Fixes #1383 or your money back.
=> Tweak timemout spec

docs/src/main/tut/index.md
Similar will be necessary for 0.17 and 0.18.
=> Update quickstart instructions

build.sbt, examples/docker/src/main/resources/logback.xml, examples/docker/src/main/scala/com/example/http4s/Example.scala, project/plugins.sbt
Not a great general tutorial for deploying with Docker, as some of the details must be extracted from the monolithic build.  
Highly convenient for throwing the latest up into the cloud and doing some load testing.
=> Creates an example project as a Docker image

project/Http4sPlugin.scala
This picks up the fix for #1172.
=> Upgrade to blaze-0.12.9

blaze-core/src/main/scala/org/http4s/blazecore/util/IdentityWriter.scala, blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala, client/src/main/scala/org/http4s/client/PoolManager.scala, core/src/main/scala/org/http4s/util/StreamApp.scala, project/Http4sPlugin.scala, server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala, servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala, servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
This fixes getLogger for classes with higher kinded type parameters
=> Upgrade log4s to 1.4.0

project/Http4sPlugin.scala, website/src/hugo/content/changelog.md
Contains some changes to Http4sPlugin to let us release milestones.
=> Release v0.18.0-M2

server/src/main/scala/org/http4s/server/middleware/GZip.scala
This will help anyone on Java 9.
=> Backport #1438: remove java.xml.bind dependency

project/Http4sPlugin.scala, project/ScalazPlugin.scala, project/plugins.sbt
Nothing exciting here.  Just getting warmed up this morning.
=> Bump some dependencies

server/src/test/scala/org/http4s/server/ServerSpec.scala, servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
We weren't flattening the chunked stream correctly.  We were discarding all but the first byte.
Fixes #1441.
/cc @bigknife
=> Fix non-blocking servlet IO

server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
This has been solid on master but haunting us on the maintenance branches, which really sucks now that we're doing Travis-based releases.
=> Backport #1419: timeout spec reliability

version.sbt, website/src/hugo/content/CHANGELOG.md
Not a very thrilling release, but a good test of our new automation.
=> Release v0.16.4

tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSpec.scala
The `Before` trait didn't work.
=> Fix TomcatServerSpec so it can run multiple times

project/Http4sPlugin.scala, scripts/helpers, server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala, version.sbt, website/src/hugo/content/changelog.md
Contains a bunch of diagnostic release steps so we can see why it's not bumping our version.sbt.
=> Release v0.18.0-M3

project/Http4sPlugin.scala
=> Update specs2 to 4.0.0

project/Http4sPlugin.scala
This combats [this change in sbt-1.0](https://github.com/sbt/sbt-pgp/blob/5891a1b8729b9fdd2df7e0593bf5822b51605d40/pgp-plugin/src/main/scala-sbt-1.0/Compat.scala#L72).  I think it will allow us to publish signed snapshots, as we do on the 0.13 builds.
If this doesn't work, I'm ripping out signed snapshots, breaking my laptop, and finally opening that aquarium shop.  I am particularly fond of African cichlids.
=> Allow overwrite of signed snapshots

build.sbt, docs/src/main/tut/auth.md, docs/src/main/tut/dsl.md, docs/src/main/tut/entity.md, docs/src/main/tut/json.md, docs/src/main/tut/methods.md, docs/src/main/tut/middleware.md, docs/src/main/tut/service.md
Those were introduced by f159f5c7f6352fa65051751ecf4c0c239bceacf8
=> Fix warnings in documentation

server/src/test/scala/org/http4s/server/staticcontent/PathNormalizerSpec.scala, version.sbt
I'm not convinced the property tests makes sense.
=> Add more tests for PathNormalizer

docs/src/main/tut/json.md
I don't think the example will work without this import
=> Add a missing import

.appveyor.yml, .travis.yml, blaze-core/src/test/scala/org/http4s/blazecore/util/Http1WriterSpec.scala, client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala, client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala, project/Http4sPlugin.scala, server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala
I feel like I could have missed something here, so check me please.
=> 2.12.4 Merge Train for release-0.17.x

.appveyor.yml, .travis.yml, build.sbt, docs/src/main/tut/json.md, project/Http4sPlugin.scala, server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala, testing/src/main/scala/org/http4s/testing/ToIOSyntax.scala
Bring with it the missing import fix as well.
=> Merge Train 2.12.4 To Master

README.md, docs/src/main/tut/service.md
People are running into issues as this is not added to their applications. We should be more transparent about the need to add this.
=> Add Partial unification for Clearer Documentation

core/src/main/scala/org/http4s/AuthedService.scala, core/src/main/scala/org/http4s/package.scala, docs/src/main/tut/auth.md, examples/src/main/scala/com/example/http4s/ExampleService.scala, server/src/main/scala/org/http4s/server/middleware/authentication/package.scala, server/src/main/scala/org/http4s/server/package.scala, server/src/test/scala/org/http4s/server/middleware/authentication/AuthMiddlewareSpec.scala, server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSpec.scala
Should fix #1506 
I hope I haven't forgotten anything, and that `sbt ci` on my machine is reliable. We shall see :)
=> Change type parameter order in Auth to trigger partial unification

core/src/main/scala/org/http4s/EntityEncoder.scala, core/src/main/scala/org/http4s/MessageOps.scala, core/src/main/scala/org/http4s/headers/Content-Type.scala, docs/src/main/tut/entity.md, json4s/src/test/scala/org/http4s/json4s/Json4sSpec.scala, server/src/main/scala/org/http4s/server/middleware/Jsonp.scala, tests/src/test/scala/org/http4s/EntityDecoderSpec.scala, tests/src/test/scala/org/http4s/ResponderSpec.scala
First PR in converting to reliable `withX`, `withoutX` and `withXOption` functions.
=> Content Type Fix

tests/src/test/scala/org/http4s/TransferCodingSpec.scala
=> Fix for TransferCodingSpec random error

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala, jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala, project/Http4sPlugin.scala, server/src/main/scala/org/http4s/server/Server.scala, tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
Partial backport of #1536.
I normally wouldn't go this far out of my way to add new functionality to 0.16, but I was already on that branch, and then realized my MiMa error, and then I was sad and did it anyway.
Enjoy.
=> Render version info and server address on startup

core/src/main/scala/org/http4s/QValue.scala, tests/src/test/scala/org/http4s/ContentCodingSpec.scala
The original tests were incorrect, Now it should be better
Fixes #1542
=> Fix for bogus compareTo test

core/src/main/scala/org/http4s/util/package.scala, server/src/main/scala/org/http4s/server/middleware/CSRF.scala, server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala
:train: CHO CHOO CSRF merge train cannot stop :train:
=> 0.18 csrf middleware

server/src/main/scala/org/http4s/server/middleware/CSRF.scala, server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala
This brings up the 0.16.x branch with the same logic present in #1546
=> Csrf updates for 0.16x 

server/src/main/scala/org/http4s/server/middleware/CSRF.scala, server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala
Update 0.17x branch relative to 0.18x logic #1546
=> CSRF Update 0.17.x

server/src/main/scala/org/http4s/server/middleware/GZip.scala, server/src/test/scala/org/http4s/server/middleware/GZipSpec.scala
- This is to enable GZip for non standard content-Type like `application/x-ndjson`.
- Changed the `defaultIsZippable` public so that we can compose out the custom `isZippable` id needed.
For further details, please follow https://github.com/http4s/http4s/pull/1558
=> GZip any content-type by passing isZippable

.travis.yml, project/ScalazPlugin.scala
Getting current before maintenance releases.
=> Upgrade to scalaz-7.2.17

core/src/main/scala/org/http4s/MediaType.scala
see https://www.iana.org/assignments/media-types/application/vnd.api+json for its specification
=> add new media type application/vnd.api+json

project/Http4sPlugin.scala, website/src/hugo/content/CHANGELOG.md
Sneaks in a Jetty patch upgrade.
=> Release v0.16.6

version.sbt
I missed the version bump on #1577.
=> Really release v0.16.6

core/src/main/scala/org/http4s/headers/Content-Length.scala
=> Dropped mention of thrown exception from docstring

core/src/main/scala/org/http4s/EntityDecoder.scala, tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
Closes #1574 
Just one way of doing it.
=> More EntityDecoder composition methods

core/src/main/scala/org/http4s/StaticFile.scala, project/Http4sPlugin.scala, version.sbt, website/src/hugo/content/changelog.md
Nothing real interesting here.  Letting Travis chew on it while I run errands.
=> Merge 0.17.6

core/src/main/scala/org/http4s/StaticFile.scala
It seems we had a bad merge after #1197 and it came back.
=> Remove the buffer copying hack from #1202

project/build.properties
Noticed this had been released.
=> Update SBT to 1.1.0

docs/src/main/tut/client.md
I ended up needing this recently so I thought I'd include it in the doc
=> Flesh out body decoding section of the client doc

website/src/hugo/content/adopters.md
Adding link of the recent open sourced Smart Backpacker App's backend
=> Linking open source app into the adopters page

bench/src/main/scala/org/http4s/bench/BytesBench.scala, project/Http4sPlugin.scala, version.sbt, website/src/hugo/content/changelog.md
=> Initial Dependency Upgrades For Release M9

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala, project/Http4sPlugin.scala, version.sbt, website/src/hugo/content/changelog.md
=> Release v0.18.0 

project/CentralRequirements.scala
=> Add @SystemFw to the POM

project/CentralRequirements.scala
Oops.  We missed Paulo when he was added.
=> Add @jcranky to POM

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
Maybe it's writing it byte-by-byte that makes that ClientRouteTestBattery flaky.
Counterpoint: it only seems to hurt async-http-client
Countercounterpoint: either way, this is marginally less ugly.
=> Simplify renderResponse in the ClientRouteTestBattery

examples/blaze/src/main/scala/com/example/http4s/blaze/demo/StreamUtils.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/MultipartClient.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/StreamClient.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Module.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Server.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/FileHttpEndpoint.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/HexNameHttpEndpoint.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/JsonXmlHttpEndpoint.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/MultipartHttpEndpoint.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/TimeoutHttpEndpoint.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/auth/AuthRepository.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/auth/BasicAuthHttpEndpoint.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/auth/GitHubHttpEndpoint.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/package.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/FileService.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/GitHubService.scala
I added a new package `demo` in the `blaze` examples and created all the examples from https://github.com/gvolpe/advanced-http4s. Later on, I'd like to add some documentation with simple examples compiling with tut and pointing out to these examples.
=> Adding examples from the gvolpe/advanced-http4s examples repo.

core/src/main/scala/org/http4s/Uri.scala, testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala, tests/src/test/scala/org/http4s/UriSpec.scala
=> Add Eq instance for Uri

build.sbt, project/Http4sPlugin.scala, prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus/PrometheusExportService.scala, prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus/PrometheusMetrics.scala
A layout of a prometheus metrics similar to dropwizard metrics, I believe my use of observe may be in error. Any guidance appreciated. 
We're also not following prometheus best practices that state metrics should not be based upon the response at all. With that it would be easy to implement an initial transformation to something that could be completed correctly in each case and be a little less dependent on responses.
=> Prometheus metrics

client/src/main/scala/org/http4s/client/middleware/Retry.scala, core/src/main/scala/org/http4s/Uri.scala, project/Http4sPlugin.scala, version.sbt, website/src/hugo/content/changelog.md
Cherry picks #1697 and #1698 and bumps Tomcat.
=> Release v0.18.2

website/src/hugo/content/adopters.md
We need to fix the need for this comment.
=> Add the necessary comment

website/src/hugo/content/adopters.md
Adds some interesting libraries that have popped up in the community
=> http4s-timer, kamon-http4s, pureconfig-http4s, typedapi

blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala, blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala, blaze-core/src/test/scala/org/http4s/blazecore/ResponseParser.scala, circe/src/main/scala/org/http4s/circe/CirceInstances.scala, client/src/main/scala/org/http4s/client/Client.scala, client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala, core/src/main/scala/org/http4s/EntityDecoder.scala, core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala, core/src/main/scala/org/http4s/multipart/MultipartParser.scala, core/src/main/scala/org/http4s/util/Renderable.scala, core/src/main/scala/org/http4s/util/package.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Module.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Server.scala, examples/src/main/scala/com/example/http4s/ScienceExperiments.scala, server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala, server/src/main/scala/org/http4s/server/middleware/Logger.scala, server/src/main/scala/org/http4s/server/middleware/Timeout.scala, server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/StaticContentShared.scala, tests/src/test/scala/org/http4s/EntityDecoderSpec.scala, tests/src/test/scala/org/http4s/multipart/MultipartParserSpec.scala, tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala, website/src/hugo/content/changelog.md
I really just took the shortest path to recompilation here.
Please check my work. I know I needed ConcurrentEffect in the examples which seems needlessly strong, but I was just following types.
=> MergeTrain 0.18.4 -> 0.19

docs/src/main/tut/testing.md
From https://github.com/http4s/http4s/pull/1699
Could you please take a look, @rossabaker, @jcranky, @jmcardon, @ChristopherDavenport? Thanks!
Closes https://github.com/http4s/http4s/issues/1504
=> Add Testing Docs for v0.18

blaze-client/src/test/scala/org/http4s/client/blaze/PooledClientSpec.scala, client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala, server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
=> Update tests to take advantage of cats-effect-0.10

core/src/main/scala/org/http4s/EntityEncoder.scala, docs/src/main/tut/dsl.md, examples/src/main/scala/com/example/http4s/ExampleService.scala, tests/src/test/scala/org/http4s/EntityEncoderSpec.scala
=> add deprecation notice to future encoder

website/src/hugo/content/further-reading.md
Adds my talk and updates a couple dependency links
=> Update the further reading page

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
=> Adding Scaladoc for BlazeBuilder

version.sbt, website/src/hugo/content/changelog.md
Tagging happens automatically right? I believe this is all that's necessary for a release.
=> Update Version and Release Notes for 0.18.8

blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala
If writing the header fails, drain, and log any errors in _that_.  Then re-raise the original error.
Fixes #1781
=> Don't swallow errors in Http1Writer

servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
If setting a servlet status or header fails, we need to drain the response body to release any associated resources.
Fixes #1782.  Relates to #1785.
=> Drain the response body after an error setting status/headers

project/Http4sPlugin.scala
=> blaze-0.12.13, http4s-websocket-0.2.1, specs2-4.0.4

core/src/main/scala/org/http4s/Uri.scala, tests/src/test/scala/org/http4s/SchemeSpec.scala
=> Fix scheme parser for /https?[A-Za-z]/

project/Http4sPlugin.scala, project/build.properties, website/src/hugo/content/changelog.md
I thought we had cats-effect-0.10.1 in the last release. :confused:
=> sbt-1.1.4, cats-effect-0.10.1, specs2-4.1.0

project/Http4sPlugin.scala, website/src/hugo/content/changelog.md
=> fs2-0.10.4

client/src/main/scala/org/http4s/client/middleware/Logger.scala, client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala, client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala, client/src/test/scala/org/http4s/client/middleware/LoggerSpec.scala
I did a bad job merging #1820 after the release.
I'll probably merge this aggressively to get master green, but this PR can be a lasting monument to my negligence.
=> Fix broken client logger merge

core/src/main/scala/org/http4s/MediaType.scala, core/src/main/scala/org/http4s/MessageFailure.scala, core/src/main/scala/org/http4s/Uri.scala, core/src/main/scala/org/http4s/headers/Cookie.scala, core/src/main/scala/org/http4s/headers/ETag.scala, core/src/main/scala/org/http4s/headers/Set-Cookie.scala, core/src/main/scala/org/http4s/package.scala, core/src/main/scala/org/http4s/parser/CookieHeader.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
Killing off Aliases which obscure types for what I don't think is a major advantage of a shorter name. Precision in communication I think is advantageous here.
=> WIP: ParseResult Alias Killing

core/src/main/scala/org/http4s/MediaType.scala, core/src/main/scala/org/http4s/MessageFailure.scala, core/src/main/scala/org/http4s/Uri.scala, core/src/main/scala/org/http4s/headers/Cookie.scala, core/src/main/scala/org/http4s/headers/ETag.scala, core/src/main/scala/org/http4s/headers/Set-Cookie.scala, core/src/main/scala/org/http4s/package.scala, core/src/main/scala/org/http4s/parser/CookieHeader.scala, core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
This reverts commit 82d49f38292569bd96483ad97195727fe6bb0562, reversing
changes made to 5cb0f2dc3c6f99b376ea8286fb97661c6ad0a06a.
WIP with a commit called Initial Save does not mean finished yet.
=> Revert "Merge pull request #1829 from ChristopherDavenport/aliasDeath"

project/Http4sPlugin.scala
I consider this approaching "why wouldn't you use this?" status.
Purely compile time, so no downstream headaches.
=> better-monadic-for is better

client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
When response body logging is on, if the entire response body isn't read, no logging happens.
This is still not ideal: it logs only the portion of the body that's been consumed.  This brings it to parity with the request logging on the server.
See #1833.
=> Log whatever part of the response has been read

server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
=> Log requests with empty body

server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
Seems like a little improvement to request logging.
@jmcardon Is going to love this one
=> Log Unmatch and Errors

server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
=> Backport request logger upgrades

build.sbt, project/plugins.sbt
Its a little verbose, however makes it very easy to keep up with project upgrades.
=> Add sbt-updates to build and have it state them on project load

build.sbt, project/Http4sPlugin.scala, project/plugins.sbt, website/src/hugo/content/changelog.md
=> Release v0.18.12

docs/src/main/tut/dsl.md
for #1868. Give a example of Optional and Validating QueryParamMater and document how missing arguments are handled.
=> Extend query paramater docs #1868

project/Http4sPlugin.scala, version.sbt, website/src/hugo/content/changelog.md
=> Upgrade to argonaut-6.2.2

docs/src/main/tut/dsl.md
This should unbreak master from the last merge.
=> Fix deprecation in dsl tut

server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala, server/src/test/scala/org/http4s/server/middleware/UrlFormLifterSpec.scala, website/src/hugo/content/changelog.md
=> Parameterize `UrlFormLifter` middleware

server/src/main/scala/org/http4s/server/middleware/VirtualHost.scala, website/src/hugo/content/changelog.md
=> Parameterize `VirtualHost` middleware

server/src/main/scala/org/http4s/server/middleware/GZip.scala
=> Parameterize GZip middleware

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml
This adds the IntelliJ project configuration to use Twitter style imports.
=> Add IntelliJ code style configuration

project/build.properties, testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
Fixes #1891
(also update sbt to 1.1.6)
=> Downcase type in MediaRange generator

.travis.yml, website/src/hugo/content/changelog.md
I've been watching that Travis ticket for over a month and I still don't know whether this works but they closed it so let's see.
=> Test on oraclejdk10

version.sbt, website/src/hugo/content/changelog.md
=> Release 0.18.13

project/Http4sPlugin.scala
Some of the dependency upgrade exemptions should be removed on merge to master.
=> jetty-9.4.11, tomcat-9.0.10

docs/src/main/tut/entity.md
All other examples are already using lower case for that.
=> Make http4sVersion val lowercase in entity.md

version.sbt, website/src/hugo/content/changelog.md
Should cut 0.18.15 when merged.
=> Update Changelog and Set Version for 0.18.15 release

server/src/main/scala/org/http4s/server/middleware/StaticHeaders.scala, server/src/test/scala/org/http4s/server/middleware/StaticHeadersSpec.scala, version.sbt, website/src/hugo/content/changelog.md
#1939, made generic to fit the 0.19 ethos.
=> Merge 0.18.15

server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala, server/src/test/scala/org/http4s/server/middleware/AutoSlashSpec.scala
=> Fix Router nested in AutoSlash

docs/src/main/tut/dsl.md
Slight unification, minor corrections.
=> Minor corrections to tut/dsl.md

project/Http4sPlugin.scala
fs2-1.0.0-M3 is more complicated, so will be done separately.
=> Upgrade async-http-client, cats, jawn-json4s

core/src/main/scala/org/http4s/headers/Referer.scala, tests/src/test/scala/org/http4s/headers/RefererSpec.scala
=> Make Referer headers extractable

project/build.properties
Already on master.  This is to catch 0.18.x up.
=> Upgrade to sbt-1.2.1

project/Http4sPlugin.scala, server/src/main/scala/org/http4s/server/Router.scala, server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala, server/src/main/scala/org/http4s/server/middleware/TranslateUri.scala, server/src/main/scala/org/http4s/server/middleware/URITranslation.scala, server/src/test/scala/org/http4s/server/middleware/TranslateUriSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/ResourceServiceSpec.scala, version.sbt, website/src/hugo/content/changelog.md
This one wasn't as trivial as some others, so going the PR route.
=> Merge 0.18.16

dsl/src/main/scala/org/http4s/dsl/impl/Path.scala, dsl/src/test/scala/org/http4s/dsl/PathInHttpServiceSpec.scala
=> OptionalMultiQueryParamDecoderMatcher accumulates

docs/src/main/tut/index.md
I believe this is responsible for https://github.com/http4s/http4s.g8/issues/73
=> Add branch to quickstart instructions

client/src/main/scala/org/http4s/client/middleware/Retry.scala, client/src/test/scala/org/http4s/client/middleware/RetrySpec.scala
=> Retry request without cleaning body

version.sbt, website/src/hugo/content/changelog.md
We had a scope.  Let's stick to it.  The blaze enhancements can simmer for a bit.
=> Release v0.19.0-M2

build.sbt, project/Http4sPlugin.scala
Solves problem of #2066, reduces complexity.
I think this is possible ever since jawn-1.13.0, but let's consult Travis CI.
=> Use play-json-2.6.10 in all crossbuilds

website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
=> Fix master version in website

project/Http4sPlugin.scala
BEAT YOU TO IT, @scala-steward!!!!1!
=> Upgrade to circe-0.10.0

.travis.yml
=> Stop testing oraclejdk10

blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala, core/src/main/scala/org/http4s/multipart/MultipartParser.scala, project/Http4sPlugin.scala
=> Upgrade to fs2-1.0.0-RC1

version.sbt, website/src/hugo/content/changelog.md
=> Release v0.18.19

version.sbt, website/src/hugo/content/changelog.md
=> Release v0.19.0-M3

examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/StreamClient.scala, examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/GitHubService.scala
#2136 deprecated calls that #2139 used.
=> Fix deprecated calls in examples

client/src/main/scala/org/http4s/client/Client.scala, project/Http4sPlugin.scala, version.sbt, website/src/hugo/content/changelog.md
If anyone is passionate about a constant for `vnd.futoin+cbor`, then we can block on #2149, but I'd rather ship.
=> Release v0.19.0-M4

core/src/main/scala/org/http4s/Message.scala
=> Add mapK to Request/Response

core/src/main/scala/org/http4s/Status.scala, dsl/src/main/scala/org/http4s/dsl/impl/Responses.scala, project/Http4sPlugin.scala, tests/src/test/scala/org/http4s/StatusSpec.scala
They are the newest additions in https://www.iana.org/assignments/http-status-codes/http-status-codes.xml.
=> Add HTTP Status Codes 103, 421, and 425

client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
Adds missing redactHeadersWhen to RequestLogger apply0 to fix #2181
=> Fix RequestLogger logs sensitive headers #2181

docs/src/hugo/config.toml, version.sbt, website/src/hugo/content/changelog.md, website/src/hugo/content/versions.md, website/src/hugo/static/_redirects, website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
- Marks 0.19 as EOL
- Updates the changelog
=> Release v0.20.0-M1

.travis.yml
Mitigate #2192 until we fix it.
=> Temporarily allow openjdk11 failures

project/Http4sPlugin.scala
Updates Circe Version. Went off Twitter Announcement. Wanted to beat our magical bot. 😄
=> Update Circe Version

server/src/main/scala/org/http4s/server/package.scala
https://gitter.im/http4s/http4s?at=5bd77ef41e23486b933a6611
Hi @rossabaker @ChristopherDavenport - please take a look!
=> Add NonFatalServiceErrorHandler.

version.sbt, website/src/hugo/content/changelog.md
Please merge _after_ #2244 and #2249.
=> Release v0.20.0-M2

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala, blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
This _potentially_ fixes #2193.  It does not appear to fix #2258.
If it fixes neither, it still fixes a bug.
=> Fix leak on a canceled connection

core/src/main/scala/org/http4s/MimeDB.scala
`application/vnd.exstream-empower+zip` users, rejoice!
=> Refresh MimeDB

version.sbt, website/src/hugo/content/changelog.md
=> Release v0.20.0-M3

core/src/main/scala/org/http4s/util/package.scala, tests/src/test/scala/org/http4s/util/DecodeSpec.scala
=> Fix Issue #2280 `org.http4s.util.decode` throws `ClassCastException` on empty chunk

version.sbt, website/src/hugo/content/changelog.md
Maybe squeezing in #2351, maybe not.
=> Release 0.20.0-M5

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
Fixes #2330
The diff is easier to understand if you hide whitespace changes.
=> Clean up resource handling in BlazeServerBuilder

prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala
=> Add MemoryAllocationExports to PrometheusExportService

project/CentralRequirements.scala
Hopefully will fix. https://travis-ci.org/http4s/http4s/jobs/492320846#L5199-L5247
=> Add Publishing Baseline to Central Requirements

server/src/main/scala/org/http4s/server/middleware/Metrics.scala
Fixes #2365 
May only fix part depending on if there still exists an error in the idleTimeout, however the bracketing on the stream looks alright to me.
=> Handle Cancelation of Metrics Middleware

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
=> Configure AHC to Use NoOp CookieStore by Default

client/src/main/scala/org/http4s/client/PoolManager.scala, website/src/hugo/content/changelog.md
Includes Logging Key Fix for Pool Manager
=> 0.18.22 Merge train

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
Same change as the one discussed in https://github.com/http4s/http4s/pull/2453 !
=> Avoid closing the previously connection if no errors occurred.

blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
This is another one that fails intermittently and only on CI
=> Skip Utilize provided Host header test in CI

core/src/main/scala/org/http4s/package.scala
Follow up of https://github.com/http4s/http4s/commit/2c42ce1d71bd9bed01eab9a33787f72fc0a99fad
=> Improve doc for HttpApp

website/src/hugo/content/adopters.md
It's not real extensive yet, but it's there. :smile:
=> We use the client at Formation

core/src/main/scala/org/http4s/internal/package.scala
This is needed for the `JdkHttpClient` (see #2490), but I think it is useful to have it in `http4s-core`.
=> add conversion for j.u.c.CompletableFuture

version.sbt, website/src/hugo/content/changelog.md, website/src/hugo/content/versions.md
Starting the release notes for 0.20.0.
=> Release v0.20.0

.travis.yml
Like https://github.com/typelevel/cats-effect/pull/518, but over here.
=> Switch to xenial and openjdk8

docs/src/main/tut/index.md, website/src/hugo/content/further-reading.md
1. Add live coding video to presentation list
2. Update giter8 invocation in Quick Start
=> 2 minor website changes

version.sbt, website/src/hugo/content/changelog.md
=> Release v0.20.1

project/Http4sPlugin.scala
Gets it on the maintenance branch.  Supersedes #2586.
=> Upgrade to okhttp-3.14.2

project/Http4sPlugin.scala
=> Update tomcat-catalina, tomcat-coyote to 9.0.21

client/src/test/scala/org/http4s/client/JettyScaffold.scala, jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala, project/Http4sPlugin.scala, website/src/hugo/content/changelog.md
Merge after #2641.  I threw in some patch upgrades, but not minor upgrades.
=> Release v0.18.24

project/Http4sPlugin.scala
=> Update blaze-http to 0.14.5

client/src/main/scala/org/http4s/client/middleware/GZip.scala, client/src/test/scala/org/http4s/client/middleware/GZipSpec.scala
This is all new.  We can get this into a maintenance release.
=> Backport #2673: Gzip middleware for client

project/Http4sPlugin.scala
This one got missed when we upgraded the server.
=> Upgrade jetty-client to 9.4.19.v20190610 in series/0.20

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala, client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala
Fixes #2692.  Same idea as #2691.
=> Release connections before following redirects

core/src/main/scala/org/http4s/multipart/Part.scala
Spotted by @Daenyth on Gitter earlier.
=> Remove unnecessary Sync constraint on Part.formData

project/Http4sPlugin.scala, website/src/hugo/content/changelog.md
Adds support for closing SSL sessions
=> Upgrade to blaze-0.14.6

version.sbt, website/src/hugo/content/changelog.md
Only the blaze upgrade, but if you're affected, highly worth it.
=> Release v0.20.5

docs/src/main/tut/index.md
This is #2697, reopened against the markdown instead of the index.html.  Thanks to @gekomad for the original PR.
=> Update quickstart for v0.21

project/Http4sPlugin.scala
=> Update tomcat-catalina, tomcat-coyote to 9.0.22

docs/src/main/tut/static.md
tut output in documentation spitting out compile errors because of missing comma
=> add missing comma in code sample

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala, blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala, blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala, client/src/main/scala/org/http4s/client/JavaNetClientBuilder.scala, client/src/main/scala/org/http4s/client/package.scala, jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala, server/src/main/scala/org/http4s/server/ServerBuilder.scala, server/src/main/scala/org/http4s/server/package.scala, servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala, tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
=> Adjust default timeouts and add warnings about missconfiguration

server/src/test/scala/org/http4s/server/middleware/MaxActiveRequestsSpec.scala
=> Longer Timeout For MaxActiveRequestsSpec

server/src/main/scala/org/http4s/server/staticcontent/FileService.scala, server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala, version.sbt, website/src/hugo/content/changelog.md
=> Release v0.20.10

project/Http4sPlugin.scala
=> Update jetty-client, jetty-server, ... to 9.4.20.v20190813

core/src/main/scala/org/http4s/QueryParam.scala, docs/src/main/tut/dsl.md, dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala, server/src/main/scala/org/http4s/server/middleware/CSRF.scala, server/src/main/scala/org/http4s/server/middleware/MaxActiveRequests.scala, server/src/main/scala/org/http4s/server/staticcontent/FileService.scala, server/src/test/scala/org/http4s/server/middleware/MaxActiveRequestsSpec.scala, server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala, tests/src/test/scala/org/http4s/QueryParamCodecSpec.scala, version.sbt, website/src/hugo/content/changelog.md
Based on #2787, but keeps commit lineage for future merges.
Posting as draft, as a couple others just need an approval, and we'll do another merge.
=> Release 0.21.0-M4

jetty-client/src/main/scala/org/http4s/client/jetty/JettyClient.scala
=> JettyClient: set followRedirects to false by default

.travis.yml
https://twitter.com/alxarchambault/status/1172581683620716544
=> Update coursier cache path

project/Http4sPlugin.scala, project/plugins.sbt, version.sbt, website/src/hugo/content/changelog.md
Contains cherry-pick of #2922 and a conservative set of upgrades.
=> Release v0.20.12

core/src/main/scala/org/http4s/ContentCoding.scala
Backport of #2948, courtesy of @ipsq.  Might as well get it into the upcoming release.
=> Backport #2948: Add missing ContentCodings

servlet/src/main/scala/org/http4s/servlet/BlockingHttp4sServlet.scala, servlet/src/main/scala/org/http4s/servlet/ServletIo.scala, servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSpec.scala
This is a fix of #2939 for 0.20. I'll port this PR to 0.21 once it is merged.
=> Fix BlockingHttp4sServlet handling requests asynchronously

servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
A follow-up to #2941, following the discussion in #2955.
=> Shift the write to Blocker in BlockingServletIo

servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
=> Fix switched local and remote addresses in servlet requests (0.21) 

docs/src/main/tut/client.md, docs/src/main/tut/middleware.md, prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala, prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala, prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusClientMetricsSpec.scala, prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusServerMetricsSpec.scala
This PR closes https://github.com/http4s/http4s/issues/2969.
WDYT @ChristopherDavenport ?
=> Unregister Prometheus metrics

core/src/main/scala/org/http4s/util/UrlCoding.scala, tests/src/test/scala/org/http4s/UserInfoSpec.scala
=> Fix false negative in UserInfo parsing test

client/src/main/scala/org/http4s/client/middleware/Logger.scala, client/src/main/scala/org/http4s/client/oauth1/ProtocolParameter.scala, client/src/main/scala/org/http4s/client/oauth1/oauth1.scala, client/src/test/scala/org/http4s/client/oauth1/OAuthTest.scala, core/src/main/scala/org/http4s/Credentials.scala, core/src/main/scala/org/http4s/Message.scala, server/src/main/scala/org/http4s/server/middleware/HttpsRedirect.scala, server/src/main/scala/org/http4s/server/middleware/Logger.scala, server/src/main/scala/org/http4s/server/middleware/Metrics.scala, server/src/test/scala/org/http4s/server/middleware/HttpsRedirectSpec.scala, tests/src/test/scala/org/http4s/MessageSpec.scala, version.sbt, website/src/hugo/content/changelog.md
I know we just released, but we've uncovered a few more that are worthy of backport.
=> Release v0.20.15

argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala, blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala, blaze-core/src/test/scala/org/http4s/blazecore/util/Http1WriterSpec.scala, blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala, blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala, build.sbt, project/Http4sPlugin.scala, server/src/test/scala/org/http4s/server/middleware/MaxActiveRequestsSpec.scala, server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala, testing/src/test/scala/org/http4s/Http4sSpec.scala
An attempt to improve the health of our CI and set a better example for others.
=> Start replacing unsafeRunSync in tests

server/src/main/scala/org/http4s/server/middleware/Timeout.scala
Fix scaladoc: the timeout response is a `503 Service Unavailable` instead of `500 Internal Server Error`.
=> Fix scaladoc

website/src/hugo/content/adopters.md
These are two little projects I created that are powered by http4s.
=> Add two open-source apps

server/src/main/scala/org/http4s/server/middleware/Date.scala, server/src/test/scala/org/http4s/server/middleware/DateSpec.scala
Adds Date Header to all responses generated by the Server.
=> Date Middleware

blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
I always hate to do this, but this one is persistently irritating and I think not teaching us anything.
=> Skip reset request timeout test on Travis CI

server/src/main/scala/org/http4s/server/middleware/ErrorAction.scala, server/src/main/scala/org/http4s/server/middleware/ErrorHandling.scala
- Adds ErrorAction Middleware, useful as it surfaces a common pattern.
- Adds ErrorAction.log which composes logging action that were internal and uncontrolled by the user into the user controlled space.
=> ErrorAction Middleware

project/Http4sPlugin.scala
Fixes some bincompat issues exposed in 2.2.0.
=> Upgrade to fs2-2.2.1

client/src/main/scala/org/http4s/client/PoolManager.scala, client/src/test/scala/org/http4s/client/PoolManagerSpec.scala
Tale of Woe was told in Gitter. 
Fixing this would make life very nice.
=> Backport Client Pool Fix for 0.18.x

testing/src/test/scala/org/http4s/Http4sSpec.scala
=> Remove Http4sSpec.writeToChunk

tests/src/test/scala/org/http4s/UriSpec.scala
=> Tests for Request query param convenience methods

version.sbt, website/src/hugo/content/changelog.md
Trying to be clearer about what's source breaking and what's binary breaking.
@gvolpe, does this help compared to previous release notes?
=> Release v0.21.0-RC2

.github/workflows/ci.yml
In scope:
* Validates on Scala {2.12, 2.13} x Java {8, 11}
* Builds scalafix
* Builds project website
* Builds docs site
Out of scope (for now):
* Publish snapshots
* Publish to sonatype
* Publish website
=> Add GitHub Action

.github/workflows/ci.yml
We use this to skip certain problematic tests.  I'd like to get away from that too, but one step at a time.
=> Add CI=true environment variable

server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala
Mitigates #3128.
I prefer the spec in #3150 in the long run, but it exposes a problem that would be solved with #2663.  This tests that we don't leak a resource acquired in the Stream, which is about the best we can do without `HttpResource`.
=> Alternate GET body cleanup test

build.sbt, examples/ember/src/main/scala/com/example/http4s/ember/EmberClientSimpleExample.scala, examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala
TLS Examples Seem Not to Be working. 😖 
Server is working correctly.
=> Add Ember Examples

.github/workflows/ci.yml
=> Publish signed snapshots

.github/workflows/ci.yml
We're using this on release. Let's test that way, too.
=> Use setup-scala GitHub Action

website/src/hugo/content/changelog.md, website/src/hugo/content/versions.md
Merge only after #3169 and #3168.
=> Release v0.21.0

.mergify.yml
This requires updating when we switch java versions.
Closes #3170
=> Update .mergify.yml for github actions

.github/workflows/ci.yml
When we switched from setup-java to setup-scala, we lost scalafmt.
=> Fix scalafmt in CI
