http4s/http4s

examples/src/main/scala/com/example/http4s/ExampleService.scala
examples/src/main/twirl/com/example/http4s/formEncoded.scala.html
examples/src/main/twirl/com/example/http4s/index.scala.html
scala-xml/src/main/scala/scalaxml/ElemInstances.scala

This makes XML literals as HTML a Bad Idea, so they are ported to
Twirl in the example.
Related to #153.

Change inferred media type of scala.xml.Elem to application/xml.

---

argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/Message.scala
core/src/test/scala/org/http4s/EntityDecoderSpec.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
scala-xml/src/main/scala/scalaxml/ElemInstances.scala
scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala
server/src/test/scala/org/http4s/server/middleware/EntityLimiterSpec.scala

The apply method on EntityEncoder is awkward to call when the decoder
takes an implicit parameter.  This gives rise to awkward overloads, like
xml, which surprisingly provide a default without regard to the scoped
implicit.  By moving the call to the request, we can move the implicit
decoder to the end, and remove the syntactic urge for troublesome
overloads.
Request decodings that prefer to be explicit can use the new
`decodeWith` for a reasonable syntax.

Put decode helpers directly on Request for Response.

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientReceiver.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-core/src/main/scala/org/http4s/blaze/Http1Stage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala

Fix blaze-client when recieving HTTP1 without content-length header

---

core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/util/option.scala
core/src/test/scala/org/http4s/UriSpec.scala

For #185.  9919979 has a very direct, imperative implementation, that mirrors the RFC language closely to be sure that it worked; then a1d2985 includes a little better-looking ones.  I included both commits so you can have your choice of either or neither :-)
The test suite currently includes a straw-man Uri parser in UriSpec.scala, which is good enough to pass all of the tests.  It can be deleted as soon as #184 is squared away.  (The tests also pass with the parser in @bryce-anderson's issue/184 branch.)

add Uri.resolve(Uri) out of RFC 3986, plus tests #185

---

core/src/main/scala/org/http4s/Uri.scala

to avoid this error:
```
[error] not found: value Uri
[error]   val x = org.http4s.Uri.uri("http://uri.com")
[error]                             ^
```
without having to import the Uri object first.

use FQCN in uri macro

---

examples/jetty/examples-jetty.sbt
examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
examples/tomcat/examples-tomcat.sbt
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
jetty/jetty.sbt
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
project/Http4sBuild.scala
server/server.sbt
server/src/main/scala/org/http4s/server/ServerBuilder.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
tomcat/tomcat.sbt

An incomplete implementation of #35.  If `withMetricRegistry` is called, the Jetty and Tomcat builders will now gather server-specific metrics.  Users who don't call this will experience a bit of classpath bloat, but no runtime hit.
Viewing the metrics currently requires mounting a servlet.  This will be addressed in #196 so http4s-blaze-server can join the party.
I'd like to discuss unifying the metrics collected, but I'd first like to discuss what people like and don't like between these two implementations.  Even before that, I'd like to get this out there because wrongly named, incomplete numbers are better than no numbers at all.

Support gathering server metrics on servlet containers

---

server/src/main/scala/org/http4s/server/middleware/GZip.scala

When using the GZIp middleware, if the Accept-Encoding header is set but not gzip or x-gzip a scala.MatchError is thrown. I think in this case it should just fall through and continue processing the request.

GZip will not throw an exception if the Accept-Encoding header is not gzip 

---

client/src/main/scala/org/http4s/client/package.scala

This closes #206 
We should get our doc string testing working. The current form of this doc example won't actually run unless we instance a client and give it a uri that actually points to a server.

Fix doc example.

---

core/src/main/scala/org/http4s/parser/ContentTypeHeader.scala
core/src/main/scala/org/http4s/parser/ScalazDeliverySchemes.scala
core/src/test/scala/org/http4s/parser/HeaderParserSpec.scala

Partial cause of issue http4s/rho#50
I don't think we should be throwing things when the parser chokes else we return an Internal Service Error, which may be true, but not very informative to the user.

Dont throw exceptions from the HttpParser

---

src/jekyll/community.md

* Advertise Gitter conversation instead of channel.  I'm not ready to shut down IRC until that bridge is fixed, but I think most people prefer Gitter long term.
* If we're adding Gitter, I don't want to watch a mailing list that never took off.  Gitter + Issues is plenty of way to talk to us, I think.

Advertise Gitter over Freenode, retire mailing list.

---

core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
core/src/main/scala/org/http4s/parser/ScalazDeliverySchemes.scala
project/Http4sBuild.scala

This PR updates the parboiled version to 2.1, which is *not* binary compatible with 2.0, hence the necessity of the upgrade. Very few changes and the tests still pass, but I'm a total parboiled noob :-), so read this carefully.

Switch to parboiled 2.1

---

servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/ServletContainer.scala
servlet/src/main/scala/org/http4s/servlet/package.scala
servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala

The check in Http4sServlet comes too late: NonBlockingServletIo is the
default, and it already tries to load classes that aren't there.  It's
fine in the xsbt-web-plugin with Jetty 9, but Tomcat 7 exposes the
problem.
Make the ServletContextOps default to the proper servlet I/O version.
Constructing a servlet by hand will now default to blocking I/O.  When
we can break binary compatibility, we will reinstate the option to
select based on the server.

Don't accidentally load non-blocking servlet API. #229

---

blaze-core/src/main/scala/org/http4s/blaze/websocket/Http4sWSStage.scala
core/src/main/scala/org/http4s/websocket/Websocket.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
server/src/main/scala/org/http4s/server/websocket/package.scala

Uses a scalaz-stream `Exchange` (see [here](https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/Exchange.scala#L30)) to model a `WebSocket`. An `Exchange` is the standard way in scalaz-stream to model a "source/sink" pair.
This opens the door to future improvements through use of `Exchange` combinators and other functions from scalaz-stream or [scalaz-netty](https://github.com/RichRelevance/scalaz-netty/blob/master/src/main/scala/scalaz/netty/Netty.scala#L49).

Uses an Exchange to model a WebSocket.

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-client/src/main/scala/org/http4s/client/blaze/PooledHttp1Client.scala
blaze-client/src/main/scala/org/http4s/client/blaze/SimpleHttp1Client.scala
blaze-client/src/main/scala/org/http4s/client/blaze/package.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala

What should we do about version numbers? I know we will forget to update if we start hard coding them. Maybe we should think about generating the library version during build time.

blaze client should add a User-Agent header

---

examples/blaze/examples-blaze.sbt
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
project/Http4sBuild.scala
server/src/main/scala/org/http4s/server/middleware/Metrics.scala
server/src/main/scala/org/http4s/server/package.scala

Metrics can be done backend independently if we simple use it as a
middleware.
This implementation is modeled after the reference
metrics-jetty package.

Add Metrics middleware

---

dsl/src/main/scala/org/http4s/dsl/Path.scala
dsl/src/test/scala/org/http4s/dsl/PathSpec.scala

Don't strip trailing `/`s in Path. Formerly, `Root / "foo"` would match
both `/foo` and `/foo/`. Now, you can/must do `Root / "foo" / ""` to
match the latter.
*Note: this change seems likely to break user code, but did not break any existing test.*
URL-decode path segments, so that it's possible to encode characters
like `/` and space.

two small changes to Path parsing (fixes #257)

---

core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala

Thanks to @toby5box for pointing this out. See issue #226 for the
discussion.

Fix CTL definition in Rfc2616BasicRules

---

core/src/main/scala/org/http4s/HttpVersion.scala
core/src/main/scala/org/http4s/ParseFailure.scala
core/src/main/scala/org/http4s/QueryParam.scala
core/src/main/scala/org/http4s/parser/QueryParser.scala
core/src/test/scala/org/http4s/EntityDecoderSpec.scala
dsl/src/test/scala/org/http4s/dsl/PathInHttpServiceSpec.scala

A few places where leaking unsanitized information into the sanitized field of ParseFailure.
Removed some default arguments to make it explicit that there are two messages bundled in a ParseFailure: `sanitized` and `details`.

Fix unsanitized Strings in ParseFailures

---

core/src/main/scala/org/http4s/UrlForm.scala
core/src/test/scala/org/http4s/UrlFormSpec.scala

This commit extends the UrlForm API with some handy utilities:
- get
- getOrElse
- getFirst
- getFirstOrElse
The names should be fairly self explanatory. These are utilities I found myself writing when using UrlForm.

Extend UrlForm API

---

core/src/main/scala/org/http4s/EntityDecoder.scala

See issue #279 for motivation.
Many types of messages are encoded as text, and some have a default charset. In situations like this, the Content-Type header may not acutally specify the charset. See UTF-8 for an example. https://tools.ietf.org/html/rfc7159
The commit allows the specification of a default charset for the `EntityDecoder.decodeString` function for situations like these.
This should be uncontroversial. I'll merge this tomorrow morning barring objections.

Add `defaultCharset` to the decodeString function

---

core/src/main/scala/org/http4s/parser/QueryParser.scala
core/src/test/scala/org/http4s/parser/QueryParserSpec.scala

PHP encodes arrays in query strings using square brackets. This goes
against the spec, but PHP ain't got no time for your spec poindexter.
This is a minimal change that only allows square brackets in keys and
values. Arguably a more permissive parser (allowing any non-separator or
terminator character in keys and values) would be better for the wild
and crazy world we call the web.

Allow PHP-style [] in query strings

---

project/Http4sBuild.scala
project/build.properties

Missing: scalaz-specs2-0.4, which introduces breaking changes via
Specs2-3.x.

Omnibus dependency upgrade commit.

---

server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala
server/src/test/scala/org/http4s/server/MockRoute.scala
server/src/test/scala/org/http4s/server/middleware/AutoSlashSpec.scala

Closes #260.
Consider a route constructed with the built in DSL
```scala
Service{ case Root / "foo" => Ok("bar") }
```
Normally a request with uri = "/foo/" would fail to match, but with this middlware the request is first attempted normally, and if it fails to match, it will attempt again with the trailing slash removed uri="/foo".

Add middleware that removes a trailing slash from the Request

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala

This PR does not address any known bugs. The current default charset for String encoding is UTF-8. The default String encoder is used for json encoding and thus get the correct charset, UTF-8.
This PR just makes the specification of UTF-8 explicit for documentation purposes and as insurance against any unlikely change of the default in the future.

Explicitly specify the UTF-8 charset in json encoders

---

core/src/main/scala/org/http4s/Header.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
core/src/test/scala/org/http4s/parser/AcceptCharsetSpec.scala
core/src/test/scala/org/http4s/parser/AcceptEncodingSpec.scala
core/src/test/scala/org/http4s/parser/AcceptHeaderSpec.scala
core/src/test/scala/org/http4s/parser/AcceptLanguageSpec.scala
core/src/test/scala/org/http4s/parser/AcceptRangesSpec.scala
core/src/test/scala/org/http4s/parser/AuthorizationHeaderSpec.scala
core/src/test/scala/org/http4s/parser/CacheControlSpec.scala
core/src/test/scala/org/http4s/parser/ContentTypeHeaderSpec.scala
core/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala
core/src/test/scala/org/http4s/parser/ProxyAuthenticateHeaderSpec.scala
core/src/test/scala/org/http4s/parser/RangeParserSpec.scala
core/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
core/src/test/scala/org/http4s/parser/WwwAuthenticateHeaderSpec.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSpec.scala

I also renamed the class to HttpHeaderParser. That resulted in the bulk of the changes in the commit log. The only significant changes are in HttpHeaderParser.scala.

Add methods to allow modification of the parser registry.

---

core/src/main/scala/org/http4s/UrlForm.scala
core/src/test/scala/org/http4s/UrlFormSpec.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientPostExample.scala

This eases the common case of a POST request with a
x-www-form-urlencoded body.

Make implicit UrlForm encoder, improve syntax, show example.

---

core/src/main/scala/org/http4s/UriTemplate.scala
core/src/test/scala/org/http4s/UriTemplateSpec.scala

UriTemplate.expandQuery should respect a QueryParameterEncoder if supplied.

---

blaze-core/src/main/scala/org/http4s/blaze/Http1Stage.scala
blaze-core/src/main/scala/org/http4s/blaze/util/CachingStaticWriter.scala
blaze-core/src/main/scala/org/http4s/blaze/util/IdentityWriter.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http4sHttp1ServerStageSpec.scala
core/src/main/scala/org/http4s/headers/Transfer-Encoding.scala
project/Http4sBuild.scala

Previously, the identity was discarded and chunked encoding was used.
This change allows one to explicitly request identy encoding for times when
chunked encoding may not play well.
See server side events for an example: http://www.w3.org/TR/eventsource/

Handle Transfer-Encoding: identity correctly

---

dsl/src/main/scala/org/http4s/dsl/Path.scala
dsl/src/test/scala/org/http4s/dsl/PathSpec.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala

Comes from the Finagle HTTP path from which the DSL was originally
inspired.  Supports matching the remainder of a path after a
specified prefix.

Add a right-associative path extractor.

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala

This fixes a race condition that occured between generating and registering the timeout callback in the blaze client. The problem is pretty small: it should happen rarely and the fallout is not timing out a request.

Fix race condition with timeout registration and route execution in blaze client

---

server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/package.scala

Closes #299
It seems that files don't care about having a double '/' in the path,
but getting resources from the classpath happens to be sensitive to this.

Avoid "//" in path uris when serving static content

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientReceiver.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-core/src/test/scala/org/http4s/blaze/TestHead.scala

blaze-client will now check if an error has been registered and uses that to fail running requests.

blaze-client error checking

---

core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/test/scala/org/http4s/EntityDecoderSpec.scala

See #279, https://github.com/beloglazov/couchdb-scala/issues/4, and https://github.com/beloglazov/couchdb-scala/pull/5
The first attempt at fixing this was tharted by `Content-Type`.charset which will default to ISO-8859-1 if not defined. This PR avoids that default and adds some unit tests to demonstrate.

Second attempt at fixing decodeString

---

examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala

Topic feels like an overkill to implement an echo server. It's confusing for a new user who can't help but wonder why the use of topic is required.

Replace use of topic with Queue in websocket example

---

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/src/test/scala/org/http4s/client/JettyScaffold.scala

closes #294
Windows doens't allow 0.0.0.0 or such things quite the same way as *nix
systems.
Really, this fixes the test battery for all clients on windows, but there
is only one right now.

Fix blaze-client tests on windows

---

core/src/main/scala/org/http4s/Http4s.scala
core/src/test/scala/org/http4s/Http4sSpec.scala

This causes pain for Scalaz use.  We still need it in our tests, but it
didn't break any of our examples.
Fixes #323.

Don't extend AllInstances in Http4s omnibus import.

---

examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala

This used to work, but was lost along the way.  We need to set it
on the async context, and then actually run the timeout renderer.
Relates to #336.

Respect asyncTimeout in servlet backends.

---

server/src/main/scala/org/http4s/server/middleware/Timeout.scala
server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala

Provides method to allow custom response for those who think
of themselves as a proxy or gateway, and should be returning
504.
Fixes #345.

Change default timeout status code to 500.

---

blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/EntityEncoder.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/UrlForm.scala
core/src/main/scala/org/http4s/headers/Accept-Charset.scala
core/src/main/scala/org/http4s/headers/Content-Type.scala
core/src/main/scala/org/http4s/package.scala
core/src/main/scala/org/http4s/util/package.scala
core/src/test/scala/org/http4s/EntityDecoderSpec.scala
core/src/test/scala/org/http4s/util/DecodeSpec.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
scala-xml/src/main/scala/scalaxml/ElemInstances.scala
twirl/src/main/scala/org/http4s/twirl/TwirlInstances.scala

Quoth https://tools.ietf.org/html/rfc7231#appendix-B:
> The default charset of ISO-8859-1 for text media types has been
> removed; the default is now whatever the media type definition says.
> Likewise, special treatment of ISO-8859-1 has been removed from the
> Accept-Charset header field.  (Section 3.1.1.3 and Section 5.3.3)
Quoth https://tools.ietf.org/html/rfc6657#page-3:
> Thus, new subtypes of the "text" media type SHOULD NOT define a
> default "charset" value.  If there is a strong reason to do so
> despite this advice, they SHOULD use the "UTF-8" [RFC3629] charset as
> the default. [...]  However, existing "text/*" registrations that fail to specify 
> how the charset is determined still default to US-ASCII.
Downside: This will break things that relied on the deprecated ISO-8859-1 …

Use UTF-8 by default.

---

dsl/src/main/scala/org/http4s/dsl/Path.scala

It's hiding `Path.unapplySeq`.
Fixes #352.

Remove `Path.unapply` 

---

build.sbt
project/Http4sBuild.scala
server/src/main/scala/org/http4s/server/package.scala
server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/ResourceServiceSpec.scala

Another experimental offshoot of #332.
A `PartialFunction` can now optionally be lifted into a `PartialService`, which gets back its `or` and `orElse` operations via syntax.  This supports a chaining style for those who want it, but tucks it out of the way because most people won't.
There is probably something clever to be done with middleware here, but I'm done being clever until someone supports this idea.

A better PartialService, for those who like to chain.

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http4sHttp1ServerStageSpec.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala

Compatible backends can enable websockets with
```
myBuilder.withWebSockets(true /* or 'false' */)
```
Blaze server builder supports the new mechanism.

Add WebSocketSupport to the ServerBuilder mechanism

---

.travis.yml
build.sbt

Applying the java 8 lambdas considerably shrinks the final jars (due to the reduced number of classes, etc)
e.g.
-rw-r--r-- 1 rhansen rhansen 307465 Jul 14 14:40 ../http4s/server/target/scala-2.11/http4s-server_2.11-0.9.0-SNAPSHOT.jar
-rw-r--r-- 1 rhansen rhansen 206861 Jul 14 14:42 server/target/scala-2.11/http4s-server_2.11-0.9.0-SNAPSHOT.jar

Use java 8 lambdas with scala 2.11.7

---

build.sbt
project/Http4sBuild.scala

Also removed blazeExample build bits for determining if we are running JDK < 1.8.
http2 examples needed a forked JVM.

Fix the blaze SSL and http2 examples

---

server/src/main/scala/org/http4s/server/package.scala

Otherwise web browsers will just render a blank page.
I've done the `Task.now(foo.run)` to fully build the new `Response` so there is less for the backends to needlessly repeat. If that is in poor taste, we can remove it.

Add a message to the default notFound

---

build.sbt
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
core/src/main/scala/org/http4s/EntityEncoder.scala

This PR configures specs2 to only report on test failure while removing loglevel manipulation in the build.
Two println statments where also removed, one was in core which is a no-go.

Make tests log something on failure

---

dsl/src/main/scala/org/http4s/dsl/Path.scala
dsl/src/main/scala/org/http4s/dsl/package.scala

So user can specify multiple Http methods that the request can possibly match, with the same path in one line....
val request: Request = ??? 
request match {
case (Method.GET | Method.POST) -> Root => ???
}

Http Method 'or' extractor

---

blaze-core/src/main/scala/org/http4s/blaze/websocket/Http4sWSStage.scala

Is it just me or would it not be more appropriate to log an error if the user stream terminates with an error?

Log error on user output stream terminating with an error

---

core/src/main/scala/org/http4s/Query.scala
server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
server/src/test/scala/org/http4s/server/middleware/UrlFormLifterSpec.scala

The UrlFormLifter is a middleware that will lift a `application/x-www-form-urlencoded` body into the Query params.
NOTE: this doesn't have tests yet. I envision debating its structure/behavior then I'll write tests and merge it (if we want it merged).

Add UrlFormLifter middleware

---

core/src/main/scala/org/http4s/StaticFile.scala

Not sure if we should send back a `404` instead, but this change can be
justified given the existing code sends back `None` if `f` is not a
file.

`f.length()` returns 0 instead of throwing error if f does not exist

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/ConnectionManager.scala
blaze-client/src/main/scala/org/http4s/client/blaze/PoolManager.scala

This is a quick fix for ensuring that the body of a request isn't perturbed until it is known that a connection is a fresh one.

PooledClient will request a fresh connection for requests with a body

---

core/src/main/scala/org/http4s/StaticFile.scala
core/src/test/scala/org/http4s/StaticFileSpec.scala

Closes #322
As it turns out `Files.probeContentType` is buggy. Therefor, for the sake of consistent behavior, we will now use the filename extension to determine the media type through the `MediaType.forExtension` function.

Change StaticFile to use extension to determine MIME type

---

blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketSupport.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http4sHttp1ServerStageSpec.scala
client/src/main/scala/org/http4s/client/oauth1/oauth1.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/MessageOps.scala
core/src/main/scala/org/http4s/MessageSyntax.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala
server/src/test/scala/org/http4s/server/middleware/VirtualHostSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala

Closes #383.
The similarity of `withHeaders` to `putHeaders` has caused unnecessary confusion. Note that this PR also fixes a few bugs, in particular in the client oath1 support, that are due to the confusion.

Rename `withHeaders` to `replaceAllHeaders`

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala

This enables hostname verification for HTTPS connections.
As it stands, even if we configure a `{Simple|Pooled}HTTP1Client` with a `SSLContext` that will verify certificates, it won't verify that the certificates are for the correct host. This change means that that verification _will_ happen, even for clients using the default configuration. Verification failures are communicated in the same way as with invalid certificates – a `java.net.ssl.SSLHandshakeException` is thrown.
For background, see [fixing hostname verification](https://tersesystems.com/2014/03/23/fixing-hostname-verification/). As the blog details, the `setEndpointIdentificationAlgorithm` method requires constructing the `SSLEngine` with the remote host and port.

Set HTTPS endpoint identification algorithm when possible

---

blaze-core/src/main/scala/org/http4s/blaze/util/ProcessWriter.scala
blaze-core/src/test/scala/org/http4s/blaze/util/DumpingWriter.scala
blaze-core/src/test/scala/org/http4s/blaze/util/ProcessWriterSpec.scala

The private `go` method is now tail recursive. For calls that must run async including writing to the wire and running Task.awaits, they run on the provided ExecutionContext which is assumed to be stack safe.
Some unit tests are added including a test for stack safety.

Some rework of the blaze ProcessWriter

---

docs/src/jekyll/index.md

This comes up from time to time and someone suggested noting it on the website, so here it is.

Add a note about the Java 8 requirement.

---

client/src/main/scala/org/http4s/client/middleware/Retry.scala
client/src/test/scala/org/http4s/client/middleware/RetrySpec.scala

This pull request includes middleware for a Retry client that takes a RetryPolicy. Currently the only policy implemented is exponential backoff.

adding Retry client middleware

---

build.sbt
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/package.scala
circe/src/test/scala/org/http4s/circe/CirceSpec.scala
project/Http4sBuild.scala

This PR adds a module for circe, similar to the one for argonaut. It depends on the current *snapshot* version of circe (0.2.0-SNAPSHOT).
Users should be aware that in practice, when they're using the circe-generic module from circe along with http4s-circe, they are pulling a shapeless version (currently 2.3.0-SNAPSHOT) that is not fully binary compatible with the one parboiled depends on here (2.1.0). A small test server of mine was fine with it though (no `ClassDefNotFound` and the like).

Add circe module

---

core/src/main/scala/org/http4s/headers/ETag.scala
core/src/main/scala/org/http4s/headers/If-None-Match.scala
core/src/main/scala/org/http4s/parser/AdditionalRules.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
core/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

fixes #446
Parsing of the `entity-tag` rule was previously malformed and only
accepted alpha-numeric characters.
Changes include ETAG and IF_MODIFIED_SINCE parsers. Notably, the
IF_MATCH header doesn't exhist and would use the same parsing bits.

Fix parsing of `entity-tag` rule

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala

closes #450
Problem: The values were hard coded to some reasonable defaults.
Solution: Honor the parameters passed by the user.

Honor connectorPoolSize and bufferSize parametesr in BlazeBuilder

---

server/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala

Problem: The Travis-ci builds fail relatively often (maybe 1/3 of the time?)
due to timeouts not happening when they should. This is likely caused by the
short timeouts and delays set in the unit tests combined with the heavy load
on the server while running tests concurrently.
Solution: Extend the durations so that threads are more likely to restart in
within their specified duration.
Bonus: make the default max entity size in the `EntityLimiter` easier to
read.

Extend timeout and wait durations in test to help travis builds

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala

`append` will not run the process if it terminates abnormally but we want cleanup to occur regardless.
This may be related to a file handle leak observed by some client users.

Change blaze stage cleanup to use stream `onComplete` as opposed to `append`

---

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala

Problem: the `method` parameter wasn't being used for redirects which ends up breaking 303 response codes which should redirect with a GET method.
(See https://tools.ietf.org/html/rfc7231#page-57 for why we need to use a GET for 303 redirects)
Solution: use the parameter.

Fix FollowRedirect client middleware

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/ClientTimeoutStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala

Problem: If a body isn't used the socket may never be released.
Solution: Adding a finalizer will ensure that the stage shuts down and presumably performs resource cleanup.

Add a finalizer to the BlazeClientStage trait

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/PoolManager.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
build.sbt

For fear of hitting a stale connection after consuming part of the body, we made no attempt to recycle requests with bodies. With this change, we can verifying the connection health by writing the header before consuming any portion of the body.

Permit recycling of requests with bodies.

---

core/src/main/scala/org/http4s/EntityDecoder.scala

Problem: The EntityDecoder trait is sealed, making it impossible to create EntityDecoder's that can access the message body.
Solution: Unseal it. The only reason to keep it sealed would be to allow totality checking with pattern matching but considering the problem EntityDecoder is intended to solve that seems like an highly improbably use case.
Mima reports no potential binary compatibilities with this PR.

Unseal the EntityDecoder trait

---

core/src/main/scala/org/http4s/Status.scala
dsl/src/main/scala/org/http4s/dsl/package.scala

HTTP 451was approved by the IESG on December 18, 2015.
https://en.wikipedia.org/wiki/HTTP_451

Add HTTP 451 Unavailable For Legal Reasons status

---

project/Http4sBuild.scala

There are quite a few (good) things happening in blaze master to in order to keep track of the fallout I would like to bump http4s master to depend on teh blaze master snapshots.

Bump blaze dependencies to 0.11-SNAPSHOT

---

core/src/main/scala/org/http4s/util/package.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala

Instead of throwing IllegalStateExceptions, make them more
fatal in nature, with a nice link to our bug tracker.
Bonus: get rid of the null sentinel in the servlet reader.

Add a `bug` constructor for when the type system lets us down.

---

core/src/main/scala/org/http4s/util/Renderable.scala

Problem: the old java time api really sucks and even the formatter isn't thread safe.
Fix: Do the right thing and use the new api. It is thread safe (allegedly...) and this should actually be more efficient.
closes #489

Fix Instant rendering

---

blaze-client/src/main/scala/org/http4s/client/blaze/PoolManager.scala

When the client is asked to make a request that cannot be opened (say, invalid Uri) it will enter an infinite loop because the failure path creates a new connection with the same key, simply failing again, etc...
This commit changes that behavior by simply discarding the connection at that point and handing the origin that failure.
This commit also changes behavior: previously if the pool received a closed connection it would open a new one to the same endpoint and place it in the idle queue. This commit doesn't do that though it would be trivial to add.
This commit also changes a strange behavior on returning a connection. Previously, if there were waiting connections but they didn't match this endpoint the connection would simply be returned to the idlequeue. This causes a potential …

Fix infinite loop

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1ClientStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/PoolManager.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-core/src/main/scala/org/http4s/blaze/Http1Stage.scala

Before this commit the blaze components would see if there wasn't a body and if there is, it would begin a streaming style parsing strategy. This commit changes the second half. The new stragegy examines any remaining bytes to see if that consists of the entire body. If so, wonderful. If not, we go back to the streaming strategy.
This behavior helps the client cleanup more efficiently.

Optimization of body collection for blaze components

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
client/src/main/scala/org/http4s/client/Connection.scala
client/src/main/scala/org/http4s/client/PoolManager.scala

If the parser is not complete when we return the body, we rely on a cleanup
hook of the body to either reset or shutdown the connection.  If this body is
not run to completion, neither happens.  This leaves the client in the
`Running` state.
Meanwhile, the pooled connection manager happily recycles any connection that
is not closed.  Hilarity ensues.
This exposes a check that the connection is recyleable, which in the blaze case
is true only when the connection has been able to reset itself.

Fix 'Stage has request in progress' leak.

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala

Old flow:
1. Borrow a request that had closed while idling.  We don't
know until we write to it.
2. Invalidate the connection and then loop with the *same*
connection.  The state is now Error.
3. On loop, we get the `InProgressException` and fail.  Invalidate
the connection again.
In step 2, we need to borrow a new connection, not retry the
invalidated connection.  This is a recent bug.
This prevents us from falling through to step 3, where the
second invalidation of the same connection caused another
decrement in the pool manager, leading to negative connection
values.
Bonus cleanup in `runRequest`: Now an `InProgressException` only
comes from a running request.  If something had moved the
connection into error state and we try to run it, we return the
error, which is now handled …

Fix bug in EOF handling within `BlazeClient`

---

core/src/main/scala/org/http4s/Message.scala

The body of a scalaz-stream does not tend to have a very
legible toString.  Ways of making it legible often require
running the body, which should only be done once.
A process of pure Emits of character data can be turned into
a String.  We can do that, for the subset of messages that
are pure emits.  If we *don't* do that, we're still
leaking the contents of the body, but not in a format that
can be sanitized by a reasonable log filter.
We can't anticipate all the things a user wants to log or not,
but we should at least make it obvious to the user what is
being logged.

Remove body from request.toString and response.toString.

---

async-http-client/src/main/scala/org/htt4s/client/asynchttpclient/AsyncHttpClient.scala
async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
async-http-client/src/main/scala/org/http4s/client/asynchttpclient/QueueSubscriber.scala
async-http-client/src/main/scala/org/http4s/client/asynchttpclient/UnicastSubscriber.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/QueueSubscriberTest.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/WhiteboxSubscriber.scala
build.sbt
project/Http4sBuild.scala

A new http4s client implementation with uses AsyncHttpClient with streaming, shutdown, configuration management and disposal. Not sure if usage of Promise[DisposalResponse] and async.unboundedQueue is correct.

asynchttpclient

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala

Take advantage of `task.futureToTask` taking a by-name
parameter to prevent the future from running prematurely.

Don't execute request until Task runs.

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-core/src/main/scala/org/http4s/blaze/util/ProcessWriter.scala
client/src/main/scala/org/http4s/client/PoolManager.scala
core/src/main/scala/org/http4s/package.scala
core/src/main/scala/org/http4s/util/threads.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala

1. Use the passed in buffer size instead of repeating the parameter.
2. Skip the promise and just use `Task.async`.
3. While we're at it, unify on one callback alias. 
4. Give the async-http-client threads a sensible name.

More cleanup on async-http-client

---

json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
json4s/src/test/scala/org/http4s/json4s/Json4sSpec.scala

It's not as typeclassy as our other json integrations, but neither is json4s.  ¯\_(ツ)_/¯

Provide an EntityDecoder based on json4s' extract.

---

argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
project/Http4sBuild.scala

Get upstream fix by upgrading to jawn-0.8.4.
Fixes #514.

Fix parsing of 8-bit characters after an escape sequence.

---

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala

This is an effort to combat the Travis timeouts.  Intends to fix #529.

Run client route test battery sequentially and in isolation.

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientConfig.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeHttp1ClientParser.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-client/src/main/scala/org/http4s/client/blaze/PooledHttp1Client.scala
blaze-client/src/main/scala/org/http4s/client/blaze/SimpleHttp1Client.scala
blaze-client/src/main/scala/org/http4s/client/blaze/bits.scala
blaze-client/src/main/scala/org/http4s/client/blaze/package.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeSimpleHttp1ClientSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ExternalBlazeHttp1ClientSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
client/src/main/scala/org/http4s/client/impl/DefaultExecutor.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
examples/blaze/src/main/resources/logback.xml

closes #534
This PR was motivated by commit 05ad145. Each commit is relatively self contained
- 5693cb7: Add the `BlazeClientConfig` class to trim down the number of parameters passed around
- 05ad145: Add the ability to configure the blaze http1 parser for things like max header lengths
- b7a79b2: unify the client `ExecutorService` management

Create a config object for the blaze client and allow HTTP/1.X parser configuration

---

core/src/main/scala/org/http4s/parser/AdditionalRules.scala

`Content-Length` requires at least one digit:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13
I thought it was safe to change the definition of `Digits` because it only seems to be used in the one place: https://github.com/http4s/http4s/blob/d525219bce17c4d59985e91afd740be1f3fb6d1e/core/src/main/scala/org/http4s/parser/SimpleHeaders.scala#L56

fix ContentLengthSpec exceptions by fixing Rfc2616 rules

---

core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/MessageFailure.scala
core/src/test/scala/org/http4s/EntityDecoderSpec.scala

- List ALL supported media types when failing to decode using a composite decoder (build with `orElse`)
- changes to message wording
- use renderString on MediaRanges instead of standard case class to String to produce nicer message for logging
- use logging message for http response since it does not contain any sensitive information (I think?)

Improve error message for unsupported media type decoding error

---

build.sbt
project/Http4sBuild.scala

This allows us to get away from the version hacks in the build surrounding shapelss 2.2.5

Upgrade parboiled dependency to 2.1.1

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientConfig.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeHttp1ClientParser.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
project/Http4sBuild.scala

The lenient parser will accept illegal chars in header values and the response line but will replace them with the replacement character (0xFFFD).
This PR supersedes #474

Add a lenient flag to the blaze config object

---

examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/NoneShallPass.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/NoneShallPass.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
servlet/src/main/scala/org/http4s/servlet/DefaultFilter.scala
servlet/src/main/scala/org/http4s/servlet/ServletContainer.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

Closes #472.
As noted on #472, it's not "the http4s way," and not recommended for general use, but it is handy for those who are heavily invested in the servlet ecosystem.

Implement mountFilter for servlet backends.

---

core/src/main/scala/org/http4s/Cookie.scala

It turns out that there is no difference between the content
allowed for an unquoted string and a quoted  string. Old
implementations didn't allow double quotes at all so its
best to just remove them all together.
This is in line with the behavior of the cookied parser.

Don't quote cookie values

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala
build.sbt
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
jetty/src/test/scala/org/http4s/server/jetty/JettyServerSpec.scala
server/src/main/scala/org/http4s/server/Server.scala
server/src/test/scala/org/http4s/server/ServerAddressSpec.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSpec.scala

When binding servers to port 0, it's important to be able to query which port actually got bound.
Fixes #557.

Add address socket address to Server trait.

---

blaze-core/src/test/scala/org/http4s/blaze/TestHead.scala
client/src/main/scala/org/http4s/client/Connection.scala

This is a bug in a test...
If the test head serves a chunk it wouldn't reset its state. Then if
it tries to serve another the previous request was still sitting there
and causes a weird error.

Fix read request bug in SlowTestHead

---

core/src/main/scala/org/http4s/Uri.scala
core/src/test/scala/org/http4s/UriSpec.scala

- Update doc on `Uri` to reflect reality
- Calling `Uri.fromEncoded` now yields a ParseFailure if the uri is not url-encoded
- Add test for parse failure and give a minor facelift to a section of `UriSpec`

Fix false positive in Uri.fromString and rename to Uri.fromEncoded

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerParser.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/ProtocolSelector.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala

Now it is possible to configure the max request line length and max headers length. This
is to avoid denial of service attacks where an evil user sends an endless request line
resulting in OOM on the server.
This behavior was already enabled before but utilized hard coded values for the cutoffs.
Some headers may be huge (think cookie session) so its not out of the question that the
headers could be very large in a minority of situations.

Enable configuration of blaze server parser lengths

---

docs/src/site/index.md

The link to the code of conduct on the home page pointed to [/conduct.md](http://http4s.org/conduct.md) instead of [/community/conduct.html](http://http4s.org/community/conduct.html).

Fix broken link to code of conduct on the home page.

---

blaze-server/src/main/scala/org/http4s/server/blaze/ProtocolSelector.scala

The Http2Stage no longer has a public constructor so we use the apply
function on the package object.
This is staged until I merge https://github.com/http4s/blaze/pull/39
I'll cowboy push it tomorrow unless someone objects.

Needed to keep up with api changes in blaze

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala

The string was missing the 's' before the quotes resultin in a lack
of string interpolation.

Fix Argonaut string interpolation

---

build.sbt
docs/README.md
project/Http4sGhPages.scala

Without this, the maintenance branches with older copies of the main site can overwrite changes, create races, etc.  One branch needs to be canonical for each part of the site.

Suppress building the main site from non-master branches.

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
build.sbt

There were two calls to `Task.apply` that didn't explicitly take an
ExecutorService.
This resulted in a new mima exception for the constructor method of `Http1Connection`. This class is private so the constructor change shouldn't leak to users.

Remove implicit resolution of Strategy.DefaultExecutor

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/test/scala/org/http4s/circe/CirceSpec.scala
json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
json4s/src/test/scala/org/http4s/json4s/Json4sSpec.scala

This avoids a common name clash that shadows the implicit and makes the
library more foreboding to new Scala users.
Fixes #599.

Rename `json` to `jsonDecoder`

---

examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeHttp2Example.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/JettySslExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslExample.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatSslExample.scala
server/src/main/scala/org/http4s/server/Server.scala
server/src/main/scala/org/http4s/server/ServerApp.scala

Provides a graceful mechanism for starting and stopping an embedded server.
Responds well to kill signals for me.  ^C, which should be a SIGINT, is hit and miss within sbt.  Explicit shutdown requests also work reliably for me.
The exposed lifecycle is imagined to be useful in implementing health check endpoints.

Add a ServerApp trait.

---

bin/publish
bin/travis
build.sbt
project/Http4sBuild.scala

This makes it easier (IMO) to change the scalazVersion. Instead of failing silently if there is a typo in the Java Property key, you get autocomplete in the sbt console!

Create `scalazVersion` sbt `SettingKey` in order to avoid relying on Java Properties

---

project/Http4sBuild.scala

It's binary compatible, so targeting 0.13.x.

Upgrade to scalaz-stream-0.8.1.

---

core/src/main/scala/org/http4s/MessageFailure.scala
core/src/test/scala/org/http4s/EntityDecoderSpec.scala

We need to return `422: UnprocessableEntity` according to [this](http://www.restpatterns.org/HTTP_Status_Codes/422_-_Unprocessable_Entity) for message bodies which are well-formed but contain incorrect values.

Added a MessageBodyFailure case returning UnprocessableEntity

---

core/src/main/scala/org/http4s/multipart/MultipartParser.scala
core/src/test/scala/org/http4s/multipart/MultipartParserSpec.scala

Preserves the distinction between semantic and syntactic failures.
This becomes more important when the status code changes in #625.

Use MalformedMessageBodyFailure for malformed multiparts

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientPostExample.scala

`fetchAs` and `getAs` have quirky semantics when the response is not
successful.  It is unusual that the body of a 4xx or 5xx response will
decode to the same type as desired in the successful case.  This returns
the unexpected status code in a failed task.
Fixes #587

Replace `fetchAs` and `getAs` with `expect`

---

CHANGELOG.md
bin/publish
build.sbt
project/Http4sBuild.scala

Most of the argonaut community is still on version 6.1.  The only reason we jumped to 6.2 milestones was to support scalaz-7.2, but this has caused pain for the people who are really using argonaut.  Now that argonaut crossbuilds for scalaz, we can use the standard, and upgrade when the argonaut team blesses 6.2.

Downgrade argonaut to last stable release (6.1)

---

client/src/main/scala/org/http4s/client/Client.scala
core/src/main/scala/org/http4s/MessageOps.scala

As the latest version of http4s is 0.14.x, I think we can remove deprecated methods before 0.14. I also fixed a typo and unnecessary documentation, which should be fine I hope :)

Clean up deprecated code

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala

This accomplishes two things:
1. Exceptions end up as failed tasks
2. We don't leak resources
Fixes #664

Catch exceptions thrown from response callback in client

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala

It only appears when tracing is enabled, but still.

Remove a lingering println

---

core/src/main/scala/org/http4s/headers/Expires.scala
core/src/main/scala/org/http4s/parser/AdditionalRules.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
core/src/test/scala/org/http4s/TestInstances.scala
core/src/test/scala/org/http4s/headers/ExpiresSpec.scala

This PR lets users easily create the `Expires` header and supports parsing on the usual `Date` format as well as bogus values used by some servers to denote expiration like `0` or `-1`

Improvements to Expires header

---

core/src/main/scala/org/http4s/Header.scala

It's so unlikely that we face thread contention parsing these, we'd
rather pay to parse the same field twice in that rare case than to pay
for the locking on each access.

Replace lazy `Raw.parsed` field with a simple null check

---

LICENSE
README.md

A friendly lawyer advised that we did not correctly declare the license.  We need to include a full copy of the text, and the "boilerplate" we previously had in LICENSE should go into the README, and, ideally, the source headers.
This is _not_ a change in the license.  We have always been, and still will be, Apache 2.

Use full text of Apache 2 license

---

core/src/main/scala/org/http4s/Uri.scala
core/src/test/scala/org/http4s/UriSpec.scala

This is a scheme-specific normalization which is further down the
"comparison ladder" in RFC3986 than I think we care to get.
This makes the rendering match the equality semantics.
Fixes #676.

Don't render a "/" for an empty path when none is provided

---

examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientExample.scala
examples/src/main/scala/com/example/http4s/site/HelloBetterWorld.scala

These were from a custom jekyll plugin that is no longer in use.
Compiled documentation belongs in tut.

Remove code_ref tags

---

core/src/main/scala/org/http4s/ServerSentEvent.scala
core/src/test/scala/org/http4s/ServerSentEventSpec.scala

Up to one space gets trimmed.  If data actually begins with a space,
which is a horrible thing to rely on but the kind of thing property
testing finds, then the optional space becomes mandatory.  It's simpler
just to always render it.
Fixes the Travis failure in #691 .

Render SSE with the leading optional space.

---

core/src/main/scala/org/http4s/ServerSentEvent.scala
core/src/test/scala/org/http4s/ServerSentEventSpec.scala

data and event for correctness, retry for consistency.
This was meant to be part of #693, but I gitted too fast.

Also space-pad data, event, and retry fields.

---

core/src/main/scala/org/http4s/Fallthrough.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/Service.scala
core/src/main/scala/org/http4s/package.scala
server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/src/test/scala/org/http4s/server/HttpServiceSpec.scala
server/src/test/scala/org/http4s/server/RouterSpec.scala

As [imagined here](https://github.com/http4s/http4s/pull/692#discussion_r76735381).
If we just call `Service.lift` on a `PartialFunction`, then match errors
will occur.  It won't fall through nicely.  A default argument is not
yet possible, because there is no `Service.empty`, because `Fallthrough`
doesn't declare a default value.

Provides Service.apply methods like HttpService.apply

---

core/src/main/scala/org/http4s/EntityEncoder.scala

- Encoding a StringBuffer or StringBuilder is probably a bug
- This may be causing http4s/rho#136

Replace CharSequence encoder with one for CharBuffer

---

core/src/main/scala/org/http4s/EntityEncoder.scala
core/src/test/scala/org/http4s/EntityEncoderSpec.scala

Just because they're possible doesn't mean they're useful.  It's
doubtful anybody is encoding a single char or byte in this way, so let's
not tempt the Ambiguous Implicit Fates.
Proposed by @bryce-anderson in #711.

Remove EntityEncoder[Char] and EntityEncoder[Byte]

---

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala

This is probably unusual, but it's a bug.

Don't follow redirect if effectful chunks follow pure ones

---

build.sbt
client/src/main/scala/org/http4s/client/middleware/Retry.scala
client/src/test/scala/org/http4s/client/middleware/RetrySpec.scala
core/src/main/scala/org/http4s/Message.scala
core/src/test/scala/org/http4s/MessageSpec.scala

* Only retry idempotent requests with pure bodies
* Only retry when status code is appropriate
* Retry failed tasks from client
Partially addresses #712.  Further fixes (e.g., Retry-After) are binary incompatible and would come in a separate PR.

Improve Retry client middleware

---

core/src/main/scala/org/http4s/EntityEncoder.scala

Add parametric empty EntityEncoder, and use it to give an instance for Unit.
I would like to add an Option EntityEncoder as well, which uses this empty encoder in case of None, but I can't write an EntityEncoder that alters the headers based on the given A. This would be possible if toEntity had type (A => (Entity, Headers)) or something like that, but it's not possible now.
This would also let us create an EitherEncoder.

Empty EntityEncoder

---

build.sbt
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
jawn/src/test/scala/org/http4s/jawn/JawnDecodeSupportSpec.scala
project/Http4sBuild.scala

Update the jawn module for #661
This depends on the not-yet released jawn-fs2, so it does not build yet. I just created it to not forget about it :)

Update jawn module to use jawnfs2 instead of jawnstreamz

---

core/src/main/scala/org/http4s/CharsetRange.scala
core/src/test/scala/org/http4s/CharsetRangeSpec.scala

It's based entirely on the QValue.  This makes it possible to write an
`f: CharsetRange => CharsetRange` that determines the QValue by the
charset, and breaks `x eqv y ==> f(x) eqv f(y)`.
We could make it lawful by using the charset to break ties, but this has
no basis in the HTTP spec.  One part of the HTTP spec we missed was to
prefer atoms over splats.  All of this is specific to
content-negotation, and belongs in code there, not a general ordering.
This was uncovered by `Cogen` in cats-0.8.  It will be tested there.
/cc @ceedubs, whose morning I helped ruin with this.

Order[CharsetRange] is unlawful, so weaken it to Equal

---

docs/src/site/resources/http4s-logo-512h.svg

Wasn't sure where to put it, so it's in the docs site resources dir. This is the version from the right of the figma page, slightly tweaked so the letters are aligned to cube face centers, the cube faces are solid colours rather than shaded with low alpha overlays, and the corners join up exactly. Exported at 512 pixels high for neatness.

Add SVG logo at 512 pixels height.

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
argonaut/src/main/scala/org/http4s/argonaut/package.scala
argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/package.scala
circe/src/test/scala/org/http4s/circe/CirceSpec.scala
project/Http4sBuild.scala

Goals:
1. Don't break existing code
2. Preserve idiom of "importing package object does something reasonable"
3. Make it relatively easy to change default (e.g., `val custom = CirceInstances.withPrinter(???); import custom._`).  You will get brainteasers if you do this _and_ import the package object.
4. Allow explicit printing case-by-case (e.g., `jsonEncoderWithPrinter`)
I think this scratches most people's itches.
* ~[ ] json4s~
See #660, #697, #761 for related discussions. 
/cc @ceedubs @jcranky @etorreborre

Allow customization of pretty printers

---

server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuthentication.scala
server/src/main/scala/org/http4s/server/middleware/authentication/package.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSpec.scala

Basic Authentication module now supports passing the cleartext password to a function which can validate the password (for example, by comparing it against a hashed value). Previously, the basic authentication middleware require that the password be stored in plaintext on the server.
Closes #730.

Minimal support for hashed passwords in basicAuth

---

core/src/main/scala/org/http4s/Uri.scala

My code is littered with:
```scala
Uri.fromString(s).valueOr(throw _) // YOLO!
```
We have a macro to verify compile-time literals.  We have a safe method that deals with an either.  But it's a frequent use case to read a URI out of configuration and use it as a base for other URIs, and the ParseResult tends to get thrown away in the real world.  :(
A better idea might be a `Uri.apply` that tolerantly parses URIs.  But that digs up old consistency questions like:
- should `apply` on our model parse inputs strictly or tolerantly?
- if strictly, is there a naming convention for a more tolerant one?
- if `apply` is partial, can we still call it `apply`?  I like `unsafe` if it might throw. 
I guess I can live with the yolos through 0.15, but if we agree on a style, we might squeeze …

Provide an unsafe String => URI function

---

dsl/src/main/scala/org/http4s/dsl/Path.scala
dsl/src/test/scala/org/http4s/dsl/PathInHttpServiceSpec.scala

Matches (and validates) optional parameters that occur mutliple
times in the query string. For #771.

Optional, Validating, Multiple-Occurence Param Matcher

---

build.sbt

This can be filled in for other modules for greater effect, but the declarations become repetitive.  Does anybody know a clever way to accumulate packages provided by each dependent module?

Populate initial commands in sbt console

---

build.sbt

There are not, and will not be, main artifacts in this project.  MiMa goes looking for them, and fails with this message:
`not a directory or jar file: /home/travis/build/http4s/http4s/tests/target/scala-2.11/classes`
This is a fatal error, even though sbt never prints `[error]` and keeps trying to resolve other artifacts.

Don't run MiMa on tests project

---

server/src/main/scala/org/http4s/server/middleware/GZip.scala
server/src/test/scala/org/http4s/server/middleware/GZipSpec.scala

Fallthrough bites us again.  This bug happened because Fallthrough used to be based on response attributes, which survived a gzipping.  Now it's based on reference equality, which doesn't.
I think I'm going to launch another War on Fallthrough, but this fixes the regression in 0.15.0.
/cc @cquiroz

Let fallthrough responses through GZip middleware

---

docs/src/hugo/content/adopters.md

Missed the '4' when talking about Version's use of 'http4s'

Minor text change in documentation.

---

build.sbt
project/plugins.sbt

- Fixes the baseURL in hugo for Travis deployments, which will correct
the pager error that @zarthross identified.
- Uses sbt-travisci plugin to do it
- As a result, our build defaults to 2.12.1 now. This is good, as long
as we're not relying on anything deprecated.

Fix baseURL in hugo, default to 2.12.1

---

core/src/main/scala/org/http4s/DecodeFailure.scala

change ParseFailure msg value to details instead of sanitized version

#828 - Add details when JSON decode failure occurs

---

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala

When we redirect, we need to dispose of the original response before issuing another request.  Failure to do so results in n+1 borrows for n redirects before any responses are disposed.  In a tight loop, that deadlocks.
Fixes #796

Dispose of redirect responses in FollowRedirect

---

core/src/main/scala/org/http4s/Headers.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala

* the hashCode passes through to the `List` hashCode, so it is order dependent
* Headers are case classes and already have a sane hashCode, allowing the above to work correctly

Add a hashCode and equals to Headers

---

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala

Fixes a compilation error as >> is not in Cats. This is replaced with simple flatMapping.

Fixed Disposable Request Disposal in FollowRedirect

---

docs/src/main/tut/middleware.md

Found a small typo in the Middleware Documentation.

Fixed Typo in Middleware docs

---

docs/src/main/tut/json.md

Scalaz Task is encountering an error when declaring a change to a task and running
that task on the same line. json.md was the only file guilty of this. By modifying
the offending code tut now compiles on 2.12

Modified json.md for tut to Compile

---

server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuth.scala
server/src/main/scala/org/http4s/server/middleware/authentication/DigestAuth.scala

As the Authentication middleware doesn't "fall through" in a stack, there is no way to allow users to authenticate with multiple different auth sources. In order to enable that kind of functionality, the existing `getChallenge` method of both `BasicAuth` and `DigestAuth` must be public so external integrations can properly invoke them.
For example, consider the use case where users can authenticate either with an api key and secret (using HTTP Basic) _or_ with an OIDC token (using Bearer authentication). Assuming there is already a `BearerAuth` object that parses and validates the OIDC token, a combined authenticator would look something like:
```
object GenericAuth {
type GenericAuthenticator[A] = Credentials => Task[Option[A]]
def apply[A](realm: String, validator: …
```

Make the `getChallenge` method of bundled auth middleware public

---

bin/travis
docs/src/main/tut/json.md

After #853 tut should be able to compile using 2.12. 
Which means this branch should compile and make the new docs and site off of 2.12

Modified bin/travis to make site using scala 2.12

---

core/src/main/scala/org/http4s/EntityEncoder.scala

Adds an encoder for `ByteBuffer` and several tests. Fixes #870 
Somehow it feels to simple, I'm not sure if we need to do more about resource management of the buffer

EntityEncoder for ByteBuffer

---

core/src/main/scala/org/http4s/EntityEncoder.scala

They're going away in fs2-cats (#878), so let's start bidding them
farewell here.

Deprecate EntityEncoder for ByteBuffer and CharBuffer

---

core/src/main/scala/org/http4s/EntityEncoder.scala
tests/src/test/scala/org/http4s/EntityEncoderSpec.scala

This PR includes an `EntityEncoder[Reader]` for fs2. The implementation is closely based on fs2's implementation for `InputStream`
I discovered though that it is very slow for long readers but my debugging indicates the issue is not on the actual reading and encoding part but more on the way the fs2 stream is built. The slowness can be reproduced for `InputStream` with this test:
https://gist.github.com/cquiroz/53cea9bfd2fdbc3d452a037edd19e130
I welcome discussions about how to improve performance
Fixes #871

EntityEncoder for Reader

---

core/src/main/scala/org/http4s/EntityDecoder.scala

This entity decoder ignore the content and returns unit.

Adds a Unit entity decoder.

---

async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala
testing/src/test/scala/org/http4s/testing/ThreadDumpOnTimeout.scala
tests/src/test/scala/org/http4s/CharsetRangeSpec.scala

Adds `ThreadDumpOnTimeout` trait that can be mixed with `Http4sSpec`
to trigger a thread dump to console if any of specs2 expectations
take longer than a specified duration.
Introduced the new instrumentation in `CharsetRangeSpec` with a
2 second timeout for #774 and in `AsyncHttpClientSpec` with a
9.5 second timeout.  Hoping the latter will shine some light on
[this](https://github.com/http4s/http4s/issues/858#issuecomment-274133582) timeout.

log thread dump when specs with possible deadlocks exceed timeouts

---

build.sbt

This sets up defining `version` in an alternate way on the cats branch and keeping the releases in sync for #875.

Define http4sVersion key to derive version for cross builds

---

build.sbt

Test output will now include all specs2 expecations and how long
each took to complete.

turn on `showtimes` for specs2 to help diagnose #774

---

blaze-client/src/test/scala/org/http4s/client/blaze/ExternalBlazeHttp1ClientSpec.scala

Thread dumps[1,2] from #897 show `ExternalBlazeHttp1ClientSpec`
running just before `AsyncHttpClientSpec` times out.  Might be
coincidence, but it seems reasonable to have a (long) timeout for
calls to external URLs anyhow.
[1] https://travis-ci.org/http4s/http4s/jobs/197158086#L6885
[2] https://travis-ci.org/http4s/http4s/jobs/198883683#L8345
Refs #858 and #817

Set 30 second timeout on blaze client requests to github.com

---

tests/src/test/scala/org/http4s/CharsetRangeSpec.scala

Wait for up to 20 x 200ms intervals (4 seconds) before triggering
a thread dump.  Spec frequently runs for 1-2 seconds on Travis CI
infrastructure and the 2 second timeout was firing for tests that
were likely not deadlocked.
Would not have been a big deal, but the thread dumps put Travis
over its 4MB log limit and cause the job to fail.  Longer term,
if we keep the dumps, they should be written to a log file and
uploaded to S3 instead of polluting the console output.
Refs #774

Increase `CharsetRangeSpec` timeout to 4 seconds before thread dump

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala

```
case POST -> Root =>
req.as[Json].flatMap(Ok(_))
```
If we post `NOT JSON` to that, it should return a 400, not a 500.
This is a change in behavior, but I was quite surprised by the old behavior.  I would like to release this as a patch to 0.15.

Call toHttpResponse on MessageFailures failed/thrown by HttpService

---

project/Http4sBuild.scala

fs2 Recently Released version 0.9.3
Seems to work clean out of the gate.

Cats - Update fs2 dependency to 0.9.3

---

project/Http4sBuild.scala

New Version Is Out Which Solves the Memory leak in 0.9.3
Closes #922

Updated fs2 version to 0.9.4

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientConfig.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-client/src/main/scala/org/http4s/client/blaze/bits.scala

The SSL context used by default, when `BlazeClientConfig.sslContext` is `None`, trusts all certificates.  This is a bad production default, leaving users vulnerable to man-in-the-middle attacks.  We should default to `SSLContext.getDefault`.
Because we've all worked in sloppy development environments before, and because the Java SSL APIs are hostile, we provide an "insecure" blaze configuration for people who want things the way they were.

Switch to a default SSL context of SSLContext.getDefault

---

server/src/main/scala/org/http4s/server/middleware/CORS.scala
server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala

Don't log CORS when no `Origin` header is present, and soften to debug level when it's wrong.  Note that the debug line will still appear multiple times in the example of #932.  The reason for this is that the CORS middleware is invoked twice.  This can be mitigated by composing smaller services and wrapping the result in `CORS`, assuming the config is the same.  Alternatively, using a `Router` supports different CORS configs across prefixes.
Depends on #934.  Helps with #931. /cc @mxl

Quieter logging of invalid CORS requests

---

server/src/main/scala/org/http4s/server/middleware/CORS.scala
server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala

The problem is related to #803: we got stricter about what is a fallthrough in 0.15, without making good use of the type system.  The elimination of `Fallthrough` in 0.16 prevents this bug on master.
Fixes #933. /cc @mxl

Don't add CORS headers to a fallthrough response

---

build.sbt
project/Http4sBuild.scala

Takes scalaOrganization, but I don't think we have any crossbuild. I think this would be a different publication, and probably should also effect scala xml, but I wanted to put it out there for compatibility. 
typelevel/scala#135

Added option for compatibility with typelevel scala

---

.travis.yml

If this was here for another reason let me know, but project uses 0.13.13 so why don't we pull that?

Update Travis SBT for 0.13.13

---

.jvmopts
bin/travis

Reduce max heap usage to 1.5gb and max metaspace to 0.75gb to keep
the overal JVM usage safely below the 4gb allowed by Travis[1].
Longer version...
When Travis builds with 2.12.1 and scalaz-7.2 on master, it runs
with:
;coverage ;clean ;test ;makeSite ;mimaReportBinaryIssues ;coverageReport ;coverageOff ;publish ;ghpagesPushSite
Locally (with OpenJDK 1.8.0_121), I have seen the JVM for those
builds use more than 3.6gb of resident memory.  Strongly suspect
memory limit, and the kernel OOM killer steps in.
After monitoring several builds with VisualVM, 1.5gb should be
more than enough heap and capping the metaspace at 0.75gb (with
stack size of 6mb), keeps the large builds closer to 3.2gb max.
Fixes #965
[1] https://docs.travis-ci.com/user/migrating-from-legacy/#More-available-resources

Avoid Travis OOM by constraining memory usage during build

---

docs/src/hugo/layouts/index.html
docs/src/hugo/layouts/partials/head.html
docs/src/hugo/layouts/single.html

There might be a slight performance gain[1] for loading the
scripts late in the page.
More importantly, removes conflicting versions of jQuery that
could break some Bootstrap behavior.  For example, it was not
possible to add a (working) Bootstrap dropdown navigation menu
in `/v0.16/index.html` before this change.
[1] http://stackoverflow.com/a/1638705

Move script tags for jQuery and Bootstrap to bottom of page

---

.travis.yml
bin/travis

Revert to author to `Travis CI <travis-ci@http4s.org>` after change
in #970.  Include build metadata in the git commit message.
Example:
updated site
Job: 3748.6
Commit: 90626678
Detail: https://travis-ci.org/http4s/http4s/jobs/206466634

Better author and commit message when Travis publishes to gh-pages

---

CONTRIBUTING.md

Removed whitespace at the left that made it into a pre-formatted
code block.

Fix table of contents rendering in contributors guide

---

.travis.yml

Prevents Traivs builds in repos other than http4s/http4s from posting to the http4s Gitter channel.

Extract webhook URL for Gitter into Travis environment

---

project/Http4sPlugin.scala

Cats branch is already using it.  Artifacts are binary compatible.
Let's help them test it.

Use Typelevel Scala where available

---

docs/src/hugo/content/versions.md
docs/src/hugo/layouts/index.html
docs/src/hugo/layouts/partials/head.html
docs/src/hugo/layouts/partials/nav-docs.html
docs/src/hugo/layouts/partials/nav.html
docs/src/hugo/layouts/single.html

Introduces "Documentation" dropdown with direct links to the v0.15
and v0.16 tuts and scaladocs.  Relocated "Versions" menu item under
"Documentation".
Fixes #819 and #903

Add documentation dropdown menu to website navbar

---

.travis.yml

I can't reproduce the metaspace problems locally, and the JDK is one
variable.  The one in the Travis container (1.8.0_31) is ancient.
Does this help?

Install a fresher JDK in Travis

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
docs/src/main/tut/error-handling.md
server/src/main/scala/org/http4s/server/package.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala

When a server converts a `MessageFailure` to an HTTP response, we're throwing away the diagnostic information that comes in the message.  The response renderings are carefully designed not to reflect request information back to the client to guard against XSS attacks by default, but at the very least the server operator should be able to support clients.  This logs all such failures to `org.http4s.server.message-failures` at DEBUG level.
Fixes #980, starts on #981.
This is binary compatible and can be released as a patch to 0.15.x.
Thanks to @thetrav for reporting this.

Log unhandled MessageFailure before backends render them

---

bin/travis

The change to `$TRAVIS_BUILD_NUMBER == 1` in commit 96bb7c5e
did not work as expected.  That value is a counter that
increments for every Travis run.  3817 is a recent example.
This is an example job showing the wrong behavior:
https://travis-ci.org/http4s/http4s/jobs/207603576#L320
Travis is building with Scala 2.12.1 and scalaz 7.2.8, but only
running with `;test ;publish`.
Switched back to checking $TRAVIS_SCALA_VERSION and $SCALAZ_VERSION
because it works and is more explicit.  Looked for a Travis environment
variable for the position in the matrix, but it's not exposed directly.
Would need to use the suffix of $TRAVIS_JOB_NUMBER.
Also extract some of the shell script logic into named functions
so it's easier to follow the guts of the script.  Might make sense
to move those function …

Fix logic to pick Travis job where coverage and mima are run

---

.jvmopts

Floating this as a temporary measure to get more green out of
Travis until we fix the root causes of metaspace usage under
control.  The build's excessive use metaspace isn't new; it just
became more visible after the recent `.jvmopts` addition (e2fc00aa).
@rossabaker has started some work to improve things in the specs
and I would want to see either a `git revert` on this commit once
we make progress, or perhaps a reduction in the max we allow.
Also worth saying that http4s itself is not a metaspace hog, the
compile and test suite is.
Refs #988

Temporarily allow Travis to use more metaspace

---

build.sbt
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala

* `genCharsetRangeNoQuality` -> `arbitraryCharset.arbitrary`
* `arbitraryCharset.arbitrary` -> `arbitraryNioCharset`
Each needs the lock of the other.  This is a "non-circular dependency"
as described in SIP-20.
A better solution based on defs or vals will be designed for 0.16.
This is a binary-compatible mitigation for 0.15.
Fixes #774

Fix deadlock of CharsetRangeSpec

---

bin/travis

In response to this build:
https://travis-ci.org/http4s/http4s/jobs/207818583#L3278
on the cats branch that hung despite `CharsetRangeSpec` completing.
Hope this will identify source of deadlock if #774 shows itself again.

Call jstack on sbt if sbt runs longer than 13 minutes

---

tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

If we don't do this, it usually leaves the port bound after stop.

Destroy Tomcat after stopping it

---

project/Http4sPlugin.scala

This fixes the build failure in version 2.11 of cats, which is caused by the ambiguous implicit and SI-2712.  `-Ypartial-unification` should be standard practice for cats users after the demise of Xor, especially on Scala 2.11.

Turn on -Ypartial-unification

---

bin/travis

Builds are on Ubuntu Precise where `pgrep --newest` is not a thing yet.
Fixes this ugliness at the end of Travis runs:
bin/travis: line 57: kill: Usage: pgrep [-cflvx] [-d DELIM] [-n|-o] [-P PPIDLIST] [-g PGRPLIST] [-s SIDLIST]
[-u EUIDLIST] [-U UIDLIST] [-G GIDLIST] [-t TERMLIST] [PATTERN]: arguments must be process or job IDs
Was not hurting anything; just cluttering the console.

Correction to watchdog script for older pgrep

---

build.sbt

This was the cause of some pain in rho between 2.11.7 to 2.11.8,
whereupon @reactormonk and I were advised by the compiler folks that
these flags are exprimental and unmaintained in 2.11.  We'll leave
them in 0.15.x because binary compatibility worries me more than
what's left of these flags, but 0.16.x is a new beginning.

Get rid of delambdafy on 2.11

---

core/src/main/scala/org/http4s/Message.scala

Removed by making this no longer a doc comment.
```
[error] ...Message.scala:213: discarding unmoored doc comment
[error]   /** A request is idempotent if and only if its method is idempotent and its body
```

Removed Unmoored Doc Comment

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
async-http-client/src/main/scala/org/http4s/client/asynchttpclient/QueueSubscriber.scala
async-http-client/src/main/scala/org/http4s/client/asynchttpclient/UnicastSubscriber.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/QueueSubscriberTest.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazePooledHttp1ClientSpec.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala

* Don't block on closing or killing the queue. (Fixes #978)
* Don't trigger `scalaz.concurrent.DefaultStrategy` to dequeue body
* Respect the buffer size on the queue subscriber
* Return response only after subscribing. Should fix sporadic Reactive Streams 3.16 rule.

Fix intermittent failure in async-http-client

---

.travis.yml

Encrypted blob created with:
travis encrypt "https://webhooks.gitter.im/e/05****************16" -r http4s/http4s
Adapted from advice here:
https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications
Will need to run through Travis to confirm it works as expected.

Fix Gitter webhook call from Travis

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientConfig.scala
blaze-client/src/main/scala/org/http4s/client/blaze/bits.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazePooledHttp1ClientSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeSimpleHttp1ClientSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
client/src/main/scala/org/http4s/client/impl/DefaultExecutor.scala
core/src/main/scala/org/http4s/StaticFile.scala
core/src/main/scala/org/http4s/util/threads.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala
tests/src/test/resources/test.fiddlefaddle
tests/src/test/scala/org/http4s/StaticFileSpec.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala
tests/src/test/scala/org/http4s/util/io/IoSpec.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

What's better:
- Default pools have minimum of 4 threads, vs. scalaz-7.1's `availableProcessors`.
- Our default test pools will evaporate in long-running sbt sessions.
What might be better:
- Scale up to `availableProcessors * 3` on demand.
What's not yet:
- Clients and servers still default to running on a daemon threads.
- scalaz pools still leak in sbt, because `Strategy` creates them eagerly.
What I hope to achieve:
- The end of #978

Replace scalaz default pool with our own

---

build.sbt

Just a small change in sbt. This is useful when working on examples as you can stop them without killing sbt
I'm targeting cats but it could go to master too

Support stopping examples without killing sbt

---

core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/EntityEncoder.scala

As suggested in #800, this adds `implicitNotFound` annotations for `EntityEncoder` and `EntityDecoder` to provide a little bit better error messages.

Add implicitNotFound annotations for Entity{Encoder,Decoder}

---

project/Http4sPlugin.scala
version.sbt

Starts publishing cats branch as `0.17.0-SNAPSHOT`, sans `-cats` qualifier.

Bump to v0.17.0-SNAPSHOT

---

docs/src/hugo/content/versions.md

Use `<code>` instead of `<pre>` and add the formatting on all mentions of a specific version.
`<pre>` is styled as a block element vs. `<code>` which is inline.

Update formatting of versions in text

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala

Dispose Task is being evaluated before the stream is consumed, which was causing Premature EOF.
This also fixes a pending test
The logic in the master  branch is similar to what I propose here, don't know why in this port the dispose Task is being evaluated before the Stream, but it could exist a very good reason I don't understand.

In Client.streaming, only call dispose when the stream finalizes.

---

bench/src/main/scala/org/http4s/bench/NioCharsetBench.scala
core/src/main/scala/org/http4s/Charset.scala

Charset.forName caches only two entries before blocking threads.  If
abused, as property tests abuse them, this can cause a severe
bottleneck.  We can iterate over the available character sets and
their aliases, prewarm the cache, and avoid the method altogether.

Cache charset lookups to avoid synchronization

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeConnection.scala

Finalizers incur a substantial performance penalty.  _Effective Java_ quotes the damage at 430x to garbage collect a simple object.  We're making everyone pay to warn of a mistake we've made rather difficult to make in the first place.

Eliminate finalizer on BlazeConnection

---

docs/src/hugo/config.toml

Also fixes the "Scaladoc" link at the bottom of the tut menu at
the right of the page.  Looks like the "Edit this page" links are
still broken though.
Follow-up to #1048 .

v0.17 docs should use 0.17.0-SNAPSHOT as version

---

server/src/main/scala/org/http4s/server/middleware/CORS.scala
server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala

- Fixes #1039
- Changed CORS to reply with ok to OPTIONS request regardless of what it wraps.

Follow the CORS implementation of Jetty and Tomcat

---

.travis.yml
project/Http4sPlugin.scala
project/ScalazPlugin.scala

Get 'em while they're hot.
- async-http-client-2.0.31
- circe-0.7.1
- jetty-9.4.3.v20170317
- json4s-3.5.1
- scalacheck-1.13.5
- scalaz-7.2.10 or 7.1.12
- tomcat-8.0.43

Dependency patch upgrades

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala

A URI fragment is illegal in an HTTP request line.  This irritates sensitive servers, like Wikipedia.  This is difficult to unit test, because both Jetty and Blaze servers tolerate fragments in the request target.  The test failed before the code fix, but is skipped to avoid an external resource dependency in our unit tests.
/cc @gwils

Strip fragment from request target in blaze-client

---

docs/README.md

Not needed in scalaz-stream branch, does not work in cats branch

Remove scalazVersion from makeSite instructions

---

docs/src/main/tut/service.md

So the `curl http://localhost:8080/hello/Pete` example higher up in the tut still works with the App server.

make App example consistent with `builder.run` example

---

.travis.yml

Travis jobs are numbered XXXX.Y.  Currently Y == 1 on `release-0.16.x` is Scala 2.12 with scalaz 7.2.  On `release-0.15.x`, it is Scala 2.10 with scalaz 7.1.  The inconsistency makes it harder to spot patterns when builds fail, e.g. for #1055.

re-sort Travis Scala/scalaz matrix for consistency across branches

---

.travis.yml
docs/src/test/resources/logback-test.xml
testing/src/test/resources/logback-test.xml

Looks like these were at DEBUG for specs and INFO for tuts before commit 17d23f97.  That was too noisy, but OFF is probably too quiet.

show ERROR and WARN messages during specs and tuts

---

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/src/test/scala/org/http4s/client/JettyScaffold.scala

AsyncHttpClientSpec occasionally exceeds the 10 second timeout when running in 2 core containers on Travis.  Does not happen consistently, so probably the result of a noisy neighbor or other CPU or disk throttling.  10 seconds *should* be enough, and I suspect there is performance still to be had with AsyncHttpClient, but the sporadic CI failures are wasting developer time without any benefit.
Also moves the timeout into `ClientRouteTestBattery` because it's not used by Jetty and that seems like a more appropriate home.
Refs #1055

increase timeout for client tests, like AHC, that connect to Jetty

---

README.md

Adds `#http4s` to http://typelevel.org/projects/ link.

link from typelevel|library badge to http4s section of project page

---

CHANGELOG.md
build.sbt
docs/src/hugo/config.toml
docs/src/hugo/content/versions.md

Update docs references from 0.15.8 to 0.15.9 and bump version to 0.15.10-SNAPSHOT.

finalize 0.15.9 release and prepare for 0.15.10 development

---

docs/src/hugo/config.toml
docs/src/hugo/layouts/shortcodes/circeVersion.html
docs/src/hugo/layouts/shortcodes/cryptobitsVersion.html
docs/src/hugo/layouts/shortcodes/http4sVersion.html
docs/src/hugo/layouts/shortcodes/version.html
docs/src/main/tut/auth.md
docs/src/main/tut/json.md
docs/src/main/tut/service.md
docs/src/main/tut/streaming.md

Add hugo shortcodes[1] for circe and cryptobits versions to
reduce the number of places version numbers are copied.
tut blocks are compiled against library versions in `build.sbt`
and `project/Http4sBuild.scala`, but the versions are also part
of surrounding markdown that is not compiled.  This copypasta
allows the compiled tuts to use version B of a library while a
reader following along at home pastes in older version A.  While
typically not a problem, it may allow the tuts, as rendered in
HTML, to break silently.
This change reduces the version copying, but does not sync the
versions in `Http4sBuild.scala` with the ones displayed in the
rendered HTML.
A good follow-up step might be to generate hugo's `config.toml`
from sbt.  Or, maybe better, export versions from sbt as
environment …

begin DRYing up library versions used by tuts

---

build.sbt
docs/src/hugo/config.toml
docs/src/hugo/layouts/_default/single.html
docs/src/hugo/layouts/shortcodes/circeVersion.html
docs/src/hugo/layouts/shortcodes/cryptobitsVersion.html
docs/src/hugo/layouts/shortcodes/http4sVersion.html
docs/src/hugo/layouts/shortcodes/version.html
docs/src/main/tut/auth.md
docs/src/main/tut/json.md
docs/src/main/tut/service.md
docs/src/main/tut/streaming.md
project/Http4sBuild.scala

Follow-up to #1127 [as promised](https://github.com/http4s/http4s/pull/1127#issuecomment-296238572)...
Instead of duplicating key library versions in `config.toml`, write them to a Hugo data file, `build.toml`, from sbt using the same values the compiler is using.
Also made the Hugo version shortcode more generic, so there is a single shortcode for retrieving versions instead of one for each of the key dependencies used in tuts.
Example usage:
val http4sVersion = "{{< version "http4s.release" >}}"
or:
```scala
libraryDependencies ++= Seq(
"org.http4s" %% "http4s-circe" % http4sVersion,
"io.circe" %% "circe-generic" % "{{< version circe >}}",
"io.circe" %% "circe-literal" % "{{< version circe >}}"
)
```
Potential gotchas:
* Argument to the version shortcode needs to be quoted if it …

finish DRYing up library version used in tuts

---

project/Http4sBuild.scala

This would "resolve" #1135 by using the scalaz-7.2 versions of http4s in the tut examples.  Might just be covering up a deeper scalaz-7.1 issue with http4s though.

use Scalaz 7.2.x versions with "a" suffix in tuts

---

build.sbt
docs/src/hugo/layouts/shortcodes/version.html
project/Http4sBuild.scala

Found several mistakes when doing a dry-run of the merge train.  Fixes:
* remove `relVersion` that should have been removed in commit 5f11b2de
* correct sample shortcode
* allow for "a" qualifier in Scalaz 7.2 version 0.16.0a-SNAPSHOT when calculating version for tut examples
Refs #1131

fix mistakes while DRYing up tut versions

---

build.sbt
docs/src/hugo/config.toml
docs/src/hugo/layouts/_default/single.html
docs/src/hugo/layouts/shortcodes/version.html
docs/src/main/tut/auth.md
docs/src/main/tut/json.md
docs/src/main/tut/service.md
docs/src/main/tut/streaming.md
project/Http4sPlugin.scala

No hurry to merge this.  Offering it because there were some merge conflicts in `config.toml` and `project/Http4sBuild.scala` and probably easier for me to resolve them than anyone else.
Two user-facing changes in the v0.16 tuts:
* Refer to http4s 0.16.0a-M1.  The "a" for Scalaz 7.2 is new.
* Refer to circe 0.7.1 in `libraryDependencies` examples.  Was 0.6.1 despite tut compilation using 0.7.1.

merge train to release-0.16.x for DRYing up tuts

---

build.sbt
docs/src/hugo/config.toml
docs/src/hugo/layouts/_default/single.html
docs/src/hugo/layouts/shortcodes/version.html
docs/src/main/tut/auth.md
docs/src/main/tut/json.md
docs/src/main/tut/service.md
docs/src/main/tut/streaming.md
project/Http4sPlugin.scala

Was minor conflict on `CirceInstances.scala` resolved by keeping HEAD and ignoring the `release-0.16.x` backport version.

merge train to master for DRYing up tuts

---

bench/src/main/scala/org/http4s/bench/CirceJsonBench.scala
build.sbt
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/package.scala
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
project/Http4sPlugin.scala

Same as #1142 with release-0.16.x target.
```
[info] Benchmark                          (approxContentLength)  (cutoff)  Mode  Cnt        Score        Error  Units
[info] CirceJsonBench.decode_adaptive                      1100    100000  avgt   20    12273.404 ±    384.060  ns/op
[info] CirceJsonBench.decode_adaptive                      5000    100000  avgt   20    57869.141 ±   2193.909  ns/op
[info] CirceJsonBench.decode_adaptive                     10000    100000  avgt   20   101528.284 ±   2941.912  ns/op
[info] CirceJsonBench.decode_adaptive                    100000    100000  avgt   20   914144.688 ±  20481.076  ns/op
[info] CirceJsonBench.decode_adaptive                    500000    100000  avgt   20  4701151.022 ± 117407.744  ns/op
[info] CirceJsonBench.decode_byte_buffer …
```

Adaptive EntityDecoder[Json] for circe (release-0.16.x)

---

project/Http4sBuild.scala

This is prep for the relase of M2.  Better if `latestMilestone` is bumped on the `release-0.16.x` branch than on `release-0.15.x` as it saves an unnecessary merge.  No need for 0.15 to know about the later
releases anyway.

release-0.15.x branch should not know about 0.16 and 0.17 milestones

---

bench/src/main/scala/org/http4s/bench/CirceJsonBench.scala
build.sbt
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/package.scala
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
project/Http4sPlugin.scala

After doing some benchmarks I've decided to make an instance that combines performance of decoding via `ByteBuffer` for small payloads and via jawn-fs2 for big payloads. 
Default cutoff value of 100000 was chosen by doing benchmarks with different cutoff value. Mesages with `Content-Length` lower than cutoff are handled by `ByteBuffer` parser. Everything higher than cutoff or when `Content-Length` is unknown is handled by incremental decoder.
```
[info] Benchmark                          (approxContentLength)  (cutoff)  Mode  Cnt        Score       Error  Units
[info] CirceJsonBench.decode_adaptive                      1100    100000  avgt   20    28218.335 ±   147.533  ns/op
[info] CirceJsonBench.decode_adaptive                      5000    100000  avgt   20    76649.070 ±  1259.016 …
```

Adaptive EntityDecoder[Json] for circe

---

CHANGELOG.md
project/Http4sBuild.scala

This already happened on 0.16+.

Upgrade to argonaut-6.2

---

.travis.yml
build.sbt
core/src/main/scala/org/http4s/package.scala
project/build.properties
tests/src/test/scala/org/http4s/multipart/MultipartParserSpec.scala

With the release of Scala 2.12.2 and 2.11.10 these changes can be reflected in our builds.
I'm sure I'm missing a location where the primary value is being populated by an sbt file. Picked the furthest upstream branch to proliferate.

Update Scala Versions in .travis.yml

---

CHANGELOG.md
core/src/main/scala/org/http4s/multipart/Multipart.scala
core/src/main/scala/org/http4s/multipart/MultipartParser.scala
tests/src/test/scala/org/http4s/multipart/MultipartParserSpec.scala

- Skip the preamble
- Bail out after a default of 10240 characters in the header.  This prevents us from buffering an arbitrarily long line in the header.  10240 is the default used by commons-fileupload.
- Skip the epilogue
- Remove non-token characters from the boundary alphabet
Also ensures that we can handle bodies with really long lines.

Fix various issues with multipart parser

---

core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/parser/Http4sHeaderParser.scala
core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
core/src/main/scala/org/http4s/parser/ScalazDeliverySchemes.scala
tests/src/test/scala/org/http4s/UriSpec.scala

Our existing delivery scheme discards too much information from the parse error.  Nearly every header parser that fails only returns `"entry"` as the detail.  Now we get:
```
scala> HttpHeaderParser.CONTENT_LENGTH("blech").leftMap(_.message)
res4: String \/ org.http4s.headers.Content-Length =
-\/(Invalid header: Invalid input 'b', expected entry (line 1, column 1):
blech
^)
```
All the leftMapping is so we can bring the `ParseError` back to where we have the input.
This will make some of the headers work @wedens is doing on #1143 more useful.

Improve error reporting from parboiled parsers

---

tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

toEither was a method added in 2.12 to Either to convert from Try. To maintain support for 2.11 utilize the cats Either.fromTry which is present in both versions.
Fixes #1163

Fix Failing UriParserSpec

---

docs/src/main/tut/client.md

Current documentation did not include the information about sbt dependencies to utilize the client. The additional section remedies this problem.
Fixes #1137

Added SBT Import to Client Tut Documentation

---

server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceFilterSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceSpec.scala

In the real world, pathInfo always begins with a '/' unless it's
empty.  In the current implementation, it's assuming no leading slash,
leading to the webjar segments being off by one.
/cc @Busti

WebjarService should assume pathInfo starts with a `/`

---

server/src/main/scala/org/http4s/server/middleware/GZip.scala
server/src/test/scala/org/http4s/server/middleware/GZipSpec.scala

`scalaz.stream.compress.deflate` never calls `.finish()` on the deflater, which produces different output from `GZipOutputStream`.  By inhaling scalaz-stream's implementation and adding the `finish` call, we pass the same property test as the fs2 version.
Further simplified by calculating the CRC32 along the way, as long as we already have our own copy.
/cc @mrdziuban

Backport #1168 to scalaz-stream: fixes GZip output

---

server/src/main/scala/org/http4s/server/middleware/GZip.scala
server/src/test/scala/org/http4s/server/middleware/GZipSpec.scala

Fixes #1167.
This adds the gzip trailer as specified in [RFC 1952](https://www.ietf.org/rfc/rfc1952.txt). It adds a 4 byte CRC32 checksum and 4 bytes to indicate the original size of the data:
```
CRC32 (CRC-32)
This contains a Cyclic Redundancy Check value of the
uncompressed data computed according to CRC-32 algorithm
used in the ISO 3309 standard and in section 8.1.1.6.2 of
ITU-T recommendation V.42.  (See http://www.iso.ch for
ordering ISO documents. See gopher://info.itu.ch for an
online version of ITU-T V.42.)
ISIZE (Input SIZE)
This contains the size of the original (uncompressed) input
data modulo 2^32.
```
@rossabaker I can work on adding tests, but wanted to get feedback before moving forward, so let me know what you think. All the tests in the [README of my test …

Add gzip trailer

---

core/src/main/scala/org/http4s/util/ProcessApp.scala
core/src/main/scala/org/http4s/util/Task.scala
server/src/main/scala/org/http4s/server/ServerApp.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
tests/src/test/scala/org/http4s/util/ProcessAppSpec.scala

Extending `ServerApp` leaves `process` abstract.  The provided `main` method overrides nothing.  `ServerApp` should only have the one abstract method it ever did.

ServerApp should override process

---

server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuth.scala

Referred to old variables no longer used generating incorrect ScalaDocs

Fix Outdated BasicAuth Docs

---

core/src/main/scala/org/http4s/UrlForm.scala
tests/src/test/scala/org/http4s/UrlFormSpec.scala

Simple Convenience Method for creating a `UrlForm` from a `Seq`

UrlForm.fromSeq Added as a Convenience Method

---

CHANGELOG.md
project/Http4sBuild.scala

Round of patch upgrades for 0.15.13.  Blaze is the important one.

Upgrade dependencies

---

core/src/main/scala/org/http4s/util/StreamApp.scala
tests/src/test/scala/org/http4s/util/StreamAppSpec.scala

This makes `StreamApp` consistent with `ProcessApp` in 0.16.
Fixes #1195. /cc @ZizhengTai

Make StreamApp stream a Stream[Task, Nothing]

---

client/src/main/scala/org/http4s/client/oauth1/oauth1.scala
core/src/main/scala/org/http4s/Credentials.scala
core/src/main/scala/org/http4s/headers/Authorization.scala
core/src/main/scala/org/http4s/parser/AuthorizationHeader.scala
server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuth.scala
server/src/main/scala/org/http4s/server/middleware/authentication/DigestAuth.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSpec.scala
tests/src/test/scala/org/http4s/parser/AuthorizationHeaderSpec.scala

Changes `GenericCredentials` so it holds an `AuthScheme` and a value, nothing else (address #921).
Renamed previous `GenericCredentials` to `KeyValueCredentials` and updated throughout.

Make GenericCredentials less opinionated; add KeyValueCredentials (#921)

---

build.sbt
client/src/test/scala/org/http4s/client/ClientXmlSpec.scala
scala-xml/src/main/scala/scalaxml/ElemInstances.scala
scala-xml/src/main/scala/scalaxml/package.scala
scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala

This PR is a fix for #1209 it includes tests and a fix.
The fix is up for discussion as it changes the way an implicit decoder is built. I can see the argument both way of keeping the parser injectable or create one by default, but the approach on this PR gives a saner default and will fix #1209 
If this is accepted I'll port it to the 0.17.x branch
Fixes #1209

Fix for multithreaded xml parsing

---

build.sbt
client/src/test/scala/org/http4s/client/ClientXmlSpec.scala
scala-xml/src/main/scala/scalaxml/ElemInstances.scala
scala-xml/src/main/scala/scalaxml/package.scala
scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala

This is a replay of #1214 for master, basically porting scalaz `Task` usage to fs2 `Task`. 
Fixes #1209

Fix for multithreaded xml parsing for fs2

---

scala-xml/src/main/scala/scalaxml/package.scala

The default XML parsing settings allows certain classes of attacks like XXE. I propose that by default the parser be set in safer mode with the settings below
if user need the features of parameter entities they can override the `saxParserFactory`
See
https://blog.compass-security.com/2012/08/secure-xml-parser-configuration/
https://github.com/scala/scala-xml/issues/17
Do you think this should target `master`?

XML parsing improved safety

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
client/src/main/scala/org/http4s/client/Client.scala
client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
client/src/main/scala/org/http4s/client/middleware/Retry.scala
client/src/test/scala/org/http4s/client/MockClient.scala
core/src/main/scala/org/http4s/AttributeMap.scala
core/src/main/scala/org/http4s/Message.scala
server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala
server/src/main/scala/org/http4s/server/middleware/DefaultHead.scala
server/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala
tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
tests/src/test/scala/org/http4s/MessageSpec.scala

https://github.com/http4s/http4s/issues/1183
What would you guys think about changing the lazy vals of scriptName + pathInfo to functions like this:
```
val caret = attributes.get(Request.Keys.PathInfoCaret).getOrElse(0)
def scriptName = {
uri.path.splitAt(caret)._1
}
def pathInfo = {
uri.path.splitAt(caret)._2
}
```
That way we wouldn't need to overwrite the copy method and we could avoid the boilerplate

update pathinfo when changing uri via Request.copy

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala

Change `s"Invalid JSON"` to `"Invalid JSON"`

Delete an unused string interpolation.

---

docs/src/main/tut/index.md

For reasons I don't have time to debug, the sbt-site plugin can't find the hugo binary that I just installed, but the GitHub markdown processor implies that I did the right thing. Perhaps this documentation suggestion is obvious to others but it wasn't to me. Hoping to save the maintainers future questions.

suggest sbt-revolver in documentation

---

bin/publishSite.sh

New Hugo Distributes Hugo Directly in unpacked folder
If you run the curl command you get a folder like below
```
-rwxr-xr-x  1 davenpcm davenpcm  12M Jun 24 04:27 hugo
-rw-r--r--  1 davenpcm davenpcm  11K Jun 17 04:06 LICENSE.md
-rw-r--r--  1 davenpcm davenpcm 5.8K Jun 21 08:12 README.md
```

Fix Hugo Publishing

---

build.sbt
core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
tests/src/test/scala/org/http4s/UriSpec.scala

If we get a `[` or `]` in a query string, parse it by encoding it.  These are the only two reserved characters in RFC 3986 that are neither explicitly permitted in a query string nor preserve special semantics (`#` delimits the fragment).  Parsing them permits real world usage, but encoding them keeps our renderings in strict compliance with the spec.
Fixes #1240 
/cc @TimothyKlim

Tolerate `[` and `]` in queries parsing URIs

---

core/src/main/scala/org/http4s/Header.scala
core/src/main/scala/org/http4s/Headers.scala
server/src/main/scala/org/http4s/server/middleware/Logger.scala
server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
server/src/test/scala/org/http4s/server/middleware/LoggerSpec.scala

Most version of observe seem to consume to body and creates errors in writing length, these two combinations seem to avoid this.
Not Sure How Valid These Tests are if at all. Recreating the failures of consuming the body is hard. However I found it a couple times in unexpected places.

Logging Middleware

---

client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala

This is what they call foreshadowing.  It's broken in master, but let's put up the safety net here.

Test that toHttpService returns a live response body

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala

This is tested in #1251, but broken in master.  This contains the fix.  We need to attach `dispose` to the finalizer of the body, not dispose and then return the body.

Return live response body from Client.toHttpService

---

core/src/main/scala/org/http4s/headers/Last-Event-Id.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
tests/src/test/scala/org/http4s/headers/LastEventIdSpec.scala

I dove into the tests to see if I could help out on the fs2-cats port. Discovered this disabled code and figured I could "fix" it. Kind of refs. https://github.com/http4s/http4s/issues/866

Re-enables last event id spec

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala
client/src/main/scala/org/http4s/client/impl/RequestGenerator.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/StaticFile.scala
core/src/main/scala/org/http4s/headers/Content-Length.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
dsl/src/test/scala/org/http4s/dsl/ResponseGeneratorSpec.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
server/src/main/scala/org/http4s/server/middleware/Jsonp.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/HeaderSpec.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala
tests/src/test/scala/org/http4s/ResponderSpec.scala
tests/src/test/scala/org/http4s/headers/ContentLengthSpec.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

After the implementation of the `Age` header it was suggested to review other cases where headers could throw an exception on construction. The other header doing that was `Content-Length`. Given how much more use `Content-Length` has this PR is quite extensive on changes to support this new style
Unfortunately this change breaks the API as the `apply` method now returns a `ParseResult[Content-Length]` value

Improvement to Content-Length header

---

core/src/main/scala/org/http4s/headers/Age.scala
tests/src/test/scala/org/http4s/headers/AgeSpec.scala

After the changes on `Content-Length` on #1244, I'm updating the `Age` header in the same way, removing the partial `apply` constructor and the anonymous class
This is an API break but given that `Age` was add very recently I'd expect the impact to be minimal

Bring Age header up to standard

---

bin/specialTest.sh

Needs the exit code to be cached on exit to avoid false positives.

Update SpecialTest for False Positives

---

core/src/main/scala/org/http4s/AttributeMap.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/StaticFile.scala
server/src/main/scala/org/http4s/server/middleware/PushSupport.scala
server/src/main/scala/org/http4s/server/websocket/package.scala
tests/src/test/scala/org/http4s/AttributeMapSpec.scala

The name parameter gives the false hope that the key
is based on something other than referential equality.
Right now, it's only purpose is to override the
`toString` method, and even that is dangerous because
`toString` doesn't allude that it's an `AttributeKey`.

Remove the 'name: String' param from AttributeKey

---

blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
project/Http4sPlugin.scala
server/src/main/scala/org/http4s/server/middleware/Timeout.scala
server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala

There are some changes to `fs2.Scheduler`.
I'm not completely happy with the `unsafeRunSync`s introduced in the example services, but to avoid those would need a larger refactoring of the examples.

FS2 0.10: Update fs2 to 0.10.0-M4

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
core/src/main/scala/org/http4s/util/StreamApp.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslExampleWithRedirect.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
server/src/main/scala/org/http4s/server/ServerApp.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
tests/src/test/scala/org/http4s/util/StreamAppSpec.scala

This is a suggestion for changes to `StreamApp`.
Currently it has quite a few `unsafeRun*`s. This changes the API quite a bit to avoid those (since getting a value out of an `F[_]: Effect` is nigh on impossible, and a horrible thing to do according to the cats-effect gitter).

FS2 0.10: Refactor StreamApp

---

docs/src/hugo/content/adopters.md

Simple fix a typo in http4s-demo github link

fix: http4s-demo github link typo

---

.travis.yml
async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala

Without a content-length, `InputStreamBodyGenerator` assumes chunked transfer encoding.  We pass the content length (or -1 if we can establish chunked transfer encoding).
I did not have a failing test before this change.  I can only reproduce the problem as described against #1264.  This fixes the issue described in #1264.
As stated in #1264, a better solution would be a non-blocking implementation of the body generator based on reactive streams.  Since scalaz-stream is dead and a proper implementation is non-trivial, I propose that this is Good Enough™.
/cc @ktonga

Pass content length to InputStreamBodyGenerator in AHC

---

core/src/main/scala/org/http4s/Uri.scala
tests/src/test/scala/org/http4s/UriSpec.scala

Follows current convention. However would we prefer an explicit `Fragment` then wrapped in `Some`?

Add withFragment to remove redundant copy calls

---

core/src/main/scala/org/http4s/headers/Strict-Transport-Security.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/StrictTransportSecurityParser.scala
docs/src/main/tut/hsts.md
docs/src/main/tut/middleware.md
examples/src/main/scala/com/example/http4s/ssl/SslExample.scala
server/src/main/scala/org/http4s/server/middleware/HSTS.scala
server/src/test/scala/org/http4s/server/middleware/HSTSSpec.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/headers/StrictTransportSecuritySpec.scala

This PR adds support for HSTS in the form of the `Strict-Transport-Security` header and a middleware to activate it
As a reference 
https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet
I was tempted to add it to Blaze as it probably makes more sense as a server feature than a `Middleware` but got lost on the details. Let me know if you think that's an avenue to pursuit

HSTS Support

---

core/src/main/scala/org/http4s/headers/X-Forwarded-For.scala
core/src/main/scala/org/http4s/parser/AdditionalRules.scala
core/src/main/scala/org/http4s/parser/IpParser.scala
core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

* Old IPv4 parser allowed invalid octets
* IPv6 parser allowed invalid addresses, threw exceptions
Not sure why #1284 didn't get a PR build to uncover this, but I think this fixes release-0.16.x.

Fix broken IP parsing

---

core/src/main/scala/org/http4s/util/CaseInsensitiveString.scala
tests/src/test/scala/org/http4s/util/CaseInsensitiveStringSpec.scala

This is a latent bug finally uncovered by property testing in [this build](https://travis-ci.org/http4s/http4s/jobs/259076280#L3246).

Fix corner case of bad hash code in CaseInsensitiveString

---

core/src/main/scala/org/http4s/QueryParam.scala
dsl/src/test/scala/org/http4s/dsl/PathInHttpServiceSpec.scala
tests/src/test/scala/org/http4s/QueryParamCodecSpec.scala

This adds instances for `QueryParamEncoder` and `QueryParamDecoder`. Instances are constructed lazily to avoid initialization issues.

Instances for QueryParam codec

---

core/src/main/scala/org/http4s/QueryParam.scala
docs/src/main/tut/dsl.md
dsl/src/test/scala/org/http4s/dsl/PathInHttpServiceSpec.scala
tests/src/test/scala/org/http4s/QueryParamCodecSpec.scala

- instances and tests from #1301 
- doc fix from #1303 
- remove method deprecated in #1301

Forward port QueryParam codec instances from 0.16 master

---

dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala

Added the `Content-Length: 0` header for responses with an obviously empty body.
I didn't touch `EmptyResponseGenerator`, because I don't know if it's intended to be used with status codes forbidden to have a body.

Add Content-Length header to empty response generators

---

core/src/main/scala/org/http4s/Headers.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/headers/Set-Cookie.scala
tests/src/test/scala/org/http4s/ResponderSpec.scala

Set-Cookie is such an odd, out-of-spec header, I propose that it ceases to be `Extractable` at all.  We instead provide an accessor for the cookies on the Response that returns the entire list.
Fixes #1299.
/cc @megri

Provide a way to retrieve all cookies from a response

---

core/src/main/scala/org/http4s/Entity.scala
docs/src/main/tut/dsl.md
docs/src/main/tut/service.md
docs/src/main/tut/streaming.md
project/Http4sPlugin.scala

As it says on the tin. Note that circe hasn't been updated to 1.0.0-MF yet … the test pass but it's probably flaky in real life. Options include turning that module off for the milestone or saying  `¯\_(ツ)_/¯` which is what I would probably do.

cats 1.0.0-MF, fs2 0.10.0-M5

---

core/src/main/scala/org/http4s/StaticFile.scala
docs/src/main/tut/static.md
examples/src/main/scala/com/example/http4s/ExampleService.scala
server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
tests/src/test/scala/org/http4s/StaticFileSpec.scala

A bunch of file I/O operations are unguarded by task, so sweep all of `StaticFile` into an `OptionT`.
Then, once safely tucked away, we can call `getContentLengthLong` on the `URLConnection`.
Fixes #1295.
/cc @ZizhengTai

Provide content-length header when serving from a URL

---

servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala

(remade the PR against 0.15.x branch) 
Please consider this just a draft for discussion as I'm a new contributor.
There might be a better way to name or handle the key definition, for example.
Or would it be more flexible to allow extension by overriding a method that produces the request attribute map?

Make servlet HTTP session available in Request attributes. Fixes #1173

---

server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/test/resources/testDir/index.html
server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala

- Change default behavior of `staticContent` to return the index.html file (when present) when the client asks for a directory
- Make it easier to extend or change the default behavior by removing the `private` modifier so it can be called from external implementations

Return index.html when a directory is specified for static content

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/ProtocolSelector.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
server/src/main/scala/org/http4s/server/package.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

Every `ServerBuilder` gets a `ServiceErrorHandler`, which is invoked when a service returns a failed task and also when a service fails synchronously.  The default is to call `toHttpResponse` on a `MessageFailure` and close the connection with a 500 on `NonFatal` errors.  Fatal errors are left to the server.
In a server end, there are more places things can go wrong, but this will let users customize the handling in _most_ cases, and provide more uniformity across backends.  Most noticeably, Blaze in HTTP/2 was not looking for 4xx errors on `MessageFailure`.
Relates to #1312.

Make a pluggable error handler for service failures

---

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala

If we redirect to a different authority, then we should not send sensitive headers, or else we can expose secrets.  Users can adjust this or opt into this by changing the default sensitive header filter.

FollowRedirect should protect sensitive headers

---

.travis.yml
bin/publish
project/Http4sPlugin.scala
project/plugins.sbt

I'd prefer to stay on Typelevel Scala in order to help test it and promote it, but we don't need its extended features yet, and the resulting POMs are causing some pain.  I hope to change back after the dust settles, but it's more important to ship our releases now.
Fixes #1330.

Revert to Lightbend compiler

---

project/Http4sPlugin.scala

This one gives me déjà vu.  I guess we only managed to get the plugin last round.

Really upgrade twirl to 1.3.4 this time

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala

BlazeBuilder is now setting the custom execution context passed in.

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientConfig.scala
blaze-client/src/main/scala/org/http4s/client/blaze/ClientTimeoutStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/main/scala/org/http4s/client/blaze/bits.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala

Adds a timeout between the completion of the request and the completion of the response header.
Addresses #1349.  The original request was for time-to-first-byte, but I think this satisfies @scottcarey's use case, and I've seen this in other APIs.

Implement a response header timeout

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ReadBufferStageSpec.scala
blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/BodylessWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/CachingStaticWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/ChunkEntityBodyWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/ChunkWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/FlushingChunkWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/Http2Writer.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/IdentityWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/package.scala
blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala
blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala
blaze-core/src/test/scala/org/http4s/blazecore/util/Http1WriterSpec.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala

A message might have a header substantially before the first chunk is calculated.  We should render the header, sans Content-Length or Transfer-Encoding header, as soon as it's available.  We call a `writeHeader` method with the header buffer, which gives each encoder the discretion to flush the header immediately or to hold it to be flushed with the beginning of the entity.
/cc @scottcarey, who mentioned this behavior on Gitter

 Flush header while awaiting first chunk

---

project/Http4sPlugin.scala
tests/src/test/scala/org/http4s/headers/RetryAfterSpec.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala
tests/src/test/scala/org/http4s/parser/AcceptEncodingSpec.scala
tests/src/test/scala/org/http4s/parser/AcceptLanguageSpec.scala
tests/src/test/scala/org/http4s/parser/HeaderParserHelper.scala

This PR updates the build to use specs2 4.x. It lets us remove the last bits of scalaz dependency and eventually run tests on scala.js
I don't know if you'd prefer to wait until a final release of specs2 is available

Update to specs2 4.x

---

build.sbt

This solves the problem of being unable to publishLocal and then depend on that when testing http4s.
I was reluctant to do this, because it appears to be another dependency, which is used in negative marketing.  All code in this newly published module is internal and was already in core.  Haters gonna hate.  This just simplifies our build and makes a better story for local development.
Alternatively, I tried `ivyXML` in addition to `pomPostProcess`, but I couldn't get it to affect the delivered Ivy file.

Make parboiled2 an actual module

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
core/src/main/scala/org/http4s/Http4s.scala
core/src/main/scala/org/http4s/Message.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
server/src/main/scala/org/http4s/server/Router.scala
server/src/main/scala/org/http4s/server/middleware/DefaultHead.scala
server/src/main/scala/org/http4s/server/syntax/package.scala
server/src/test/scala/org/http4s/server/HttpServiceSpec.scala
server/src/test/scala/org/http4s/server/middleware/GZipSpec.scala

by re-introducing the implicit `Monoid[F[MaybeResponse[F]]]` in `MaybeResponseInstances`.
This trait is then mixed into the `Http4sInstances` trait, which puts it into scope in most places where a user would need it, i.e. when importing or mixing in the DSL.
To let `BlazeBuilder` pick the right instance, when instantiated with `IO` as the effect type, `BlazeBuilder` now mixes in the `MaybeResponseInstances` trait as well.

Remove the Semigroup[F[MaybeResponse[F]]] constraint from classes

---

core/src/main/scala/org/http4s/syntax/EffectMessageSyntax.scala
core/src/main/scala/org/http4s/syntax/EffectRequestSyntax.scala
core/src/main/scala/org/http4s/syntax/EffectResponseSyntax.scala

Currently all `F`s that use syntax on `F[Message[F]]` must be covariant. This removes that requirement at the cost of a `.widen`.

Make F in Effect*Syntax invariant

---

project/Http4sPlugin.scala

This removed a warning with possibly incompatible transitive dependencies.

Upgrade jawn-fs2

---

examples/war/project/plugins.sbt
project/plugins.sbt

Not sure why there was a conflicting version in project/plugins.sbt.  Though maybe that was a good place for it: it would be nice if our example projects descended less from the main build or common modules, and were more self-contained.  To assemble a working example, you need the right plugin, and it refers to a service definition in the parent project.
/cc @AronT-TLV

Update xsbt-web-plugin for war example

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/test/scala/org/http4s/circe/CirceSpec.scala
json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
json4s/src/test/scala/org/http4s/json4s/Json4sSpec.scala

This is the continuation of #1351.
By moving the constraint on `F[_]` to the implicit class, we can do:
```scala
msg.decodeJson[A]
// or
msg.decodeJson(customDecoder)
```
without any `implicitly`.

Add decodeJson to Message

---

server/src/main/scala/org/http4s/server/middleware/Logger.scala

I want to add a unit test, but we haven't yet developed any means to capture the log output.

Pass redacted headers to request and response logger

---

core/mima.sbt
core/src/main/scala/org/http4s/Charset.scala
core/src/main/scala/org/http4s/CharsetRange.scala
core/src/main/scala/org/http4s/headers/Accept-Charset.scala
tests/src/test/scala/org/http4s/CharsetRangeSpec.scala
tests/src/test/scala/org/http4s/headers/AcceptCharsetSpec.scala

`Accept-Charset.qValue` was ignoring the passed in charset and returning the first atom's q-value.

Fix Accept-Charset matching

---

core/mima.sbt
core/src/main/scala/org/http4s/CharsetRange.scala
core/src/main/scala/org/http4s/ContentCoding.scala
core/src/main/scala/org/http4s/LanguageTag.scala
core/src/main/scala/org/http4s/headers/Accept-Charset.scala
core/src/main/scala/org/http4s/headers/Accept-Encoding.scala
core/src/main/scala/org/http4s/headers/Accept-Language.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/headers/AcceptCharsetSpec.scala
tests/src/test/scala/org/http4s/headers/AcceptEncodingSpec.scala
tests/src/test/scala/org/http4s/headers/AcceptLanguageSpec.scala
tests/src/test/scala/org/http4s/parser/AcceptEncodingSpec.scala
tests/src/test/scala/org/http4s/parser/AcceptLanguageSpec.scala

* `satisfiedBy` on the values makes little sense and is deprecated
* `satisfiedBy` on the headers did not understand priority
* made more consistent with `Accept-Charset`
`LanguageTag` and `ContentCoding` are still broken in that they are both values (in the `Content-*` headers) and ranges (in the `Accept-*` headers).  These should be split into different types, but there's no reasonable way to do that without breaking binary compatibility.  We'll address that in a later version.

Fix Accept-Encoding and Accept-Language

---

blaze-core/src/main/scala/org/http4s/blazecore/util/ChunkWriter.scala
build.sbt
core/src/main/scala/org/http4s/HttpDate.scala
project/Http4sPlugin.scala
project/build.properties
project/plugins.sbt
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala

Won't build yet, because it's based on a snapshot of sbt-rig.
Pulls in sbt-tpolecat, which makes our compiler flags stricter, which cleans up our code more.  That's the meat of this.
Fixes #1401.

Upgrade to sbt-1.0

---

core/src/main/scala/org/http4s/util/StreamApp.scala

This caused [confusion](https://gitter.im/scala/scala?at=59c15d57cfeed2eb652b4e18) on Gitter.
/cc @jmcardon

Remove implicit strategy from StreamApp

---

bin/specialTest.sh
build.sbt
project/Http4sPlugin.scala
website/src/hugo/content/contributing.md

This makes me sad, but it's taking my laptop 25 seconds to figure out there's nothing new to compile, on every compile.
I welcome better suggestions, because this is going to trip up new contributors constantly.

Grudgingly disable scalafmt on compile

---

core/src/main/scala/org/http4s/Message.scala
server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala

The presence of this monoid risks implicit resolution that breaks service chaining by evaluating both effects.  This retains binary compatibility but warns people who fall into this trap.
The long-term solution is #1424.

Deprecate Monoid[MaybeResponse]

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala

Same change we made in #1411, but for HTTP/2.
We don't have an HTTP/2 client handy, so I'm not certain how we test this.

Thread shift the service function in HTTP/2 server

---

version.sbt
website/src/hugo/content/CHANGELOG.md

Merging this should trigger a release of v0.17.3 with sonatype release, tag, and version on this branch bumped to v0.17.4-SNAPSHOT.

Release v0.17.3

---

server/src/main/scala/org/http4s/server/middleware/GZip.scala

java.xml.bind is under a separate module in Java 9 and needs to be
included with a command line switch. Implement GZip trailer calculation
without javax.xml.bind.DatatypeConverter for better Java 9
compatibility.

Remove java.xml.bind dependency.

---

scripts/helpers

Fixes #1446, though I'm now drawing a blank which builds have `$TRAVIS_PULL_REQUEST = false` and _aren't_ on that repo slug.

Don't decrypt unless on http4s/http4s

---

.travis.yml

When Travis pushes a tag, it's kicking off a build that complains that the tag already exists.  Since pushing non-snapshot versions to the release branches is our release process, we shouldn't build tags.

Don't build tags from Travis CI

---

project/Http4sPlugin.scala

Tagging all releases, even when we don't push, is why I had to temporarily delete a tag when cleaning out the other mess.  We _do_ need to tag before we build the site to generate the site matrix properly, but that also only runs on the primary build.

We only need to tag the primary build

---

project/plugins.sbt

This fixes the `None.get` issue we're seeing when publishing snapshots (i.e., publishing without opening a dedicated Sonatype repo).

Upgrade to rig-5.0.39

---

project/PrivateProject.scala

Our examples projects shouldn't be publishing.  I think it's biting us now because we started [signing our snapshots](https://travis-ci.org/http4s/http4s/jobs/283139624#L4514).
If this fixes it, I'll add the fix in rig and remove it from our private project plugin.

Disable publishSigned in private projects

---

core/src/main/scala/org/http4s/util/StreamApp.scala
docs/src/main/tut/service.md
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslExampleWithRedirect.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
tests/src/test/scala/org/http4s/util/StreamAppSpec.scala

This is an extension on #1444 and @hejfelix s ideas.
It introduces an `ExitCode` type that wraps an int, with values for success (0) and a generic error (-1).
Naming and location of the type can certainly be discussed.
This works around the dead code warning/error when using the `.serve` stream in a for-comprehension, allowing code like the following to compile with strict scalac flags:
```scala
import cats.effect._
import fs2._
import org.http4s.server.blaze.BlazeBuilder
import org.http4s.util.StreamApp
import org.http4s.util.StreamApp.ExitCode
object TestApp extends Test[IO]
class Test[F[_]: Effect] extends StreamApp[F] {
case class SomeClient(success: Boolean)
val mkClient: Stream[F, SomeClient] = Stream.emit(SomeClient(true))
def mkServer(client: SomeClient): Stream[F, ExitCode] = { …
```

Change StreamApp to take Stream[F, ExitCode]

---

docs/src/main/tut/auth.md
server/src/main/scala/org/http4s/server/package.scala

This is a small QOL change. In particular, extracting a `T` from a `Request[F]` probably has more explicit errors like the `apply` signature, but the default case where an `Option` is enough to signify no such T was extracted (where you can just discard the error), is common enough for stuff like extracting a token from a header or decoding a body.
edit: A few commas to make it readable.

Change AuthMiddleware default apply to use OptionT

---

server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/PathNormalizer.scala
server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
server/src/main/scala/org/http4s/server/staticcontent/package.scala
server/src/test/scala/org/http4s/server/staticcontent/PathNormalizerSpec.scala

`org.http4s.server.staticcontent.sanitize` is supposed to protect against getting arbitrary files in static services by replacing `..` with `.`
However, if you pass it `...` it will replace it with `..`
This PR replaces an arbitrary number of periods with a single.

Sanitize more than two dots as well

---

client/src/main/scala/org/http4s/client/Http4sClientDsl.scala
client/src/main/scala/org/http4s/client/dsl/io.scala
client/src/main/scala/org/http4s/client/io.scala
client/src/main/scala/org/http4s/client/package.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala
docs/src/main/tut/dsl.md
docs/src/main/tut/json.md
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientPostExample.scala

* `Http4sClientDsl[F]` is like `Http4sClientDsl[F]`
* Create `io` object that extends `Http4sClientDsl[IO]`, like http4s-dsl has
* Don't extend `Http4sClientDsl[IO]` from client package, like http4s-dsl doesn't.
This is still not quite harmonious: http4s-dsl imports the status codes, whereas client doesn't.

Make client DSL more similar to server DSL

---

core/src/main/scala/org/http4s/Method.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/MethodSpec.scala

As discussed on #956 we should try to refactor methods that use mutable structures or reflection. This PR removes the use of a mutable map to record

Don't use a mutable map to record Methods

---

build.sbt
circe/src/test/scala/org/http4s/circe/CirceSpec.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
project/Http4sPlugin.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
testing/src/main/scala/org/http4s/testing/EntityCodecTests.scala
testing/src/main/scala/org/http4s/testing/EntityEncoderTests.scala
testing/src/main/scala/org/http4s/testing/ToIOSyntax.scala
testing/src/main/scala/org/http4s/testing/package.scala
tests/src/test/scala/org/http4s/EntityCodecSpec.scala
tests/src/test/scala/org/http4s/EntityEncoderSpec.scala

If we have an `EntityEncoder[A]` and an `EntityDecoder[A]`, they ought to make a round trip.

EntityCodecLaws

---

version.sbt
website/src/hugo/content/changelog.md

I clarified the merging strategy in the changelog.  It would be tedious to explicitly reference each release that contains changes that rolled downhill.

Release v0.18.0-M4

---

bench/src/main/scala/org/http4s/bench/SchemeBench.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
build.sbt
client/src/main/scala/org/http4s/client/RequestKey.scala
core/src/main/scala/org/http4s/HttpCodec.scala
core/src/main/scala/org/http4s/Scheme.scala
core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/UriTemplate.scala
core/src/main/scala/org/http4s/internal/Macros.scala
core/src/main/scala/org/http4s/parser/Http4sParser.scala
core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
core/src/main/scala/org/http4s/syntax/AllSyntax.scala
core/src/main/scala/org/http4s/syntax/LiteralsSyntax.scala
core/src/main/scala/org/http4s/syntax/package.scala
core/src/main/scala/org/http4s/util/CaseInsensitiveString.scala
core/src/main/scala/org/http4s/util/package.scala
docs/src/main/tut/uri.md
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslExampleWithRedirect.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
testing/src/main/scala/org/http4s/testing/HttpCodecTests.scala
tests/src/test/scala/org/http4s/SchemeSpec.scala
tests/src/test/scala/org/http4s/UriSpec.scala
tests/src/test/scala/org/http4s/UriTemplateSpec.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala
tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

Less exciting as a type as much as a template for shoring up the HTTP model.
* `HttpCodec` is anything that can be parsed and rendered as a round trip, with a law to enforce it.
* `unsafeFromString` that is polluting everything gets moved to the `HttpCodec` type class.
* Move literal support to `StringContext` instead of methods on the companion.
* Macros get centralized in their own object.
* Gets rid of skull-and-crossbones constructors for macros.
* `toString` is for debugging, not serialization.
* Begins to phase out `CaseInsensitiveString`.

Scheme type

---

docs/src/main/tut/service.md

We were even lying about 2.10 support.

Fix Displayed Scala Version in Service Doc

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/package.scala
client/src/main/scala/org/http4s/client/middleware/Retry.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/UrlForm.scala
core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
core/src/main/scala/org/http4s/multipart/MultipartParser.scala
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
project/Http4sPlugin.scala
scala-xml/src/main/scala/scalaxml/ElemInstances.scala
server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
server/src/main/scala/org/http4s/server/middleware/Logger.scala
server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
server/src/main/scala/org/http4s/server/staticcontent/CacheStrategy.scala
server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
server/src/main/scala/org/http4s/server/staticcontent/NoopCacheStrategy.scala
server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
server/src/main/scala/org/http4s/server/staticcontent/package.scala

I have taken the easy way out and just changed `Sync` to `Effect` wherever the compiler complained. I guess we could use the `runSync` variants in some places, but I do not like the chance of a runtime error if there's an async bit in there.
There are a couple of tests that time out, that I haven't been able to figure out.

Upgrade fs2 to 0.10.0-M7

---

core/src/main/scala/org/http4s/TransferCoding.scala
core/src/main/scala/org/http4s/headers/Transfer-Encoding.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/TransferCodingSpec.scala

I'm trying to remove the use of `Registry` as it creates troubles on `scala.js` and it is not very sound anyway.
In this PR I'm removing `Registry` from `TransferCoding`. Any reason why this was mutable? Should end users be able to add their own `TransferCoding` definitions?
I'm also making the conversion from `CaseInsensitiveString` explicit and added the `Eq` instance

Make TransferCoding immutable

---

core/src/main/scala/org/http4s/MessageFailure.scala

Having a sealed `MessageFailure` hierarchy does not to a great deal of good.  `MessageFailure`s usually end up in a failed effect and statically typed as `Throwable`.  It is rare to get any benefits from exhaustiveness checking.
Having an unsealed `MessageFailure` hierarchy lets users customize the `toHttpResponse`.  This was previously handled by the addition of "Generic" case classes in the hierarchy, but were commented out during the parameterization of the effect.  We want the effect parameter to be on `toHttpResponse`, not the `MessageFailure`.  The clearest way to define a `MessageFailure` with a custom response is to implement an abstract class.
The use case of customizing HttpResponses could theoretically be done by pattern matching against a (sealed) `MessageFailure` hierarchy. …

Unseal the message failure hierarchy

---

core/src/main/scala/org/http4s/TransferCoding.scala
tests/src/test/scala/org/http4s/SchemeSpec.scala
tests/src/test/scala/org/http4s/TransferCodingSpec.scala

Its equality semantics are not consistent with the equality of its components.  Better to just make this a wrapper class, like `Scheme`.

TransferCoding is not a case class

---

website/src/hugo/content/changelog.md

Added warning to releases M2-M5 about classpath  incompatibilities between blaze and http4s

Log4s classpath incompatibility warning

---

docs/src/main/tut/entity.md

Updated `EntityBody` to have the correct alias of ``Stream[F, Byte]` instead of `Stream[F, ByteVector]`
Updated links to the functional streams library and a youtube video on the topic.
closes https://github.com/http4s/http4s/issues/1505

Updating EntityBody[F] alias, to have the correct parameters

---

project/Http4sPlugin.scala
project/plugins.sbt

Notable:
- blaze upgrade should resolve log4s warning reported by @coltfred and @tpolecat 
- coursier upgrade is Java 9 compatible, which may unblock #1462.

Upgrade dependencies and plugins

---

testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/headers/TransferEncodingSpec.scala

For completeness and as a corollary of #1499 here are unit tests for `Transfer-Encoding`

Unit tests for Transfer-Encoding

---

docs/src/main/tut/auth.md
docs/src/main/tut/index.md

I wasn't sure whether tsec-auth should be at the top, or at the bottom, so I put it at the bottom by default.
If you guys feel tsec-http4s is good, we can move it accordingly so it's easier to see.

update authentication docs to point to tsec-http4s

---

core/src/main/scala/org/http4s/QValue.scala
core/src/main/scala/org/http4s/parser/AcceptCharsetHeader.scala
core/src/main/scala/org/http4s/parser/AcceptEncodingHeader.scala
core/src/main/scala/org/http4s/parser/AcceptLanguageHeader.scala
tests/src/test/scala/org/http4s/QValueSpec.scala

I noted several instances of parsers for `QValue`. This PR removes that duplication and adds a `QValueParser`
It also adds an instance of `HttpCodec[QValue]`
Let me know what you think. It may make the header's parsers a bit less readable

Remove duplication of QValue parsers

---

server/src/main/scala/org/http4s/server/package.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthMiddlewareSpec.scala

This pr aims to address this issue
```scala
import cats._
import cats.data._
import org.http4s._
import org.http4s.dsl.io._
import cats.effect.IO
import cats.implicits._
import org.http4s.implicits._
import org.http4s.server.AuthMiddleware
case class User(id: Int)
val authedService: AuthedService[User, IO] = AuthedService[User, IO] {
case GET -> Root / "asd" as user =>
Ok()
}
val middleware: AuthMiddleware[IO, User] =
AuthMiddleware[IO, User](Kleisli(_ => OptionT.none))
val service1 = middleware(authedService)
val service2: HttpService[IO] = HttpService[IO] {
case GET -> Root =>
Ok()
}
(middleware(authedService) <+> service2).orNotFound(Request[IO]()).unsafeRunSync()
```
For security reasons, going through an `AuthMiddleware` should consume an entire request: i.e, it should never fall …

authmiddleware to consume the entire request

---

tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

`getClass.getResource("/")` may return null.  When it does, we throw an NPE.
The `docBase` property isn't hugely useful to most users anyway.  It's used to set the context root from which calls like `servletContext.getResource` work.  http4s services don't have a concept of a servlet root, so this is only useful when mixing in legacy servlets.  Serving static files still works even when this property is `null`.
In 0.18, we can make this configurable.  On 0.16 and 0.17, we'll just make the most conservative change.
Fixes #1453

Set Tomcat docBase to null

---

docs/src/main/tut/json.md

It seems the syntax with `.as(..)` and the function call is not used anymore so it could be dropped from the docs or replaced with something else if there is explanation necessary?

Remove reference to `.as()` function call from docs

---

core/src/main/scala/org/http4s/ContentCoding.scala
core/src/main/scala/org/http4s/headers/Accept-Encoding.scala
core/src/main/scala/org/http4s/parser/AcceptEncodingHeader.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/ContentCodingSpec.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala
tests/src/test/scala/org/http4s/headers/ContentEncodingSpec.scala
tests/src/test/scala/org/http4s/parser/AcceptEncodingSpec.scala

This started as a removal of `Registry` from `ContentCoding` but grew into a bigger refactoring using the current coding standards:
* Removal of `Registry` usage
* Removed usage of `CaseInsensitiveString`
* Implementation of `HttpCodec[ContentCoding]`
* Tightening constructions. Empty strings codings are not allowed
* More testing

ContentCoding without Registry

---

core/src/main/scala/org/http4s/util/NonEmptyList.scala
core/src/main/scala/org/http4s/util/package.scala
server/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/src/main/scala/org/http4s/server/middleware/CSRFMiddleware.scala
server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala

Here's a tentative implementation of the backport from `TSec`.
I had to port apache commons `Hex.encodeHex` to avoid bringing in another dependency to be able to get a 
performant Hex encoder, and handwrote `find` on NonEmptyList only because I'm not too familiar with `scalaz`. I figured there maybe a find function already I just can't find it.
It's syntactically Equivalent to the version I currently am PRing fixes onto `tsec` for, and adapted similarly from the `play framework` implementation. The gist of the vulnerability mitigation is to use the middleware to set the token cookie, and send such a token along with a custom header value. Given that an attacker forging a request cannot access the values of a cookie due to same-origin policy, this will guard against CSRF.
To defend against …

CSRF middleware backport - 0.16.x

---

core/src/main/scala/org/http4s/util/package.scala
server/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/src/main/scala/org/http4s/server/middleware/CSRFMiddleware.scala
server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala

Same as #1533, but for 0.17.x
The tests kinda look ugly because old fs2 task returns `Option`.
Practically copy paste from the other branch, except with different imports.

CSRF Middleware backport 0.17.x

---

core/src/main/scala/org/http4s/HttpService.scala
core/src/main/scala/org/http4s/package.scala

It seems that the docs for the `apply` is outdated, as there is no `org.http4s.Response.notFoundFor` anymore.
I suggest replacing it with the `OptionT.none` response.

Update `HttpService[F].apply` docs

---

core/src/main/scala/org/http4s/ContentCoding.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/ContentCodingSpec.scala

I haven't been able to reproduce this locally but I suspect this is happening because `QValue` is an `AnyVal`. I have changed compare to use the `thousandths` element for comparisons

Fix #1542 Random error on ContentCoding equality

---

server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

Should preserve semantics and chunkiness rather than pulling a single element at a time from the queue. This is more of a patch for optimizations than a fix of any kind.

Retain Logging Concept With Less Bulk

---

server/src/main/scala/org/http4s/server/middleware/GZip.scala

Fixes #1561
Prevents OutOfMemory in GZip with streams with large
segments.  Eg:
def bigStream: fs2.Stream[IO, Byte] = fs2.Stream.range(1, 2014922827).map(_.toByte).covary[IO]

Limit the amount of data pulled from the stream

---

project/Http4sPlugin.scala

This got overlooked in 0.16.6.

Upgrade Tomcat in 0.16.x

---

blaze-core/src/test/scala/org/http4s/blazecore/ResponseParser.scala
blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/EntityEncoder.scala
core/src/main/scala/org/http4s/multipart/MultipartEncoder.scala
core/src/main/scala/org/http4s/util/Renderable.scala
core/src/main/scala/org/http4s/util/chunk.scala
scala-xml/src/main/scala/scalaxml/ElemInstances.scala
server/src/main/scala/org/http4s/server/middleware/GZip.scala
server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala
tests/src/test/scala/org/http4s/EntityCodecSpec.scala
tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
tests/src/test/scala/org/http4s/StaticFileSpec.scala

This is to improve on the previous proliferation of chunks everywhere, especially after the fs2 M9 changes.

(WIP) Replace `Chunk` For `Segment` where appropriate

---

website/src/hugo/content/adopters.md

Fixes #1562. I just added the G8 templates at the end of the document, felt natural to do so. See what you think.

Adding Giter 8 templates into the adopters page.

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/package.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/UrlForm.scala
core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
core/src/main/scala/org/http4s/multipart/MultipartParser.scala
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
scala-xml/src/main/scala/scalaxml/ElemInstances.scala
servlet/src/main/scala/org/http4s/servlet/ServletContainer.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala

Now that the different run methods on Streams just require a Sync instance, many typeclass constraints can be relaxed.

Relax some typeclass constraints

---

core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/parser/HeaderParserHelper.scala
tests/src/test/scala/org/http4s/parser/Rfc2616ParserSpec.scala
tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

This PR starts from a change I want to do removing `Registry` from `MediaRange`. To do so I needed to generate `MediaRange` instances for scalacheck, which led me to create generators for various parts of the http spec previously untested.
This PR contains a test and the generators but there is one that is contentious and I'd like to get your comments

Tests for Rfc2616 parser

---

bench/src/main/scala/org/http4s/bench/BytesBench.scala
core/src/main/scala/org/http4s/util/chunk.scala

We have `ByteVectorChunk` in part so we can wrap `ByteBuffer`s, and then we forfeit that advantage when converting them back to a `ByteBuffer` at rendering time.

Smarter version of Chunk.toByteBuffer syntax

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
core/src/main/scala/org/http4s/websocket/Websocket.scala
server/src/main/scala/org/http4s/server/websocket/package.scala

Rename read/write to send/receive

---

server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala

All the other metric names are plural.  This is for consistency.

Make abnormal-terminations and service-errors plural

---

server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala

1) GET /http4s/metrics does not increment counters (it’s not wrapped in the middleware)
2) GET /http4s/metrics does not leave a dangling active request
3) GET /http4s/dfdajkfldajfklddasfadskl does not leave a dangling active request. (This is one where a wrapped service returns None).
4) GET /http4s/ping increments 200 and does not leaving dangling active request
Closes #1606

Metrics fix

---

version.sbt
website/src/hugo/content/changelog.md

This should be set to fire off an M8 Release.

Prep Changelog and Update Version for 0.18.0-M8

---

build.sbt
project/Http4sPlugin.scala

End our transitive library version dependency by explicitly stating versions for cats and cats-effect

Explicit Upstream Dependencies

---

blaze-core/src/main/scala/org/http4s/blazecore/util/ChunkWriter.scala
blaze-core/src/test/scala/org/http4s/blazecore/util/Http1WriterSpec.scala

Fix trailer headers and add a test for it

---

.scalafmt.conf

We Have moved parboiled to its own project so this exclusion is no longer necessary.

Remove Unecessary Parboiled Exclusion

---

server/src/main/scala/org/http4s/server/ServerBuilder.scala

Fixes Concurrently Leakage
I don't know why we were even using async here originally but by not calling the provided callback we broke lots of stuff. Lesson for the day, don't do that.

Call Async Callback to Correctly Initiate Shutdown

---

docs/src/main/tut/service.md
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
examples/docker/src/main/scala/com/example/http4s/Example.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslClasspathExample.scala
examples/src/main/scala/com/example/http4s/ssl/SslExample.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala

Not sure about the EC, but once translate bug is fixed this work as expected.

Fix immediately returning serve

---

core/src/main/scala/org/http4s/multipart/Part.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala

The filename is something that is often needed when handling a multi part encoded request, having a method to extract this from a part is helpful.

extract filename for multipart

---

docs/src/main/tut/service.md

The cats documentation is more relevant (that is what http4s uses) and
easier to follow if you don't know scalaz.

Replace Kleisli tutorial with the Cats doc for it

---

docs/src/main/tut/auth.md

The REPL output is just adding noise and making reading the documentation
harder.

Make authentication doc code silent

---

project/Http4sPlugin.scala

I think one of these is causing release-0.18.x build to break.  I'd like to know why, but I'd like even more to have a green build.

Remove diagnostic git commands in release steps

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala

Fixes #1487.
The Http1ServerStage doesn't consider whether the stage has been
shutdown from within it's request loop. When the stage is shutdown, it
is reset, which can race with a read-and-parse operation happening in
another thread.
To fix it, we restrict concurrent access to the parser and flag whether
the stage has been shutdown, halting parsing of the prelude if
disconnect has happened.

Fix race condition between shutdown and parsing in Http1ServerStage (#1487)

---

docs/src/main/tut/auth.md
server/src/main/scala/org/http4s/server/package.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthMiddlewareSpec.scala

Reopening for the fallen comerade #1665

Reintroduce the option for fallthrough for authenticated services

---

testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala

Simpler version of fix in #1677.  Prevents the generator from giving up due to a long run of discarded values, which results in a `None` sample.

Don't use filter in Arbitrary[`Content-Length`]

---

core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/MessageOps.scala
core/src/main/scala/org/http4s/ResponseCookie.scala
core/src/main/scala/org/http4s/headers/Cookie.scala
core/src/main/scala/org/http4s/headers/Set-Cookie.scala
core/src/main/scala/org/http4s/parser/CookieHeader.scala
docs/src/main/tut/auth.md
docs/src/main/tut/dsl.md
server/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala
tests/src/test/scala/org/http4s/CookieSpec.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala
tests/src/test/scala/org/http4s/MessageSpec.scala
tests/src/test/scala/org/http4s/ResponderSpec.scala
tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala

This PR adds a `RequestCookie` and `ResponseCookie` per the discussion in https://gitter.im/http4s/http4s?at=5a90d82b0202dc012e79241a.
I opened this PR due to the following motivation:
> The only reason I ask is that, at work, I, having not used Cookie's in a real app, wrongly wrote code that checked on an HTTP Request's Cookie's cookie.isSecure && cookie.isHttpOnly. If an HTTP Request's Cookie only contained name=value pairs, then that would eliminate that type of error
per https://gitter.im/http4s/http4s?at=5a90d82b0202dc012e79241a.
It uses the `abstract class` approach that @jmcardon mentioned in https://gitter.im/http4s/http4s?at=5a90d8cd0202dc012e79266d.

Break up Cookie into Request and Response

---

docs/src/main/tut/json.md

I think a lot of Http4s users would be using it for largely Json services. I understand why this is not the default behaviour, but I think this would be good to sit in the docs for those of us who write 100% Json services.

Add to Json docs to explain how to generate EntityDecoder instances for all A that has Decoder instances.

---

project/Http4sPlugin.scala

The main event is getting rid of the log4s compatibility warning.

blaze-0.12.12, log4s-1.6.1, jetty-9.4.9

---

server/src/main/scala/org/http4s/server/middleware/Timeout.scala
server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala

Deprecates the old versions, which leave the response running in the background.  We carve out namespace for the new versions by operating on `FiniteDuration` instead of `Duration`.

Introduce timeout middleware based on Concurrent.race

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala

Reopening #1634 so we can get it across the finish line.  It looks like this is binary compatible.  Apologies for this falling off my radar.
Is this helpful as is, or do we want to address the discussion in #1632 to make it useful?
/cc @kailuowang

Add expectOr methods for custom error handling on failed expects

---

blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
blaze-core/src/test/scala/org/http4s/blazecore/ResponseParser.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
core/src/main/scala/org/http4s/multipart/MultipartParser.scala
core/src/main/scala/org/http4s/util/Renderable.scala
core/src/main/scala/org/http4s/util/package.scala
examples/src/main/scala/com/example/http4s/ScienceExperiments.scala
server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
server/src/main/scala/org/http4s/server/middleware/Logger.scala
server/src/test/scala/org/http4s/server/staticcontent/StaticContentShared.scala
tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
tests/src/test/scala/org/http4s/multipart/MultipartParserSpec.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala

Port multipart goodness to to 0.18.x branch

---

scripts/helpers

Travis clones to a depth of 50, which doesn't include all the tags.  We need them all.  This is why the versions table seems to work on a local site preview, but isn't populating past a certain point on the live site.

Fix the versions table on the site

---

tests/src/test/scala/org/http4s/EntityDecoderSpec.scala

This test has added about 5 minutes to our builds.  Build less and smaller.

Tune scalacheck parameters for SemigroupK[EntityDecoder[IO, ?]]

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
build.sbt
docs/src/main/tut/auth.md
docs/src/main/tut/middleware.md
project/CentralRequirements.scala
website/src/hugo/config.toml
website/src/hugo/data/principles.toml
website/src/hugo/themes/http4s.org/layouts/_default/single.html
website/src/hugo/themes/http4s.org/layouts/partials/nav.html

http4s.org and typelevel.org are now both served over https.  Canonicalize the links appropriately.

Fix URI scheme for http4s.org and typelevel.org

---

build.sbt
website/src/hugo/static/_redirects

After this, we can set up a banner to render on EOL versions of the site, and always direct to the current versions without having to go back and republish those.

Set up /stable and /latest rewrites

---

core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/headers/Accept-Charset.scala
core/src/main/scala/org/http4s/headers/Connection.scala
core/src/main/scala/org/http4s/headers/ETag.scala
core/src/main/scala/org/http4s/headers/If-None-Match.scala
core/src/main/scala/org/http4s/syntax/NonEmptyListSyntax.scala
core/src/main/scala/org/http4s/syntax/package.scala
docs/src/main/tut/dsl.md
dsl/src/test/scala/org/http4s/dsl/PathInHttpServiceSpec.scala
tests/src/test/scala/org/http4s/headers/TransferEncodingSpec.scala

Completely removes the internal custom syntax for `NonEmptyList` using cats' instead. Note this removes some deprecated instances and may break existing code.
Is there a better alternative for `collectFirst` in cats?
Fixes #1510

Remove internal syntax for NonEmptyList and use cat's instead

---

core/src/main/scala/org/http4s/headers/ETag.scala

This is a leftover change from PR #1739 applicable to master

Place Show[EntityTag] in the companion object

---

docs/src/main/tut/testing.md

I broke this when I merged #1718 to master without running tut.  My fault.  This is what ails #1749.
Observation: it's hard to use the DSL for a polymorphic service inside a tut.

Fix deprecated call in testing.md

---

tests/src/test/scala/org/http4s/ContentCodingSpec.scala

Only in the first case did we validate that the qValues were equal.
Fixes #1669

 Fix failure in ContentCodingSpec

---

core/src/main/scala/org/http4s/multipart/MultipartParser.scala
tests/src/test/scala/org/http4s/multipart/MultipartParserSpec.scala
version.sbt
website/src/hugo/content/changelog.md

Closes #1755 .
Fixes a bug happening on uneven chunks + chunks that ended on a partial match with the boundary, but the boundary was contained in the middle of the chunk.

fix parsing of uneven stream bodies

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala

Added this while investigating #1774.
The `apply` method should return an effect.  It's inconsistent with `Http1Client`, and that one is better.  But we can't fix that here.

Add a stream constructor for async-http-client

---

build.sbt
project/Http4sPlugin.scala
prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus/PrometheusExportService.scala
prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus/PrometheusMetrics.scala

Would be cool to cut a release with this.

Backport Prometheus Server Metrics

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala

Fixes #1774
Right now, if you reuse the `F[DisposableResponse]` returned from the
`BlazeClient`, it will keep using the same submit time, which doesn't make
sense. To fix it we suspend the entire call body so those important parts
are request specific instead of `F` specific.

Make the F returned by BlazeClient Kleisli reusable

---

.appveyor.yml
.travis.yml
build.sbt
core/src/main/scala/org/http4s/QValue.scala
core/src/main/scala/org/http4s/Uri.scala
docs/src/main/tut/methods.md
docs/src/main/tut/service.md
project/Http4sPlugin.scala
testing/src/test/scala/org/http4s/illTyped.scala
website/src/hugo/content/changelog.md

Macro Paradise is not yet available for 2.12.6 and won't be for 2.13.  It appears we only needed it to bridge the macro gap to Scala 2.10, which is no longer an issue.
Fixes #1803.

Upgrade to scala-2.12.6, drop macro-compat

---

client/src/main/scala/org/http4s/client/middleware/Logger.scala
client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
client/src/test/resources/testresource.txt
client/src/test/scala/org/http4s/client/middleware/LoggerSpec.scala

The copied files are mostly unchanged, except for updating the package name, running `scalafmt`, and changing the interface of `Logger.apply` to work better with `Client[F]`.
(Hopefully this is set up against the right base branch to be merged and released as part of the 0.18 series.)

copy server logging middleware to client module

---

blaze-client/src/main/scala/org/http4s/client/blaze/bits.scala

Having a resource allocated in an object is something we want to address in #1821.  Meanwhile, @lbialy made this monkey patch for his Graal work, and I don't see any downside for regular use.

Make the blaze-client tick wheel executor lazy

---

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
jetty/src/test/scala/org/http4s/server/jetty/Issue454.scala
servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/BlockingHttp4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

The current `Http4sServlet` [uses](https://github.com/http4s/http4s/blob/release-0.18.x/servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala#L70) the async `Servlet` feature in its implementation. Unfortunately this is [not supported](https://issuetracker.google.com/issues/65104189) in the Google App Engine (GAE) standard environment so that a blocking implementation is necessary.
Consider this PR as an initial draft. I started off by copying the `Http4sServlet` and ripping it apart. So there is currently quite a lot of code duplication which should be improved.
Please note that I have never worked with `Servlet` nor with `cats.Effect` before, so unfortunately some of the changes here were a bit of guesswork for me.

Add BlockingHttp4sServlet

---

build.sbt
project/Http4sPlugin.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
servlet/src/test/scala/org/http4s/servlet/ServletIoSpec.scala

In the servlet backend, rest of request body chunk is padded with zero, and it causes a following exception in decoding JSON request:
```
org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON
at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$1(CirceInstances.scala:30)
at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:87)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:128)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:310)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:292)
at cats.effect.internals.Callback$AsyncIdempotentCallback$$anon$3.run(Callback.scala:142)
at cats.effect.internals.TrampolineEC.cats$effect$internals$TrampolineEC$$localRunLoop(Tr …
```

Prevent zero padding at servlet input chunk

---

blaze-client/src/test/scala/org/http4s/client/blaze/PooledClientSpec.scala
client/src/main/scala/org/http4s/client/middleware/Logger.scala
client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
client/src/test/scala/org/http4s/client/middleware/LoggerSpec.scala

Going to and from HttpService in the client logging middleware means dispose isn't called. :face_with_head_bandage: 
Unit testing this is tricky: the problem is in the client project, and we'd normally test that with `Client.fromHttpService`, but that has a trivial `dispose` method.  We need to test this somewhere we have a real client.  I manually tested this with the reproduction in #1833.
When merged to master, apply0 will replace apply.
Fixes #1833.
/cc @rhyskeepence

Fix deadlock in client logging middleware

---

client/src/main/scala/org/http4s/client/middleware/Logger.scala
client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
server/src/main/scala/org/http4s/server/middleware/Logger.scala
server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

A small PR to remove `log4s` dependency from `Logger` and the fixed log level (`info`).
before:
```
Logger.logMessage[F, Message[F]](msg)(logHeaders, logBody)(org.log4s.Logger)
```
now:
```
Logger.logMessage[F, Message[F]](msg)(logHeaders, logBody)(message => log.info(message) // or .warn, .error, etc.)
```

Removed fixed log level from Logger

---

build.sbt

It was necessary when it was added mid-cycle, but now it's ready to play by the rules.

Remove prometheus-server-metrics MiMa exemption

---

boopickle/src/main/scala/org/http4s/booPickle/BooPickleInstances.scala
boopickle/src/main/scala/org/http4s/booPickle/package.scala
boopickle/src/test/scala/org/http4s/booPickle/BoopickleSpec.scala
build.sbt
project/Http4sPlugin.scala

We use [boopickle](https://boopickle.suzaku.io/) on our application with the encoders in this PR. I thought this could be generally useful in http4s though I'm not sure how widely used `boopickle` is.
This is also an opportunity, to receive any criticism you may have to my implementation. In particular I'm not sure if there is enough testing
I couldn't find an aggregate on `build.sbt` to include this into the overall build. Is it needed?

Boopickle encoders

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala

Targeting 0.18.x as discussed in #1856

Remove redundant slash check in BlazeBuilder (0.18.x)

---

core/src/main/scala/org/http4s/multipart/Part.scala

Deprecate Part.empty

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/test/scala/org/http4s/client/ClientSpec.scala

Addresses #1872 in the easy case where the request URI is absolute.

add Host header to requests submitted by Client.fromHttpService if the request URI is absolute

---

build.sbt
okhttp-client/src/main/scala/org/http4s/client/okhttp/OkHttp.scala
okhttp-client/src/test/scala/org/http4s/client/okhttp/OkHttpClientSpec.scala
project/Http4sPlugin.scala

This adds an OkHttp implementation for Client.
This is heavily based on the one for async-http-client.
The motivation for this is to have a Client backend which is capable of HTTP/2.
This PR continues https://github.com/http4s/http4s/pull/1851 and is against `release-0.18.x` in stead of master

Add an OkHttp client (with HTTP/2) (to 0.18)

---

core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/ServerSoftware.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
website/src/hugo/content/changelog.md

http4s-core shouldn't have anything in the `org.http4s.server` package.

Move ServerSoftware to top-level package

---

server/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
website/src/hugo/content/changelog.md

Parameterize EntityLimiter

---

server/src/main/scala/org/http4s/server/middleware/HSTS.scala
website/src/hugo/content/changelog.md

Parameterize HSTS middleware

---

core/src/main/scala/org/http4s/MimeDB.scala
mimedb-generator/src/main/scala/mimegenerator/MimeGenerator.scala

The flags `Uncompressible` and `NotBinary` were wrongly set. This PR fixes that and updates `MimeDB` accordingly. There are some changes on the upstream db as reflected on some changes in the resulting file
/cc @sderosiaux

Fix MimeGenerator flags

---

examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Module.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Server.scala
server/src/main/scala/org/http4s/server/middleware/Timeout.scala
server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
website/src/hugo/content/changelog.md

I've only generalised the non-deprecated, public API so far. Should I continue?

Parameterize `Timeout` middleware

---

server/src/main/scala/org/http4s/server/middleware/URITranslation.scala
website/src/hugo/content/changelog.md

Parameterize `URITranslation` middleware

---

server/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala
website/src/hugo/content/changelog.md

Parameterize `CSRF` middleware

---

client/src/main/scala/org/http4s/client/Client.scala
docs/src/main/tut/client.md

The documentation says that when using `.stream` you'll receive
a `Stream[F, Http1Client]`, this is false. The method returns a
`Client[F]`.
I've also added the type on the `val` below just to make it obvious
what you have at this point. To me, it was not when I first reached
into the doc.

Docs: improve client doc

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
website/src/hugo/content/changelog.md

fixes https://github.com/http4s/http4s/issues/1878
We wanted to keep consistency with our Content Type headers across JSON implementations.

Removing charset for argonaut encoders

---

client/src/main/scala/org/http4s/client/PoolManager.scala

Should fix https://github.com/http4s/http4s/issues/1920

Remove the key from idleQueue if it is empty after dequeue

---

core/src/main/scala/org/http4s/Credentials.scala
server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuth.scala

Changes the BasicCredentials extractor to give (username, password).
This is motivated by having a `Credentials` object and needing the authentication information. Currently, the pattern match looks like
```scala
authInfo match {
case BasicCredentials(BasicCredentials(username, password)) => ...
...
}
```
After this change, it now looks like
```scala
authInfo match {
case BasicCredentials(username, password) => ...
...
}
```

Change BasicCredentials extractor to return (username, password)

---

server/src/main/scala/org/http4s/server/middleware/Logger.scala
server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
server/src/test/scala/org/http4s/server/middleware/LoggerSpec.scala

Couple of concerns:
1. Lost the handling of a none in F inside RequestLogger. Would this need to be handled in the passed in natural transformation?
2. Existing spec only appears to assert that there is no impact on the requests, not that the logging occurs. Also doesn't exercise the !logBody paths.
Thanks in advance for review and feedback.

Altered Logger, RequestLogger and ResponseLogger to be more parametric using Kleisli

---

server/src/main/scala/org/http4s/server/middleware/StaticHeaders.scala
server/src/test/scala/org/http4s/server/middleware/StaticHeadersSpec.scala

Adds Static Headers to a request. Puts in place a `no-cache` middleware based on this design.

Add StaticHeaders middleware

---

client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala

Added redactHeadersWhen arg to Logger.logMessage
In the !logBody branch of RequestLogger this argument was accidentally
not passed, causing the default value to be used, potentially logging
sensitive headers.

Fix RequestLoggerRedaction #1950. Supercedes PR #1951.

---

dsl/src/main/scala/org/http4s/dsl/Http4sDsl.scala
dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
dsl/src/test/scala/org/http4s/dsl/PathSpec.scala

Add UUIDVar, a path extractor for java.util.UUID
I also considered adding a ValidatedUUIDVar to extract a Validated[Throwable, UUID] from paths but then realized that there is already a simple way to return BadRequest for invalid UUIDs:
```
HttpService[IO] match {
case GET -> Root / "user" / UUIDVar(userId) => ...
case GET -> Root / "user" / str => BadRequest(s"Invalid identifier '$str'")
}
```
The [original PR](https://github.com/http4s/http4s/pull/1945) targeted 0.18.x but broke binary compatibility, this new one targets master to avoid that complication.

Add UUID path extractor

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala

This currently throws an `IOException`, which is far too general.

Throw ConnectException on connection failure in blaze client

---

.idea/codeStyles/Project.xml

With IntelliJ 18.2, scalafmt is supported directly by the scala plugin.
This PR enables that.

Use scalafmt directly from IntelliJ

---

docs/src/main/tut/dsl.md

As support for `java.util.UUID` has been recently added in https://github.com/http4s/http4s/pull/1953

Mention UUIDVar in tut/dsl.md

---

build.sbt
prometheus-client-metrics/src/main/scala/org/http4s/client/prometheus/DestinationAttribute.scala
prometheus-client-metrics/src/main/scala/org/http4s/client/prometheus/PrometheusClientMetrics.scala

Client middleware that collects a few Prometheus metrics, very similar to the `prometheus-server-metrics` module. Hopefully this will be useful to the http4s community. This is my first http4s PR, feedback would be greatly appreciated.
Currently, four client metrics are collected:
- Counter for total number of responses received
- Histogram for response duration/latency
- Gauge for number of active requests
- Counter for total number of client errors
At Banno, we often use the same `Client` instance to send requests to multiple destinations (e.g. endpoints, services) and want to track metrics separately based on destination, so several of the metrics use a `destination` label. This PR uses the value of the request attribute `PrometheusClientMetrics.Destination` as the `destination` label …

Prometheus client metrics

---

.idea/codeStyles/Project.xml
blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
core/src/main/scala/org/http4s/websocket/Websocket.scala
server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala
server/src/main/scala/org/http4s/server/websocket/package.scala

This PR should optimize some of the websocket stream code, as well as providing clients a finalizer to run when the websocket closes. 
Breaking down the old inputStream:
```scala
val wsStream = inputstream
.to(ws.receive)
.onFinalize(onStreamFinalize)
.mergeHaltR(ws.send.onFinalize(onStreamFinalize).to(snk).drain)
.interruptWhen(deadSignal)
.onFinalize(sendClose)
.compile
.drain
```
Problems with this code:
- We do not need to end the stream because we decided to stop sending elements. we can choose to not send any more on the server. If anything, we can also give a handler to shutting down manually if necessary, and I can add this.
- `onStreamFinalize` is a moot check: the stream will be interrupted regardless once it receives a close frame since that will set the signal.
- `onClose` can …

improve WS stream, add `onClose` handler

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala

banner is being printed with a single logger call

---

project/Http4sPlugin.scala

Not doing on release-0.18.x, because json4s-3.5 is not compatible with 3.6.  But jawn only depends on the ast, and from my research on non/jawn#113, it seems compatible.

 json4s-3.6 is compatible with jawn-0.12.2?

---

server/src/main/scala/org/http4s/server/Router.scala
server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala
server/src/main/scala/org/http4s/server/middleware/TranslateUri.scala
server/src/main/scala/org/http4s/server/middleware/URITranslation.scala
server/src/test/scala/org/http4s/server/middleware/TranslateUriSpec.scala
server/src/test/scala/org/http4s/server/middleware/UriTranslationSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/ResourceServiceSpec.scala

This PR changes the behaviour of `UriTranslation` to take the contents of the prefix into account as well.
It inlines the old implementation in `Router`, to not do the check twice.
Fixes #1962

Make UriTranslation check prefix contents before matching

---

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala

1. `HttpConfiguration.setSecurePort` and `HttpConfiguration.setSecureScheme` are a part of the mechanism for redirecting some requests to another (secure) port/scheme. Setting them for HTTPS connector doesn't do anything. See this [example](https://github.com/eclipse/jetty.project/blob/21365234f8cf036829f7a03e5c7b89a9572444f9/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ManyConnectors.java#L71-L72).
2. `ServerConnector` has constructors that build an `SslConnectionFactory` and `HttpConnectionFactory` automatically.
3. `SecureRequestCustomizer` is [automatically added](https://github.com/eclipse/jetty.project/blob/21365234f8cf036829f7a03e5c7b89a9572444f9/jetty-server/src/main/java/org/eclipse/jetty/server/AbstractConnectionFactory.java#L123-L128) for HTTP connection factories …

JettyBuilder: Clean up HTTP/HTTPS configuration

---

server/src/main/scala/org/http4s/server/middleware/HeaderEcho.scala
server/src/test/scala/org/http4s/server/middleware/HeaderEchoSpec.scala

A server middleware that echoes selected headers from request to response

Add header echoing server middleware

---

website/src/hugo/content/code-of-conduct.md

Add additional resource for those seeking community staff support.

Add additional community staff support

---

.idea/codeStyles/Project.xml
core/src/main/scala/org/http4s/internal/package.scala
core/src/main/scala/org/http4s/util/package.scala
server/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala

closes #1989 
This changes our CSRF middleware significantly. In particular:
- CSRF tokens are now newtyped... because passing around `String` everywhere was honestly giving me a goddamn headache
- CSRF token signatures are encoded in hexadecimal strings, making it url-safe. For example: In the case of websockets, clients (if using a browser) often have no way of embedding the csrf token in the header, forcing sending in a query parameter or as part of the path.
- CSRF Internal functions are now not private, as I've had to define my own combinators with them before. Just in case of a very special use case for whatever reason (i.e csrf token in multipart payload), the functions are exposed to be able to construct csrf actions from a specific endpoint.
- CSRF now takes a conditional …

CSRF Overhaul

---

blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
client/src/test/scala/org/http4s/client/JavaNetClientSpec.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala

If we aggressively use this one, we won't leak two threads every test run.
`AsyncHttpClient` will still leak until #1993 is merged.

Create an expiring test scheduler

---

client/src/main/scala/org/http4s/client/middleware/Retry.scala

In short, this PR updates logging when considering whether to re-try or not.
https://gitter.im/http4s/http4s?at=5b8ec8fc60f9ee7aa4d980ca prompted this change.

Modify Logging within Retry

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/ProtocolSelector.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala
build.sbt
client-metrics/src/test/scala/org/http4s/client/metrics/MetricsSpec.scala
docs/src/main/tut/service.md
examples/docker/src/main/scala/com/example/http4s/Example.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
jetty/src/test/scala/org/http4s/server/jetty/JettyServerSpec.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
server/src/test/scala/org/http4s/server/ServerSpec.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSpec.scala

Switch BlazeBuilder to HttpApp. Can either get stolen or merged after #1993

Blaze Builder Switch

---

server/src/main/scala/org/http4s/server/middleware/Throttle.scala
server/src/test/scala/org/http4s/server/middleware/ThrottleSpec.scala

Feedback appreciated!
There is definitely room for more features, in a subsequent PR I'd like to make taking tokens a function of the `Request` so that throttling can be based on request sizes or IPs rather than just simply the number of requests.  I'd also like to enable customisation of the response to throttled requests.  If these are considered essential then I can add them to this PR however my preference would be to get this merged before iterating further.

Initial implementation of Throttle middleware

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala

This fixes the name of a duplicate function `withIdleTimeout` that should actually be named `withMaxTotalConnections`. The implementation is already correct, and the real `def withIdleTimeout(idleTimeout: Duration): BlazeClientBuilder[F]` remains untouched.

Renames incorrect, duplicate withIdleTimeout to withMaxTotalConnections

---

CODE_OF_CONDUCT.md
README.md
website/src/hugo/content/code-of-conduct.md
website/src/hugo/content/getting-help.md

The Scala Code of Conduct is clearer, [endorsed by Typelevel], and aligned with our foundation of [cats-effect], [fs2], and [Scala] itself.
[endorsed by Typelevel]: https://typelevel.org/blog/2016/12/17/scala-coc.html
[cats-effect]: https://github.com/typelevel/cats-effect/pull/356
[fs2]: https://github.com/functional-streams-for-scala/fs2/blob/267e9debd206a6f1df5cfdc7ce1aa5d3112051ac/CODE_OF_CONDUCT.md
[Scala]: https://www.scala-lang.org/conduct/

Scala Code of Conduct

---

testing/src/main/scala/org/http4s/testing/Http4sMatchers.scala
testing/src/main/scala/org/http4s/testing/IOMatchers.scala
testing/src/main/scala/org/http4s/testing/RunTimedMatchers.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala

Resolves #1430.
As described in issue #1430, the `Http4sMatchers` trait is  not generic on the _effect_ `F[_]` type, and neither was a parent trait `IOMatchers` trait. We try to address this situation doing the following: 
- We factor out the trait `IOMatchers` into a `RunTimedMatchers` trait, which keeps most fo the IOMatchers trait methods and logic, but is generic on the effect type `F[_]`. Since IOMatchers was using some specific methods of `cats.effect.IO`, we need to extract those as abstract method, following the GoD template-method pattern. 
- We turn `IOMatchers` into an extension of `RunTimedMatchers` that specialises those abstract methods, to the methods of IO.
- We make `Http4sMatchers` generic on the F type. Luckily, this is just replacing "IO" with F
One thing to note is …

Refactor Http4sMatchers to be generic on F-Type

---

core/src/main/scala/org/http4s/headers/Origin.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/OriginHeader.scala
server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala
tests/src/test/scala/org/http4s/parser/OriginHeaderSpec.scala

This PR improves the parsing of the `Origin` header. It's joint work with @hosamaly at Syntactic Sugar, London.
Instead of being interpreted as a string, the header is now interpreted as a list of items of type `Origin.Host`. These are similar to `Uris` except that Origin only permits a scheme, host, and port.
We commonly think of the Origin as containing a single host. According to the Mozilla Developer page, however, the header may be an empty string (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin). And according to the RFC, it may contain multiple hosts (https://tools.ietf.org/html/rfc6454#section-7).
There's one last complication. The RFC technically states that `Origin` may be the literal string `null`, which translates to an "opaque origin" ()

Structured parsing of the Origin header (issue #2007)

---

core/src/main/scala/org/http4s/UrlForm.scala
tests/src/test/scala/org/http4s/UrlFormSpec.scala

add Monoid instance for UrlForm

---

docs/src/main/tut/index.md

Looks like sbt-revolver launches with `reStart` now.

re-start => reStart

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala

More to come, but I'm trying to keep things smaller.

Remove ExecutionContext and Timer from async-http-client

---

blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala

When we read an EOF, request a disconnect.  This signals outbound that we're done and allows a chance to clean up.
Before this change, when a client disconnects without either the server or client signalling the end of the connection, the HTTP stage is shut down but no command is passed out.  This delays the cleanup of the middle stages, such as `QuietTimeoutStage`.

Send Disconnect event on EOF

---

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala

Hi!
I've added tracking redirect locations in the response attributes. I've also pulled the status code handling logic into a separate function.

Record intermediate redirect locations

---

jetty/src/test/scala/org/http4s/server/jetty/JettyServerSpec.scala
servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/BlockingHttp4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
servlet/src/main/scala/org/http4s/servlet/package.scala
tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSpec.scala

It is an error to add an async context listener after a context is completed.  We need to install the timeout listener before we race against the response.
The unit test passed before the fix, but shows that we don't break the basic functionality.  The error condition is rendered on an asynchronous, container owned thread, and I don't see that we have access to it.  Furthermore, it only happens under load.
Fixes #2103.

Don't start response until after we add async timeout listener

---

build.sbt
project/Http4sPlugin.scala
project/PrivateProject.scala
project/plugins.sbt

Fails the build if we declare a dependency we don't use.  Prevents us from passing liabilities downstream.
Not enforced on private (e.g. unpublished) projects.
Bonus: stop publishing empty http4s-tests module.

Enable unusedCompileDependenciesTest

---

client-metrics/src/main/scala/org/http4s/client/metrics/Metrics.scala
client/src/main/scala/org/http4s/client/PoolManager.scala
core/src/main/scala/org/http4s/AuthedRequest.scala
core/src/main/scala/org/http4s/ServerSentEvent.scala
core/src/main/scala/org/http4s/headers/Origin.scala
dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/GitHubService.scala
jetty-client/src/main/scala/org/http4s/client/jetty/ResponseListener.scala
jetty-client/src/main/scala/org/http4s/client/jetty/StreamRequestContentProvider.scala
prometheus-client-metrics/src/main/scala/org/http4s/client/prometheus/PrometheusClientMetrics.scala
prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus/PrometheusMetrics.scala
server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala
server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala

Co-authored-by: Andrea Magnorsky <roundcrisis@gmail.com>
Adds the `final` modifier to case classes that are not already `final` or `sealed abstract`. Exceptions listed below:
- `TimedMatcher` in `/testing/src/main/scala/org/http4s/testing/RunTimedMatchers.scala`
- Anything under a `src/test` path
Adding the `final` or `sealed abstract` modifiers to the following case classes fails to compile, so these have also been excluded from this refactor:
- `/core/src/main/scala/org/http4s/parser/StrictTransportSecurityParser.scala:  private case class StrictTransportSecurityParser(override val input: ParserInput)` 
- `./examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/JsonXmlHttpEndpoint.scala:  case class Person(name: String, age: Int)`
Fixes #2074

Mark case classes final

---

core/src/main/scala/org/http4s/StaticFile.scala

Beware, this PR depends on change in fs2 (https://github.com/functional-streams-for-scala/fs2/pull/1257) and will fail the build until that one is merged

#2071 use read range of fs2

---

testing/src/main/scala/org/http4s/testing/Http4sMatchers.scala
testing/src/test/scala/org/http4s/testing/Http4sMatchersSpec.scala

The `haveHeaders` matcher was using reference equality, not value equality.
Fixes #2099.

Fix haveHeaders matcher to work on value equality

---

client/src/main/scala/org/http4s/client/JavaNetClient.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala

`HttpUrlConnection` returns the body in `getErrorStream` rather than `getInputStream` when the response code is unsuccessful.  Well, sometimes.  Sometimes it returns `null`.
1. Try to read the body from `getInputStream`
2. If that throws, try to read an error from `getErrorStream`, if it's there.
3. Otherwise, return an empty body.
4. Close whatever we can find to close on dispose.
Fixes #2114.

Handle unsuccessful responses in JavaNetClient

---

build.sbt

When we add a new module in the middle of a series, we have to disable the `mimaPreviousArtifacts`.  We neglected to clean these up later.

Remove MiMa opt-outs for recent modules

---

build.sbt

We've got @scala-steward working for us.  It's less important to have this in our face.
Arguably this is still useful on maintenance branches, where @scala-steward doesn't operate.  Discuss.

Don't check for dependency updates on load

---

jetty-client/src/main/scala/org/http4s/client/jetty/JettyClient.scala
jetty-client/src/main/scala/org/http4s/client/jetty/ResponseListener.scala

The `ConcurrentEffect` is enough.

Remove ExecutionContext from jetty-client interface

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/main/scala/org/http4s/client/DefaultClient.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala
docs/src/main/tut/streaming.md

Based on @ChristopherDavenport's good idea in #1714.  The abstract method is still based on `Resource`, but a `Stream[F, Response[F]]` is simpler than `.streaming`, and `.streaming` can be easily derived from it.

Replace Client.streaming with Client.stream

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala
blaze-server/src/main/scala/org/http4s/server/blaze/WSFrameAggregator.scala
blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala
build.sbt
core/src/main/scala/org/http4s/websocket/FrameTranscoder.scala
core/src/main/scala/org/http4s/websocket/WebSocket.scala
core/src/main/scala/org/http4s/websocket/WebSocketContext.scala
core/src/main/scala/org/http4s/websocket/WebSocketFrame.scala
core/src/main/scala/org/http4s/websocket/package.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
project/Http4sPlugin.scala
server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala

The `org.http4s.websocket` package is awkwardly split across the http4s-websocket repo and http4s-core.  No package should ever live in two artifacts.
The reason for the http4s-websocket repo was to share a model between blaze and http4s without adding any dependencies to the former.  Since then, the blaze repo dropped websocket support entirely.  If we unify it here, we can use a model with all our dependencies.  This includes `ByteVector`, which is back on our classpath since fs2-core again depends on scodec-bits.  That gives us an immutable model.
There are all kinds of shady numeric truncations and widenings going on here, and it's worth looking closely at the `WebSocketFrame` class.
Additionally, standardizes on the `WebSocket` capitalization in place of `Websocket`

Unify org.http4s.websocket package, use ByteVector

---

website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html

Pointed out by @Tomczik76
Ideally, older versions of the docs would pull this from a common place, so we don't need to go back and republish old versions when new series are published.

Fix 0.19 link in 0.18 docs

---

blaze-client/src/main/scala/org/http4s/client/blaze/ClientTimeoutStage.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ReadBufferStageSpec.scala
blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala
blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketSupport.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
core/src/main/scala/org/http4s/websocket/WebSocketHandshake.scala
core/src/main/scala/org/http4s/websocket/package.scala
project/Http4sPlugin.scala
tests/src/test/scala/org/http4s/websocket/WebSocketHandshakeSpec.scala
tests/src/test/scala/org/http4s/websocket/WebSocketSpec.scala

This gets us working again off blaze master, so we can release that as blaze-0.14.0 before http4s-0.19.0.

Remove outbound commands, get on blaze master

---

core/src/main/scala/org/http4s/Message.scala

Response.timeout is currently only used by AsyncHttp4sServlet, so I think this change is extremely low risk.
A 503 ("The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state") code is more appropriate to a timeout than the generic 500 ("A generic error message" that something broke horribly). We also considered and rejected 429 ("The user has sent too many requests") because it blames the client for a server problem.

Changed Response.timeout from 500 to 503 - ServiceUnavailable

---

version.sbt
website/src/hugo/content/changelog.md

Republishes v0.19.0 as v0.19.0-M4, as was originally intended.  Explains our mistake and our recovery plan in the changelog.
version.sbt will need to be manually bumped to 0.19.1-SNAPSHOT after this is merged.
Thanks to @bpholt and @Daenyth for their suggestions on how to deal with this.

Release v0.19.0-M4; explain v0.19.0

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
jetty-client/src/main/scala/org/http4s/client/jetty/JettyClient.scala

Add Allocate builders

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/ProtocolSelector.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
docs/src/main/tut/client.md
docs/src/main/tut/json.md
docs/src/main/tut/service.md
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExampleWithRedirect.scala
examples/docker/src/main/scala/com/example/http4s/Example.scala
project/Http4sPlugin.scala

If an `HttpApp` takes too long to respond, cancel it and respond with a 503.

Implement a response line timeout for blaze server

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala
core/src/main/scala/org/http4s/internal/package.scala
core/src/main/scala/org/http4s/syntax/AsyncSyntax.scala
core/src/main/scala/org/http4s/syntax/package.scala

The proper place for this is cats-effect.  We should not pollute the namespace or take long term support burden on things unrelated to HTTP.

Deprecate async syntax

---

client/src/main/scala/org/http4s/client/middleware/Retry.scala

It'd be nice to have a little bit more control on what's logged in `Retry`, specially in the headers.
This is not nice, but it captures the intention. Ideally I'd like to use the `Logger.logMessage` that's in master so I can format the string representation of the request. Would we possible to have in in .18?

Redact headers in Retry logging

---

testing/src/main/scala/org/http4s/testing/ErrorReportingUtils.scala
tests/src/test/scala/org/http4s/util/ExecutionSpec.scala

Stack trace that print directly to stderr are suppressed, while exceptions logged at error level are still logged.
Should these logs be suppressed too?
Any advice on the "copyright" for the copied function from cats-effect?
Closes issue  #2049

Silence expected exceptions

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala

Start receiving the response concurrently with rendering the request.  Many responses can be generated without consuming the body in its entirety, so there's no need to finish the write before trying to read.

Request and response concurrent in blaze-client

---

blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala

Fixes #2191.
These are not doing anything but testing a race condition for an obscure scenario that would be better implemented without a blaze client in the first place.

Remove ill-conceived, zero-timeout unit tests

---

server/src/main/scala/org/http4s/server/middleware/Timeout.scala
server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala

Seems consistent with recent changes.

Change Default Response on Timeout Middleware to ServiceUnavailable

---

blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala

Fix "behave and not deadlock" test:
* Run in parallel, which is a more interesting test.
* Scale the size of the test to the number of processors.  We may just be asking too much of Travis.
* Remove random sleep in test servlet.  I can reproduce the failure with a long enough sleep.
Fixes #2199, I hope.

Make "behave and not deadlock" test parallel

---

server/src/main/scala/org/http4s/server/middleware/ResponseTiming.scala
server/src/test/scala/org/http4s/server/middleware/ResponseTimingSpec.scala

- Uses implicit `Clock[F]` to time from headers parsed to response started
- Adds header to `Response`, named "X-Response-Time" by default
For #2014

Add simple `ResponseTiming` middleware and test

---

project/Http4sPlugin.scala

We decided to open an 0.20 series instead, so we don't need this cruft anymore.

Remove MiMa exceptions on 0.19

---

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/package.scala

Adds a `shutdownTimeout` to the server builder.
- When the resource is closed, we call `jetty.stop()`.
- Add a lifecycle listener to await the stop.
- If the server stops within the `shutdownTimeout`, complete the release.
- If not, jetty force stops and we fail the release with a `TimeoutException`

Shut down a jetty server gracefully

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientBuilderSpec.scala

add method to set max header length to BlazeClientBuilder

---

client/src/main/scala/org/http4s/client/PoolManager.scala
client/src/test/scala/org/http4s/client/PoolManagerSpec.scala

We're not counting ourselves against the `maxWaitQueueLimit` when enqueuing a waiter, which results in us going one past the `maxWaitQueueLimit`.

Fix off-by-one error in maxWaitQueueLimit

---

core/src/main/scala/org/http4s/parser/CookieHeader.scala
tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala

Allow cookie string to have ';' at the end

---

client/src/main/scala/org/http4s/client/DefaultClient.scala
core/src/main/scala/org/http4s/internal/package.scala
tests/src/test/scala/org/http4s/internal/AllocatedSpec.scala

My definition of `allocated` wasn't as clever as I thought it was.  Centralized the bulky interpreter in our internal package for eventual contribution to cats-effect.

Define an allocated that doesn't hang on failure

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
server/src/main/scala/org/http4s/server/package.scala
servlet/src/main/scala/org/http4s/servlet/ServletContainer.scala
servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

The server builder traits were a poor means of abstraction that few were using in the wild anyway.
* Eliminate marker traits for server builders
* Privatize `ServerBuilder`, which does still contribute to consistency
* Move defaults into `org.http4s.server.defaults` package

Remove or privatize server builder *support traits

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala

When debug logging is on, an infinite idleTimeout crashes, and an infinite idle timeout is useless anyway.

Only add the idle timeout stage when idleTimeout is finite

---

version.sbt
website/src/hugo/content/changelog.md

I haven't reproduced #2193 yet. No reason to sit on a working bugfix in the meantime.

Release v0.18.21

---

dsl/src/main/scala/org/http4s/dsl/Http4sDsl.scala
dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
dsl/src/test/scala/org/http4s/dsl/PathInHttpRoutesSpec.scala

Adds an new matcher to the DSL supporting option flag-style query parameters as discussed in  #2254.

Support flag query parameters in DSL

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
client/src/main/scala/org/http4s/client/PoolManager.scala
client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala

Both of these tests fail by timing out on my local machine:
```scala
[info] BlazeClientSpec                                                                                     
[info] Blaze Http1Client should                                     
[info]   + raise error NoConnectionAllowedException if no connections are permitted for key (789 ms)
[info]   + make simple https requests (966 ms)                                                                                                      
[info]   + behave and not deadlock (1 second, 34 ms)                                         
[error]   x behave and not deadlock on failures with parTraverse (30 seconds, 245 ms)                      
[error]    None is not Some (BlazeClientSpec.scala:151)                               
[error] …
```

Fix deadlocks on failures with parTraverse and parSequence

---

server/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala

- fix `checkCSRFToken` to use `createResponseCookie`.
- make it possible to configure various relevant settings
for csrf cookie.
- add builder for `CSRF`
- add ability to read token from form

csrf: cookie settings + builder + `createResponseCookie` usage

---

client/src/main/scala/org/http4s/client/oauth1/oauth1.scala
core/src/main/scala/org/http4s/UrlForm.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
tests/src/test/scala/org/http4s/UrlFormSpec.scala

Chain has a Monoid instance available to it, while Seq does not. Partially addresses #2096.
This was a pretty mechanical conversion and might be able to be optimized.

change UrlForm to use Chain instead of Seq

---

client/src/main/scala/org/http4s/client/middleware/Metrics.scala
dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardClientMetricsSpec.scala
dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/util.scala
prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/util.scala

Fixes a bug with the `Client` `Metrics` code where we would decrement active requests and record total time before the `Resource` returned from the `client.run` was actually `release`d. This means our metrics were not accurate. 
The fix here is to perform both of these actions _after_ the `client.run` has `.release`d. To do so, both the `recordTotalTime` and incr/decr of the active requests have been turned into `Resource`s of their own, that `.release` after the `client.run`. This results in the behavior we expect. A test has been added to demonstrate the bug, and to show that it is now fixed. 
fixes https://github.com/http4s/http4s/issues/2282

Record Metrics after `client.run` Resource has released 

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
docs/src/main/tut/client.md
docs/src/main/tut/service.md
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala

We deprecated `BlazeBuilder` without deprecating its companion.  It used the old `QuietTimeoutStage`, which was broken by other changes.
Now the companion is also deprecated, so people are warned not to use it, and the deprecated implementation now forwards to the maintained version.
Fixes the redux of #2253.

Deprecate BlazeServer companion, forward to BlazeServerBuilder

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala

Multiple IdleTimeoutStages, whose timers have been canceled, are piling up on recycled connections.  This ensures that we clean up what we add.
It's sloppy, but so is the problem.  It's another case of trying to shift life cycles outside a traditional bracket, and I haven't yet figured out how to make it work as a bracket.
I expect that this fixes #2289.

Stop leaking IdleTimeoutStages

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Client.scala
client/src/main/scala/org/http4s/client/BasicManager.scala
client/src/main/scala/org/http4s/client/ConnectionManager.scala
client/src/main/scala/org/http4s/client/PoolManager.scala

We were throwing away the `F[Unit]` instead of returning it.
Bonus: removed parens on `shutdown()`, since it's a pure value, not a side effect.

Fix shutdown in BlazeClientBuilder

---

client/src/main/scala/org/http4s/client/PoolManager.scala
client/src/main/scala/org/http4s/client/middleware/Retry.scala
client/src/test/scala/org/http4s/client/middleware/RetrySpec.scala

It seems odd to retry on a `TimeoutException`.
`PoolManager` throws a `TimeoutException` when a request has been in the wait queue for too long: https://github.com/http4s/http4s/blob/master/client/src/main/scala/org/http4s/client/PoolManager.scala#L209 so is something that might be a problem.

`Retry` client middleware: don't retry on `WaitQueueTimeoutException`

---

docs/src/main/tut/auth.md
docs/src/main/tut/client.md
docs/src/main/tut/cors.md
docs/src/main/tut/dsl.md
docs/src/main/tut/entity.md
docs/src/main/tut/hsts.md
docs/src/main/tut/json.md
docs/src/main/tut/methods.md
docs/src/main/tut/middleware.md
docs/src/main/tut/service.md
docs/src/main/tut/static.md
docs/src/main/tut/testing.md
docs/src/main/tut/uri.md

Note: I just applied this change to a single file. Feel free to close this if it's not desired, or let me know if this seems better and I'll happily apply the same change to all the docs.
:silent is desirable to avoid showing the user repl responses
about each individual import. Usually we want to show the
user the types inferred from repl lines, but for import
statements there's no value. The proof the import was
found is in the docs compiling at all.
The tradeoff here is that when the markdown is rendered, there will be a break between blocks that otherwise would be in the same file

Docs: Use :silent on import statements

---

docs/src/main/tut/service.md

Motivated by this example, where a user tried to lift
a server created in IO via `.stream` into a `Resource`,
then was left with a process that appeared to work
but could not exit
https://gitter.im/http4s/http4s?at=5c2550d7d945b968820580ef

Docs: Add a simple example of building server using Resource

---

dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
dsl/src/test/scala/org/http4s/dsl/PathSpec.scala

Leading slashes in the DSL `Path` do not create an empty segment, because we can't distinguish `www.example.com` from `www.example.com/`.  In other words, `Path("/") == Path("") == Root`.
Currently, we drop the leading slash not once, not repeatedly, but twice:
* `Path("//a") == Root / "a"`
* `Path("///a") == Root / "" / "a"`
This change consistently drops the leading slash once:
* `Path("//a") == Root / "" / "a"`
* `Path("///a") == Root / "" / "" / "a"`
Adds a scaladoc, with doctests, and a property test about consistency between `apply(String)` and `apply(List[String])`.
This is inspired by the discussion on #2273.

Make double slashes more reasonable in DSL

---

.gitignore
client/src/main/scala/org/http4s/client/Client.scala
client/src/main/scala/org/http4s/client/DefaultClient.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala

Adds - 
```
def expectOptionOr[A](req: Request[F])(onError: Response[F] => F[Throwable])(implicit d: EntityDecoder[F, A]): F[Option[A]]
def expectOptionOr[A](uri: Uri)(onError: Response[F] => F[Throwable])(implicit d: EntityDecoder[F, A]): F[Option[A]]
def expectOptionOr[A](s: String)(onError: Response[F] => F[Throwable])(implicit d: EntityDecoder[F, A]): F[Option[A]]
def expectOption[A](req: Request[F])(implicit d: EntityDecoder[F, A]): F[Option[A]]
def expectOption[A](uri: Uri)(implicit d: EntityDecoder[F, A]): F[Option[A]]
def expectOption[A](s: String)(implicit d: EntityDecoder[F, A]): F[Option[A]]
```
These methods decode and are Some on Succesful, and return None on 404. And have a failure mechanism similar to the expect line. 
Open Questions - None on `Gone`?

Option Client Decoding

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerMtlsSpec.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/SSLClientAuthMode.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

With this mTLS can be optional for the request.
Changes as per discussion on #2218.
Note that this is a breaking change. Existing boolean value is changed to an enum.

Change clientAuthMode to an enum

---

core/src/main/scala/org/http4s/EntityDecoder.scala

Noticed the typo and just gave the file a quick scan, generated the scaladoc locally to verify

Fix typo in EntityDecoder.apply scaladoc

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
argonaut/src/main/scala/org/http4s/argonaut/package.scala
argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/package.scala
circe/src/test/scala/org/http4s/circe/CirceSpec.scala
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
jawn/src/test/scala/org/http4s/jawn/JawnDecodeSupportSpec.scala

The direction I was taking was to allow overriding of the error messages in the traits .
I'm open to using implicits instead, just need suggestions.

Custom Json Error messages for Argonaut and Circe

---

docs/src/main/tut/cors.md

Clarifies CORS documentation based on a comment in
https://github.com/http4s/http4s/issues/2361#issuecomment-457558974
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)
the scheme is a required part of the header so a change in the underlying header
parser to reflect this makes sense.
Connects #2361

Include scheme in CORS middleware examples

---

docs/src/main/tut/client.md
docs/src/main/tut/middleware.md
prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala
prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusClientMetricsSpec.scala
prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusServerMetricsSpec.scala

Fixes #2367 
Registration is not happening in an effect and can throw if it double registered for the same metric.

Prometheus Effect suspension

---

client/src/main/scala/org/http4s/client/PoolManager.scala

Recently I ran into this message:
> No connections available for the desired key. Stats: ...
I wasn't sure which downstream service call was not being serviced, i.e. per the above message.
It seems useful to me to add this value to know this information, i.e. which downstream's call is not being serviced.

Log Request Key

---

bench/src/main/scala/org/http4s/bench/CirceJsonBench.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala

Allow specification of media type

---

client/src/main/scala/org/http4s/client/middleware/Retry.scala

Effect is totally unnecesarry. We don't use Sync, but only bracket. But if we want to be honest in the future about logging/etc then the Sync constraint will be necessary.

Lower Constraint on Retry to Sync

---

server/src/main/scala/org/http4s/server/middleware/CORS.scala

Firefox doesn't allow * in allowed headers for a cors request. [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1309358)
Authorization is a pretty common header and it would make sense to have it in the default set.
I was recently bitten by this.

Add authorization header in allowed headers

---

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
core/src/main/scala/org/http4s/multipart/Multipart.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala

I discovered that the java.net/Async/Ok clients would not send the body of a multipart request, nor do any request logging. Fundamentally, this turned out to be related to issue #2348, where these clients do not send the body of a request unless Transfer-Encoding or Content-Length headers have been set, however this fix just adds the request header for multipart.

Include chunked Transfer-Encoding header in multipart requests

---

server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

Make ResponseLogger log request if service terminates due to async cancellation to help error analysis

Log request if service terminates due to async cancellation

---

server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
server/src/test/scala/org/http4s/server/middleware/ChunkAggregatorSpec.scala

This PR adds convenience shortcuts to the ChunkAggregattor to apply the middleware on HttpRoutes and HttpApps.
Related issue: #2402

ChunkAggregator for HttpRoutes and HttpApp

---

build.sbt

The link looks like
https://github.com/http4s/http4s/blob/vSettingKey(This%20/%20This%20/%20This%20/%20version)/circe/src/main/scala/org/http4s/circe/CirceInstances.scala
instead of https://github.com/http4s/http4s/blob/v0.20.0-M6/circe/src/main/scala/org/http4s/circe/CirceInstances.scala

Fix scaladoc github url with tagged version

---

docs/src/main/tut/client.md

Fixes https://github.com/http4s/http4s/issues/2439
Seems it's just the extra dot's fault

fix broken links

---

dsl/src/main/scala/org/http4s/dsl/Http4sDsl.scala
dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
dsl/src/main/scala/org/http4s/dsl/impl/Responses.scala

Add new type constructor to be able to construct this DSL for http4s-directives.
```
trait DirectivesDsl[F[_]] extends Http4sDsl2[Directive[F, ?], F]
object DirectivesDsl {
def apply[F[_]]: DirectivesDsl[F] = new DirectivesDsl[F] {}
}
object io extends DirectivesDsl[IO]
```

Extensible dsl

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/test/scala/org/http4s/circe/CirceSpec.scala

`CirceInstancesBuilder` is using two `val`s in `CirceInstances` as default arguments, but is instantiated (as `builder`) before those `val`s are initialized.

Fix CirceInstances.builder initialization

---

core/src/main/scala/org/http4s/package.scala

The sacala doc for `HttpApp` has a reference to a `G` typeparam that no longer exists

Remove reference to G type on HttpApp

---

server/src/main/scala/org/http4s/server/middleware/Logger.scala

Logger has two flags to indicate if we want to log headers and/or body. However if both are false nothing is logged.
With this PR we still log the prelude in that case
Fixes #2456

In case logHeaders/logBody are both false still log the prelude

---

blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala

I'm deeply reluctant to do this, but these tests have been failing intermittently in Travis for a long time, and never fail for me locally, and nobody has rolled up their sleeves and fixed them.  These tests have negative value on CI.
Long term, we need to fix these tests, fix blaze, or build something better.

Skip flaky blaze tests when running on CI

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala

This is a workaround for https://github.com/typelevel/cats-effect/issues/487 causing blaze client to wait indefinitely if a `requestTimeout` occurs while `manager.borrow(key)` is running and the borrow eventually fails. This is what happens when we try to send a request to an unreachable host (incorrect IP address, firewalls, etc.).
IMO this is a solution for #2338. It literally implements "a reasonable timeout, even if hardcoded" as @rossabaker described it ;).
This is also a partial solution for #2386 . The requestTimeout still isn't enforced,  instead we wait for an OS level timeout of an attempt to establish TCP connection, but at least the request fails eventually, instead of waiting indefinitely. I want to follow up with a more complete solution, but I feel it requires making some …

Prevent never ending wait for cancelation of a failed (timed-out) attempt to acquire a connection.

---

docs/src/main/tut/static.md

I didn't know (until recently) about the org.http4s.server.staticcontent package object. It seems to be a much more convenient way to host static content (one line, like wai-middleware-static). I've updated the docs to include it.

Static content documentation

---

.travis.yml

We need to source `scripts/helpers` before calling `decrypt_deploy_key`.  I think it's to blame for [this error](https://travis-ci.org/http4s/http4s/jobs/515220273).

Source helpers in before_install stage

---

client/src/main/scala/org/http4s/client/oauth1/oauth1.scala
core/src/main/scala/org/http4s/Message.scala

Fixes #2504. Similar to #2502.
This code was written before the effect was polymorphic, and relies on now undefined behavior.  The `MonadError` constraint lets us raise the error into `F` lawfully.  Optimization coming in cats is noted. This rippled to the oauth1 client.

Raise DecodeFailure with MonadError instead of throwing

---

project/Http4sPlugin.scala

perhaps there is some other in-flight PR with this change, but
regardless, it would helpful for the Scala community build to have
just this change land on master

kind-projector has moved to typelevel org

---

core/src/main/scala/org/http4s/Message.scala

From discussion of #2502.  This takes advantage of smarter `rethrow`, in case such exists.

Use leftWiden[Throwable].rethrowT in as

---

client/src/main/scala/org/http4s/client/DefaultClient.scala

A json decoding failure was causing fiber death when used with ZIO.

Client: avoid throwing outside of effect system

---

core/src/main/scala/org/http4s/LiteralSyntaxMacros.scala
core/src/main/scala/org/http4s/MediaType.scala
core/src/main/scala/org/http4s/QValue.scala
core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/package.scala
tests/src/test/scala/org/http4s/MediaTypeSpec.scala
tests/src/test/scala/org/http4s/QValueSpec.scala
tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

https://gitter.im/http4s/http4s?at=5caeb05293fb4a7dc20c2646

add MediaType literal parsing

---

examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala

The current `BlazeServerBuilder` enables web sockets by default. Should that really be the case? I feel like opting-in for features is a better interface.
If not, then the following line can be elided.

Drop redundant enable web sockets

---

prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala

Closes #2423
Note that I chose NonEmptyList[Double] instead of List[Double] due to:
```scala
$amm
Loading...
Welcome to the Ammonite Repl 1.0.3
(Scala 2.12.4 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`io.prometheus:simpleclient:0.6.0`
import $ivy.$
@ import io.prometheus.client.{Histogram, CollectorRegistry}
import io.prometheus.client.{Histogram, CollectorRegistry}
@ val c = new CollectorRegistry()
c: CollectorRegistry = io.prometheus.client.CollectorRegistry@fa11fda
@ Histogram.build().buckets(List.empty[Double] : _*).name("foo").help("help").labelNames("bar").register(c)
java.lang.IllegalStateException: Histogram must have at least one bucket.
io.prometheus.client.Histogram$Builder.create(Histogram.java:84) …
```

Add optional argument to override Histogram's buckets.

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
project/Http4sPlugin.scala

Inspired by [Twitter conversation](https://twitter.com/djspiewak/status/1116371300765847552) with @djspiewak.  I'm not changing the default at this stage in the release cycle, but making it possible for Daniel (or others) to get empirical evidence that it's the right thing to do.  We can tweak the default in 0.20.1 or later, but this needs to go in now.
Pending release of https://github.com/http4s/blaze/pull/282 before it will compile.

Parameterize selectorThreadFactory for blaze server

---

server/src/main/scala/org/http4s/server/package.scala

The previous implementation of noSpider, while functional and point-free, was a bit too difficult to understand, and was making unneeded use of the `Kleisli` and `OptionT` wrappers.
An alternative implementation, that uses these wrappers as little as possible, is far more readable.

NoSpider: use a point-full implementation.

---

server/src/main/scala/org/http4s/server/middleware/authentication/package.scala

We extract an "unauthorized" function, that generates a response with the "Unatuthorized" status with the given authentication challenge.
We edit the code of challenged, so as to avoid using the `Kleisli` and `OptionT` combinators, which can be unclear, and replace them with a slightly more transparent style.

Authentication: simplify code.

---

server/src/main/scala/org/http4s/server/middleware/PushSupport.scala

We try to simplify the code of PushSupport.collectResponse.
- We extract the main function from the foldLeft into a separate local function.
- Since we are not staying in the `OptionT`, we replace the special combinators `semiFlatMap`, `mapF`, or `liftT`, by the Monad  methods of the base `F`, and pattern-matches on the Option constructors.

PushSupport.collectResponse: simplify code.

---

.travis.yml
docs/src/hugo/layouts/partials/edit-button.html
docs/src/hugo/layouts/partials/edit-link.html
project/Http4sPlugin.scala
website/src/hugo/content/contributing.md

Lots of our ecosystem (e.g., cats, cats-effect, fs2) use a `series/x.y` naming convention for maintenance branches.  Proposing this before we open `series/0.20` instead of `release-0.20.x`
"Not worth it" is a totally legitimate answer, but we need to get it open one way or the other.

Switch to more standard series/x.y naming convention

---

core/src/main/scala/org/http4s/syntax/AllSyntax.scala
core/src/main/scala/org/http4s/syntax/KleisliSyntax.scala
core/src/main/scala/org/http4s/syntax/package.scala

Adds `imapK` extension methods to the `Kleisli` syntax module to change the effect type of `HttpRoutes` and `HttpApp`.

Add translate extension methods for HttpRoutes and HttpApp

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
build.sbt
project/Http4sPlugin.scala

- use cats-effect 1.3.0
- remove the workarounds for https://github.com/typelevel/cats-effect/issues/487 introduced in #2470 as the issue is fix in cats-effects 1.3.0 (https://github.com/typelevel/cats-effect/releases/tag/v1.3.0)

Use cats-effect 1.3.0 and remove workarounds introduced in #2470

---

version.sbt
website/src/hugo/content/versions.md
website/src/hugo/static/_redirects
website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html

This release is for cats-2 support.  It will be released ASAP after our dependencies are available for Scala 2.13.0.

Begin 0.21 series

---

core/src/main/scala/org/http4s/EntityDecoder.scala

Simplifies the code of the `combineK` function, from the instance of
`SemigroupK` for `EntityDecoder`. Before there were two cases, based
on an `Option`, that were very similar.

EntityDecoder_combineK unify cases.

---

server/src/main/scala/org/http4s/server/middleware/Timeout.scala

Use method [`Concurrent.timeoutTo`](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Concurrent.scala#L349-L354).

Use Concurrent timeoutTo method.

---

boopickle/src/main/scala/org/http4s/booPickle/BooPickleInstances.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala

Both the `BooPickle` and the `Circe` decoder instances call to `collectBinary` and then applied an analysis to extract either the decoded result or a failure. This analysis phase was written as a function of Chunk to a DecodeResult, flatMapped to the result of  `collectBinary`. 
This PR rewrites it as a *pure* function of `Chunk[Byte]` to `Either`, which is applied to the result of `collectBinary` using the `EitherT.subflatMap` function.

BooPickle and Circe Decode Instances: more Cats

---

project/Http4sPlugin.scala

blaze-0.14.1 was a cursed release, because I published it with openjdk11.

Upgrade to blaze-0.14.2

---

core/src/main/scala/org/http4s/StaticFile.scala
tests/src/test/scala/org/http4s/StaticFileSpec.scala

Static content caching header fix

---

server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala

The operation to log the request was repeated three times, so we
extract it as a `def`. Also, folds two cases in the `guaranteeCase`.

RequestLogger: drying up some code

---

server/src/main/scala/org/http4s/server/package.scala

The `apply` method from the AuthMiddleware object bulds a service out of three elements: a function to get the auth info from a request, the authenticated service to run if it is authenticated, and the fallback service to run if authentication fails.
We simplify the code of this apply method by doing the following:
- We avoid the methods `local` and `mapF` of Kleisli.
- We avoid using the `Choice` instance for `Kleisli[OptionT]`. Instead we pattern-match right after the call to the `authUser` function. 
- We avoid calling the `AuthedRequest.apply(Kleisli)` method, a combinator. Instead, we build the `AuthedRequest` in each branch of the pattern-match. 
What is left is the code of the function in a direct style. 
This change is **BINARY-INCOMPATIBLE**, since it removes one parameter (the …

AuthMiddleware / Apply: simplify code

---

core/src/main/scala/org/http4s/Credentials.scala
dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
server/src/main/scala/org/http4s/server/middleware/DefaultHead.scala
server/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeper.scala

Apparently redundant braces around the body of a `case` are not  detected and removed by ScalaFmt

Remove Redundant Braces.

---

.travis.yml

As it stands, Travis CI is responsible for the tagging, so we shouldn't let it build tags.

Skip Travis on tags

---

server/src/main/scala/org/http4s/server/middleware/DefaultHead.scala

Removes the use and allocation of extra Kleisli in the private method.
Avoids use of instance `MonoidK[F] => MonoidK[Kleisli[F, A, B]`

Default head no inner kleisli

---

server/src/main/scala/org/http4s/server/middleware/GZip.scala

A small performance tweak in GZip: instead of doing the `map` on `Kleisli.map`, which would create a new Kleisli every time, we first apply to the request, then `map` on the `F[Response]` directly.

GZip: map on the F response, not the `Kleisli`.

---

core/src/main/scala/org/http4s/LiteralSyntaxMacros.scala
core/src/main/scala/org/http4s/MediaType.scala
core/src/main/scala/org/http4s/QValue.scala

Change literal interpolator macros to use unsafe methods to avoid
triggering Wartremover EitherProjectionPartial warning.

Using literall interpolators triggers Wartremover error

---

server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala

- Replace OptionT methods with direct style (function calls) and
pattern matching, using the `Option` type most of the time.
- Replace Option.map and Option.collect by pattern-matching on Option ADT.

WebjarService: Simplify code

---

server/src/main/scala/org/http4s/server/staticcontent/FileService.scala

In the inner methods `getPartialContentFile` and `getFile`, the `OptionT` wrapper serves no purpose, since no special method is used. We remove its from those functions, and put it in the call places, where they are actually used.

FileService: remove OptionT from inner methods.

---

bench/src/main/scala/org/http4s/bench/EncodeHexBench.scala
core/src/main/scala/org/http4s/internal/package.scala

Filename: package.scala
Action Items:
1. Logic to remove mutable iteration for encoding the hexadecimal data.

Optimize mutable iterations while encoding data

---

docs/src/main/tut/client.md
docs/src/main/tut/cors.md
docs/src/main/tut/dsl.md
docs/src/main/tut/gzip.md
docs/src/main/tut/hsts.md
docs/src/main/tut/json.md
docs/src/main/tut/middleware.md
docs/src/main/tut/streaming.md
docs/src/main/tut/testing.md
docs/src/main/tut/uri.md

Does this look better for Issue #2603 ? I am sorry if I am creating more work for you, genuinely trying to help, but I do not have a lot of experience with sbt. If this isn't correct, please kindly let me know if you want me to take a step back so someone else with more sbt experience can address the issue. Otherwise, I will take a couple of days to practice and test this out before submitting another PR. Also I am not sure if I needed to actually close the previous PR and create a new one, hope what I did was okay. Thanks for your patience and appreciate all your feedback.  :-)

replaced Uri.uri(...) with uri(...) in tuts docs Issue 2603

---

project/Http4sPlugin.scala

Retargeted to 0.20.x from #2618.

Update cats-core, cats-kernel-laws, ... to 1.6.1

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala

`SSLContext.getDefault()` throws on some platforms, which makes it untenable to pass as a default argument to the builders.  We use an `Option` to signify deferred creation.
Hard to test.  We'd need to do some byte code magic to intercept the creation of `SSLContext.default`, or fork a JVM configured such that it fails.  
Fixes #2431.

Defer creation of SSLContext.getDefault() in the client

---

server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala

- Change the inner function removeChunkedTransferEncoding from
function of `Response` to `Response` (which was asking for an
unused `Functor` parameter) into a `Headers` to `Headers` function.
- Since `List.flatMap` would allocates two objects for each element of
the result list, we use instead a mutable ListBuffer and a foreach.
This "imperative" code is no longer than the "functional" one.

Chunk Aggregator: rework

---

dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala

- DRY out a method `addEntityLenght`, which transforms a set of headers by addding the `Content-Length` of an entity, if the length of that entity is known.
- Relax type-class constraint of several methods from Monad to Applicative.

ResponseGenerator: DRY up and relax method implementations

---

core/src/main/scala/org/http4s/AuthedRequest.scala
core/src/main/scala/org/http4s/AuthedRoutes.scala
core/src/main/scala/org/http4s/AuthedService.scala
core/src/main/scala/org/http4s/package.scala
core/src/main/scala/org/http4s/syntax/AllSyntax.scala
core/src/main/scala/org/http4s/syntax/KleisliSyntax.scala
core/src/main/scala/org/http4s/syntax/package.scala
docs/src/main/tut/auth.md
examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/auth/BasicAuthHttpEndpoint.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
server/src/main/scala/org/http4s/server/middleware/authentication/package.scala
server/src/main/scala/org/http4s/server/package.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthMiddlewareSpec.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSpec.scala

- Add `of` and `apply` methods to `AuthedService` companion that are consistent with those for `HttpRoutes`
- Add `mapK` to AuthedRequest
- Add `mapK` extension method for AuthedService
AuthedService seems to have fallen behind `HttpRoutes` - perhaps it's worth a breaking PR to rename it to `AuthedRoutes` and change the order of the type params?
EDIT: The overloaded `apply` method on `AuthedService` caused a bunch of things to break. I've renamed the new one to `apply_` for now, but I'm not very happy with that name - thoughts?

Deprecate `AuthedService`, replace it with `AuthedRoutes` with updated API

---

core/src/main/scala/org/http4s/Header.scala
core/src/main/scala/org/http4s/util/Renderable.scala
tests/src/test/scala/org/http4s/HeaderSpec.scala

Add renderedLength to Header to support unchunked multipart

---

client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala

Some changes to simplify the code in `FollowRedirect` by removing false options. 
- The variable `pureBody` was defined as a `Some`, so there was no   need for the `Option` in its type.
- The Method `nextRequest` was identical in both branches except for the last instruction, about the body, which depends on whether `bodyOpt` is a `Some` or a `None`
- The `bodyOpt` parameter was fixed in each call to either a `Some` or a `None`, which means we can fold last part of the `def nextRequest` method after the call. 
- The `nextRequest` was an Option only because the `pureBody` was.  Since `pureBody` is always `Some`, we can remove branching there.
- And thus remove the `nextReq.fold(dontRedirect)` at the end.

Simplify code in Follow Redirect: No Options

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
core/src/main/scala/org/http4s/AuthedRequest.scala

Changes the `Option[SSLContext]` to be truly optional instead of a sneaky laziness in the innards of the client.
The default remains `Some(SSLContext.getDefault())`, except on systems where this fails, in which case the error is caught and SSL is disabled.  Any client may now opt out of SSL support by calling `withoutSslContext`.  Making an https call on a client where SSL is disabled now results in an `IllegalStateException` with suggestions how to configure it, rather than throwing whatever exception may come from `SSLContext.getDefault()`.
Refines the changes in #2604.  Is binary compatible, but changes the behavior of weird cases.

Don't depend on laziness of SSLContext in blaze-client

---

client/src/main/scala/org/http4s/client/Client.scala

It’s no longer a case class so there’s no `open` or `shutdown` params.

Remove obsolete bits of scaladoc from Client

---

server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala

Pass RedactHeadersWith from RequestLogger

---

docs/src/main/tut/static.md

The syntax error causes confusing noise in the docs.

Fix string literal in Router example

---

build.sbt
core/src/main/scala/org/http4s/MimeDB.scala
project/Http4sPlugin.scala
project/MimeLoader.scala
project/build.sbt

Run with `core/generateMimeDb`
Pros:
* It's only needed on one Scala version
* This is blocking #2493 
* We can get rid of that `thirteen` nonsense now that boopickle is published and this is no longer a module
* `core/generateMimeDb` is a fairly reasonable way to generate it.
Cons:
* Puts a lot on the sbt classpath, including an older version of ourselves
Mitigation:
* It doesn't have to use circe or http4s, but I'd rather lazily port to something we like less if it bites.

Make generateMimeDb an sbt task instead of a project

---

.jvmopts

A shameless ripoff of https://github.com/typelevel/cats/pull/2797.  Our Travis release is running out of steam after about 45 minutes.  Maybe this will help.  Maybe it'll even fix the blaze flickering!

Tune JVM options for throughput

---

core/src/main/scala/org/http4s/QueryParam.scala
tests/src/test/scala/org/http4s/QueryParamCodecLaws.scala

Allows to create `QueryParamDecoder` instances more easily by starting from a simple type and validate & lift into something more specific, for example using some function like `String` => `Either[BadFormat, TelephoneNumber]`.
More details on #1997

Add emap and emapValidatedNel to QueryParamDecoder

---

core/src/main/scala/org/http4s/Uri.scala

Our URIs don't have to begin with a scheme: they represent both absolute URIs and relative references.

Clarify scheme scaladoc

---

docs/src/main/tut/service.md

`// defined object Main` is confusing.

tut:silent IOApp examples

---

client/src/main/scala/org/http4s/client/middleware/GZip.scala
client/src/test/scala/org/http4s/client/middleware/GZipSpec.scala

Gzip middleware for client

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala

As described in #2651, we're getting a noisy EOF when shutting down web sockets under certain circumstances.  Usually we call `stageShutdown()` when we receive this to do any cleanup, so added that as a special case.  This may result in `stageShutdown()` being called multiple times, but that's normal.
This feels a tad sloppy, but not as sloppy as scary errors in user logs for situations that should be harmless.

Handle EOF in web socket by shutting down stage

---

core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
tests/src/test/scala/org/http4s/UriSpec.scala

Closes #2583 by implementing one of @rossabaker's suggestions from #2583 (comment).
Per https://github.com/http4s/http4s/pull/2664#issuecomment-506858839, I decided to close https://github.com/http4s/http4s/pull/2664 in favor of this PR.

Address Uri#fromString Defect for Parsing the Port

---

core/src/main/scala/org/http4s/LiteralSyntaxMacros.scala
core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/UriTemplate.scala
core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
core/src/main/scala/org/http4s/syntax/LiteralsSyntax.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
server/src/main/scala/org/http4s/server/Server.scala
tests/src/test/scala/org/http4s/Ipv6AddressSpec.scala
tests/src/test/scala/org/http4s/UriSpec.scala
tests/src/test/scala/org/http4s/UriTemplateSpec.scala
tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

* Deprecate `IPv6` in favor of `Ipv6Address`
* `Ipv6Address` is a case class of eight hextets
* Implements RFC5952 for normalized output
* Adds string interpolator
* Requires that ipv6 addresses be bracketed in authority form of request target

Improved ipv6 support in Uri

---

core/src/main/scala/org/http4s/Message.scala
server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala
tests/src/test/scala/org/http4s/MessageSpec.scala

`Request#withPathInfo` should preserve the position of the caret, an internal attribute that splits the URI path into `scriptName` and `pathInfo`.
Fixes #2726.  See #1183, #1213 for more historical context.

Preserve request caret in withPathInfo

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala

When a websocket connection is closing, stageShutdown can be called from
within another effect. If this then calls unsafeRunSync, there exists
the risk of a deadlock. Changing to unsafeRunAsync does not change the
semantics and removes this risk.

unsafeRunSync->unsafeRunAsync to prevent deadlocks

---

docs/src/main/tut/auth.md

So this is my attempt to clarify composition rules on AuthedRoutes
I've expanded the note on spidering in it's whole section and provided examples for the solutions explained in #2718. 
It resolves #2718

Clarify AuthedRoutes composition rules

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Client.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
client/src/main/scala/org/http4s/client/ConnectionManager.scala
project/Http4sPlugin.scala

Follow-up to https://github.com/http4s/blaze/pull/308.
WIP: It won't compile until the aforementioned PR is merged and blaze 0.14.7 is released.
This PR:
- gives users ability to provide custom TickWheelExecutor in place of the one allocated by BlazeClientBuilder
- adds `connectingTimeout` for configuring the newly introduced `connectingTimeout` in blaze's `ClientChannelFactory`
Fixes: #2386, #2338, #2690

Connecting timeout

---

docs/src/main/tut/client.md
docs/src/main/tut/dsl.md
docs/src/main/tut/json.md

Clarifies the documentation to specify that `org.http4s.Methods._` is imported into scope with the default routing DSL, and that the client DSL needs an extra import in order for some of the examples to compile.
Changes could/should also be made for the current 0.20.x documentation, if it all looks good I'll write this up for that as well.

Clarify Method imports for client DSL in docs

---

blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala

This is an implementation detail and we can't fix it in 0.20 without breaking binary compatibility.

Make Http1Stage private[http4s]

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
blaze-core/src/main/scala/org/http4s/blazecore/ResponseHeaderTimeoutStage.scala
build.sbt

Also fixes #2760 by restricting that to a `FiniteDuration`.  As a bonus, stop calling `.toMillis` to guard against regressions that are hard to test when we're not in debug logging.

Don't add ResponseHeaderTimeoutStage on infinite timeout

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala

Throw in a grammar fix and some test warning mitigation while we're here.

Fix incorrect warning in blaze-client timeouts

---

server/src/main/scala/org/http4s/server/middleware/MaxActiveRequests.scala
server/src/test/scala/org/http4s/server/middleware/MaxActiveRequestsSpec.scala

Initial Code for a MaxActiveRequest middleware. That will immediately return the default response if all requests allowed are currently active.
Can get test code up tommorow.

Add MaxActiveRequest middleware

---

core/src/main/scala/org/http4s/QueryParam.scala
docs/src/main/tut/dsl.md
tests/src/test/scala/org/http4s/QueryParamCodecSpec.scala

Addresses part of https://github.com/http4s/http4s/issues/2670.
Please take a look, @rossabaker and @LukaJCB.

Add QueryParamEncoder[Instant] and QueryParamDecoder[Instant]

---

docs/src/main/tut/csrf.md

Could probably use some fleshing out, but probably a good enough base to get feedback for and I can build upon it -- or just have someone else flesh it out a bit more!.

feat: add some simple csrf documentation

---

dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala

We got a failing test in our test suite after trying to upgrade http4s. After some digging it appeared to be introduced in https://github.com/http4s/http4s/pull/2446
This PR fixes the failing test for us.
Take `body: F[A]` as parameter instead of `G[A]` which enables following the code to be structured as it was here https://github.com/http4s/http4s/pull/2446/files#diff-09e729dc8ff0315c384e774351a8720fL42
If 👍 I'm happy to make analogous change to other branches.

Fix EntityResponseGenerator

---

.travis.yml
project/Http4sPlugin.scala
website/src/hugo/content/versions.md

Sonatype is routinely too slow to publish three crossbuilds within the 50 minute timeout, and this was just a preview release.  People who need Scala 2.13 are better off on http4s-0.21.

Drop Scala 2.13.0-M5 support in 0.20.x

---

dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala

#2785 passed MiMa, but was not a compatible change.  We hoped it wouldn't break anything in practice, but it broke http4s-directives.

Revert "Take `body: F[A]` as parameter instead of `G[A]`"

---

build.sbt

It's already removed from Travis.
When merging this to master, we'll need to be careful to keep 2.13.0.

Remove 2.13.0-M5 from crossScalaVersions

---

core/src/main/scala/org/http4s/headers/Allow.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
core/src/main/scala/org/http4s/util/Renderable.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala

[RFC7231 section-7.4.1](https://tools.ietf.org/html/rfc7231#section-7.4.1):
> An empty Allow field value indicates that the resource allows no methods, which might occur in a 405 response if the resource has been temporarily disabled by configuration

Allow 'Allow' header to specify empty list of methods

---

dsl/src/main/scala/org/http4s/dsl/Http4sDsl.scala
dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
dsl/src/main/scala/org/http4s/dsl/impl/Responses.scala

Added a Natural transformation to ReponseGenerator to allow the F and G
to work in unison.
The default implementation is the identity transformation.
@rossabaker suggested that the use of an implicit parameter for
FunctionK is not the way it is supposed to be used, I had to thread that
through the method chain. This means that we no longer can have the
Responses as value classes, as they can only have one member. This will
increase the cost of using the implicit conversions as a new object has
to be allocated.
This change is ~~most likely~~ not binary compatible, so a backport to 0.20
is probably not that useful. It is source compatible though.

Make PR-2785 work as intended

---

server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala

Apparently the very same tests exist in the lines above the removed code.

remove duplicated CORS tests

---

circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
circe/src/test/scala/org/http4s/circe/middleware/JsonDebugErrorHandlerSpec.scala

Can be improved by #2848  and the 2 hkt message handling/decode approach

Add JsonDebugErrorHandler

---

tests/src/test/scala/org/http4s/UserInfoSpec.scala

I *believe* that what's the test intended.
Now it does work with "@" as a parameter - not sure if it's worth adding another test to make it explicit though

Fix UserInfoSpec (#2767)

---

client/src/main/scala/org/http4s/client/middleware/Logger.scala
server/src/main/scala/org/http4s/server/middleware/Logger.scala

1. concat the message body more efficiently (using `StringBuilder`)
2. client.middleware.Logger: log the `prelude` if `logBody` and `logHeaders` are false

Minor patches to logger 

---

core/src/main/scala/org/http4s/Http.scala
core/src/main/scala/org/http4s/HttpRoutes.scala

`Sync` is no longer required, we only need `Delay` for the ability to suspend the route analysis.

Weaken Http/HttpRoutes Constraint

---

build.sbt
core/src/main/scala/org/http4s/util/UrlCoding.scala

I think this will resolve #2936. This adds back `UrlCodingUtils` methods, annotates them as deprecated, and forwards to corresponding `Uri` methods.

Deprecate UrlCodingUItils methods

---

blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/IdentityWriter.scala
website/src/hugo/content/changelog.md

This was advertised as fixed in 0.20.12, but I messed up.  Want to get this released ASAP in 0.20.13.

Backport #2922: chunked upload of long Content-Lengths

---

core/src/main/scala/org/http4s/Message.scala
tests/src/test/scala/org/http4s/MessageSpec.scala

[Relevant specification link](https://tools.ietf.org/html/rfc6265#section-4.2.1)

Fix Request.addCookie so it complies with the HTTP specification

---

servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala

Fix switched local and remote addresses in servlet requests (0.20)

---

core/src/main/scala/org/http4s/AuthedRequest.scala
core/src/main/scala/org/http4s/AuthedRoutes.scala
core/src/main/scala/org/http4s/ContextRequest.scala
core/src/main/scala/org/http4s/ContextRoutes.scala
core/src/main/scala/org/http4s/package.scala
docs/src/main/tut/auth.md
dsl/src/main/scala/org/http4s/dsl/impl/Auth.scala
server/src/main/scala/org/http4s/server/ContextMiddleware.scala
server/src/main/scala/org/http4s/server/package.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthMiddlewareSpec.scala

A ContextRequest is defined as a request with some data.
AuthedRequest can be defined as a ContextRequest with auth data
as the context.
AuthedRequest signals that it should only be used for auth stuff, but
ContextRequest opens up possibility to reuse it to other things.

Generalize AuthedRequest to ContextRequest

---

core/src/main/scala/org/http4s/headers/Link.scala
core/src/main/scala/org/http4s/headers/LinkValue.scala
core/src/main/scala/org/http4s/parser/LinkHeader.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/headers/LinkSpec.scala

Parse should accept format RFC 8288

---

project/Http4sPlugin.scala
project/PrivateProjectPlugin.scala
project/plugins.sbt

WARNING: This does more than just fix the compilation errors, it also has at least one non-trivial consequence. As of [SBT 2.0.0][sbt-bc-deprecation] Bouncy Castle based PGP is deprecated. Thus this commit removes `useGpg := false`. I believe this means that `gpg` _must_ be on the `PATH` in order for `sbt-pgp` to provide PGP based operations.
[sbt-bc-deprecation]: https://github.com/sbt/sbt-pgp/blob/90465fcde014eb0688f0086fdec56db60ebfbfd6/sbt-pgp/src/main/scala/com/jsuereth/sbtpgp/SbtPgp.scala#L21 "SbtPgp.scala"
This should replace: https://github.com/http4s/http4s/pull/2870

Fix Compilation Errors With New `sbt-pgp` Plugin Version

---

core/src/main/scala/org/http4s/Message.scala
dsl/src/test/scala/org/http4s/dsl/PathInHttpRoutesSpec.scala
project/Http4sPlugin.scala
tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSpec.scala

Repeating @rossabaker's comments here:
* Reimplement the case classiness of Request by hand to work around scala/bug#11457.
* Work around Seq aliasing in a spec
* Eliminate early initializer in TomcatSpec, which no longer appears to be necessary
Matching on `Message[F]` with this new encoding causes some obscure problem with the pattern matcher on 2.12. updated Request.unapply to first match on `Message[F]`, and `Request[F]`, this trick avoids the pattern matcher bug on 2.12.

Adapted @rossabaker's patch in #2891 to make it work for 2.12 as well

---

server/src/main/scala/org/http4s/server/middleware/Metrics.scala

Prior to this commit there was an edge case where the `ops.decreaseActiveRequests` would get run more than once if an error or cancellation occurred _after_ the `onFinalize` method was run in `onResponse`.
This change adds a `Ref` which is initialized at the start of request handling and set to `true` once the `ops.decreaseActiveRequests` is run. All attempts to set `ops.decreaseActiveRequests` are guarded by this boolean value.

Ensure That Metrics Only Decrements Active Requests Once

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/JsonDecoder.scala

Single Type Abstraction for separation of Sync and the locations using the `Json`, which is primarily businesss logic where we'd prefer to remove effects.

Add JsonDecoder Algebra

---

core/src/main/scala/org/http4s/StaticFile.scala
tests/src/test/scala/org/http4s/StaticFileSpec.scala

Should fix both #2468 and #2834

Improve StaticFile.fromResource handling

---

dsl/src/main/scala/org/http4s/dsl/impl/Path.scala

I think these may have been missed in c15b8ef8c02bb28d49ffda2de0d665f34f113173.

Be more explicit about Seqs

---

server/src/main/scala/org/http4s/server/Router.scala

`Monad` is needed for `<+>`, otherwise it could work with only `Applicative`.

Relaxing constraints on Router.apply

---

boopickle/src/main/scala/org/http4s/booPickle/BooPickleInstances.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/Media.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/multipart/Part.scala
docs/src/main/tut/entity.md
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala

This PR is an attempt to improve **multipart** decoding by allowing to use `EntityDecoder` on a `Part[F]`:
1) It introduces new interface `Media[F]` which is implemented by `Message[F]` and `Part[F]`;
2) `EntityDecoder.decode` now accepts a `Media[F]` instead of `Message[F]`.

Multipart decoding using EntityDecoder

---

server/src/main/scala/org/http4s/server/middleware/Throttle.scala

- Sync is Stronger Constraint than what is required 
- Add ability to lift Bucket, since it will likely need to be lifted into the transformer due to how apply is written.

Server Throttle Middleware: Lower Constraint Add Translated Bucket

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/test/scala/org/http4s/circe/CirceSpec.scala

This adds some functions to create a simple encoder for Streams, which encodes it as a single JSON array. The specs show how they work.
I also added the option to specify which charset to use when encoding a JSON to all the previous functions, since the method has a default argument, I guess it is binary compatible?
I am actually pretty bad at that. If the change is dangerous I may remove it.
I am open to any feedback you may have about these changes.
_(btw, I tried to follow the style conventions that were already there)_.

Adding a simple Stream as JSON array circe encoder

---

core/src/main/scala/org/http4s/HttpDate.scala
docs/src/main/tut/dsl.md
server/src/test/scala/org/http4s/server/middleware/DateSpec.scala
tests/src/test/scala/org/http4s/HeaderSpec.scala
tests/src/test/scala/org/http4s/HttpDateSpec.scala
tests/src/test/scala/org/http4s/ResponderSpec.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

Following Feedback from after #3051 was merged, deprecate `HttpDate.now` and instruct to use `current` instead.

Deprecate HttpDate.now

---

project/build.sbt

http4s-0.20 is built on circe-0.11.  So is bloop, I think: this made it load for me on metals-0.7.6 with Emacs.

Fix conflicting circe on plugin path

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/main/scala/org/http4s/client/DefaultClient.scala

These are similar to the `expect` methods which take the same arguments. They are particularly useful for test.

Add status Methods Which Use `String` or `URI`

---

server/src/main/scala/org/http4s/server/ContextMiddleware.scala

A const constructor for a ContextMiddleware. Useful primarily for testing, but can have other uses as well.

Add ContextMiddleware Const

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
client/src/main/scala/org/http4s/client/ConnectionFailure.scala
client/src/main/scala/org/http4s/client/RequestKey.scala

See http4s/blaze#373.
Java's `UnresolvableAddressException` does not carry any information about the host that failed to resolve.  If a client fails to connect, we should provide context on which host we failed to connect to.  We do so by introducing a wrapper exception, `ConnectionFailure`, in the client package.
Other clients should probably use this if they can.   Fixed for blaze, as it was reported on blaze.

  Wrap uninformative Java exceptions in ConnectionFailure

---

argonaut/src/main/scala/org/http4s/argonaut/Parser.scala
argonaut/src/test/scala/org/http4s/argonaut/ArgonautSpec.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/StreamClient.scala
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
project/Http4sPlugin.scala
server/src/test/scala/org/http4s/server/staticcontent/StaticContentShared.scala
tests/src/test/scala/org/http4s/StaticFileSpec.scala

We're working on finalizing Jawn 1.0.0 and this is a WIP PR that updates to the latest Jawn RC and Circe milestones. It also depends on [this unpublished PR](https://github.com/http4s/jawn-fs2/pull/86).
This probably shouldn't be merged until we release Jawn 1.0.0 (which is likely to happen in the next week), but I needed to update http4s for some local testing and thought I should go ahead and open this.

Update Jawn and Circe

---

client/src/main/scala/org/http4s/client/PoolManager.scala
client/src/test/scala/org/http4s/client/PoolManagerSpec.scala

Fixes the issue I've described in this comment: https://github.com/http4s/http4s/issues/2962#issuecomment-576041384

Fix connection leak in PoolManger (#2962)

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala

This PR applies to changes to the CirceInstances file.
The first one, replaces the combinations of **Contex Bounds** with **implicit parameters**.
The change leaves all methods with only one of them; bounds, only when neither of the implicits was explicitly required, and implicits otherwise.
The second one was to replace the two **implicit classes** with **one value class** and one **implicit conversion**.

Cleaning the CirceInstance implicits

---

core/src/main/scala/org/http4s/QueryOps.scala

I could not find a more elegant way of returning `Self` (and folding on `self`) other than the proposed
```scala
replaceQuery(Query.fromVector(s.withQueryParam(k, v).query.toVector))
```
If anyone has input on this, let me know.

Implement withQueryParams and withMultiValueQueryParams

---

build.sbt
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
project/Http4sPlugin.scala

Add server side ssl support for ember

---

server/src/test/scala/org/http4s/server/middleware/ChunkAggregatorSpec.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala
testing/src/test/scala/org/http4s/testing/fs2Arbitraries.scala
tests/src/test/scala/org/http4s/EntityCodecSpec.scala

Part of an effort to slim down `Http4sSpec`. These don't need to be in scope everywhere, and we won't publish them because they're not our type.

Move Arbitrary[Chunk[Byte]] out of Http4sSpec

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala

Fixes #3102.  In addition to pongs outside the normal stream, we can also send a close frame, so it seemed simplest just to guard the write in a semaphore.
/cc @khrupalyk

Write to blaze websockets with a permit

---

server/src/main/scala/org/http4s/server/middleware/DefaultHead.scala
server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala

So if we are processing a GET as a HEAD, we know we do not care about the body, but we still want to ensure finalizers are run. To get the finalizers we must run the original stream, but we do not want to process all the bytes, in fact any of the bytes. 
To this end we immediately interrupt the stream and make sure that is empty. 
Requires the addition of a `Concurrent` restraint on the body, however I think that is worth it for the potentially gigabytes of processing this saves the server.

Interrupt Body of DefaultHead Middleware

---

circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/MessageFailure.scala
server/src/main/scala/org/http4s/server/middleware/ErrorHandling.scala
server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
server/src/main/scala/org/http4s/server/package.scala
tests/src/test/scala/org/http4s/EntityDecoderSpec.scala

`Applicative` constraints on `MessageFailure.inHttpResponse` looks redundant because one can't do anything useful with them (given polymorphic context).

MessageFailure: simplify toHttpResponse/inHttpResponse

---

core/src/main/scala/org/http4s/Media.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/multipart/Part.scala
tests/src/test/scala/org/http4s/MessageSpec.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala

Adding a `covary` function to `Message` and its subtypes that matches the `Stream.covary` function.
It's implemented as a type cast to avoid the costs of creating a new `Request` object for something that should be safe to do as a cast.
Alternative implementation without a type cast, (but including an extra allocation of `Request` is [here](https://github.com/zarthross/http4s/commit/290831ad41ccb6ef1777cecabb9e2a583f09a5b8)

Covary `F` in Message types. 

---

project/Http4sPlugin.scala
version.sbt
website/src/hugo/content/changelog.md

I'm not interested in actively backporting to 0.20 anymore, but this is a bug fix, and it was just as easy to initiate on this branch.

Release v0.20.17

---

core/src/main/scala/org/http4s/Message.scala
tests/src/test/scala/org/http4s/MessageSpec.scala

Initial Implementation for the curl-representation of the request.
Maybe  --data-body for POST-Requests should be included still.  What do you think?
Also I kept it that stringified version of the Request probably should redact sensitive information (Authorization- and Cookie-Headers). Is that fine?

Http4s 3095 Pretty-print an org.http4s.Request as a curl command

---

core/src/main/scala/org/http4s/util/package.scala
tests/src/test/scala/org/http4s/util/DecodeSpec.scala

Fixes #2956
Test was failing when the generated string contained UTF-8 BOM character (that's why the minimum example looked like an empty String).
Last year fs2 started ignoring UTF-8 BOM characters:
https://github.com/functional-streams-for-scala/fs2/issues/1484
So flakiness of this test is a successful discovery of the difference between the behavior of fs2 and http4s decoders.
Following the example of fs2, I made changes to the `decode` function dropping BOM characters and added an example test to verify that.

Fix flaky decode
