jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala

* Deprecate `withSSLContext`, toward deprecating `SSLClientAuthMode`
* Add `withSslContext`, `withSslContextAndParameters`, and `withoutSsl`
Fixes #2499 for Jetty.  Relates to #3132.

Support SSLParameters in jetty-server

---

server/src/main/scala/org/http4s/server/ContextRouter.scala
server/src/main/scala/org/http4s/server/Router.scala
server/src/test/scala/org/http4s/server/ContextRouterSpec.scala
server/src/test/scala/org/http4s/server/RouterSpec.scala

This changes the router to use segment routing instead of string prefix matching.
The previous behaviour was unsafe and would match longer prefixes which may cause unexpected matches.
This will no longer fall-through on partial matches.
* Add ContextRouter with same routing logic

Change behaviour of Router to use segments

---

server/src/main/scala/org/http4s/server/staticcontent/CacheStrategy.scala
server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
server/src/main/scala/org/http4s/server/staticcontent/NoopCacheStrategy.scala

The extra features provided by `Effect` are not used and relaxing the constraints makes it easier to use it with `ZIO` instead of `IO`.
Edit: I'm a bit confused about the failing spec. Seems unrelated to my change but I don't have much experience with the test suite so I could be wrong.

Change Effect to Sync in FileService

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala

Possible fix for [Provide ability to receive WebSocket Ping/Pong frames](https://github.com/http4s/http4s/issues/3129)`

Added new WS API which allows receiving Ping messages from the client

---

examples/jetty/src/main/scala/com/example/http4s/jetty/JettySslExample.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

* Refactors the Tomcat SSL configuration
* Lets us deprecate types from the `ServerBuilder` not in the public API
* Deprecated `JettyBuider.withSSL`, like Blaze's.  Tomcat doesn't currently have an alternative.
* Tomcat still falls short of the other four backends in being able to use `SSLParameters` or fs2's `TLSParameters`. :shrug:

Refactor Tomcat SSL config, deprecate abandoned ServerBuilder

---

server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
server/src/main/scala/org/http4s/server/staticcontent/NoopCacheStrategy.scala
server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
server/src/main/scala/org/http4s/server/staticcontent/package.scala
server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/ResourceServiceSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/StaticContentShared.scala
server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceFilterSpec.scala
server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceSpec.scala

All methods in the `staticcontent` package only require a `Sync`
instance.

Relax Effect to Sync in staticcontent

---

version.sbt
website/src/hugo/content/changelog.md

Didn't get feedback on Gitter, so I'll throw it up here for discussion.
This gets #3145 out there for people to try before it's final.  The alternative is to sit on it and release it along with the bump to circe-0.13.0 in our own 0.21.0.

Release 0.21.0-RC4

---

core/src/main/scala/org/http4s/ContextRoutes.scala
core/src/main/scala/org/http4s/HttpRoutes.scala
tests/src/test/scala/org/http4s/HttpRoutesSpec.scala

If users don't care about efficient route composition under a large number of routes, this exposes the ability of `of` as a partial function but only requires applicative and not `of`. 
Open to different naming semantics. This change doesn't effect existing api and can be a patch if we don't want it in final, but I don't see why that's necessary for a convenience method like this.

Add HttpRoutes.strict

---

website/src/hugo/content/changelog.md

Will give us a chance to test the new release pipeline from #3151 before burning the eagerly anticipated 0.21.0 tag.

Release v0.21.0-RC5

---

version.sbt

This is preventing sbt-dynver (and therefore sbt-ci-release) from detecting the tag.
Published snapshots will now also have a qualifier.

Remove version.sbt

---

project/Http4sPlugin.scala
website/src/hugo/content/changelog.md

#3156 only got the Mime generator, not http4s-circe.
/cc @IndiscriminateCoding

Really update to circe-0.13.0

---

build.sbt
prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala

Discovered in #3167.  Prometheus shouldn't require DSL.

Drop prometheus dependency on http4s-dsl

---

project/Http4sPlugin.scala

The only change in jawn-fs2 is to bump from fs2-2.2.1 to fs2-2.2.2, which http4s already depends on.  This gets us off an RC that we neglected to finalize before http4s-0.21.0.
Thanks to @travisbrown for calling it out on Gitter.

Update to jawn-fs2-1.0.0

---

tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

We should be using [the values in `certificateVerification`](https://tomcat.apache.org/tomcat-9.0-doc/config/http.html#SSL_Support_-_SSLHostConfig).  This is already fixed in #3140, and there probably aren't many people who care, but it is a bug.

Fix client auth values in TomcatBuilder

---

version.sbt

Automated release is going to demand this, as well.

Delete version.sbt from 0.20

---

core/src/main/scala/org/http4s/ResponseCookie.scala
core/src/main/scala/org/http4s/parser/CookieHeader.scala
tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala

Addresses #3178 in a binary compatible way.
* Supports leading dot in domain.  We punt on modeling it as a domain as opposed to a raw String.
* Supports multiple extension attributes
* Supports case-insensitive parsing of cookie attributes
* Does not preserve non-extension attributes with the same name

ResponseCookie parsing improvements (0.20.x)

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala

Recover EOF raised by the body encoder rather than catching it as an exception, which some implementations may wrap.  This better expresses intent and cleans up logs in such implementations.
/cc @jadlr

Recover EOF on bodyEncoder.write to close connection

---

core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala

Fixes #3189.  The Graalers will appreciate it.

Replace runtime reflection in HttpHeaderParser init

---

project/Http4sPlugin.scala

These are already in 0.21, but as long as a release is imminent, might as well scoop them up.

Update argonaut, async-http-client, tomcat

---

core/src/main/scala/org/http4s/parser/CookieHeader.scala
tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala

Like those in #3184, `SameSite` is [case insensitive](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-05#page-27).

Fix case sensitivity of SameSite

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/client/blaze/bits.scala
core/src/main/scala/org/http4s/ProductIdOrComment.scala
core/src/main/scala/org/http4s/headers/Server.scala
core/src/main/scala/org/http4s/headers/User-Agent.scala
core/src/main/scala/org/http4s/headers/package.scala
core/src/main/scala/org/http4s/parser/CookieHeader.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

This is a model for the Server header as for #2011. `User-Agent` and `Server` parse the same way so I unified the parsers and component classes:
`AgentProduct` -> `HeaderProduct`
`AgentToken` -> `HeaderToken`
`AgentComment` -> `HeaderComment`
I'm not sure if this is the right approach an it breaks mima. Feel free to comment
Should Blaze return a server header like
`Server: blaze-http4s/0.21.0`?

Model Server header

---

.github/workflows/ci.yml

I think we broke this backporting to an older version of scalafmt on 0.20.x, and then merging back.

Run scalafmt as intended

---

project/plugins.sbt

o we do not need this plugin anymore
o conflicts with coursier based sbt launcher

Remove coursier plugin, it is now part of sbt

---

ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/src/test/scala/org/http4s/ember/core/ParsingSpec.scala

Fixes #3235.
Also fixes an [issue I mentioned in gitter](https://gitter.im/http4s/http4s-dev?at=5e58a30153fa513e285a69da) with response parsing, which can cause the response body stream to be closed prematurely.

Write ember-client request to socket before reading response

---

core/src/main/scala/org/http4s/MediaType.scala
core/src/main/scala/org/http4s/QValue.scala
core/src/main/scala/org/http4s/Uri.scala
testing/src/test/scala/org/http4s/illTyped.scala

I noticed this while porting the macros to Dotty, and found [this comment](https://github.com/http4s/http4s/pull/2508#pullrequestreview-226336649):
> Also can't remember why these had to be whitebox instead of blackbox.
…but these definitely shouldn't need to be whitebox. Maybe there was an issue on 2.11? In any case tests pass with this change now.

Prefer blackbox macros

---

play-json/src/main/scala/org/http4s/play/PlayEntityEncoder.scala
play-json/src/main/scala/org/http4s/play/PlayInstances.scala

This is a minor follow-up to #3253 that couldn't be included there because it breaks bincompat. The issue is that the `EntityEncoder` constraint here is unnecessary, but the compiler didn't warn because of the kind-projector syntax. This PR just removes the unnecessary parameter.
This change will have to wait for 0.22.x because it breaks bincompat, but it's source-compatible for normal usage.

Remove unused EntityEncoder argument

---

core/src/main/scala/org/http4s/ResponseCookie.scala
core/src/main/scala/org/http4s/parser/CookieHeader.scala
server/src/main/scala/org/http4s/server/middleware/CSRF.scala
tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala

I mentioned this in gitter and figured I'd open a PR with the change. To get the behavior of `SameSite=None` in all browsers, it's necessary to completely exclude the `SameSite` attribute for [certain clients that handle it incorrectly](https://www.chromium.org/updates/same-site/incompatible-clients). This updates the field to be optional to allow for this.

Make SameSite cookie attribute optional

---

docs/src/main/tut/service.md

Here: https://http4s.org/v0.21/service/, the example `build.sbt` file includes the following line:
```scala
scalacOptions ++= Seq("-Ypartial-unification")
```
I added the information that this option should be used only with Scala 2.12.x.

docs(v0.21/service): add info about the usage of -Ypartial-unification

---

client/src/test/scala/org/http4s/client/JettyScaffold.scala

On some personal computers (namely on MacBooks) the following unit tests:
* org.http4s.client.jetty.JettyClientSpec
* org.http4s.client.okhttp.OkHttpClientSpec
may fail with the following errors correspondingly:
```
[error]  java.net.UnknownHostException: john-doe-macbookpro (SocketAddressResolver.java:170)
[error] org.eclipse.jetty.util.SocketAddressResolver$Async.lambda$resolve$1(SocketAddressResolver.java:170)
[error] org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
[error] org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
``` 
and
```
[error]  java.net.UnknownHostException: john-doe-macbookpro (Dns.kt:49)
[error] okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
[error] …
```

Fixes failing local unit tests

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerMtlsSpec.scala
docs/src/main/tut/static.md
ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExample.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
examples/jetty/src/main/scala/com/example/http4s/jetty/JettySslExample.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatSslExample.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/Server.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

From `server/src/main/scala/org/http4s/server/Server.scala`:
```
abstract class Server[F[_]] {
...
}
```
As per [conversation](https://gitter.im/http4s/http4s-dev?at=5e7ffe79426d5b06bf92c340) with @rossabaker, this type parameter looks like a legacy and isn't actually used anymore.

Remove type parameter from `org.http4s.server.Server`

---

blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
client/src/test/scala/org/http4s/client/PoolManagerSpec.scala

We're not fixing them, and we're not touching blaze internals much, and these spurious failures are frustrating other work.  This is regrettable, but the status quo is worse.

Skip some flaky tests

---

core/src/main/scala/org/http4s/util/threads.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala

- The method `newDefaultFixedThreadPool` was deprecated years ago,
and it was also marked as internal to http4s.
- The method `charsetRangesNoQuality` is part of the laws tests,
has a default mapping, and has been deprecated for a while.

Drop deprecated methods from

---

client/src/main/scala/org/http4s/client/Client.scala
client/src/main/scala/org/http4s/client/DefaultClient.scala

These methods were marked deprecated in version 0.14, which was published in June 2016, and they have a quick fix. That should have been enough time for adjustment.

Client: Remove old deprecated methods.

---

server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala

`Path#toString` uses the OS-specific directory separator if a `Path`
contains of multiple components. On Windows this means that the
`WebjarAsset#asset` field might contain backslashes. The `assets` field
is then later used to load a resource which [fails because of the
backslashes](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResources-java.lang.String-).
This change always uses `/` as directory separator for the assets path
so that loading them works on all operating systems again.
Closes: #3304

WebjarService: Do not use OS-specific directory seperators

---

core/src/main/scala/org/http4s/Media.scala

The note referred to `redeem` but I am not sure how this corresponds to `redeem`. By directly using method in `F` (expanding `rethrowT`) we no longer need syntax or the `leftWiden`.

Media: small change to remove note.

---

blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala

Regretfully. Is causing problems, for example on https://github.com/http4s/http4s/pull/3338/.

Skip call a second host test on CI

---

project/Http4sPlugin.scala

Upgrades jetty-server to 9.4.28, which we missed before, because the old way was too complicated.
This is going to be unpleasant to merge forward, but I think will be nicer once we do.

Extract dependency versions into own object

---

.github/workflows/ci.yml

We might regret this, because we have some unstable tests, and it raises the things that can go wrong by 50%.  And it's not an LTS JDK, so I'd kind of like to allow failures and just let this be a canary, but I don't know how to do that in GitHub Actions.  But we should be proactively testing this somehow.

Start testing on JDK-1.14

---

version.sbt
website/src/hugo/content/versions.md

There is currently no distinction between 0.21 and (incompatible) 1.0 snapshots.  `version.sbt` is a hack that invents a pseudo-release for version derivation until the branch has a real release.
Adds another row to the versions table.
More interestingly, this is a public statement to the next breaking release being 1.0, not 0.22.  We can squeeze in an 0.22 if we must, but I'd rather we don't.

Start publishing snapshots for v1.0

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala

1. Guards the callback invocation in `onCompleted` so that it is only called if `onStream` wasn't called.
2. Fixes `bodyDisposal` to actually sequence the stream finalizer via `.pull.uncons.void`. `take(0)` turns out to [be a noop](https://github.com/functional-streams-for-scala/fs2/blob/v1.0.0/core/shared/src/main/scala/fs2/Stream.scala#L3446), so the previous version wasn't finalizing.
Fixes #3293

Avoid incorrectly responding with an empty body in AHC client

---

docs/src/main/tut/middleware.md

Show how the PrometheusExportService can be used to expose the metrics for scraping. I spent a long time trying to figure it out, would like to pay it forward.

Improve Prometheus middleware usage example

---

client/src/main/scala/org/http4s/client/ConnectionFailure.scala

Somewhere between jdk11 and jdk14 the toString for InetSocketAddress changed.

Use stable hostaddress in ConnectionFailure message

---

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala

Overlooked this case when I cherry-picked #3333.

In jetty-server, warn on HTTP/2 support with SSLContextBits

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
core/src/main/scala/org/http4s/HttpRoutes.scala
core/src/main/scala/org/http4s/LiteralSyntaxMacros.scala
core/src/main/scala/org/http4s/MediaType.scala
core/src/main/scala/org/http4s/QValue.scala
core/src/main/scala/org/http4s/util/package.scala
server/src/main/scala/org/http4s/server/middleware/Caching.scala
tests/src/test/scala/org/http4s/HttpRoutesSpec.scala
tests/src/test/scala/org/http4s/util/DecodeSpec.scala

In preparation for EOL of 0.20, these issues were:
* Not binary breaking
* Not semantic changing
* Didn't give me a headache at 1:30am
Each can be reviewed as an independent commit.

Backports to 0.20

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
blaze-client/src/main/scala/org/http4s/client/blaze/ReadBufferStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/WSFrameAggregator.scala
core/src/main/scala/org/http4s/internal/package.scala
core/src/main/scala/org/http4s/util/package.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala

Should never have been part of the public API. Begin hiding it.

Deprecate org.http4s.util.bug

---

website/src/hugo/content/changelog.md
website/src/hugo/content/versions.md
website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html

It's time to consider EOL for series/0.20.  We haven't been backporting to this branch as aggressively as 0.21, which has been out since the beginning of February.  I'll look for low-hanging fruit, but it's a drag maintaining three branches, so I'd like to be done with it soon.
This PR has the mechanics for it.

Release v0.20.22, mark 0.20.x EOL

---

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
website/src/hugo/content/changelog.md

It was just a private constructor.  Probably could have gotten away with a MiMa exception, but those have burned us in the past.
We should tag v0.20.23 off this.
We still need to understand why CI didn't catch this.

Restore binary compatibility of http4s-jetty

---

build.sbt

This is not responsible for #3362, which was a failure on the server. But this is a landmine.

Check MiMa on jetty-client

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/package.scala
core/src/main/scala/org/http4s/internal/Trampoline.scala
core/src/main/scala/org/http4s/internal/package.scala
core/src/main/scala/org/http4s/util/execution.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
tests/src/test/scala/org/http4s/internal/TrampolineSpec.scala

We are an HTTP API, and we shouldn't be publishing general thread management utilities.
* Move our trampoline to internal.
* Move our non-shifting `fromFuture` to blaze-core, which is the only place it's used.  It would be slow to context shift between each chunk write.  For more general use, the newer `Async.fromFuture` is preferred.

Deprecate the org.http4s.util.execution package

---

server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala

This uses `CollectionCompat.CollectionConverters.asScalaIterator` instead of our own `asScalaIterator`. Motivated by https://github.com/http4s/http4s/pull/3326#pullrequestreview-395934628.

Use CollectionCompat in WebjarService

---

project/plugins.sbt

It has been the default since sbt-1.3.

Remove sbt-coursier plugin

---

project/Http4sPlugin.scala

It's already in build.sbt, and I'm trying to shrivel Http4sPlugin.

Don't redundantly set git.remoteRepo

---

build.sbt

I don't think this ever worked, and I don't think Ivy is used anymore.

Remove ivy logging level config

---

build.sbt
project/Http4sPlugin.scala

We've not needed this since Scala 2.10.

Remove http4sJvmTarget setting

---

project/Http4sPlugin.scala

This doesn't fail anymore, so decruft.

Remove unused compile dep filter on scala-reflect

---

project/Http4sPlugin.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

There are a bunch of deprecated attributes not yet migrated. This just takes care of migrating the object values so we can keep current without abandoning fatal warnings.
Supersedes #3413.

Upgrade to tomcat-9.0.35

---

project/Http4sPlugin.scala

* ~~boopickle-1.3.2 (supersedes #3419)~~
* json4s-3.6.8
* log4cats-1.1.1 (supersedes #3418)
* metrics-4.1.7 
* okhttp-4.6.0
* scalatags-0.9.1
* specs2-4.9.4
* Adds filters so dependencyUpdates runs clean

Update compatible dependencies on 0.21.x

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeHttp1ClientSpec.scala
blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
core/src/main/scala/org/http4s/internal/threads.scala
core/src/main/scala/org/http4s/util/threads.scala
testing/src/test/scala/org/http4s/Http4sSpec.scala

Another detestable PR in the name of binary compatibility.  Part of the process of moving our util package into proper public libraries, or tucking it away where we can change it at will.

Deprecate org.http4s.util.threads

---

core/src/main/scala/org/http4s/Method.scala

https://tools.ietf.org/html/rfc7540#section-11.6

Add PRI method

---

core/src/main/scala/org/http4s/TransferCoding.scala
core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/internal/package.scala
core/src/main/scala/org/http4s/util/CaseInsensitiveString.scala
core/src/main/scala/org/http4s/util/package.scala

1. This is not a great hash. We've done much better in typelevel/case-insensitive#19.
2. It shouldn't be public API anyway.
In a followup, we should fix `Scheme` and `TransferCoding` to just use a `CIString`.

Deprecate org.http4s.util.hashLower

---

client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala
core/src/main/scala/org/http4s/Method.scala

in [`http4s-finagle`](https://github.com/http4s/http4s-finagle)
```
sbt "++ 0.24.0-RC1 test"
```
will get runtime exception
```
May 14, 2020 1:21:20 PM com.twitter.util.RootMonitor$$anonfun$2 applyOrElse
SEVERE: Fatal exception propagated to the root monitor!
java.lang.AbstractMethodError: Method org/http4s/dsl/io$.org$http4s$dsl$impl$Methods$_setter_$GET_$eq(Lorg/http4s/Method$Semantics$Safe;)V is abstract
at org.http4s.dsl.io$.org$http4s$dsl$impl$Methods$_setter_$GET_$eq(io.scala)
at org.http4s.dsl.impl.Methods.$init$(Methods.scala:12)
at org.http4s.dsl.io$.<clinit>(io.scala:11)
```
publishLocal and rerun `sbt "++ 0.24.0-RC1 test"` in `http4s-finagle`
dotty runtime is not binary compat to initialize `PermitsBody` because it extends an abstract class
well I found it is unnecessary to …

Fix dotty runtime error

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Client.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
core/src/main/scala/org/http4s/internal/SSLContextOption.scala

Follows up on https://github.com/http4s/http4s/issues/2431#issuecomment-627474729.
Ross suggested using a sum type in https://github.com/http4s/http4s/issues/2431#issuecomment-496961469. Today, my teammates got confused at the `Option[SSLContext]`'s behavior when upgrading from 0.20.x -> 0.21.4 in `http4s`. 
Those two served as motivations to open this PR.
Hi @rossabaker - please take a look. Thanks!

Use Sum Type instead of Option[SSLContext] for BlazeClientBuilder#apply

---

core/src/main/scala/org/http4s/Header.scala
core/src/main/scala/org/http4s/headers/Accept-Patch.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
core/src/main/scala/org/http4s/util/Renderable.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala
tests/src/test/scala/org/http4s/headers/AcceptPatchSpec.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

As part of modeling headers, here's `Accept-Patch`

Model Accept-Patch header

---

client/src/main/scala/org/http4s/client/middleware/Logger.scala
core/src/main/scala/org/http4s/internal/Logger.scala
server/src/main/scala/org/http4s/server/middleware/Logger.scala

Both [org.http4s.server.middleware.Logger#logMessage](https://github.com/http4s/http4s/blob/v0.21.4/server/src/main/scala/org/http4s/server/middleware/Logger.scala#L52-L98) and [org.http4s.client.middleware.Logger#logMessage](https://github.com/http4s/http4s/blob/v0.21.4/client/src/main/scala/org/http4s/client/middleware/Logger.scala#L26-L72) are the same.
As a result, I copied their same definition to `org.http4s.internal.Logger#logMessage`, and then referenced that definition from both call sites.
Could you please review this one, @rossabaker, @ChristopherDavenport and @bpholt? 
Side note - Brian, we sat next to each other at NEScala in Philly 1-2 years ago. I'm the guy from Banno/Jack Henry. I hope you're well! Also, I reached out to you, Brian, per …

DRY (Don't Repeat Yourself) up Logger#logMessage

---

server/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
server/src/test/scala/org/http4s/server/middleware/EntityLimiterSpec.scala

This PR is part of #2402.
Note: this time I opened the PR against the series/0.21 branch, I hope this makes things easier (please let me know if it should be a different branch).

Implement httpRoutes and httpApp constructors for EntityLimiter 

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
core/src/main/scala/org/http4s/websocket/WebSocket.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala

This kind of API is much more easy to use and it is kinda superset of old API - as you see I can implement old API via new, but it's very hard to do new API with an old one.
Related to http4s/http4s#1863

Implement WebSocket stream with a single send-receive pipe

---

core/src/main/scala/org/http4s/internal/Logger.scala

My primary motivation of this PR is to, via this Logger for `client`, offer a function, Option[String => F[String]]. It supplies the option of further modifying the String body.
In my case, I'm interested to transform the String into Json, sanitize it, and then print out the sanitized JSON. By "sanitize," I mean to hide/obscure JSON keys' values that are sensitive.
I intend, in a follow-up PR, to make such a change for `org.http4s.server.middleware`'s `Request/ResponseLogger`.

Add org.http4s.internal.Logger#logMessageWithBodyText

---

scalafix/build.sbt

Allows the **scalafix** rules get published and then references from other projects.
**Note**: this also changes the **http4s** output version from "0.20.0-M5" to the final "0.20.0"
since there's no reason to reference a milestone version anymore.
This change is inspired by this conversation: #3372,
and ideally should be merged _before_ the former PR.

Assign an initial version to the scalafix subproject

---

blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala

The initial intent was to fix some bad spellings, but I think these docs are obsolete: I don't know what "Cancellation" exception it's talking about.

Remove obsolete docs about Canceled

---

scalafix/build.sbt
scalafix/project/plugins.sbt

Just enough extra *.sbt to backpublish the scalafix for 0.20.0, per #3502
If I understand our strategy correctly, we want to start publishing these with output version concurrent with http4s version, and should move scalacheck out of its isolated build and into a first-class module.
/cc @satorg

Publishing http4s-scalafix-0.20.0

---

docs/src/main/mdoc/middleware.md

I broke this in the backport of #3487. It's right on master.

Fix CIString reference in middleware.md

---

server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

We should not call toString on the input to `ResponseLogger`, because it will usually be a request, and we don't have the means to redact non-default sensitive information.
Fixes #3482

Don't call .toString on ResponseLogger input

---

client/src/main/scala/org/http4s/client/middleware/Logger.scala
client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
core/src/main/scala/org/http4s/internal/Logger.scala
server/src/main/scala/org/http4s/server/middleware/Logger.scala
server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

Adds functions to `org.http4s.client.middleware.{Logger, RequestLogger, ResponseLogger}` and `org.http4s.client.middleware.{Logger, RequestLogger, ResponseLogger}` for specifying how to explicitly log the HTTP Request/Response payload.
My end goal is to be able to use these `Logger`'s in order to log a sanitized/redacted JSON payload on my server and client(s). So, in short, I'll be going from `Stream[F, Byte] => Stream[F, Json] => Stream[F, Json] => F[String]` or something like that where the second `Stream[F, Json]` indicates that it's sanitized.
Note that I'll be using https://github.com/circe/circe/blob/v0.14.0-M1/modules/extras/src/main/scala/io/circe/extras.scala#L7-L51 in order to sanitize the JSON.
Hi @hamnis and @rossabaker - can you please review? This one is in a follow-up to …

Add Functions to org.http4s.[client|server].middleware.{Logger, RequestLogger, ResponseLogger} for Logging Payloads Explicitly

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala

async-http-client can call `onThrowable` after we've returned a response from `onStream`.  We need a way to surface those to the client. We can't fail the response effect after we've already returned a response with a streaming body, but we can raise an error into that streaming body.
I haven't figured out a performant unit test, but my adaptation of @denisovlev's report is [here](https://gist.github.com/rossabaker/0934df905f2a11d3b658a9df66a0b6eb).
Fixes #3509.

Raise throwables into body if streaming has begun

---

core/src/main/scala/org/http4s/Query.scala
core/src/main/scala/org/http4s/QueryOps.scala
tests/src/test/scala/org/http4s/UriSpec.scala

If a Uri has a trailing `?`, calling `withQueryParams` on it should not preserve the empty parameter.  We unfortunately already defined `Query.empty` to be the _absence_ of a query string, so we need a new name.  We probably should have made that an `Option`, which is something we can consider in 1.0.
I believe this will fix #3519.

Introduce Query.blank, make it behave in withQueryParams

---

laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/ContentCodingSpec.scala

I'm sorry. I led @ashwinbhaskar down a wrong path.
Cats' `OrderLaws` [inherit]((https://github.com/typelevel/cats/blob/fd586f0b010deef4fdcd8d4b94c560d72396dc24/kernel-laws/shared/src/main/scala/cats/kernel/laws/PartialOrderLaws.scala#L15-L16)) this:
```scala
def antisymmetry(x: A, y: A): IsEq[Boolean] =
(!(E.lteqv(x, y) && E.lteqv(y, x)) || E.eqv(x, y)) <-> true
```
And they also [inherit](https://github.com/typelevel/cats/blob/master/kernel-laws/shared/src/main/scala/cats/kernel/laws/EqLaws.scala#L15-L16) this:
```scala
def antiSymmetryEq(x: A, y: A, f: A => A): IsEq[Boolean] =
(!E.eqv(x, y) || E.eqv(f(x), f(y))) <-> true
```
I thought we were failing on the former, but it's actually the latter being checked.  The `ARG_2` in the failure is the `f`:
```
2020-04-13T03:25:16.4858291Z …
```

Fix Cogen[ContentCoding]

---

website/src/hugo/content/changelog.md

Fixes the release notes I accidentally pushed straight to the branch.
And after that, we should be ready to release.

Release v0.21.5

---

client/src/main/scala/org/http4s/client/middleware/GZip.scala
client/src/test/scala/org/http4s/client/middleware/GZipSpec.scala

This PR generlizes the solution to the ["GZip client middleware crashes when processing an HTTP HEAD response"](https://github.com/http4s/http4s/issues/3452) issue as was suggested from the [prevoius PR](https://github.com/http4s/http4s/pull/3476), by not decompresing a response body regardless of the corresponding request method.
The GZip client middleware inspects the response stream whether it's empty, by trying to peek the first byte from it without consuming it. If there is at least on byte in the stream, then the stream is considered non empty and the decompression process is applied; otherwise it just returns an empty stream. 
I only was able to signal whether the stream is empty via the error channel, because the `fs2.compression.gunzip` method before proceeding with the …

GZip client middleware should not decompres empty response body

---

ember-core/src/main/scala/org/http4s/ember/core/Encoder.scala
ember-core/src/test/scala/org/http4s/ember/core/EncoderSpec.scala

- It was previously UTF-8, we've switched to ASCII to match the [gist](https://gist.github.com/rossabaker/31ea688c2337c40a0a0a7070cc8b4e1d), is that the correct encoding?

More Efficient Ember Encoding

---

client/src/main/scala/org/http4s/client/middleware/Retry.scala

I recently copied and pasted this function since I need to use it.
I propose exposing it to be `public` via this PR.

Make RetryPolicy#isErrorOrRetriableStatus public, not private.

---

client/src/main/scala/org/http4s/client/middleware/GZip.scala
client/src/test/scala/org/http4s/client/middleware/GZipSpec.scala

This is a backport of #3550 to the 0.21 line.  It restores the deprecated `fs2.compress` calls for binary compatibility, because `Bracket` is the only constraint we have.  When we merge this back to master, we should keep the version from #3550.
Also add a `NoStackTrace` to the internal exception.  It should never be thrown outside the private method, and it's not an error condition.  We're using an untyped exception for control flow here, which is uncomfortable, but it's a highly localized implementation detail with a test.
I think this elides the concern from my bad merge of #3476, but I wanted to get eyes on it.
/cc @nelusnegur

Backport #3550: Empty bodies in client.GZip

---

core/src/main/scala/org/http4s/headers/Max-Forwards.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/headers/MaxForwardsSpec.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

Simple modeling of `Max-Forwards` as part of https://github.com/http4s/http4s/issues/2011

Models the Max-Forwards header

---

ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-core/src/main/scala/org/http4s/ember/core/Encoder.scala

Fixes #3592 
First Error Discovered: When we are actually able to reuse a connection it was draining the root stream of extra bytes. As we had listed to take 2060 bytes, and then with the same reference try to pull 2060 more bytes as the effect was executed in the use block. This hung waiting for new bytes. (This signals to me that the user has a hold of the root connection not only a handle of 2060 bytes worth of it as pulling twice tries to take that twice, unsure if we should do something or how to do something that separates that logic). This means as well that a partially consumed stream will trigger the finalizers for reuse but the underlying stream will have however many bytes are uncomsumed present. We could add something that measures how much is read and then read that on …

Fixes Connection Reuse for Ember Client

---

.scalafmt.conf
core/src/main/scala/org/http4s/StaticFile.scala

Retargets #3596 and reformats.  Done on series/0.21 to minimize branch divergence.

Upgrade to scalafmt-2.6.4

---

core/src/main/scala/org/http4s/headers/Access-Control-Allow-Headers.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/headers/AccessControlAllowHeadersSpec.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

This PR models `Access-Control-Allow-Headers` header as part of #2011. The header specification can be found on [Fetch spec](https://fetch.spec.whatwg.org/#http-access-control-allow-headers) and [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers).
The header has the following syntax:
```
Access-Control-Allow-Headers: <header-name>[, <header-name>]*
Access-Control-Allow-Headers: *
```

Model Access-Control-Allow-Headers header

---

core/src/main/scala/org/http4s/StaticFile.scala

Previous discussion in #3584
The URLConnection in StaticFile.fromURL is never closed (if the resource is not expired).
This PR reuses the already opened URLConnection to read the response body which in effect causes fs2 to close the URLConnection once the body is fully read.
This PR also wraps `urlConn.getInputStream.close()` in a `Try` because it should just be a last attempt to close the resource and should return NotModified in case of errors.
Because of the discussion in #3594 I opened this against series/0.21

Close urlConn in StaticFile.fromURL

---

jetty-client/src/main/scala/org/http4s/client/jetty/JettyClient.scala

I believe this might have been an oversight, comparing with alternativ clients such as [AsyncHttpClient](https://github.com/http4s/http4s/blob/master/async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala#L43). Please feel free to close this PR if the current implementation was chosen for compatibility reasons.

Use defaultHttpClient in JettyClient builder

---

build.sbt
ember-core/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/src/main/scala/org/http4s/ember/core/Shared.scala
ember-core/src/test/scala/org/http4s/ember/core/ParsingSpec.scala
ember-core/src/test/scala/org/http4s/ember/core/TraversalSpec.scala

Adds Trailer Headers to Ember - Previous to this we had been marking chunked streams not reuseable because it did not parse correctly. Specifically it was leaving bytes left in the root stream.
The old behavior stopped reading after it had parsed 0\r\n, however the termination for chunked is 
`0\r\n\r\n` OR `0\r\nheader:keyr\r\nheader:key\r\n\r\n`
Since we had previously pulled `0\r\n` that means we need to parse to either an immediate `\r\n`, or pull into a buffer until we reach `\r\n\r\n`.  The only thing I feel is missing is a termination condition if the bytevector for accumulation gets too large. Is there a reasonable default here?
That final `\r\n\r\n` or `\r\n` should signal the very last bytes and hence mean connections are truly ready for reuse.

Add Trailer Headers to Ember

---

build.sbt
ember-core/src/main/scala/org/http4s/ember/core/Util.scala
ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

- Enables Server Connection Reuse For Ember
- Add Similar Processing as is done in Client, with implicit keep-alive and date.
Performance Locally
```
hey -z 30s  http://localhost:8080/hello
Summary:
Total:	30.0007 secs
Slowest:	0.5015 secs
Fastest:	0.0001 secs
Average:	0.0015 secs
Requests/sec:	75735.8589
Total data:	68549378 bytes
Size/request:	68 bytes
Response time histogram:
0.000 [1]	|
0.050 [999948]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.100 [1]	|
0.151 [0]	|
0.201 [0]	|
0.251 [0]	|
0.301 [0]	|
0.351 [0]	|
0.401 [0]	|
0.451 [0]	|
0.502 [50]	|
Latency distribution:
10% in 0.0003 secs
25% in 0.0004 secs
50% in 0.0005 secs
75% in 0.0007 secs
90% in 0.0011 secs
95% in 0.0014 secs
99% in 0.0039 secs
Details (average, fastest, slowest):
DNS+dialup:	0.0000 secs, 0.0001 secs, 0.5015 …
```

Enable Ember Server Connection Reuse

---

build.sbt
ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-client/src/test/scala/org/http4s/ember/client/internal/ClientHelpersSpec.scala
ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
project/build.properties

- Connection Keep-Alive added if not present to request
- Date add if not present to request
- Default User-Agent added, and added to request if not present along with builder options
- Added Tests For the above and for response cancelation. We have an intriguing position that streams are scoped as closing before the last element. I wonder what else this could cause elsewhere as well.

Client Request/Response Modifications

---

.mergify.yml

Mergify is looking for the result of the Scalafix job, but there no longer is a distinct Scalafix job.

Remove Scalafix from mergify config

---

testing/src/test/scala/org/http4s/Http4sSpec.scala
tests/src/test/scala/org/http4s/QueryParamCodecSpec.scala

Should resolve #3664
The root cause of the issue is a bug in Java 1.8 which fails parsing of zoned dates/times with "GMT0" zone id.
Please find more details on this here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8138664
The suggested fix simply suppresses generation of `ZonedDateTime` instances with "GMT0" in `QueryParamCodecSpec` if the test runs on Java 1.8.
It doesn't fix the corresponding `QueryParamCodec` itself – I'm not sure if it would be a correct approach to try mitigating Java bugs on this level.
Also it slightly improves output for this test as well as other tests based on `Http4sSpec`.

Fixes QueryParamCodecSpec flakiness

---

core/src/main/scala/org/http4s/QueryOps.scala
core/src/main/scala/org/http4s/QueryParam.scala

Any `QueryParam` instance is also an instance of `QueryParamKeyLike`, this commit makes that relationship explicit. This solves, and prevents, a few edge cases in the DSL. For example, the following would yield a compilation error before this commit.
```scala
final case class Foo(value: String)
object Foo {
implicit val queryParam: QueryParam[Foo] = QueryParam.fromKey("foo")
implicit val queryParamEncoder: QueryParamEncoder[Foo] = QueryParamEncoder[String].contramap(_.value)
val foo: Foo = Foo("bar")
val baseUri: Uri = Uri()
// Works
val uri0: Uri = baseUri.+*?(foo)
// Works
val uri1: Uri = baseUri.withOptionQueryParam(Some(foo))
// Fails
val uri2: Uri = baseUri.withQueryParam(foo)
}
```
The reason the final case fails is that there is no `withQueryParam` which takes a `QueryParam` …

Make QueryParam A SubClass Of QueryParamKeyLike

---

server/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/src/test/scala/org/http4s/server/middleware/CSRFSpec.scala

- The `recover` cases in `validate` and `checkCSRFToken` use the defined `onFailure` response. This is by definition already `Response[G](Status.Forbidden)` and does not change the former behavior of the hard-coded responses.
- Add tests for a CSRF object that has a defined `onFailure` response.
- Fixes #3665

#3665 Bug in CSRF error handler for `onFailure`

---

docs/src/main/mdoc/dsl.md

Document this powerful matcher.

Add docs for 'OptionalValidatingQueryParamDecoderMatcher'.

---

core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
tests/src/test/scala/org/http4s/MethodSpec.scala

Should resolve #3680
Fixes the `Rfc2616BasicRules.token` method which is used in `Method.fromString`.
The `Rfc2616BasicRules.isToken` method should also get fixed.

Fix Method.fromString

---

core/src/main/scala/org/http4s/Uri.scala
server/src/main/scala/org/http4s/server/Router.scala
server/src/main/scala/org/http4s/server/middleware/TranslateUri.scala
server/src/test/scala/org/http4s/server/RouterSpec.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
tests/src/test/scala/org/http4s/MessageSpec.scala
tests/src/test/scala/org/http4s/UriSpec.scala

Added deprecations to indexOf and indexOfString and added the implementation to findSplit and findSplitOfString
Fixes #3713

Router should use correct prefix when routing

---

prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala

Should be work that resolves #3731

resolving PrometheusExportService path comparison failure

---

build.sbt

Resolves #3613
Suppresses all "unused-whatever" warnings in the `scalafixInput` module.
Sometimes `scalafixInput` have to contain unused stuff (imports, parameters, etc) just to let the `scalafixOutput` module be semantically correct and thus compile successfully.

Fix 'unused' warnings in scalafix-input module

---

core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/parser/Rfc2616ParserSpec.scala

Fixes `ListSep` parser according to RFC2616

---

core/src/main/scala/org/http4s/headers/Forwarded.scala
core/src/main/scala/org/http4s/headers/ForwardedRenderers.scala
core/src/main/scala/org/http4s/parser/ForwardedHeader.scala
core/src/main/scala/org/http4s/parser/ForwardedModelParsing.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
tests/src/test/scala/org/http4s/headers/ForwardedArbitraryInstances.scala
tests/src/test/scala/org/http4s/headers/ForwardedAuxiliaryGenerators.scala
tests/src/test/scala/org/http4s/headers/ForwardedRenderersSpec.scala
tests/src/test/scala/org/http4s/headers/ForwardedSpec.scala
tests/src/test/scala/org/http4s/parser/ForwardedHeaderSpec.scala

Resolves #3471.
The `Forwarded` header model tries to be as type safe as possible and thus introduces a hierarchy of model classes for that.
In particular, `Element` enables the following syntax for building elements:
```scala
Element
.fromFor(Node(...))
.withBy(Node(...))
.withHost(Host(...))
.withProto(Proto(...))
```

Models 'Forwarded' header

---

core/src/main/scala/org/http4s/QueryOps.scala
tests/src/test/scala/org/http4s/UriSpec.scala

When using [`+?` operator](https://github.com/http4s/http4s/blob/e45ca2c8703c43d7c00a55d47a35d3bd3b79dfdd/core/src/main/scala/org/http4s/QueryOps.scala#L39) to add a query param to an `Uri` value in Scala 2.13.3 the following warning is raised:
```scala
[warn] ${BASE}/Test.scala:14:37: multiarg infix syntax looks like a tuple and will be deprecated
[warn]   val uri = uri"localhost" / "test" +? ("key", "value")
[warn]                                     ^
```
The warning only dissapears if no-infix syntax is used:
```scala
(uri"localhost" / "test").+?("key", "value")
```
...which completely breaks the goal of those operators.
- Separate usages of `+?` and `+??` in tests to be able to see the error (if someone tries to compile the first commit of this PR it should fail with `multiarg infix …

Refactor query param infix operators to avoid 2.13 error

---

build.sbt
dsl/src/main/scala/org/http4s/dsl/Http4sDsl.scala
project/Http4sPlugin.scala
project/build.properties
project/plugins.sbt

Pulls in a compatible sbt-explicit-dependencies that's blocking #3755.

sbt-1.4.1 and friends

---

core/src/main/scala/org/http4s/headers/Forwarded.scala

Clean up unbound placeholders

---

client/src/main/scala/org/http4s/client/middleware/GZip.scala
core/src/main/scala-2.12/scala/annotation/nowarn.scala
core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/parser/CookieHeader.scala
core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
server/src/main/scala/org/http4s/server/middleware/GZip.scala

It's the basic idea @Daenyth suggested on #3764.  I'm still avoiding the (nice) scala-collection-compat library for now, just to avoid taking on more heft.
Paired with https://github.com/http4s/sbt-http4s-org/pull/33, we should be able to re-enable the `SilencerPlugin` on the dotty branch.

Replace silent annotation with nowarn

---

.gitignore

Adds  `/.bsp/` dir (which was introduced in SBT 1.4.0) to `.gitignore`

Adjusts .gitignore for newer SBT version

---

dsl/src/main/scala/org/http4s/dsl/Http4sDsl.scala

This reverts commit 1db158894111c555a60312066197538cca2d8a6e.
It is necessary in 0.21, but it's noise in 1.x.

Revert "Fix binary compatibility issues uncovered by MiMa-0.8"

---

core/src/main/scala-0.27/org/http4s/internal/CollectionCompat.scala

We could add scala-collection-compat, and also pick up `@nowarn` support (see #3764).  I'm not so sure we can do that without breaking binary compatibility, and this hasn't grown out of control _yet_.  This just copies the 2.13 trait.
This build will not pass yet, and targets the dotty branch.

Adds CollectionCompat trait for Dotty

---

build.sbt
project/plugins.sbt

With the sbt-http4s-org plugin, silencer now does the right thing in Scala 2 and Dotty.  It also opts out of the backend-parallelism option for Dotty.

Reinstate silencer plugin

---

ember-core/src/main/scala/org/http4s/ember/core/Encoder.scala
ember-core/src/test/scala/org/http4s/ember/core/EncoderSpec.scala

Adds `0/crlf/crlf` 5 bytes to every empty request/response and transfer-encoding is just a longer string as well.
But puts us in line with blaze without the cheating based on knowing the buffer is empty.

Ember: Chunked Default like Blaze Semantics

---

core/src/main/scala/org/http4s/QueryParam.scala

We broke MiMa when we backported #3792.  This can safely be rolled back when merged to main.

Add missing AbstractFunction1 inheritance

---

okhttp-client/src/main/scala/org/http4s/client/okhttp/OkHttpBuilder.scala

Fixes #3810.  If the body is not rendered before the callback completes, chunks are silently dropped.
I think this needs to block one of okhttp's threads, so there's no integration with Blocker.  I don't know this backend particularly well, so we may be able to do better.  Anyhow, this fixes the sample code in #3810 for me.
Thanks to @GrafBlutwurst for the bug report.

Render okhttp request body synchronously

---

build.sbt
laws/src/main/scala/org/http4s/laws/EntityCodecLaws.scala
laws/src/main/scala/org/http4s/laws/EntityEncoderLaws.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
laws/src/main/scala/org/http4s/laws/discipline/EntityCodecTests.scala
laws/src/main/scala/org/http4s/laws/discipline/EntityEncoderTests.scala
project/Http4sPlugin.scala

As per the title. I spent a good chunk of time reading docs and sources and wasn't getting anywhere, so I though I'll take Fabio's advice and open a draft PR for guidance.
My troubles come from 2 places:
- `EntityCodecTests`
- `ArbitraryInstances`
I'll start with `EntityCodecTests`. To refresh your memory it currently looks like this 
```scala
def entityCodec(implicit
arbitraryA: Arbitrary[A],
shrinkA: Shrink[A],
eqA: Eq[A],
eqFBoolean: Eq[F[Boolean]],
testContext: TestContext): RuleSet =
new DefaultRuleSet(
name = "EntityCodec",
parent = Some(entityEncoder),
"roundTrip" -> Prop.forAll { (a: A) =>
laws.entityCodecRoundTrip(a)
}
)
```
Because I changed `Effect` for `Concurrent` in `EntityCodecLaws` now `entityCodecRoundTrip` is a `IsEq[F[Either[Decodefailure, A]]`. And that is failing to …

CE3 Laws upgrade

---

nix/pkgs.nix
shell.nix

This ensures we get a Java 8 even in SBT.
I realize I'm probably the only one who cares.

Pin the Java version in the nix-shell

---

build.sbt

Turns out we only need cats-laws, not cats-effect-laws.

Start compiling laws for CE3

---

async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClientStats.scala
async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala

Currently there is no way to access `org.asynchttpclient.DefaultAsyncHttpClient#getClientStat` when we create a `Resource[F, Client[F]]` using `org.http4s.client.asynchttpclient.AsyncHttpClient#resource`.
This PR adds an additional apply method in `AsyncHttpClient` which lets the user pass in their own `DefaultAsyncHttpClient` so that they can have a handle on its state and use it for metrics etc.

Add Ability to pass own client in AsyncHttpClient so that it's state can be referenced

---

core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/FormDataDecoder.scala
core/src/main/scala/org/http4s/UrlForm.scala

As per the discussion on gitter.
I also have a separate branch where I went over other `Sync` usages in core, but I think that might need some discussion, so for the sake of expediency I'm PRing this separately first.

EntityDecoder constraints loosened

---

testing/src/test/scala/org/http4s/testing/Http4sLegacyMatchersIO.scala

Previously it depended on `org.specs2.matcher.IOMatchers`, which was using ce2 classes in the implementation. I removed it as a mix-in and attempted to reimplement its behavior straight on `Http4sLegacyMatchersIO`. While I _think_ this is the correct implementation, `IOMatchers` ([link](https://github.com/etorreborre/specs2/blob/master/cats/shared/src/main/scala/org/specs2/matcher/IOMatchers.scala#L71)) also had a section which I didn't quite get
```scala
protected[specs2] override def attemptRun[T](check: ValueCheck[T], duration: Option[FiniteDuration]): IOMatcher[T] =
IOMatcher(check, duration)
case class IOMatcher[T](check: ValueCheck[T], duration: Option[FiniteDuration])
extends TimedMatcher[T](check, duration) {
def checkIOWithDuration[S <: IO[T]](e: Expectable[S], d: …
```

Http4sLegacyMatchersIO

---

dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
dsl/src/test/scala/org/http4s/dsl/PathSpec.scala

Approximates what is described at https://www.w3.org/DesignIssues/MatrixURIs.html

Implement a matrix path variable parser

---

build.sbt
jawn/src/main/scala/org/http4s/jawn/JawnInstances.scala
project/Http4sPlugin.scala

Fixes https://github.com/http4s/http4s/issues/3839

jawn module for cats-effect 3

---

boopickle/src/main/scala/org/http4s/booPickle/BooPickleInstances.scala
boopickle/src/test/scala/org/http4s/booPickle/BoopickleSuite.scala
build.sbt
project/Http4sPlugin.scala
testing/src/test/scala/org/http4s/Http4sSuite.scala

This PR ports boopickle to run on CE3 but perhaps more important it lays the basics to use
munit/munit-cats-effect for tests.
There is still some work to do but I wanted to verify if the idea of munit seems workable

Port Boopickle to cats effect 3 and add basic munit infrastructure

---

project/build.sbt
project/plugins.sbt

This causes friction on Scala upgrades. Can we remove it yet?

Stop pinning scalameta

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala

Fixes #3890 
Questions: Is this a good chunk size? should we make it configurable in other versions? how does this relate to the benches for cutoff?
This should see a reduction in buffer flushes of 2000x

Fix Streamed Json Encoding

---

server/src/test/scala/org/http4s/server/middleware/HttpsRedirectSpec.scala

This is a sample of a test using `Http4sLegacyMatchersIO` ported to use `munit.CatsEffectSuite`. IMHO it looks cleaner but I'm happy to get more feedback

Port HttpsRedirectSpec to munit

---

client/src/main/scala/org/http4s/client/Http4sClientDsl.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/MultipartClient.scala

MethodOps apply returns Request[F]

---

build.sbt
json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala

I'd like to enable some tests to check https://github.com/http4s/http4s/pull/3871
Now that we are using `Concurrent` instead of `Sync`, we cannot use `F.delay` anymore.
I'm not sure that would be the right approach here.
I've started with `pure`.
As the parsing of a json can take CPU time, should we signal it that some way so that maybe a new thread should be used for it? Could this block a fiber?
Should we use something different from `F.pure()`? `F.unit.as()`?

migrate json4s, json4s-native, json4s-jackson to cats-effect 3

---

core/src/main/scala/org/http4s/Header.scala
core/src/main/scala/org/http4s/Headers.scala
tests/src/test/scala/org/http4s/HeaderSpec.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala

I left the old `Eq` based symbols in place so as not to break binary compatibility.

Add Order Instance For Header and Headers

---

core/src/main/scala/org/http4s/HttpVersion.scala
tests/src/test/scala/org/http4s/HttpVersionSpec.scala

For https://github.com/http4s/http4s/issues/3869
Test had to be adapted in order to fix the following compile error:
```
ambiguous implicit values:
both value http4sHttpOrderForVersion in object HttpVersion of type cats.Order[org.http4s.HttpVersion]
and value http4sHttpHashForVersion in object HttpVersion of type cats.Hash[org.http4s.HttpVersion]
match expected type cats.kernel.Eq[org.http4s.HttpVersion]
checkAll("HttpVersion", OrderTests[HttpVersion].order)
```
Do let me know if there's a better way to fix this.

Add Hash and BoundedEnumerable instances for HttpVersion

---

core/src/main/scala/org/http4s/Query.scala
core/src/main/scala/org/http4s/parser/QueryParser.scala

- Lazily parse Query by access of "pairs" variable
- Add raw for access and withRaw to replace the internal string representation
This should hopefully be binary compatible, lets see what MIMA says.

Support raw query string

---

ember-core/src/test/scala/org/http4s/ember/core/TraversalSpec.scala
project/Http4sPlugin.scala
website/src/hugo/content/changelog.md

Before:
```
sbt:http4s> show client/fullClasspath
[info] * Attributed(/home/ross/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-effect_2.13/2.3.0-M1/cats-effect_2.13-2.3.0-M1.jar)
```
After:
```
sbt:http4s> show client/fullClasspath
[info] * Attributed(/home/ross/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-effect_2.13/2.2.0/cats-effect_2.13-2.2.0.jar)
```
This is confirmed to work in the failing @scala-steward test case, and should help @alexandervanhecke.
Followup work will be done in #3931.

Downgrade to munit-cats-effect-0.8.0, curse 0.9.0

---

docs/src/main/mdoc/client.md
docs/src/main/mdoc/dsl.md
docs/src/main/mdoc/json.md

Fixes #3933.  Some of the regular crossbuilds failed with the regular flakes, which failed fast, and we never successfully ran the doc job before we merged #3903.

Fix docs for client DSL changes in #3903

---

build.sbt
play-json/src/main/scala/org/http4s/play/PlayEntityDecoder.scala
play-json/src/main/scala/org/http4s/play/PlayInstances.scala
play-json/src/test/scala/org/http4s/play/PlaySpec.scala

As discussed with @rossabaker. Use `Concurrent` instead of `Sync` in the play-json module. Issue: #3962

Issue-3946 Activate and migrate play-json to Cats-effect 3

---

core/src/main/scala/org/http4s/Query.scala
core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/internal/package.scala
core/src/main/scala/org/http4s/package.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/src/test/scala/org/http4s/AuthoritySpec.scala
tests/src/test/scala/org/http4s/QuerySpec.scala
tests/src/test/scala/org/http4s/RegNameSpec.scala
tests/src/test/scala/org/http4s/UriHostSpec.scala
tests/src/test/scala/org/http4s/UriSpec.scala

This commit adds `Order`, `Hash`, and `Show` instances for the following types.
* `org.http4s.Uri.Authority`
* `org.http4s.Query`
* `org.http4s.Uri.Host`
* `org.http4s.Uri.RegName`
* `org.http4s.Uri`
The impetus for all of them was to support instances for `org.http4s.Uri`.
In addition, two functions were added to the package object `org.http4s.internal` scoped to be private to `http4s`, `compareField`, `reduceComparisons_`, and `reduceComparisons`.
These functions substantially reduce the amount of code required to write `Order` instances for Product types.
In order to support testing the laws for these types, several new instances of `Arbitrary` and `Cogen` were added, as not all types had instances for each of these.

Add Order/Hash/Show Instances For Uri And Related Types

---

core/src/main/scala/org/http4s/parser/LinkHeader.scala
tests/src/test/scala/org/http4s/headers/LinkSpec.scala

[RFC 8288, Section 3.3](https://tools.ietf.org/html/rfc8288#section-3.3) states that any occurrences of the `rel` parameter after the first one must be ignored. This fixes the `Link` header parser to conform to this behavior.

Improve Link header parser conformance to RFC 8288

---

core/src/main/scala/org/http4s/HttpApp.scala
core/src/main/scala/org/http4s/implicits.scala
core/src/main/scala/org/http4s/internal/Logger.scala
core/src/main/scala/org/http4s/multipart/Part.scala
core/src/main/scala/org/http4s/syntax/AllSyntax.scala
core/src/main/scala/org/http4s/syntax/KleisliSyntax.scala
core/src/main/scala/org/http4s/syntax/package.scala

Still using `Sync` given the changes
- `EntityEncoder`: `inputStreamEncoder` (uses `readInputStream`), `readerEncoder`
- `StaticFile`: `fromResource`, `fromURL`
- `org.http4s.internal.package.scala`: `CompletionStage` interop
Some notes on the changes:
- Changed `HttpApp` to `Defer` from `Sync`. My gut says that that's not right, but it's possible so I did it 🤷‍♂️ 
- `KleisliSyntax` has the sacred words `BinCompat` - not sure if that means that _no_ changes should be done there or something else in this case (my binary compatibility understanding is admittedly lackluster)

Loosened some constraints in core

---

core/src/main/scala/org/http4s/headers/Accept-Ranges.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
core/src/main/scala/org/http4s/parser/RangeParser.scala
tests/src/test/scala/org/http4s/parser/AcceptRangesSpec.scala

This is a preliminary PR to request feedback, it does not fully replace `RangeParser` yet.
I added the cats-parse implementation to the  `Accept-Ranges` companion object and I'd like some general feedback on my usage of cats-parse and any formatting/style stuff.
I also have a question about the previous implementation, ([here](https://github.com/http4s/http4s/blob/c8d349dbf05af3ea76284801e49759778decaea9/core/src/main/scala/org/http4s/parser/RangeParser.scala#L65)) the top level rule for `Accept-Ranges` is matching on EOL  but this caused the cats-parse version to fail tests, I assume that parboiled2 is different from cats-effect and this is not necessary but I want to confirm this.

Replace `Accept-Ranges` parser with cats-parse implementation

---

okhttp-client/src/main/scala/org/http4s/client/okhttp/OkHttpBuilder.scala

see https://github.com/http4s/http4s/pull/4005

Set content header on OKHttpClient [targeting series/0.21]

---

core/src/main/scala/org/http4s/parser/CookieHeader.scala
tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala

Fixes #4003 in the current parboiled2 implementation.
Space is not a valid cookie value, but some popular specifications depend on it anyway.  We don't have an easy way right now to support pluggable header parsers for differing levels of compliance.  This is a compromise for users caught in the crossfire.

Tolerate space in cookie values

---

build.sbt
circe/src/main/scala/org/http4s/circe/CirceEntityDecoder.scala
circe/src/main/scala/org/http4s/circe/CirceEntityEncoder.scala
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/DecodingFailures.scala
client/src/main/scala/org/http4s/client/Client.scala
client/src/main/scala/org/http4s/client/DefaultClient.scala
client/src/main/scala/org/http4s/client/middleware/Metrics.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/EntityEncoder.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/Uri.scala
play-json/src/main/scala/org/http4s/play/PlayEntityDecoder.scala
play-json/src/main/scala/org/http4s/play/PlayEntityEncoder.scala
project/ScaladocApiMapping.scala
server/src/main/scala/org/http4s/server/middleware/Caching.scala
server/src/main/scala/org/http4s/server/middleware/ConcurrentRequests.scala
server/src/main/scala/org/http4s/server/middleware/Metrics.scala
twirl/src/main/scala/org/http4s/twirl/TwirlInstances.scala

This commit corrects _most_ of the Scaladoc issues.
The Scaladoc issues fell into one or more of the following categories.
* Reference was not fully qualified.
* For external links, and for _some_ internal links, Scaladoc wants a fully qualified symbol to link against, even if the given symbol is in scope.
* For example, `[[Kleisli]]` -> `[[cats.data.Kleisli]]`.
* Third party library is not exposing `apiURL` in the POM, or is doing so incorrectly.
* This prevents SBT from automatically configuring the URLs for linking into the third party Scaladoc.
* To solve this issue `ScaladocApiMapping` was added in `project/`. This contains manual code to construct the linking,
using `https://javadoc.io` if the project does not provide another more specific URL.
* Overloaded references
* These are …

Fixup Most Of The ScalaDoc Issues

---

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
project/ScaladocApiMapping.scala

This commit makes two meaningful changes,
* Allow for the user to provide their own `HttpConfiguration` value. This is important as there are many settings which are not modeled in the `JettyBuilder` that one would general expect to have access to.
* Enforces that the `HttpConfiguration` is used whether or not http2 is enabled. Formerly the `HttpConfiguration` was only used if there was not an `SslConnectionFactory` and http2 support was enabled.

Allow For Providing HttpConfiguration With Jetty

---

server/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala

As requested by (and effectively written by) @nigredo-tori (https://github.com/http4s/http4s/pull/3977#discussion_r540608488)

Add `Resource` Based Middlewares To `BracketRequestResponse`.

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/package.scala

This commit attempts to normalize some of the common server configuration parameters between backends.
When switching between different backends, one would assume that the operational semantics would be as close as possible, assuming there was no direct configuration change in user code. Prior to this commit there was a substantial delta between these parameters in Blaze/Jetty/Ember.
It is likely that _more_ parameters can be shared in the future, but some configuration options are not exposed for any give backend, and some things which are configurable on one backend may not even be expressible on another.
Thus, this commit attempts to be relatively conservative, synchronizing the more obvious parameters only.
When two backends currently differed on the configuration value for a given …

Normalize Some Of The HTTP Server Parameters Between Backends

---

.github/workflows/ci.yml
build.sbt
core/src/main/scala/io/chrisdavenport/unique/Unique.scala
core/src/main/scala/io/chrisdavenport/vault/Key.scala
core/src/main/scala/io/chrisdavenport/vault/Locker.scala
core/src/main/scala/io/chrisdavenport/vault/Vault.scala
project/Http4sPlugin.scala

`core/update` works on Scala 3.0.0-M2.  There are still many compile failures, but we already have dependencies that have left -M1 behind.  Inlined vault just so we can make progress pending its Dotty releases, similar to what we've done on cats-effect-3.
Also has an even more aspirational 3.0.0-M3 target

Onward to Scala 3.0.0-M2

---

core/src/main/scala/org/http4s/ContentCoding.scala
core/src/main/scala/org/http4s/HttpDate.scala
core/src/main/scala/org/http4s/HttpVersion.scala
core/src/main/scala/org/http4s/MediaType.scala
core/src/main/scala/org/http4s/Method.scala
core/src/main/scala/org/http4s/QValue.scala
core/src/main/scala/org/http4s/headers/Accept-Charset.scala
core/src/main/scala/org/http4s/headers/Accept-Encoding.scala
core/src/main/scala/org/http4s/headers/Accept-Language.scala
core/src/main/scala/org/http4s/headers/Accept-Ranges.scala
core/src/main/scala/org/http4s/headers/Accept.scala
core/src/main/scala/org/http4s/headers/Content-Type.scala
core/src/main/scala/org/http4s/headers/Cookie.scala
core/src/main/scala/org/http4s/headers/Date.scala
core/src/main/scala/org/http4s/headers/ETag.scala
core/src/main/scala/org/http4s/headers/Expires.scala
core/src/main/scala/org/http4s/headers/If-Modified-Since.scala
core/src/main/scala/org/http4s/headers/If-Unmodified-Since.scala
core/src/main/scala/org/http4s/headers/Last-Modified.scala
core/src/main/scala/org/http4s/headers/Link.scala
core/src/main/scala/org/http4s/headers/Retry-After.scala
core/src/main/scala/org/http4s/headers/Set-Cookie.scala

@aeons added this helper after a bunch of parsers had already been written, or were in flight.  It gives a more consistent error rendering for our cats-parse parsers.

Use the ParseResult.fromParser helper for errors

---

core/src/main/scala/org/http4s/metrics/MetricsOps.scala
core/src/main/scala/org/http4s/parser/ForwardedHeader.scala

These are compile errors on the Dotty branch and don't hurt anything to clean up now.
Part of #3768.

Add more missing parens on lambdas

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala
circe/src/main/scala/org/http4s/circe/CirceSensitiveDataEntityDecoder.scala
circe/src/test/scala/org/http4s/circe/CirceSensitiveDataEntityDecoderSpec.scala

```scala
/** Derive [[EntityDecoder]] if implicit [[Decoder]] is in the scope without need to explicitly call `jsonOfSensitive`
*
* Note that it varies from [[CirceEntityDecoder]] in that, when failing to decode [[io.circe.Json]] to an `A`,
* the JSON will not be included in the raised [[Exception]]. In the event the JSON includes sensitive data, this trait is,
* arguably, a better choice since it eliminates the risk of logging sensitive data, e.g. due to logging a raised [[Throwable]]
* that includes the sensitive JSON.
*/
```

Add CirceSensitiveDataEntityDecoder

---

.github/workflows/ci.yml
build.sbt
core/src/main/scala/io/chrisdavenport/unique/Unique.scala
project/Http4sPlugin.scala

Restores the unusedCompileDependenciesTest to the CE3 branch.
Went ahead and inlined Unique, whose inclusion in CE3 is presently stalled.  We'll go back to a proper Unique release or inherit it from CE3 before this gets merged.

Restore unusedCompileDependenciesTest, inline Unique

---

client/src/main/scala/org/http4s/client/middleware/Logger.scala
client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
client/src/test/scala/org/http4s/client/middleware/LoggerSuite.scala
core/src/main/scala/org/http4s/internal/Logger.scala

Refactor Logger implementation.
Add customized loggers.
Add colored loggers.
Closes #4019

ResponseLogger constructor overload receiving the response

---

jetty-client/src/main/scala/org/http4s/client/jetty/JettyClient.scala

Without this, https requests fail out of the box.  That's a hostile default.
```
java.lang.NullPointerException: Missing SslContextFactory
at java.util.Objects.requireNonNull(Objects.java:228)
at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.<init>(SslClientConnectionFactory.java:54)
at org.eclipse.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1208)
at org.eclipse.jetty.client.HttpClient.newSslClientConnectionFactory(HttpClient.java:1214)
at org.eclipse.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:149)
at org.eclipse.jetty.client.HttpDestination.newSslClientConnectionFactory(HttpDestination.java:155)
at org.eclipse.jetty.client.HttpDestination.<init>(HttpDestination.java:95)
at …
```

Provide an SslContextFactory to jetty-client

---

core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala

Add an explicit instance to allow access to the mixed multipart decoder.
Referencing this discussion: https://gitter.im/http4s/http4s?at=5fecd60de7f693041f3efd9c

Mixed multipart decoder -> series 0.21

---

core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala

Necessary for binary compatibility.

Restore defaults on MuliptartDecoder.mixedMultipart

---

core/src/main/scala/org/http4s/MediaType.scala
core/src/main/scala/org/http4s/QValue.scala
core/src/main/scala/org/http4s/Uri.scala

This doesn't prevent using the macros (see #4078 for discussion of their future).  This sets us up to move them somewhere less burdensome, or remove them entirely, for 1.0.
We don't want imports `scala.reflect.macros` outside the scala-2 directory.

Deprecate macros on companions

---

build.sbt

Alternative to #4067.  We just simply filter the `@nowarn` annotation out of the jar.
Pros:
- No new core dependencies
- Preserves fatal warnings without further complexity
Cons:
- Compat trait will need to be copied to a scala-3 directory on the Dotty branch.
- Doesn't steer our source toward modernity.
- MiMa doesn't catch that the annotations are missing. But we'll note it and move on, and it's 2.12 only.

Filter nowarn annotation from jar

---

core/src/main/scala/org/http4s/headers/ETag.scala
core/src/main/scala/org/http4s/parser/AdditionalRules.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

Introduced new ADT for `ETag` weakness param.
Fixes #3956

Fixed boolean blindness of `EntityTag`'s weakness indicator

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerMtlsSpec.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSuite.scala

Partially addresses #4134 for blaze-server

Create Dispatcher within BlazeServerBuilder

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala

This is (hopefully) the solution to the notorious bug that has plagued the reputation of blaze-client in the past several years (#2278). I could do a longer write up here, but essentially the bug is a race condition that manifests as an interaction between channel writes and connection pooling. 
The offending line of code is here (https://github.com/http4s/http4s/blob/cats-effect-3/blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala#L181). What's happening here is that connection starts a fiber that writes to the underlying NIO channel, while concurrently starting to read from the same channel. Each connection maintains a state machine that reflects whether the connection is idle or active. The state machine is reset to `Idle` after the streaming read of the response …

blaze-client WritePendingException fix

---

build.sbt
project/Http4sPlugin.scala

I meant to pick up async-http-client-2.12.2, but we blocked that for binary compatibility.  And http4s is only used in MimeDb.  This is a thoroughly uninteresting PR, but it will make the next bumps smaller. :shrug:

http4s-0.21.15, filter ahc-2.12.2

---

blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSuite.scala
testing/src/test/scala/org/http4s/Http4sSuite.scala

I'm wondering if we should use the same `Http4sSpec.TestIORuntime` in all tests / suites.

Use test io runtime in munit

---

blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSuite.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala
testing/src/test/scala/org/http4s/testing/DispatcherIOFixture.scala

following https://github.com/http4s/http4s/pull/4160, try if using `ResourceFixture(Dispatcher[IO])` is better than the current approach.

use ResourceFixture(Dispatcher[IO])

---

testing/src/test/scala/org/http4s/Http4sSpec.scala

Fix https://github.com/http4s/http4s/issues/4058
Follow up on https://github.com/http4s/http4s/pull/4173
Now that there is no unnecessary blocking, we can revert the changes made in https://github.com/http4s/http4s/pull/3857

back to small daemon pool for computation

---

blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientBase.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSuite.scala
client/src/test/scala/org/http4s/client/JettyScaffold.scala
core/src/main/scala/org/http4s/StaticFile.scala
tests/src/test/scala/org/http4s/EntityDecoderSuite.scala

Those places were found by running the tests with a compute thread pool of 2 threads.
In theory, we should be able to run all the tests on only one thread, but some blocking places are quite difficult to get rid of for now.

use blocking where necessary to use the right thread pool

---

testing/src/test/scala/org/http4s/Http4sSuite.scala

To look for blocking code, one can setup the excecution context used by http4s to a minimal number of thread (`Http4sSpec.TestExecutionContext`).
As munit is using the same execution context, it is difficult to find out which code is blocking as munit is always blocking on one thread.
By using a different thread pool for munit, this investigation is much easier.

use a different EC for munit

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
core/src/main/scala/org/http4s/Uri.scala
ember-core/src/main/scala/org/http4s/ember/core/Encoder.scala
ember-core/src/test/scala/org/http4s/ember/core/EncoderSpec.scala
ember-core/src/test/scala/org/http4s/ember/core/EncoderSuite.scala
tests/src/test/scala/org/http4s/UriSuite.scala

Before this, Ember was sending requests in absolute-form.  This is legal, but it's also unusual unless going through a proxy, and not all servers support it. even though they "MUST".
Refactored blaze to use the same mechanism.
The absolute form is also giving an ember-server [a hard time on series/0.22](https://github.com/http4s/http4s/runs/1715619314#step:11:3860).

Render request URIs in origin form

---

build.sbt
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSuite.scala

Fix https://github.com/http4s/http4s/issues/4092

port tomcat to CE3

---

project/Http4sPlugin.scala

M11 had an empty jar for Scala 3.0.0-M3.

Upgrade to vault-2.1.0-M14

---

tests/src/test/scala/org/http4s/EntityDecoderSuite.scala
tests/src/test/scala/org/http4s/FormDataDecoderSpec.scala
tests/src/test/scala/org/http4s/Ipv4AddressSpec.scala
tests/src/test/scala/org/http4s/Ipv6AddressSpec.scala
tests/src/test/scala/org/http4s/MediaTypeSpec.scala
tests/src/test/scala/org/http4s/QValueSpec.scala
tests/src/test/scala/org/http4s/UriSpec.scala
tests/src/test/scala/org/http4s/UrlFormSpec.scala
tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

* Use illTyped macro instead of typecheck
* parameters around lambdas
* add types to implicits
* Remove cats Eq typeclass to avoid multiple syntax implicits

Changes to make core tests compile on Scala 3

---

docs/src/main/mdoc/client.md
docs/src/main/mdoc/service.md
docs/src/main/mdoc/static.md
project/Http4sPlugin.scala
website/src/hugo/content/contributing.md
website/src/hugo/themes/http4s.org/layouts/shortcodes/version.html

This PR removes the final lingering mentions of `tut` and updates them to link to mdoc.

Link to mdoc and final cleanup of tut references

---

ember-core/src/test/scala/org/http4s/ember/core/EncoderSuite.scala

Added this test while mulling over what to do with a request that has a relative URI.  It's not that exciting, but I didn't want to throw it away.

Ember req host test

---

project/Http4sPlugin.scala
prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/util.scala

Prometheus is changing the naming scheme of some of their metrics in order to be compatible with the OpenMetrics standard. Part of this means that all counters will have `_total` or `_created` as a suffix. There is no way to create a counter without a `_total` suffix.
See: https://github.com/prometheus/client_java/pull/615

Update Prometheus Client To 0.10.0 And Fix Tests

---

build.sbt
ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
ember-server/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala

Ember startup backpressure

---

ember-client/src/main/scala/org/http4s/ember/client/EmberClient.scala
ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-client/src/test/scala/org/http4s/ember/client/internal/ClientHelpersSpec.scala
project/Http4sPlugin.scala

Includes upgrade to keypool-0.3.0-RC1.

ember-client on 3.0.0-M2 (with Typelevel keypool)

---

server/src/test/scala/org/http4s/server/middleware/DateSpec.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSuite.scala

This plus #4289 plus #4290 makes server tests pass on 3.0.0-M2.

Server tests on Scala 3.0.0-M2

---

blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientBase.scala
blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala
blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSuite.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
ember-server/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
jetty/src/test/scala/org/http4s/server/jetty/JettyServerSuite.scala
project/Http4sPlugin.scala
prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusClientMetricsSuite.scala
prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusServerMetricsSuite.scala
servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
testing/src/test/scala/org/http4s/Http4sSuite.scala
tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSuite.scala

Upgrade to munit-cats-effect 0.13.0 so we get a saner default execution context. Slight tangent, it was discovered awhile back that `ResourceFixture` wasn't referentially transparent, so we had to wrap in `SyncIO`, which is forcing us to delete some type annotations here. We also don't make heavy use of `map2` but that would've necessitated some fixes too

Upgrade munit-cats-effect to 0.13.0 and enable some ember-server tests

---

core/src/main/scala/org/http4s/Uri.scala

use oneof instead of cascading, memoize uri parser construction

chipping away at the perf regression

---

core/src/main/scala-2.12/org/http4s/internal/CollectionCompat.scala
core/src/main/scala-2.13/org/http4s/internal/CollectionCompat.scala
core/src/main/scala/org/http4s/Query.scala

Discovered while working on https://github.com/http4s/http4s/pull/4304 we can inline `pairsToMultiParams` to reduce `CollectionCompat` a bit.

Inline pairsToMultiParams from CollectionCompat

---

core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/headers/Content-Location.scala
core/src/main/scala/org/http4s/headers/Forwarded.scala
core/src/main/scala/org/http4s/headers/Host.scala
core/src/main/scala/org/http4s/headers/Link.scala
core/src/main/scala/org/http4s/headers/Location.scala
core/src/main/scala/org/http4s/headers/Origin.scala
core/src/main/scala/org/http4s/headers/Referer.scala
core/src/main/scala/org/http4s/headers/X-Forwarded-For.scala
tests/src/test/scala/org/http4s/parser/UriParserSpec.scala

seems that it is super easy to accidentally introduce an initializiation cycle in the uri parsers.
so this is a request for comments wether the uri parsers should live in there own dedicated object so that issues with hangs or nullpointers are gone

Fix parser cycles

---

build.sbt

All supported versions of Scala now support the `@nowarn` annotation, so we no longer need this build plugin to set up silencer.
The annotation must remain for bincopmat reasons, but is cleaned up in #4239.

Drop the NowarnCompatPlugin

---

tests/src/test/scala/org/http4s/HttpDateSuite.scala

This is kind of a wild guess attempt to fix https://github.com/http4s/http4s/issues/4341
All I've done is change this test to match the existing one in HttpDateSpec which does not have the "extra" `IO.map` call:
https://github.com/http4s/http4s/blob/79c78d164b1d05e812a10bc10f4160f89b2d8ef5/tests/src/test/scala/org/http4s/HttpDateSpec.scala#L27

Match HttpDateSuite current test with HttpDateSpec

---

scalatags/src/main/scala/org/http4s/scalatags/ScalatagsInstances.scala

This is necessary to render fragments with `Frag` annotations.

Make scalatags encoder a bit more generic

---

core/src/main/scala/org/http4s/HeaderKey.scala
core/src/main/scala/org/http4s/Headers.scala

Some quick wins while we get the header working on Dotty:
* `GetT` is vestigial.
* ``get(`Set-Cookie`)`` has been deprecated since 0.16!
~~* The signature of default `unapply` methods changes in Scala 3, and we're not using the one on `HeaderKey` anyway.~~

Header cleanups

---

blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala

Wait for request to be read before gathering it.  Without this, there's a race condition, and sometimes we assert on a partial request.
Fixes #4151.

Fix flaky User-Agent header test

---

core/src/main/scala/org/http4s/multipart/MultipartParser.scala

The FS2 library, by construction, guarantees that the `uncons` does not give, in the result, a non-empty chunk.

FS2 - Remove "elide empty chunks"

---

core/src/main/scala/org/http4s/HttpVersion.scala
core/src/main/scala/org/http4s/Uri.scala
core/src/main/scala/org/http4s/UriTemplate.scala

These only warn on Dotty, but Dotty is right.  They can only match null, and we don't need them.

Advance cleanup of Dotty warnings

---

core/src/main/scala/org/http4s/HeaderKey.scala

This is unused in http4s.  I had forgotten it exists.  And as of #4352, it's gone.  Let's warn others.

Deprecate unused Header.Recurring.GetT

---

project/Http4sPlugin.scala

This version trims some redundant features from blaze-http and brings Dotty support.

Upgrade to blaze-0.15.0-M1

---

build.sbt

The `libraryDependencies` is a nasty hack that I think every Twirl application needs to do, but it does work!
This allows us to keep the module compiling until The Great Schism.  @SethTisue has expressed optimism about an eventual Dotty release, and I don't think there's a better alternative in this space.  I'd like to save it from the burn pile for now.
We won't publish it for Dotty until we can remove the `withDottyCompat`.

Test, but don't publish, Twirl in withDottyCompat

---

build.sbt

There is no Scalatags release for Dotty. It works in compat mode, which lets us keep it part of the build until there is a Dotty release.

Scalatags testing, without publishing, for Dotty

---

examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/endpoints/JsonXmlHttpEndpoint.scala
examples/src/main/scala/com/example/http4s/ExampleService.scala
scala-xml/src/main/scala/scalaxml/implicits.scala
scala-xml/src/main/scala/scalaxml/instances/AllInstances.scala
scala-xml/src/main/scala/scalaxml/instances/ElemInstances.scala
scala-xml/src/main/scala/scalaxml/instances/package.scala
scala-xml/src/main/scala/scalaxml/package.scala
scala-xml/src/test/scala/scalaxml/ScalaXmlSuite.scala

Inheriting from package objects is on the way out in Scala 3, after being briefly deprecated in Scala 2.13.  It also causes problems with sbt's incremental compiler.
It's extensible as a codec project grows, and Cats users should feel at home.  It also feels quite overengineered.
The net effect is former importers of
```scala
import org.http4s.scalaxml._
```
would now need to do:
```scala
import org.http4s.scalaxml.instances.all._
```
or 
```scala
import org.http4s.scalaxml.instances.elem._ // a la carte
```
or
```scala
import org.http4s.scalaxml.implicits._
```
The choice is bad and the verbosity is bad and the boilerplate in the code is bad but the futureproofing is good and the consistency with upstream is good.
Discuss.

Package object disinheritance for scala-xml

---

build.sbt
play-json/src/main/scala/org/http4s/play/Parser.scala
play-json/src/main/scala/org/http4s/play/PlayInstances.scala
play-json/src/test/scala/org/http4s/play/PlaySuite.scala
project/Http4sPlugin.scala

Had to copy the jawn facade, which is published withDottyCompat.  This could be resolved with https://github.com/typelevel/jawn/issues/312.
Needing to dance around withDottyCompat was the breaking point for me on a couple other JSON libraries, but the play-json team delivered a working Dotty release on request, and it has an active open source dependency.

http4s-play-json on Dotty

---

build.sbt

There is no Boopickle release for Dotty (https://github.com/suzaku-io/boopickle/issues/148), and we can't yet compile it withDottyCompat because of its macro.  This can keep the project alive until the Great Schism of this repo.

Skip Boopickle in Dotty

---

tests/src/test/scala/org/http4s/headers/RefererSuite.scala
tests/src/test/scala/org/http4s/parser/LocationHeaderSuite.scala
tests/src/test/scala/org/http4s/parser/OriginHeaderSuite.scala

HeaderKey#HeaderT values needs to be own vals for Scala 3 to be able 
type them correctly.

HeaderTests now compile on Scala 3

---

core/src/main/scala/org/http4s/EntityEncoder.scala

Probably an oversight from https://github.com/http4s/http4s/commit/2635573b43975dd4fb4a7b66efeeca978d220381

Lower constraint for EntityEncoder#fileEncoder from Effect to Sync

---

argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
argonaut/src/main/scala/org/http4s/argonaut/Parser.scala
argonaut/src/test/scala/org/http4s/argonaut/ArgonautSuite.scala

Argonaut support has required burdensome build hacks over the years, and is again causing problems by publishing its Dotty version using withDottyCompat on its dependencies, rendering us unable to compile with or without Dotty compat.
http4s-argonaut's usage is estimated to be less than 5% of http4s-circe's, and Circe is the recommendation of the http4s team.
If no volunteer steps up by February 13 to fix and maintain this module, we will proceed with this deprecation and removal from series/0.22 and main.

Deprecate http4s-argonaut

---

json4s-jackson/src/test/scala/org/http4s/json4s/jackson/Json4sJacksonSuite.scala
json4s-native/src/test/scala/org/http4s/json4s/native/Json4sNativeSuite.scala
json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
json4s/src/test/scala/org/http4s/json4s/Json4sSuite.scala

There is no public momentum toward a json4s port on Dotty.  `jawn-json4s` in Dotty compat mode conflicts with the Dotty `jawn-fs2`, so there is no way to nurse it along in 0.22 without copying code.  The interest is estimated less than 5% of http4s-circe.  The http4s team recommends Circe for JSON.
If no volunteer steps up by February 13 to fix and maintain the http4s-json4s modules, we will proceed with this deprecation and removal from series/0.22 and main.
If a new maintainer does emerge for these module, note that the plan is to spin them off into their own repo: #4140

Deprecate http4s-json4s

---

client/src/main/scala/org/http4s/client/middleware/GZip.scala
client/src/test/scala/org/http4s/client/middleware/GZipSuite.scala

When the gzip middleware decompresses a response, these headers are no
longer correct, so it seems best to remove them. This is crucial when
the client is used as a proxy (or, in my case, as an STTP backend) to
prevent downstream consumers attempting to decompress the response
again.
This change was previously introduced here: https://github.com/http4s/http4s/pull/2673#discussion_r298684594 but was removed in this PR: https://github.com/http4s/http4s/pull/3476

Remove `Content-Length` and `Content-Encoding` when decompressing

---

testing/src/test/scala/org/http4s/Http4sSuite.scala

fixes the failing main build: https://github.com/http4s/http4s/runs/1898542059

align thread name with 0.22

---

blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala

The method `Stream.evalMap` creates a singleton chunk for each element of the input chunk that is written.
There is no need to keep those `Chunk[Unit]`. Using the Pull interface, we can just do the action and continue iterating, without leaving any garbage behind.

Blaze-Core: optimise entity body writer

---

build.sbt
project/Http4sPlugin.scala

There are no `IO` dependencies except in tests. This will enable a cleaner classpath for Monix users.

core only depends on cats-effect-std

---

NOTICE
project/Http4sPlugin.scala

* Reorders the attributed sources
* Removes some that no longer exist
* Removes license notices for projects whose code is no longer bundled
Many thanks to Specs2, which served us well for many years.

Cleanup some attributions

---

.github/workflows/ci.yml
build.sbt
project/Http4sPlugin.scala
project/plugins.sbt
scalafix/build.sbt
scalafix/project/build.properties
scalafix/project/plugins.sbt

looking for some feedback, this is a bit of a change in the setup for scalafix.
it's modeled after what cats and [cats-effect](https://github.com/typelevel/cats-effect/pull/1686/files)
this disables the publishing but the scalafix can still be run via `sbt ";scalafixEnable ;scalafixAll github:http4s/http4s/series/0.22"` but would enable any dotty plans

cleanup scalafix build

---

blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketSupport.scala

Dotty RC1 required a stable val.  I don't like eager abstract vals in traits, but the tests passed.

Change WebSocketSupport#F from a def to a val

---

core/src/main/scala/org/http4s/ContextRoutes.scala
core/src/main/scala/org/http4s/HttpRoutes.scala

Defer is no longer in Sync hierarchy. This is definitely correct for any F that has Concurrent, but will work fine in most cases that are actually used without a messy api.

Fix Routes Constraint

---

docs/src/hugo/config.toml
website/src/hugo/content/contributing.md

When trying to run website/docs site locally with latest hugo, site is broken. Users noticed this already [three years ago](https://gitter.im/http4s/http4s?at=5af21a03b37eab7d04797c45).
I'm not sure if there are any plans to migrate docs/website to the latest hugo version, but hopefully this description will save time in figuring out that latest version of hugo is not supported.

Add 'Running site locally' section into Contributing guide

---

core/src/main/scala/org/http4s/syntax/HeaderSyntax.scala
tests/src/test/scala/org/http4s/headers/AcceptCharsetSuite.scala
tests/src/test/scala/org/http4s/headers/AcceptHeaderSuite.scala
tests/src/test/scala/org/http4s/headers/AcceptPatchSuite.scala
tests/src/test/scala/org/http4s/headers/AccessControlAllowHeadersSpec.scala
tests/src/test/scala/org/http4s/headers/AccessControlExposeHeadersSpec.scala
tests/src/test/scala/org/http4s/headers/ExpiresSuite.scala
tests/src/test/scala/org/http4s/headers/HeaderLaws.scala
tests/src/test/scala/org/http4s/headers/TransferEncodingSuite.scala

Existing header laws can be changed to use new one by replacing
parentheses, for example
```
checkAll("Expires", headerLaws(Expires))
```
to
```
checkAll("Expires", headerLaws[Expires])
```
partially addresses #4535

Port headerLaws to use Header typeclass

---

blaze-core/src/test/scala/org/http4s/blazecore/ResponseParser.scala
blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala
tests/src/test/scala/org/http4s/HeaderSuite.scala

Remove deprecation warnings from
- `ResponseParser.scala`
- `Http1ServerStageSpec.scala`
- `HeaderSuite.scala`
looks like after this it's only the headers and their own test + `HttpHeaderParser`
btw, sorry for too many small PRs!

Migrate more header

---

core/src/main/scala/org/http4s/Headers.scala
core/src/main/scala/org/http4s/headers/Referer.scala
core/src/main/scala/org/http4s/headers/Retry-After.scala
core/src/main/scala/org/http4s/headers/Server.scala
core/src/main/scala/org/http4s/headers/Set-Cookie.scala
core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
tests/src/test/scala/org/http4s/headers/RefererSuite.scala
tests/src/test/scala/org/http4s/headers/RetryAfterSuite.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

There was custom extractor on `Set-Cookie` header which is removed in this PR. It wasn't covered by test, so I'm not sure how much important it was.
It was removed since it depends on `matchHeader` from old `HeaderKey`.
Partially addresses #4535

Header migration

---

core/src/main/scala/org/http4s/headers/Accept-Charset.scala
core/src/main/scala/org/http4s/headers/Accept.scala
core/src/main/scala/org/http4s/headers/Access-Control-Allow-Headers.scala
core/src/main/scala/org/http4s/headers/Forwarded.scala
core/src/main/scala/org/http4s/headers/Transfer-Encoding.scala
core/src/main/scala/org/http4s/headers/User-Agent.scala
core/src/main/scala/org/http4s/headers/WWW-Authenticate.scala
core/src/main/scala/org/http4s/headers/X-B3-Flags.scala
core/src/main/scala/org/http4s/headers/X-B3-Sampled.scala
core/src/main/scala/org/http4s/headers/X-B3-TraceId.scala
core/src/main/scala/org/http4s/headers/X-Forwarded-For.scala
server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
tests/src/test/scala/org/http4s/headers/StrictTransportSecuritySuite.scala
tests/src/test/scala/org/http4s/headers/TransferEncodingSuite.scala
tests/src/test/scala/org/http4s/headers/ZipkinHeaderSuite.scala
tests/src/test/scala/org/http4s/parser/AcceptHeaderSpec.scala
tests/src/test/scala/org/http4s/parser/AcceptLanguageSuite.scala
tests/src/test/scala/org/http4s/parser/CacheControlSpec.scala
tests/src/test/scala/org/http4s/parser/ContentLanguageSpec.scala
tests/src/test/scala/org/http4s/parser/HeaderParserHelper.scala
tests/src/test/scala/org/http4s/parser/ProxyAuthenticateHeaderSuite.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
tests/src/test/scala/org/http4s/parser/WwwAuthenticateHeaderSpec.scala
tests/src/test/scala/org/http4s/parser/WwwAuthenticateHeaderSuite.scala

Removing temporal functionality (which was replaced by header syntax) and making header more consistent.

Header migration cleanup

---

boopickle/src/main/scala/org/http4s/booPickle/implicits.scala
boopickle/src/main/scala/org/http4s/booPickle/instances/AllInstances.scala
boopickle/src/main/scala/org/http4s/booPickle/instances/BooPickleInstances.scala
boopickle/src/main/scala/org/http4s/booPickle/instances/package.scala
boopickle/src/test/scala/org/http4s/booPickle/BoopickleSuite.scala

I'm not sure if there is a ticket for that
The other package objects with inheritance I could found are:
/play-json/src/main/scala/org/http4s/play/package.scala
/jawn/src/main/scala/org/http4s/jawn/package.scala
/circe/src/main/scala/org/http4s/circe/package.scala
/http4s/scalatags/src/main/scala/org/http4s/scalatags/package.scala
/http4s/twirl/src/main/scala/org/http4s/twirl/package.scala
If these changes are ok, I can proceed with other files as well- but probably not today ;)

removing inheritance from package object - booPickle

---

docs/src/main/mdoc/entity.md

Old scalatags link returns 404.

Fix scalatags link

---

client/src/test/scala/org/http4s/client/PoolManagerSuite.scala
core/src/main/scala-2/org/http4s/LiteralSyntaxMacros.scala
core/src/main/scala-2/org/http4s/syntax/LiteralsSyntax.scala
core/src/main/scala-3/org/http4s/syntax/LiteralsSyntax.scala
tests/src/test/scala/org/http4s/Ipv4AddressSuite.scala
tests/src/test/scala/org/http4s/Ipv6AddressSuite.scala
tests/src/test/scala/org/http4s/MessageSuite.scala
tests/src/test/scala/org/http4s/UriSpec.scala
tests/src/test/scala/org/http4s/parser/OriginHeaderSuite.scala
tests/src/test/scala/org/http4s/parser/UriParserSuite.scala

Our `ipv4` and `ipv6` clash with ip4s'.
I think this change actually make the ergnomics of the Uri model worse, but so does this conflict.  all the more reason to invest in a good URI interpolator?

Remove our ipv4 and ipv6 literals

---

client/src/main/scala/org/http4s/client/middleware/Retry.scala
client/src/test/scala/org/http4s/client/middleware/RetrySuite.scala
core/src/main/scala/org/http4s/headers/`Idempotency-Key`.scala

Hi, small enhancement for consideration.
At the moment retry middleware is retrying failed requests only if method is idempotent.
Idempotency defined in rfc7231 (https://tools.ietf.org/html/rfc7231#section-4.2.2): as PUT, DELETE and safe methods.
However, it does not say that POST requests can’t be idempotent.
Enhancement is about giving user flexibility to make their requests idempotent by adding to request http header: `Idempotency-Key`. If method is idempotent by definition or if header present allow retrying failed requests.
This is in line with how some public API designed: https://stripe.com/docs/api/idempotent_requests
Moreover, there is a draft RFC to standardise it: https://tools.ietf.org/html/draft-idempotency-header-00#section-2.1

Retry based on Idempotent-Key header.

---

tests/src/test/scala/org/http4s/QueryParamCodecSuite.scala

This is due to bug in JDK8 where round trip conversion fails
on ZonedDateTime with region-based zone and daylight saving time
See https://bugs.openjdk.java.net/browse/JDK-8066982 and
https://bugs.openjdk.java.net/browse/JDK-8183553
Fixes #4615

Disable flaky ZonedDateTime QueryParamCodec spec on JDK8

---

ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

1. On reused connections which have empty buffers we should delay for the full idle period, and not timeout on the shorter header timeout. This addresses that.
2. On the very first connection we should automatically start reading headers.
3. We should be clear what is the cause of our timeouts, perhaps in even more places. This doesn't change the class but changes the message to more clearly indicate the cause of the timeout.

Ember: Idle vs Header Receive Timeouts

---

dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
dsl/src/main/scala/org/http4s/dsl/impl/Responses.scala

The model in 0.22 and 1.0 is changed and Scala does not know how to dispatch to the overloaded apply.
This removes the undispatchable apply method and adds a `headers` constructor.
This should be documented.

Status.headers constructor for dsl

---

server/src/main/scala/org/http4s/server/middleware/Caching.scala

Remove private from no-cache set

---

server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/src/test/scala/org/http4s/server/staticcontent/FileServiceSuite.scala

Exception is `java.nio.file.FileSystemException: Not a directory`.
Found bot queries in Scala Algorithms logs that are leading to an HTTP 5xx error.
To avoid this, we explicitly check if what we are querying is a file, before attempting to resolve the real path; the exception is currently raised in particular where `.toRealPath` is called.
Alternative approach would be to capture the `FileSystemException` as well, but it could hide other errors like `AccessDeniedException`. Because we already do a check, the check for `NoSuchFileException` becomes redundant.
Before changing main code:

FileService: Querying /file.png/anything where /file.png is a file throws

---

project/Http4sPlugin.scala

I don't think the 1.0 of the test libraries are public API anymore, but there's no reason to risk it.  They'll be upgraded in 0.22.

netty-4.1.61.Final, block new test libraries

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Client.scala
blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala

Hi, AFAIK there is currently no way to add custom DNS resolver for blaze-client (similar to one provided in akka-http ([this PR](https://github.com/akka/akka-http/pull/3202) and [here in docs](https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/client-side/client-transport.md#custom-host-name-resolution-transport)).
I kinda need that feature, potential use cases are in linked akkka-http doc.
I added new parameter in `BlazeClientBuilder` - `customDnsResolver` - which is passed to `Http1Support` and if present - used instead of [getAddress](https://github.com/http4s/http4s/blob/e522b34ad9dbf6866a8faddb6e102503ac5822a0/blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala#L137).
I'm glad to adjust/change implementation if it is not suitable.
Also, are changes …

Add custom dns resolver to BlazeClientBuilder.

---

ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

This fixes the issue #4714 by adding the same error handling around the initial `read` as is around the `runApp` such that errors are converted to `Left`s, the stream is ended and the socket closed.

handle errors/close socket in ember server initial req read

---

core/src/main/scala/org/http4s/Query.scala
tests/src/test/scala/org/http4s/UriSpec.scala
tests/src/test/scala/org/http4s/UriSuite.scala

Should make #1813 #3277 and  #3233 work better on 0.22+.
I think this also was done on 0.21 a while ago, must have been lost in the parsing update.
The test failure assumes that we encode the `[]` brackets. this change would then pass them through, since we have allowed them in the parser.

Postpone using Query model until we need it

---

async-http-client/src/main/scala/org/http4s/asynchttpclient/client/AsyncHttpClient.scala
async-http-client/src/main/scala/org/http4s/asynchttpclient/client/AsyncHttpClientStats.scala
async-http-client/src/main/scala/org/http4s/asynchttpclient/client/EmptyBodyGenerator.scala
async-http-client/src/main/scala/org/http4s/asynchttpclient/client/NoOpCookieStore.scala
async-http-client/src/test/scala/org/http4s/asynchttpclient/client/AsyncHttpClientSuite.scala
okhttp-client/src/main/scala/org/http4s/okhttp/client/OkHttpBuilder.scala
okhttp-client/src/test/scala/org/http4s/okhttp/client/OkHttpClientSuite.scala
scalafix/build.sbt
scalafix/input/src/main/scala/fix/RewritePackagesTests.scala
scalafix/output/src/main/scala/fix/RewritePackagesTests.scala
scalafix/rules/src/main/scala/fix/RewritePackages.scala

Part of #2702.
Depends on #4748 being merged first.

Move asynchttpclient client package

---

blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala

Warning is from #2735, but the underlying issue is fixed.

Remove obsolete comment about deadlock

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala

I've got a use case in which I need my HTTP server (implemented with http4s-blaze-server) to process lots of lightweight requests (small request body, small response body, cheap business logic). The thoughput in that case is determined mainly by the http4s-blaze-server.
My main observations regarding performance of http4s-blaze-server in such case are:
- http4s is the dominant consumer of CPU time (roughly 10% CPU time goes to actual application logic)
- the application is unable to fully utilise processing power of a multicore CPU. For benchmarking I'm using Ryzen 5600X - 6 cores 12 threads CPU. On that platform it's utilising only 50% of CPU, despite having 13 blaze selector threads and 12 thread in the main ExecutorContext / ContextShift.
- There's high allocation rate, with the …

Avoid lock contention

---

blaze-client/src/main/scala/org/http4s/client/blaze/BasicManager.scala
blaze-client/src/main/scala/org/http4s/client/blaze/ConnectionManager.scala
blaze-client/src/main/scala/org/http4s/client/blaze/PoolManager.scala
blaze-client/src/test/scala/org/http4s/client/blaze/PoolManagerSuite.scala
client/src/main/scala/org/http4s/client/package.scala

Resolves #4712.
The second commit in this PR might be controversial. I made all of the moved classes private, including some of the classes extending exceptions. I'd like some opinions on this.
Furthermore, I just dropped the `WaitQueueTimeoutException` class in `package.scala` under `client`. It is used by the `Retry` middleware. Not sure if it needs to be in a separate file.

Move ConnectionManager to blaze-client

---

README.md
build.sbt
project/Http4sPlugin.scala

Resolves #4707.
Curl output:
```
vasil@vasil-mac ~ % curl -v -k https://localhost:8443/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8443 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher …
```

Update blaze to 0.14.16

---

blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
server/src/main/scala/org/http4s/server/ServerBuilder.scala
server/src/main/scala/org/http4s/server/package.scala
tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala

The implementation for our default `Host` was the following,
```scala
val Host = InetAddress.getLoopbackAddress.getHostAddress
```
Whether the result of this invocation is the canonical IPv4 or IPv6 loopback address is the result of this code in the JRE.
```java
class InetAddressImplFactory {
static InetAddressImpl create() {
return InetAddress.loadImpl(isIPv6Supported() ?
"Inet6AddressImpl" : "Inet4AddressImpl");
}
static native boolean isIPv6Supported();
}
```
Where `isIPv6Supported` is some native method.
On standard JREs, this is governed by a set of system properties including `java.net.preferIPv6Addresses`. For example,
```shell
> scala
Welcome to Scala 2.13.4-20201218-225751-unknown (OpenJDK 64-Bit Server VM, Java 16).
Type in expressions for evaluation. Or try :help.
scala> …
```

Make Use Of IPv4 Or IPv6 In Defaults Explicit

---

jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyLifeCycle.scala
jetty/src/main/scala/org/http4s/server/jetty/JettyThreadPools.scala
jetty/src/main/scala/org/http4s/server/jetty/LazyThreadPool.scala
jetty/src/main/scala/org/http4s/server/jetty/UndestroyableThreadPool.scala

We had a resource leak in Jetty due to us not calling `.destroy` in the `def resource` after the server terminated. Fixing this leak was a bit complicated.
By default, Jetty will terminate the provided `ThreadPool` as part of the resource cleanup in `.destroy`. Since we were sharing the `ThreadPool` in the builder, this would cause any new invocations of `def resource` to fail as the underlying `ThreadPool` will have now been terminated.
To fix this problem we now use a `Resource[F, ThreadPool]` which will ensure that we get a fresh `ThreadPool` on each invocation, as well as ensuring proper shutdown semantics. We have to keep around the old `ThreadPool` for binary compatibility. In order to avoid starting _two_ `ThreadPool` instances we introduce a `LazyThreadPool` which _should_ never …

Fix Resource Leak In Jetty

---

blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala

This is fix for one (half) of the issues I mentioned in #4761
So it's the same application use-case, but I'll sketch the background one again to highlight the aspects that are important for this specific issue
We have an http4s-blaze-client calling an http4s-blaze-server. These normally run as separate processes on separate machines, but in the process of reproducing this issue I'm running both in one JVM. Requests sent by the client have unique identifiers. There is no retry logic. The same request is never sent twice. The server fails loud when it receives a second request with the same identifier. Detection of such case is not guaranteed but when it happens it's clean and unambiguous. The whole solution worked since years without any duplicates, until we replaced akka-remote …

Reset idle timeout when request is received by blaze-server

---

blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala

This PR fixes #4809. It depends on the #4810.
blaze-client currently has a retry logic which attempts to rerun a request on a new connection if previous attempt was done on a reused connection and it failed with EOF. 
My understanding is that the intention behind that retry was to handle the scenario in which the connection as been closed while it was sitting the the connection pool, but we only learn about it once we start reading from it. #4810 proposes a better solution to that problem (by detecting that the connection is closed, before we even borrow it from the pool). 
The current retry logic is dangerous, because it either assumes that:
1. EOF in reused connection implies the connection was closed before we sent the request
2.  or that the request can be safely sent twice
Point 1. …

Remove retry from blaze client

---

core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/ResponseCookie.scala
tests/src/test/scala/org/http4s/ResponderSpec.scala

Because `putHeaders` deduplicates, calling `removeCookie` repeatedly will remove the first one.

Remove multiple cookies

---

docs/src/main/mdoc/client.md
docs/src/main/mdoc/cors.md
docs/src/main/mdoc/json.md
docs/src/main/mdoc/streaming.md
project/MimeLoader.scala
scalafix/build.sbt
scalafix/input/src/main/scala/fix/RewritePackagesTests.scala

Part of #2702, Missed changes from #4838 PR

Fixed mdocs from blazeclient repackaging

---

blaze-client/src/test/scala-2.13/org/http4s/client/blaze/BlazeClient213Suite.scala

I usually get the following failures when I run the tests locally.
* `BlazeClient213Suite.behave and not deadlock on failures with parTraverse`
* `BlazeClient213Suite.Blaze Http1Client should behave and not deadlock on failures with parSequence`
fail with `TimeoutException: Future timed out after [30 seconds]`, this PR may fix it.

Fix TimeoutException: Future timed out after [30 seconds] on BlazeClient213Suite testing

---

blaze-client/src/test/scala-2.13/org/http4s/client/blaze/BlazeClient213Suite.scala

These are still eating us, even at the greater timeout.

Reflag flaky blaze client tests as flaky

---

core/src/main/scala/org/http4s/MessageFailure.scala
core/src/main/scala/org/http4s/headers/Content-Type.scala

Fixes an issue found in https://github.com/http4s/http4s/pull/4787#issuecomment-846633626.

Catch Exceptions in ParseResult.fromParser, and fix Content-Type so it doesn't throw

---

blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
blaze-server/src/test/scala/org/http4s/blaze/server/ServerTestRoutes.scala
core/src/main/scala/org/http4s/Header.scala
core/src/main/scala/org/http4s/Headers.scala
core/src/main/scala/org/http4s/headers/User-Agent.scala
core/src/main/scala/org/http4s/syntax/HeaderSyntax.scala
core/src/main/scala/org/http4s/util/Renderable.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala
tests/src/test/scala/org/http4s/headers/ForwardedRenderersSuite.scala
tests/src/test/scala/org/http4s/headers/HeaderLaws.scala
tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

Some enhancements needed to help enable Rho support. 
See: https://github.com/http4s/rho/pull/501 for some usage example.
I could use feedback on these, once I get buy in I'll happily add/fixup the unit tests!
Resolves https://github.com/http4s/http4s/issues/4706

Adding Header.Select fromSafe, toRaw multiple, and Aux

---

project/Http4sPlugin.scala

We don't want a final release on a release candidate.  
Closes #4867.  If play-json-2.10.0 appears suddenly, abandon it.

Downgrade to play-json-2.9.2

---

.github/workflows/ci.yml
.mergify.yml
blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala
blaze-core/src/main/scala/org/http4s/blazecore/ResponseHeaderTimeoutStage.scala
build.sbt
core/src/main/scala/org/http4s/multipart/Part.scala
project/Http4sPlugin.scala
project/plugins.sbt
server/src/test/scala/org/http4s/server/middleware/GZipSuite.scala

Bumps `kind-projector` via `sbt-spiewak` via `sbt-http4s-org` which allows us to upgrade scala to 2.13.6.
Also allows us to drop `sbt-dotty`
Closes #4839

Scala 2.13.6

---

ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala

Use `Network[F]` over `forAsync` and use the default `Network[F]` socket group as default for ember client.

Use more idiomatic `Network[F]`

---

build.sbt
ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala

Verify AltSubjName and CN by setting TLSProperties "endpointIdentificationAlgorithm" to "HTTPS"

Ember-Client: Enable endpoint verification by default

---

blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala
project/Http4sPlugin.scala

Can be enhanced by including: https://github.com/http4s/blaze/pull/535

Add try/catch arounds reset timeout so we dont blow up on shutdown

---

blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientBase.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala

The `GetRoutes.getPaths` used to block for 1 second due to `unsafeRunSync` waiting for `timer.sleep(1.second)`. This PR fixes it which should make some tests faster. The difference is most noticeable in `BlazeClient213Suite`.

Avoid sleeping 1 second in tests which don't use the /delay path.

---

core/src/main/scala/org/http4s/Header.scala

Ran into this when while trying to debug why a header parser was throwing an exception on a header it wasn't even intended for. The way it's coded right now, if we try to parse a header from its raw form, it'll parse every preceding header searched as well, even if the name doesn't match. This is definitely a performance hit when headers are queried

Lazy header parse

---

blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala

I *think* this PR fixes a flaky User-Agent test.
Prior to these changes this test repeatedly failed on my system.
Weirdly, metals couldn't find the definition of `BuildInfo`, and `BuildInfo.version` was also 0.15.1 in scope of this test.
(That happens to be the [blaze version number](https://github.com/http4s/http4s/blob/83df69ae4ba56d1062bff9e55722cbc9eb0bc478/project/Http4sPlugin.scala#L286), but I can't figure that out.)
Adding the import meant the test passed each time I ran it.
I've removed the `.flaky`, perhaps that is over confident...

Fix "Insert a User-Agent header" test

---

docs/src/main/mdoc/client.md

This just adds type annotations to the Uri creation in the docs to help when reading what types we're dealing with.  In theory it shouldn't have been a problem but from reading it I thought it was a Path because of 0.21 having `withQueryParam` on the `Path`.
If this is too noisy please just close :)

Type annotations for clearness

---

build.sbt
client/src/main/scala/org/http4s/client/DefaultClient.scala
client/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
core/src/main/scala/org/http4s/Message.scala
project/Http4sPlugin.scala

Fixes #4987 
If an `Accept` header is present on the request, preserve it along with headers from the EntityDecoder.  This preserves the 0.21 behavior.
There's an argument to be made that we should only supply it if it was missing, because the user needs to customize the EntityDecoder (awkward) to get full control over the Accept header otherwise.  But that would be a breaking semantic change not surfaced by the types.
Bonus: add an `addHeader` to `Message`, because it was awkward without.
Bonus bonus: enable doctests in core.  Examples in the docs are good, and we should be doing more of this.

Append, not replace, Accept header in client methods

---

core/src/main/scala/org/http4s/MimeDB.scala

Sneaks in any binary breaking changes before the 0.23 lockdown.

Update MimeDb before 0.23.0

---

core/src/main/scala/org/http4s/EntityDecoder.scala
core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
core/src/main/scala/org/http4s/multipart/MultipartParser.scala
tests/src/test/scala/org/http4s/multipart/MultipartParserSuite.scala
tests/src/test/scala/org/http4s/multipart/MultipartSuite.scala

Fixes #2627.
The behavior and the interface should mostly match the existing mixed multipart parser. The difference is twofold:
1. The main point is that, instead of deleting files manually, this spawns a background fiber with the resource's lifecycle (as a `Resource.use`). Said fiber is managed by the provided `Supervisor`. When the `Supervisor` is closed, the fiber is canceled, at which point the file is deleted. See `superviseResource` for the implementation. This setup is not perfect (e.g. if the main stream fails, the fibers are not released, and the resources are not released until the supervisor is released), but it should be enough for the intended scenario (one-use `EntityDecoder`s).
2. A minor improvement is the addition of a separate parameter controlling chunk size when …

Add file-based multipart decoder with better resource handling

---

website/src/hugo/content/versions.md

- 0.21 is EOL.
- Stop recommending it for Scala 2 users
- 0.22 is stable
- 0.23 will be stable before we merge this

Update version matrix

---

tomcat-server/src/test/scala/org/http4s/tomcat/server/TomcatServerSuite.scala

This test was failing on an unrelated PR, but I could not read what the incorrect value was because we were using `assert` rather than `assertEquals`.

Use `assertEquals` Rather Than `assert`

---

core/src/main/scala-2/org/http4s/MediaTypePlaform.scala
core/src/main/scala-2/org/http4s/UriPlatform.scala
core/src/main/scala-3/org/http4s/MediaTypePlaform.scala
core/src/main/scala/org/http4s/QValue.scala

Deprecating a macro definition doesn't generate a deprecation warning when the macro is called.  We need to deprecate the code the macro expands to.
We eliminated these entirely in 0.23, but it ate somebody at $WORK because the deprecation clock had never started.

Properly deprecate old literals

---

ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala

Fixes #4935
Uses the conservative firefoxy strategy for retrying connections that are dead from the pool.

Add Conservative Retry For Dead Connections

---

core/shared/src/main/scala/org/http4s/headers/Access-Control-Allow-Headers.scala
core/shared/src/main/scala/org/http4s/headers/Access-Control-Expose-Headers.scala
core/shared/src/main/scala/org/http4s/internal/parsing/Rfc7230.scala
core/shared/src/main/scala/org/http4s/util/Renderable.scala
laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
tests/shared/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

Per the [fetch spec](https://fetch.spec.whatwg.org/#http-new-header-syntax), these headers can be empty. Unfortunately I don't think binary compatibility can be preserved.

Allow empty `Access-Control-{Allow, Expose}-Headers`

---

blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala

Fixes #5074 
Explicitly reference correct BuildInfo for Http4s version.
Seems that original import got lost, so, this time I reintroduced it in a more explicit way with meaningful alias.

Print correct http4s version on Blaze startup

---

core/src/main/scala/org/http4s/Uri.scala

This commit adds a method on the companion object of `Host` to create an instance of `Host` from an `ip4s.IpAddress`. It's just a short hand for not having to introspect the underlying ADT constructor.

Add Function To Creat Host From ip4s.IpAddress

---

core/src/main/scala/org/http4s/Message.scala
tests/src/test/scala/org/http4s/MessageSuite.scala

Fixes #5059.
With the global header registry, we used to be able to append two sets of headers and detect which were single and which were recurring from their names.  In the type class model of 0.22, this is no longer possible.  We need to merge the headers from the `EntityEncoder` with the headers already on the message.
Usually the headers are `Content-Type` and `Content-Length`, both of which are single.  Using a merge operation that replaces existing headers fits well here.  We get a change in behavior if the message already has any recurring headers that the `EntityEncoder` tries to add, but it's fair to say anything the `EntityEncoder` cared to specify, it should control.

Replace existing headers in withEntity

---

website/jvm/src/hugo/content/versions.md

Once upon a time many projects cross-built for Scala.js `0.6.x` and `1.x`. We most certainly will not!

Specify Scala.js binary version on website

---

dom-core/src/main/scala/org/http4s/dom/package.scala

This addresses the bug identified in #5090, although the Firefox CI question remains at large.
Explanation is in a code comment.

Fix readable stream cancellation bug for Firefox

---

client/src/main/scala/org/http4s/client/Client.scala
core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/syntax/package.scala
docs/src/main/mdoc/static.md
examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Server.scala
examples/docker/src/main/scala/com/example/http4s/Example.scala
server/src/test/scala/org/http4s/server/middleware/BracketRequestResponseSuite.scala
server/src/test/scala/org/http4s/server/middleware/DateSuite.scala
tests/src/test/scala/org/http4s/syntax/KleisliSyntaxSpec.scala

As discussed in #5062 - by adding these implicits to the companion of one of the type parameters, we remove the need for an import.

Make `Http*` syntax available without an import

---

dom-core/src/main/scala/org/http4s/dom/package.scala

Reworks the patch applied in #5094 to work in all Resource exit cases, not just success.

Check if `ReadableStream` is locked in all exit cases

---

ember-server/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala

When a client closes a web-socket connection abruptly an `IOException` is thrown by the underlying networking libraries.
The error handler in the `WebSocketHelpers` object (`ember-server`) logs an error for every error that occurs, even client errors.
This change aims to remove the noise caused by the logger.
- Unfortunately the error originates from a native method call and all we can do is check the error msg.

ignoring error caused by client abruptly closing connection

---

blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala

In Cats-Effect 3, cancellation applies backpressure on completion of the finalizer.  If a response can't be canceled, the cancellation task does not complete.  Beginning in http4s-0.23, we started running this cancellation token synchronously in `Http1ServerStage`.  The result is that an uncancelable response can lock up the `TickWheelExecutor`'s scheduler thread.  Unhandled scheduled events may continue to pile up until OOM.
This runs cancellation asynchronously, as was done before http4s-0.23.  The test demonstrates that scheduling continues even after the cancellation of an uncancelable request.
Fixes #5116.

Don't block on cancellation in Http1ServerStage

---

.github/workflows/ci.yml
build.sbt

An attempt to solve the Firefox testing problem reported in #5090 while avoiding flakiness by only testing the DOM modules, which are deeply intertwined with browser APIs.

Re-enable Firefox CI, only for DOM modules

---

project/Http4sPlugin.scala

Gets us the monotonic TickWheelExecutor.  This didn't cause #5116, but it theoretically could.

blaze-0.14.18

---

core/shared/src/main/scala/org/http4s/headers/Origin.scala
tests/shared/src/test/scala/org/http4s/parser/OriginHeaderSuite.scala

Resolves #5009.
I've also taken the opportunity to backtify the `null` value for consistency with the rest of the library, to stop parsing empty values as `null` (it's not allowed by the spec), and generally to simplify the parsing implementation.

Update Origin header

---

server/src/main/scala/org/http4s/server/middleware/CORS.scala
server/src/test/scala/org/http4s/server/middleware/CORSSuite.scala

Fix CORS preflight status

---

project/Http4sPlugin.scala

Follow up from #5124, in reaction to the [breaking change](https://github.com/prometheus/client_java/releases/tag/parent-0.12.0).  I think it will be safe for individual projects to upgrade if they so choose, but they should go into the breaking metrics name with eyes wide open.

Block prometheus simpleclient-0.12

---

core/src/main/scala/org/http4s/headers/Origin.scala
tests/src/test/scala/org/http4s/parser/OriginHeaderSuite.scala

We can't fully backport #5082 for binary compatibility reasons, but we can fix the bug where an empty string is treated as the null origin.

Backport empty Origin failure from #5082

---

.github/workflows/ci.yml
build.sbt

I don't think this update is critical to the [reported security vulnerability](https://github.blog/2021-09-08-github-security-update-vulnerabilities-tar-npmcli-arborist/) but can't hurt.

Update setup-node action to v2.4.0

---

blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientState.scala
blaze-client/src/main/scala/org/http4s/blaze/client/ConnectionManager.scala
blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
blaze-client/src/test/scala-2.13/org/http4s/client/blaze/BlazeClient213Suite.scala
blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala

* Exposes some basic metrics on the client pool for monitoring.  Our use case is to see that the wait queue is backing up before it pops.
* Introduces a `ConnectionManager.Stateful`.  The only production implementation, `PoolManager`, is this. 
* Similar to `EmberClient`, though I didn't name the tuple. 
* Less similar to `AsyncHttpClientStats`, because we don't retain an underlying backend object to obtain stats separately

Support monitoring of the blaze-client pool

---

core/src/main/scala/org/http4s/ResponseCookie.scala
tests/src/test/scala/org/http4s/headers/SetCookieHeaderSpec.scala

Allow optional spaces when separating cookie value from directives
According to [rfc-6265](https://datatracker.ietf.org/doc/html/rfc6265#section-2.2) spaces after `;` separating a `set-cookie` directives are optional:
> This specification uses the Augmented Backus-Naur Form (ABNF)
>    notation of [RFC5234].
> 
>    The following core rules are included by reference, as defined in
>    [RFC5234], Appendix B.1: ALPHA (letters), CR (carriage return), CRLF
>    (CR LF), CTLs (controls), DIGIT (decimal 0-9), DQUOTE (double quote),
>    HEXDIG (hexadecimal 0-9/A-F/a-f), LF (line feed), NUL (null octet),
>    OCTET (any 8-bit sequence of data except NUL), SP (space), HTAB
>    (horizontal tab), CHAR (any [USASCII] character), VCHAR (any visible
>    [USASCII] character), and WSP (whitespace).
> …

Allow optional spaces when separating cookie value from directives

---

core/src/main/scala/org/http4s/headers/`Access-Control-Max-Age`.scala
core/src/main/scala/org/http4s/parser/AdditionalRules.scala
tests/src/test/scala/org/http4s/headers/AccessControlMaxAgeSuite.scala

Here it's the changes that introduce management of the header Access-Control-Max-Age.
I'm still missing some parsing internals, but I think it could be a good starting point.
Any feedback will be appreciated :)
The reference issue is #5010

Addition of the Access-Control-Max-Age header

---

website/jvm/src/hugo/themes/http4s.org/layouts/_default/single.html
website/jvm/src/hugo/themes/http4s.org/layouts/partials/nav.html

Bootstrap 5 renamed the `mr-auto` class to `me-auto`. This class applies the `margin-right: auto` rule which has the effect of pushing the remaining elements to the right. Since we're on Bootstrap 5 now, use the new class.
| Current | Proposed |
| - | - |
| <img width="961" alt="image" src="https://user-images.githubusercontent.com/4206232/133856873-3bcaeadc-af47-44c3-90ec-20f21440e7f8.png"> | <img width="990" alt="image" src="https://user-images.githubusercontent.com/4206232/133856883-1f0f8635-98e6-4112-8d9f-c88d1868c1e7.png">

Right align the social icons in the navbar again

---

website/jvm/src/hugo/layouts/partials/edit-button.html
website/jvm/src/hugo/themes/http4s.org/layouts/_default/single.html

There are some floating edit and navigation offcanvas buttons that have stopped floating due to Bootstrap 5 renaming some classes, so I've fixed that. I also rolled in a change that fixes the website edit links. The docs edit links are fine, though.
I also considered updating [this file](https://github.com/http4s/http4s/blob/66e322e1650f424ddd5ffd49ca211b6d9540ba8b/website/jvm/src/hugo/layouts/partials/edit-link.html) but it seems to be unused from what I can tell. Maybe ripping out all of this unused stuff can be its own issue? Or maybe it's not actually unused? (Related: https://github.com/http4s/http4s/pull/5208#issuecomment-922099474)
| Current | Proposed |
| - | - |
| <img width="1017" alt="image" src="https://user-images.githubusercontent.com/4206232/133869844-9d6db379-0cbe-4140-a4c1 …

Fix edit button links and positioning

---

build.sbt
project/Http4sPlugin.scala

This seems to have been preventing mima from finding any previous versions. ~There'll need to be fixes or exclusions before this can actually be merged.~ There were a couple of mima errors but they seem to be safe to exclude.
I also ran scalafmt by mistake 😐

fix build version

---

bench/src/main/scala/org/http4s/ember/bench/EmberParserBench.scala
build.sbt
ember-core/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala

Looks to improve the expected case performance. 
Most servers will encode their prelude and headers within a single buffer. Presently we do a O(n) lookup for a doublecrlf to separate the header array from the body array. Then we do an O(n) parse over the prelude and body. 
Instead we give ourselves where we will repeat parsing over the buffers O(n) and iterate to do so again. If servers have odd chunking behavior there will be more reused work, but it the default case this will be much more performant. 
To make sure I was being scientific in this approach I created a bench suite to test our parsing timings only. 
```
[info] EmberParserBench.parseRequest     avgt   10  1658.321 ± 74.716  ns/op
[info] EmberParserBench.parseResponse    avgt   10  1080.508 ± 96.766  ns/op
[info] …
```

Improve Ember Parser Performance

---

blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
dom-fetch-client/src/main/scala/org/http4s/dom/FetchClient.scala
dom-fetch-client/src/main/scala/org/http4s/dom/FetchClientBuilder.scala
dom-fetch-client/src/main/scala/org/http4s/dom/FetchOptions.scala
dom-fetch-client/src/main/scala/org/http4s/dom/FetchReferrer.scala
dom-fetch-client/src/test/scala/org/http4s/dom/FetchClientSuite.scala
dom-service-worker-tests/src/test/scala/org/http4s/dom/ServiceWorkerAppSuite.scala

Add timeout capability to `FetchClient` and allow passing all the options present in `RequestInit`.

Add fetch options+timeout to FetchClient.

---

core/src/main/scala/org/http4s/Query.scala

I think it would be good to have optional manual control over percent-encoding, but documenting the existing behaviour is a start.
By the way, what does "modulo the identity of separators" mean?

Expand scaladoc for Query

---

shell.nix

Need this to be able to run `ember-serverJS/test` from a fresh checkout.

Add yarn to the nix-shell

---

server/src/test/scala/org/http4s/server/middleware/CSRFSuite.scala

Seems they must have added a default implementation.

Add override to fix JDK17 build

---

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala

We released the security patches privately, without CI.  I panicked because the tests were failing, but it was due to an inversion in the logic that was ported to the HttpExchange server in 0.23.
I ran the tests locally when releasing, so I'm not sure how this slipped through.  Manual releases are bad.

Fix inverted logic in ClientRouteTestBattery

---

client/shared/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
server-testing/src/test/scala/org/http4s/server/ServerRouteTestBattery.scala

We don't have fatal warnings locally, so I didn't catch this in the security release.

Fix fatal warning on ClientRouteTestBattery

---

ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

Strictness strikes again!
I ran a performance test against Ember Server with the change (after a warmup run)
```
$ hey -n 1000000 -c 50 http://127.0.0.1:8080/
```
Before:
```
Summary:
Total:    58.2501 secs
Slowest:    0.1386 secs
Fastest:    0.0003 secs
Average:    0.0029 secs
Requests/sec:    17167.3672
Total data:    14000000 bytes
Size/request:    14 bytes
Response time histogram:
0.000 [1]    |
0.014 [995073]    |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.028 [3517]    |
0.042 [964]    |
0.056 [313]    |
0.069 [101]    |
0.083 [19]    |
0.097 [7]    |
0.111 [1]    |
0.125 [3]    |
0.139 [1]    |
```
After:
```
Summary:
Total:    56.8599 secs
Slowest:    0.1795 secs
Fastest:    0.0002 secs
Average:    0.0028 secs
Requests/sec:    17587.0752
Total data:    14000000 bytes
Size/request: …
```

Eliminate exception allocation on parser hot path

---

blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
core/src/main/scala/org/http4s/HttpVersion.scala
jetty-client/src/main/scala/org/http4s/jetty/client/JettyClient.scala
jetty-client/src/main/scala/org/http4s/jetty/client/ResponseListener.scala
okhttp-client/src/main/scala/org/http4s/okhttp/client/OkHttpBuilder.scala
server/src/test/scala/org/http4s/server/middleware/VirtualHostSuite.scala
tests/src/test/scala/org/http4s/HttpVersionSuite.scala

* Add constants for `HTTP/0.9` and `HTTP/3`
* Rename `HTTP/2.0` to `HTTP/2`, updating references. This is consistent with the specification and other backends.
* Document each version, linking to their specifications.
* Adds scaladoc and doc tests

Define and link all specified HTTP versions

---

ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala

This is a follow up for #4935 and #5286. To sum it up, there are more IO exceptions from which we can recover and retry idempotent requests.
While the particular conditions I'm trying to observe here are very well-defined within the TCP layer, the various IO syscalls and the Java IO API make it impossible to observe those conditions with any precision. I also don't want to blindly match against any `IOException` because that may catch non-retryable IO errors like connect exceptions, unresolved hosts, etc. We may be able to enumerate those out but it seems risky
So, we have to resort to match against exception messages instead. Unsurprisingly, there is precedent for doing this:
1. https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty …

Ember Client retry reset connection and broken pipe errors

---

project/Http4sPlugin.scala

This is a pretty serious bug for JS. I think this slipped through our suite because all of our tests have `case-insensitive-testing` on the classpath which was correctly defined with the triple `%%%`.

Add missing % to case-insensitive dependency

---

blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
ember-core/src/main/scala/org/http4s/ember/core/Encoder.scala

A user was passing an untrimmed string to `Uri.withPath`.  In 0.22, this will be properly encoded.  In 0.21, it was silently tolerated through 0.21.29 and [GHSA-5vcm-3xc3-w7x3](https://github.com/http4s/http4s/security/advisories/GHSA-5vcm-3xc3-w7x3).
We must prohibit carriage return, newline, and null.  But there's no reason space is worse than other unencoded characters not in the URI alphabet that the weak 0.21 `Uri.withPath` model accepts.  This should not have been a breaking change to users just trying to get patched.

Forbidding space in URI path was overzealous

---

ember-core/src/main/scala/org/http4s/ember/core/EmberException.scala
ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

Today, Ember Server returns a 500 Internal Server Error and closes a connection after any server-related timeout occurs (socket read timeout, idle timeout, write timeout, request header receive timeout). This means that a downstream client who writes a request after the timeout response is returned will immediately see a 500 response. This is inconsistent with several widely used HTTP servers (AWS ALB/ELB, nginx, blaze-server).
This behavior means that a retry needs to be instrumented against a 500 in userspace by downstream users. I think this is poor out-of-the-box experience. We should close the connection immediately without writing any sort of response; most mature clients (blaze, okhttp, jetty) are coded to retry immediately against a closed or reset connection. The client will …

Ember Server immediately close connection on timeout

---

core/src/main/scala/org/http4s/Status.scala

`apply` doesn't validate the status code.

Deprecate Status.apply

---

ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

Should get things green again. Also removes `InterruptedByTimeoutException` following up on https://github.com/http4s/http4s/pull/5330#discussion_r721875680 and to simplify the merge into main.

Fix 0.23 merge

---

core/shared/src/main/scala/org/http4s/HttpVersion.scala

Binary breaking, but nobody should be calling these directly.

Privatize HttpVersion constructors

---

blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
core/shared/src/main/scala/org/http4s/Status.scala
ember-core/src/test/scala/org/http4s/ember/core/ResponseSplittingSuite.scala
laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
tests/shared/src/test/scala/org/http4s/StatusSpec.scala

Follows up on the deprecations initiated in 0.22.6.
Also ports the encoding away from the weird case class with a second parameter list.  It's an exotic Scala feature that we don't need.

Remove custom status reason phrases

---

ember-client/js/src/main/scala/org/http4s/ember/client/internal/ClientHelpersPlatform.scala

Backport from https://github.com/http4s/http4s/pull/5514#discussion_r739475285. H/t @bplommer.

Use Scala 3 cross-compatible `@nowarn`

---

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala

In it's current shape the "POST a chunked body" test sends a request with just one chunk (which may be transferred together with the head of the request). That means that the test provides poor coverage of the implementation of chunked encoding. In order to improve the coverage I changed the request body to contain multiple chunks (implemented similarly to the `/chunked` in the `GetRoutes`).

Send multiple chunks when testing chunked requests

---

core/src/main/scala/org/http4s/Uri.scala
tests/src/test/scala/org/http4s/SegmentEncoderSuite.scala

Adding a `SegmentEncoder` typeclass that works similar to a `QueryParamEncoder` but for `Uri.Path.Segment`
This would make working with newtypes/anyvals and urls a bit easier.
```
case class Foo(value: Long) extends AnyVal
val foo: Foo = ???
val myInt: Int = ???
```
```
myBaseUrl / "bar" / foo.value.toString / myInt.toString
```
```
myBaseUrl / "bar" / foo / myInt
```
- Int, Long, Float, Double, Byte, Boolean?

Uri Path Segment Encoder

---

tests/src/test/scala/org/http4s/multipart/MultipartSuite.scala

It seems to work as expected now in Scala 3.

Don't ignore the `Part.covary` test suite in the `MultipartSuite`

---

tests/src/test/scala/org/http4s/QueryParamCodecSuite.scala

A custom instance is not needed anymore.

Use an instance of `Arbitrary[Year]` from ScalaCheck

---

circe/src/test/scala/org/http4s/circe/CirceSuite.scala
laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
play-json/src/test/scala/org/http4s/play/PlaySuite.scala

A bit richer tests of the `Uri` parsing.

Use `Arbitrary[Uri]` in some tests

---

build.sbt
dsl/src/test/scala/org/http4s/dsl/PathInHttpRoutesSuite.scala

Remove redundant isScala3 from build.sbt

---

tests/src/test/scala/org/http4s/MessageSuite.scala

That tests work well in Scala 3 now.

Don't ignore `covary` tests in the MessageSuite

---

blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala

A small enhancement. Semantics seems preserved.

Use `Bracket` in the `Http1Writer.write`

---

blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala

Use `MonadCancel` in the `Http1Writer.write`

---

core/shared/src/main/scala/org/http4s/StaticFile.scala

This is a small tweak for fixing scalajs linking when using `StaticFile` (when using the `1.0.0` series).
Targeting this PR to series/0.23 so the changes can be synchronized with other branches more easily. 
Because `staticFileKey` is not lazy, scalajs linker will fail to link a project if `StaticFiles` is referenced: 
```
[error] Referring to non-existent class java.io.File
[error]   called from constructor org.http4s.StaticFile$.<init>()void
```
Making it a `lazy val` fixes the linking :) (as long as `fromFile` / `fromResource` / `fromURL` are not called)

(scalajs linking) StaticFile: make staticFileKey a lazy val

---

project/Http4sPlugin.scala
server/shared/src/test/scala/org/http4s/server/middleware/ThrottleSuite.scala

Steward is a bit late for now, so here is CE 3.3.0 (though it doesn't migrate changes of `TestContext` https://github.com/typelevel/fs2/runs/4344942116?check_suite_focus=true).

Update `cats-effect` version to 3.3.0

---

client/shared/src/main/scala/org/http4s/client/Client.scala

MiMa flags this change, so I assume it needs to target 1.x?

relax Client.translate bound on G[_] to MonadCancelThrow

---

build.sbt
project/SiteConfig.scala

Closes #5452. Do we want a backport for 0.22/0.23?
How will looks the landing page: https://www.dropbox.com/s/4d46p7nsbb7mcwj/Screenshot%20from%202021-12-02%2012-56-22.png?dl=0
How will looks the download page in the docs: https://www.dropbox.com/s/65e5jdhh6bx9j0o/Screenshot%20from%202021-12-02%2012-59-47.png?dl=0
The Generated EPUB: https://www.dropbox.com/s/dg5sq5anwb54c0h/http4s-1.0.epub?dl=0

EPUB download of the docs

---

.scala-steward.conf

Unpin `scalatags` in the Steward config

---

.scala-steward.conf
project/Http4sPlugin.scala

It's back on Scala 3, so we can start it on 0.22.

Update discipline to 1.4.0

---

.github/release.yml
.mergify.yml

Trying out some of the ideas in https://github.com/http4s/http4s/issues/5683.
1. A mergify config, to label PRs based on their target branch and also steward PRs. Seems like this is always read from the default branch, but probably won't hurt to repeat it.
2. A GH release config, which will have to be customized for every branch. I hope GH respects that.

Configure mergify & release notes

---

blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala

It turns out these tests I marked with `fail` sometimes pass on CI, leading to build failure.
(https://github.com/http4s/http4s/runs/4498932845?check_suite_focus=true)

Mark the failing tests as flaky because they sometimes pass

---

blaze-core/src/main/scala/org/http4s/blazecore/util/BodylessWriter.scala
blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala
core/shared/src/main/scala/org/http4s/internal/ChunkWriter.scala
prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala
server/shared/src/main/scala/org/http4s/server/middleware/Timeout.scala
server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
server/shared/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
server/shared/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala

I initially planned to fix only `blocker` but ended up checking all outdated params in scaladocs.

Remove some outdated params in scaladocs

---

blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
client/shared/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala
project/plugins.sbt

It turns out that some tests in the `BlazeClientConnectionReuseSuite` ain't failed now, though it was intended by test-suite:
`BlazeClient should reuse the connection after a successful request with large response`;
`BlazeClient should reuse the connection after response decoding failed and the (large) entity was drained`
I marked them as flaky (just because I'm not sure if they are stable enough).
cc @RafalSumislawski

Merge `series/0.22` into `series/0.23`

---

client/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala

The default we currently use takes 2 seconds.

Speed up shutdown of NioEventLoopGroups

---

blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala

Apparently this test is flaky
https://github.com/http4s/http4s/runs/4509815070?check_suite_focus=true#step:13:5144

Mark one more connection reuse test as flaky

---

blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala

This PR make the `Http1ClientStageSuite#getSubmission` method pure by suspending creation of mutable state (`Http1Connection`) in `IO` (and `Resource`).

`Http1ClientStageSuite` purity

---

build.sbt
project/Http4sPlugin.scala
project/plugins.sbt

Also removes the dependency on `server` in `client`, limiting to tests only.

Remove jvm log4cats dependency in ember client js

---

blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/CachingStaticWriter.scala
blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala
client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
core/src/main/scala/org/http4s/ResponseCookie.scala
core/src/main/scala/org/http4s/UriTemplate.scala
core/src/main/scala/org/http4s/internal/parsing/Rfc3986.scala
core/src/main/scala/org/http4s/multipart/Boundary.scala
core/src/main/scala/org/http4s/websocket/FrameTranscoder.scala
dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
project/Http4sPlugin.scala
project/MimeLoader.scala
server/src/test/scala/org/http4s/server/middleware/HeaderEchoSuite.scala
server/src/test/scala/org/http4s/server/middleware/ThrottleSuite.scala
testing/src/test/scala/org/http4s/Http4sSuite.scala
tests/src/test/scala/org/http4s/HeadersSpec.scala
tests/src/test/scala/org/http4s/headers/ZipkinHeaderSuite.scala
tests/src/test/scala/org/http4s/websocket/WebSocketHandshakeSuite.scala

This brings some micro-optimizations of using collections, such as:
* using the `contains` instead of `exists(_ == foo)`;
* using the `getOrElse(foo, bar)` instead of `get().getOrElse()`;
* using the `find` instead of `filter().headOption()`;
* removing the redundant collections conversions;
* and little others.

Collection micro-opts

---

project/SiteConfig.scala
website/src/hugo/content/default.template.html
website/src/hugo/content/versions.md
website/src/hugo/static/templates/no-page-nav.template.html

Now that [feral](https://github.com/typelevel/feral) is released, we have interesting http4s.js offerings for both browser clients and serverless backends. This sneaks a couple links to feral into the site, as well as teases cross-platform capabilities on the landing page.

Promote http4s.js a bit

---

core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/internal/CurlConverter.scala
tests/src/test/scala/org/http4s/MessageSuite.scala

This makes the output of `asCurl` verbose and adds line breakers. The result of method calls will look like this:
```
curl \
--request GET \
--url 'http://localhost:1234/foo' \
--header 'Cookie: <REDACTED>' \
--header 'Authorization: <REDACTED>'
```

Make the output of `asCurl` more human-readable

---

core/src/main/scala/org/http4s/Uri.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
servlet/src/test/scala/org/http4s/servlet/AsyncHttp4sServletSuite.scala
servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
servlet/src/test/scala/org/http4s/servlet/RouterInServletSuite.scala
servlet/src/test/scala/org/http4s/servlet/TestEclipseServer.scala

This is a fix for the #5362 (a regression introduced most likely in #3221). A fix for this issue has already been proposed by @fthomas in #5100 but it got stuck. I followed Franks findings, and @hamnis's suggestion to have a deeper look in order to find the root cause of the issue. So in this PR I propose an alternative way of solving the problem which (at least according to my understanding) deals with the issue at it's origin. 
This PR:
- a320e1f61b57f7fd862649151e191e98d7db5bf9: Adds a test suite verifying behaviour and interactions between `Routes`, `Router` and `contextPath` and `servletPath`.
- 5ae3db5b6d1c7f4102cc8b0d86adb530f1baf630: Removes the fallback to `-1` in case of failure to find split. IMO using the value of `-1` as a fallback is an anti-pattern, that in this case lead …

Path info index fix

---

server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala

This bug is masked in our test suite because of https://github.com/scalameta/munit/issues/437.

Fix FileService Config linking on JS

---

.scala-steward.conf

This is a non-comprehensive collection of dependencies that scala-steward shouldn't update on `main` because the updates will be merged forward from 0.23.

Scala-steward exclusions in `main`

---

ember-client/shared/src/test/scala/org/http4s/ember/client/EmberClientSuite.scala

Opening for CI.
Update:
Fixes https://github.com/http4s/http4s/issues/5256.
I think the real credit for the fix goes to @RafalSumislawski in https://github.com/http4s/http4s/pull/5587.

Re-enable broken ember client test

---

build.sbt

The `lint` command fails when running `scalafixAll` with Scala 3. We get:
> To use Scalafix on Scala 3 projects, you must unset `scalafixBinaryScalaVersion`. Rules such as ExplicitResultTypes requiring the project version to match the Scalafix version are unsupported for the moment.
I suppose It's fine to run the `scalafixAll` only for the base Scala version (which is 2).

Fix the `lint` command

---

build.sbt

I find this is not optimal to use fatal warnings in the CI and not in local development. Users should get feedback as quickly as possible. Newly, I get into that situation on my own.
Also, @ChristopherDavenport pointed about that in #5709.
That is for the `series/0.23` (and not `series/0.22`) for the reason I described in https://github.com/http4s/http4s/pull/5841#issuecomment-1008708190.

Enable fatal warnings in `lint`/`quicklint` commands

---

.scala-steward.conf

Steward exclusions in 0.23 for dependencies merged forward from 0.22

---

flake.lock

Installs a Metals that uses the same JDK as the rest of the project.  I was getting linker errors running tests from Metals without it, because Metals compiled the code with JDK17, and the editor still ran it with JDK8.

Upgrade typelevel-nix to pick up Metals

---

ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerMtlsSuite.scala
ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala

Should fix the `BindException` reported in https://github.com/http4s/http4s/issues/5844#issuecomment-1010403086.
I tried to target this down to 0.22, but the 0 port trick doesn't work there since ember returns its address with the port number that was provided and not the port that was actually bound. Seems like that can be fixed.

Auto-select available port for ember suites

---

blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala

The copy method should use the current value, not a fresh default value.  Without this, the custom DNS resolver will be blanked out by any other `with*` call.

Fix customDnsResolver in BlazeClientBuilder

---

blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
blaze-client/src/main/scala/org/http4s/blaze/client/BlazeConnection.scala
blaze-client/src/main/scala/org/http4s/blaze/client/Connection.scala
blaze-client/src/main/scala/org/http4s/blaze/client/ConnectionBuilder.scala
blaze-client/src/main/scala/org/http4s/blaze/client/ConnectionManager.scala
blaze-client/src/main/scala/org/http4s/blaze/client/Http1Client.scala
blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
blaze-client/src/main/scala/org/http4s/blaze/client/package.scala
blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
build.sbt
client/src/main/scala/org/http4s/client/Connection.scala
client/src/main/scala/org/http4s/client/package.scala

These are blaze-specific types and clutter the Client namespace.
We keep the traits in the blaze package, because some tests use non-`BlazeConnection` implementations.
All the affected types are private, so generous MiMa exceptions are granted.  I'd rather not, but I think the alternative is an avalanche of `@nowarn`.

Deprecate client.Connection and client.ConnectionBuilder

---

async-http-client/src/main/scala/org/http4s/asynchttpclient/AsyncHttpClient.scala

Just cos there is no `ContextShift` anymore.

Remove mentioning of `ContextShift` in the AHC scaladoc

---

jetty-server/src/main/scala/org/http4s/jetty/server/JettyThreadPools.scala

Cos `org.eclipse.jetty.util.thread.ThreadPool#join` is a [blocking operation](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/thread/ThreadPool.html) then it's better to run it on Cats-Effect blocking thread pool.

Use blocking thread pool on joining Jetty's thread pool

---

prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala

`CollectorRegistry.clear`, `CollectorRegistry.register`, `CollectorRegistry.unregister` may block threads so it's better to use blocking thread pool.

Use blocking thread pool in the Prometheus metrics

---

ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala

Adds support for parsing response bodies without a `Content-Length` header to `ember`.
Fixes #5865

Support parsing response bodies without Content-Length in ember

---

client/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala

Pretty sure this should fix the `BindException`s that are proliferating.

Use loopback address for Netty scaffold

---

jetty-client/src/main/scala/org/http4s/jetty/client/JettyClient.scala

`org.eclipse.jetty.util.component.AbstractLifeCycle#stop` uses under the hood synchronized lock, so blocking thread pool is more desired to use.

Use blocking thread pool in the `JettyClient#resource`

---

.github/workflows/ci.yml
build.sbt

I forgot to do this. We don't currently have snapshots for stable branches, do we want this? Personally I like snapshots and they help mitigate infrequent releases 🙃

Enable snapshots for 0.22

---

blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala

Adds an automated retry policy to blaze-client to account for connections that closed while idling in the pool.
This is less flexible than Ember's, mainly because we don't have access to a `Timer`.  Then again, this is the bare minimum suggested by HTTP specs, and we don't need all that power.  Like Ember's, this is a conservative default that only retries idempotent requests.
This, like Ember's default strategy, may interact surprisingly with an explicit retry middleware as the retry policies compose.

Stale connection mitigation in blaze-client

---

build.sbt

`scalafixInternalRules` was omitted from the root aggregate, so CI failed to catch the header issue. Fixes https://github.com/http4s/http4s/issues/5917.

Add `scalafixInternalRules` to root project

---

servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
servlet/src/test/scala/org/http4s/servlet/RouterInServletSuite.scala

This could be the villain in #5844.
* That `.get` in the suite should definitely be blocking
* The servlet pool is wedged, so let's use the AsyncHttp4sServlet there, too.
* I don't know if anyone has thought about what CE3 blocking means for servlets. 🤔

Non-deadlocking RouterInServletSuite

---

.mergify.yml

Part of https://github.com/http4s/http4s/pull/5940#issuecomment-1019702909. Targeting main because that's where mergify reads the config from.
Getting auto-labeling for dependencies will be a little trickier.

Add module labeling to mergify config

---

blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
testing/js/src/test/scala/org/http4s/Http4sSuitePlatform.scala
testing/jvm/src/test/scala/org/http4s/Http4sSuitePlatform.scala
testing/shared/src/test/scala/org/http4s/Http4sSuite.scala

Ours was written in olden times to get daemon threads.  The IORuntime.compute pool is also daemon threads, and implements a fancy work stealing algorithm.  This is the one that gets used in practice, and is a more honest test.  It also touches the ClientTimeoutSuite that's acting up.  Let's see if it helps!
Also removes our `TestIORuntime` and `TestScheduler`.  If the global is good enough for munit-cats-effect, maybe it's good enough for us.

Replace our TestExecutionContext

---

blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala

We missed the setter for #5899, rendering it useless until the next release.  This is what happens when we unit test without integration testing.

Add withMaxIdleDuration setter to BlazeClientBuilder

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala

Throwables that are neither Exceptions nor Errors are awkward.  Use standard types.

Clean up Throwables in HTTP/2

---

build.sbt
ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Compressor.scala
ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Decompressor.scala
ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/H2TLSPlatform.scala
ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Frame.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/PseudoHeaders.scala

Cleans up a few vars that could have been vals.
Tolerates numeric widening in two classes.  I think they were all `Int => Long`, which is a safe conversion.  Fixing them wouldn't be that hard, but would be an ongoing chore.  As long as there's no floating point lurking within, it's fine.
Most of this is unused variable names, including a few that were shadowed.  I think the net effect is good, but we lost some descriptive names of discarded effects.  I don't miss them, but if anyone does, I would extract the generators into descriptively named inner methods.

Fix HTTP/2 warnings and restore compiler settings

---

build.sbt
docs/src/main/mdoc/README.md
docs/src/main/mdoc/client.md
docs/src/main/mdoc/json.md
docs/src/main/mdoc/service.md
docs/src/main/mdoc/static.md
docs/src/main/mdoc/streaming.md
docs/src/main/resources/logback.xml

This PR updates all the mdoc checked docs to use ember instead of blaze.
This is a continuation of https://github.com/http4s/http4s/pull/4932 and https://github.com/http4s/http4s/pull/4279.
Everything is rebased on latest `series/0.23`, but I can change the target branch if desired.
I have introduced three changes that are worth calling out as they may be controversial.
Starting the ember server in mdoc now looks like:
```scala
val startAndSleep = server.use(_ => IO.never).start <* IO.sleep(2.seconds)
val fiber = startAndSleep.unsafeRunSync()
```
Without an `IO.sleep`, any attempt to connect to the ember server would fail with a `java.net.ConnectException: Connection refused` as the request would be attempted before the ember server was actually bound to the address.
This was absolutely …

Use ember in docs

---

docs/src/main/mdoc/json.md

This failing mdoc example was causing trouble in https://github.com/http4s/http4s/pull/5337#issuecomment-1027252442
On Scala 2.13 this starts failing with or without the mdoc `fail` modifier
with mdoc `fail`: 
> Expected compile errors but program compiled successfully without errors 
without mdoc `fail`: 
> Cannot invoke "io.circe.Encoder.apply(Object)" because "encoder" is null
While we might be able to figure this out. I think it's worth considering if this is the best documentation example anyways.
I think it might be more useful to just show the user how to do things correctly in the first pass.
This unlocks us to move to 2.13 in `docs/mdoc` which is likely more interesting than solving this mystery.

Tweak json.md to work on scala 2.13

---

docs/src/main/mdoc/dsl.md
docs/src/main/mdoc/streaming.md

This PR fixes two mdoc warnings:
- Fixes the huge text output warning about mdoc generated code in dsl.md
- Fixes the deprecation warning around oauth1 in streaming.md

Mdoc warnings v23

---

dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
server/src/test/scala/org/http4s/server/RouterSuite.scala

Path.Root has changed to be absolute and endsWithSlash. We need to take
this into account when routing. Added a check for non-root to avoid
matching on paths we shouldn't
Fixes #5959

Fix regression in routing dsl

---

build.sbt
ember-core/js/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Decompressor.scala
ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/package.scala

The ember h2 support on Scala.js requires an npm package [hpack.js](https://www.npmjs.com/package/hpack.js).
Previously, this was expressed as a global `@JSImport` annotation, which forced _all_ users of ember.js to reckon with npm and/or Scala.js bundler even if they are not enabling h2. This manifests as a breaking change for existing users.
This PR changes it to a "lazy" `require`, so the npm package is only loaded if h2 support is enabled.
The long term solution is still to replace the npm package with a pure Scala implementation. This will let us remove npm from our own build.

Don't force npm onto ember.js users

---

.scalafmt.conf
build.sbt
client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala
project/build.sbt

I'm working on a browser implementation in https://github.com/http4s/http4s-dom/pull/93 and these are a couple things that tripped me up.
1. Use `DeferredSource` instead of `Deferred` for `closeFrame`. This prevents external completion of it :)
2. Remove `final` modifiers. Not sure how necessary they are and I'd like to override `receiveStream` with a more efficient implementation in the browser.
H/t Ross for making sure we kept these package-private 😅

Improve the `WSClient` API

---

build.sbt
client/src/main/scala/org/http4s/client/websocket/WSClient.scala

Backports the good stuff from https://github.com/http4s/http4s/pull/5974 into 0.22.

Improve `WSClient` API

---

docs/src/main/mdoc/auth.md
docs/src/main/mdoc/cors.md
docs/src/main/mdoc/csrf.md
docs/src/main/mdoc/dsl.md
docs/src/main/mdoc/entity.md
docs/src/main/mdoc/gzip.md
docs/src/main/mdoc/hsts.md
docs/src/main/mdoc/json.md
docs/src/main/mdoc/middleware.md
docs/src/main/mdoc/service.md
docs/src/main/mdoc/static.md
docs/src/main/mdoc/testing.md

This PR removes nearly all uses of the `nest` mdoc modifier.
As discussed in https://github.com/http4s/http4s/pull/5970 the `nest` modifier can make debugging documentation difficult and it doesn't buy us a whole lot.
The "hardest" part about removing `nest` is coming up with reasonable and unique value names. :)
I've left the `nest` modifiers in "Handling Query Parameters" section of `dsl.md` because we are creating different implicit values with the same type. So `nest` here is necessary to avoid ambiguous implicit errors.

Remove most mdoc nest modifiers

---

ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala

This PR adds scaladocs to all the EmberClientBuilder methods.
**Disclaimer**: I am very new to ember-client. This required a fair amount of reading the code to figure out where settings actually got used and what they did. I could easily be wrong.
**General principles**:
- Tried to highlight "where" the setting was applicable, for example calling out specifically when something affected the connection pool
- Mentioned default behaviours / values
- On things I had never heard of before (hello endpoint identification in HTTPS) I tried to add a bit more detail about why we care

Add scaladocs for EmberClientBuilder

---

build.sbt
client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala

We now have implementations ready in:
- https://github.com/http4s/http4s-dom/pull/93
- https://github.com/http4s/http4s-jdk-http-client/pull/571

Make `WSClient` and friends public

---

.scala-steward.conf

This is on the same release cycle as main Jetty, so no need to generate duplicate PRs.

Ignore Jetty HTTP/2 updates

---

servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/ServletIo.scala

We need to flush the response prelude before the first chunk when rendering a response with chunked transfer encoding.  This reaches parity with Ember and Blaze.
I thought we could just set the buffer size to zero, but this renders each byte as its own chunk.

Flush the prelude in non-blocking Servlet IO

---

blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala

When we acquire a `Response`, it is the server's responsibility to ensure that its body's finalizer runs.  Lacking a resourceful model of a response (#2663), the `.attempt.flatMap` can be interrupted and cause a leak.
We can't fix this in general, because `Http4sServlet` only requires an `Effect`.  We do a best effort by pattern matching the instance.  In `AsyncHttp4sServlet`, we can guarantee the better behavior.
Bonus: plug the same leak in blaze-server and ember-server

Render continually between response prelude and body

---

jetty-server/src/main/scala/org/http4s/jetty/server/JettyLifeCycle.scala
project/Http4sPlugin.scala

The `AbstractLifeCycleListener` was deprecated because `LifeCycle.Listener` now has default methods.
Replaces #6014.

Upgrade to jetty-9.4.45.v20220203 on series/0.22

---

blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala
blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala

The "encode" counterpart to https://github.com/http4s/http4s/pull/5813, perhaps.
Gives a significant performance improvement in some cases.
In techempower benchmarks, plaintext goes from 172k req/s to 267k req/s. JSON serialization goes from 146k req/s to 201k req/s (with an `EntityEncoder` that uses `EntityEncoder.simple` but also changing to jsoniter-scala, so not quite a direct comparison).
For another example, similar to plaintext:
example1 (strict): Requests/sec: 286024.12
example2 (non-strict): Requests/sec: 229754.28
Results from `docker run --network=host techempower/tfb.wrk wrk -H 'Host: localhost' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 4096 --timeout 8 -t 16 …

Optimize Http1Writer for cases when the entity is Empty or Strict

---

.scala-steward.conf

Updates should proceed from the `0.22` branch.

Ignore `sbt-buildinfo` updates

---

ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala

Fixes #6058
makeCase surpresses cancellation. makeCaseFull does not. We could probably specify better what spaces are cancelable and get some better semantics, but this fixes the critical issue of all cancellation being suppressed.
Big Bug need to fix ASAP

Fix ember client cancellation bug

---

examples/war/src/main/scala/com/example/http4s/war/Bootstrap.scala
servlet/src/main/scala-2.12/org/http4s/servlet/syntax/ServletContextOpsCompanionCompat.scala
servlet/src/main/scala-2.13/org/http4s/servlet/syntax/ServletContextOpsCompanionCompat.scala
servlet/src/main/scala-3/org/http4s/servlet/syntax/ServletContextOpsCompanionCompat.scala
servlet/src/main/scala/org/http4s/servlet/syntax/ServletContextSyntax.scala

- closes #1812 
- Deprecates `mountService`, clients should use the new `mountRoutes` method with the timeout param
- Deprecates `mountHttpApp` without the timeout param, clients should use `mountHttpApp` with the timeout param

- Adds the async timeout as a method param

---

blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala

Together with the other PRs (#6080, #6090, #6091), this increases performance on "plaintext" from the Techempower benchmarks by around 125% (from 172k reqs/s to 392k reqs/s), and around 80% for JSON.

Optimize CachingChunkWriter for Chunk.empty case

---

blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala
client/jvm/src/main/scala/org/http4s/client/middleware/GZip.scala
client/shared/src/main/scala/org/http4s/client/Client.scala
client/shared/src/main/scala/org/http4s/client/DefaultClient.scala
client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/shared/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
core/shared/src/main/scala/org/http4s/Message.scala
server/jvm/src/main/scala/org/http4s/server/middleware/GZip.scala
server/shared/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
server/shared/src/main/scala/org/http4s/server/middleware/DefaultHead.scala
server/shared/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
server/shared/src/main/scala/org/http4s/server/middleware/PushSupport.scala
server/shared/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
server/shared/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

Add an `alterBodyBy` function to `Message`, which is just to pass a function. Use it at a few places on the code base.
_Edit_ since this is a stream to stream transformation, the method is called `pipeBodyTo`.

Message: add pipeBodyThrough method

---

blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala

Together with the other PRs (#6080, #6090, #6092), this increases performance on "plaintext" from the Techempower benchmarks by around 125% (from 172k reqs/s to 392k reqs/s), and around 80% for JSON.

Avoid draining body on error/cancel for Entity.Strict and Empty

---

blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerParser.scala
blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala

Together with the other PRs (#6080, #6091, #6092), this increases performance on "plaintext" from the Techempower benchmarks by around 125% (from 172k reqs/s to 392k reqs/s), and around 80% for JSON.

Collect entity from parser, support Entity.Strict and Empty

---

core/shared/src/main/scala/org/http4s/EntityDecoder.scala

Removes redundant converting into `Stream` for `Entity.Strict` and `Entity.Empty` cases.

Optimize `EntityDecoder.{collectBinary|collectByteVector|error|void}`

---

client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
server/shared/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

There is no need to copy an entity body in the case of `Entity.Strict` and `Entity.Empty`.

Optimize `ResponseLogger` and `RequestLogger`

---

blaze-core/src/main/scala/org/http4s/blazecore/util/BodylessWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala
blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala
blaze-core/src/test/scala/org/http4s/blazecore/util/FailingWriter.scala
build.sbt

Remove unused ExecutionContexts in blaze-core

---

core/shared/src/main/scala/org/http4s/internal/Trampoline.scala
tests/shared/src/test/scala/org/http4s/internal/ExecutionSuite.scala

#6115 didn't fly on 0.22, but when I went to remove it from main, I noticed it's not used in 0.23.

Deprecate internal Trampoline

---

async-http-client/src/main/scala/org/http4s/asynchttpclient/AsyncHttpClient.scala
async-http-client/src/main/scala/org/http4s/asynchttpclient/AsyncHttpClientStats.scala
async-http-client/src/test/scala/org/http4s/asynchttpclient/AsyncHttpClientSuite.scala

As noted on #6107, upstream has been [unmaintained for months](https://github.com/AsyncHttpClient/async-http-client/commit/c959fa0483adb4a71fbccc5be94d8b6faa4f74be).  We should start chasing people off it.

Deprecate async-http-client

---

blaze-core/src/main/scala/org/http4s/blazecore/util/BodylessWriter.scala
blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala
core/src/main/scala/org/http4s/EntityDecoder.scala
servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala

A tiny refactoring as a follow-up from https://github.com/http4s/http4s/pull/6116#discussion_r825437891

Remove redundant draining of request/response body

---

servlet/src/main/scala/org/http4s/servlet/ServletIo.scala

Previously `BlockingServletIo` used a blocker (https://github.com/http4s/http4s/pull/4175/files#diff-476d2c035d983230b75e27a4ec07fbc8a40cb2ed1ef26c75c4dbef39a4bf1c1eL58), so I opine it should use a blocking EC accordingly.

Use blocking EC in the `BlockingServletIo`

---

blaze-core/src/main/scala-2.13/org/http4s/blazecore/util/ParasiticExecutionContextCompat.scala

This is a follow-up from https://github.com/http4s/http4s/pull/6141#pullrequestreview-914574674. I think this is legit to use parasitic EC from std for Scala 2.13.

Use parasitic EC in the blaze for Scala 2.13

---

.github/workflows/ci.yml
project/Http4sPlugin.scala

Fixes https://github.com/http4s/http4s/issues/6150.
When it comes to the http4s site, you just can't win 😩

Don't publish website from 0.21

---

ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
site/src/main/mdoc/changelog.md

I didn't realize the backport was from 0.23 instead of 0.22.  Mostly had to change some `message.rest` to `finalBuffer`.

Merge after 0.21.33

---

ember-core/shared/src/main/scala/org/http4s/ember/core/Parser.scala
project/build.sbt
site/src/main/mdoc/changelog.md

The only feature was a backport.  The change is because a refactor to Pull was proposed and accepted.

Merge 0.22 to 0.23

---

build.sbt

This unfortunate setting has mucked up our API urls for the last release cycle.

Don't override api url

---

blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala

Zero usages found. So, let's burn it?

Remove unused `EntityBodyWriter.wroteHeader`

---

core/shared/src/main/scala/org/http4s/Entity.scala

A bit more human-readable `toString`.

Override `toString` for `Entity`

---

server/src/main/scala/org/http4s/server/middleware/authentication/DigestAuth.scala
server/src/main/scala/org/http4s/server/middleware/authentication/DigestUtil.scala
server/src/main/scala/org/http4s/server/middleware/authentication/Nonce.scala
server/src/main/scala/org/http4s/server/middleware/authentication/NonceF.scala
server/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeper.scala
server/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeperF.scala
server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSuite.scala

Resolves #6068
Attempting to address PR feedback in #6077
- Removing `synchronized` calls
- Switching `var` to `Ref`
- Making all exposed methods `F[_]`
- Splitting out `AuthStore` trait with a more secure scheme that doesn't require the user storing the user's passwords in plaintext
Some remaining tasks:
Opening this draft early on to communicate intent and direction, as well to get feedback early

Resolve #6068 digestauth challenge redux

---

blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala

Following a [discussion on discourse](https://discord.com/channels/632277896739946517/632286375311573032/950816734288412672), I'd like to improve the docs on the custom execution context provided to the `BlazeServerBuilder` and `BlazeClientBuilder`.
Let me know what you think.
Thanks!

Document the use of the execution context passed to the blaze builders.

---

blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala
blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
blaze-server/src/main/scala/org/http4s/blaze/server/WebSocketSupport.scala
blaze-server/src/test/scala/org/http4s/blaze/server/ServerTestRoutes.scala
build.sbt
circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
core/shared/src/main/scala/org/http4s/Message.scala
core/shared/src/main/scala/org/http4s/headers/Connection.scala
core/shared/src/main/scala/org/http4s/internal/package.scala
core/shared/src/main/scala/org/http4s/metrics/MetricsOps.scala
core/shared/src/main/scala/org/http4s/multipart/MultipartEncoder.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/DigestAuth.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/DigestUtil.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/Nonce.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/NonceF.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeper.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeperF.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/package.scala
server/shared/src/main/scala/org/http4s/server/package.scala
server/shared/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSuite.scala
server/shared/src/test/scala/org/http4s/server/middleware/authentication/NonceFSpec.scala
testing/shared/src/test/scala/org/http4s/testing/ErrorReporting.scala
tests/shared/src/test/scala/org/http4s/ResponderSpec.scala
tests/shared/src/test/scala/org/http4s/internal/JavaMajorVersionSuite.scala
tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala

Demonstration of what `Random` looks like in the public API.  We want to decide before the next 0.23.x release, and also decide on the fate of `SecureRandom` in Cats-Effect 3 (https://github.com/typelevel/cats-effect/pull/2905).

Surface Random

---

client/shared/src/main/scala/org/http4s/client/Client.scala

Fix `Client` scaladoc

---

client/shared/src/main/scala/org/http4s/client/Client.scala
client/shared/src/main/scala/org/http4s/client/DefaultClient.scala

Those methods were deprecated since `0.21`, so I feel we can do that clean-up. If not now, then when? `2.0` is probably too far from nowadays.

Remove deprecated `Client.fetch`, `DefaultClient.fetch`

---

tests/src/test/scala/org/http4s/StatusSpec.scala

`0x80` is allowed, too.
Fixes #5736,

Fix StatusSpec sanitization property

---

server/shared/src/main/scala/org/http4s/server/ContextRouter.scala

Closes #6105. Fixing this for `0.22`/`0.23` would mean breaking MiMa. I'm not confident it's worth the hassle. The fix for `1.0` is pretty straightforward and clear.

Relax ContextRouter's constraints

---

blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala

This PR brings several proposals to the blaze server:
1. Tries to reduce lock contention in case of saving cancel token.
2. Avoid canceling the previous request in the case of failing the current one.

Blaze server enhancements

---

blaze-client/src/main/scala/org/http4s/blaze/client/bits.scala
blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala

It's unused publicly.  A safer version is ported to the test that uses it.
The unfitness for production extends beyond the blocking call, for the record.

Deprecate blaze TrustingSslContext

---

blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala

This is a follow-up from https://github.com/http4s/http4s/pull/6196#discussion_r835964580.

Use `guarantee` on failed request clean-up in the blaze

---

core/src/main/scala/org/http4s/Message.scala
core/src/main/scala/org/http4s/headers/Transfer-Encoding.scala
project/Http4sPlugin.scala
server/src/main/scala/org/http4s/server/middleware/BodyCache.scala

Similar to the logic in `BodyCache`, but applies to any Message.  Takes care of setting an appropriate `Content-Length` header and stripping `chunked` from any `Transfer-Encoding` header.
Motivation: there are many servers that can't handle chunked transfer encoding.  This is particularly common in multipart implementations.  Calling `toStrict` defeats streaming, but enables communication with such servers.

Add withContentLength and toStrict helpers to Message

---

blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala

These synchronizations seem redundant. Unfortunately, we didn't achieve any significant performance boost. Nevertheless, it could be considered just like refactoring.

Remove synchronizations in `TestHead`, `QueueTestHead`, `SlowTestHead`

---

build.sbt
server/jvm/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/Nonce.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/NonceF.scala

The Java `SecureRandom` blocks. The JS `SecureRandom` was first shimmed in http4s-crypto, then in CE.
CE's `Random.javaSecuritySecureRandom` doesn't solve the blocking problem yet, but hopefully it will soon. In any case, this change lets us iterate in CE and reap the benefits everywhere.

Use CE `Random.javaSecuritySecureRandom` instead of Java `SecureRandom`

---

blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala

`-=`/`+=` operators aren't thread-safe. So this means we almost certainly* have issues in counting current allocated connections.
\* I haven't proof, just speaking from common sense.

Fix counting of current allocated connections in the blaze client pool manager

---

core/shared/src/main/scala/org/http4s/Message.scala

Takes a few more lines, but should be evident.
It could be an Option `fold`, but that would need type arguments

Message - remoteHost: define without OptionT.

---

client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
core/src/main/scala/org/http4s/multipart/Boundary.scala
core/src/main/scala/org/http4s/multipart/Multipart.scala
core/src/main/scala/org/http4s/multipart/Multiparts.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/MultipartClient.scala
tests/src/test/scala/org/http4s/multipart/BoundarySuite.scala
tests/src/test/scala/org/http4s/multipart/MultipartSuite.scala
tests/src/test/scala/org/http4s/multipart/MultipartsSuite.scala

Not all servers gracefully handle multipart quoted boundaries.  We remove all non-token characters.  This new alphabet is consistent with the generators in both Apache HTTP and Spring.  It's also a built-in Base64 decoder, so we can use the platform's optimized encoder from an array of bytes vs. our (ugh) random access into a List!
`Boundary.create` is impure and deprecated.
Introduces a `Multiparts` algebra to house all this.

Improvements to multipart boundaries

---

core/shared/src/main/scala/org/http4s/Header.scala
examples/ember-server-h2/src/main/scala/com/example/http4s/ember/EmberServerH2Example.scala
server/shared/src/main/scala/org/http4s/server/middleware/Throttle.scala

The `guard` method of the `Alternative` typeclass is less known that the Scala `if-then-else`

Avoid Alternative-Guard

---

project/Http4sPlugin.scala

The recent `sbt-doctest` version is backed by a fix.

Remove ignoring some files for `doctest`

---

core/shared/src/main/scala/org/http4s/Message.scala

That fits better with the new `Entity` model.

Tweak `Message#withEmptyBody`

---

.scala-steward.conf

We will get updates from 0.23.

Ignore `scala-lang` updates

---

blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
client/shared/src/test/scala/org/http4s/client/middleware/RetrySuite.scala
core/shared/src/main/scala/org/http4s/package.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/Parser.scala
server/shared/src/test/scala/org/http4s/server/middleware/ChunkAggregatorSuite.scala

`EmptyBody` clashes a bit with the current `Entity` model in the sense that it's an implementation detail of `Entity.Default`, so it should be gone from public API (and overall IMO).

Remove `http4s.EmptyBody`

---

client/shared/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
client/shared/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
examples/ember-server-h2/src/main/scala/com/example/http4s/ember/EmberServerH2Example.scala
server/jvm/src/test/scala/org/http4s/server/middleware/GZipSuite.scala
tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala

After #5712 the `covary` method is less necessary. In some places we can just remove it. In the case of calls to `.pure[F]`, it happens that the syntax extensions fixes the type of the receiver object, so we need to use `F.pure` instead.

Reduce use of `covary` method.

---

core/shared/src/main/scala/org/http4s/Headers.scala
core/shared/src/main/scala/org/http4s/Message.scala

Following discussion on #6282 - I think this is too low-level to expose on `Message`.

Move `withContentLength` from Message to  Headers

---

client/shared/src/main/scala/org/http4s/client/Client.scala

Sorry for annoying with that kind of PRs, but I believe they bring some performance enhancements. Though I don't give the numbers to support my points, it just goes from common sense and looks natural.

Address the entity model in the `Client#fromHttpApp`

---

docs/contributing.md

Our contributing guide needs some polishing after migration on `sbt-typelevel-site`.

Tweak the contributing guide

---

server/shared/src/main/scala/org/http4s/server/ContextRouter.scala
server/shared/src/main/scala/org/http4s/server/Router.scala

Avoid use of `<+>` and `local` methods of Kleisli.

Server - ContextRouter - Simpler Code 

---

.github/workflows/ci.yml
build.sbt

First of all the extra jobs were worthless, because they weren't doing anything.
Secondly, because they ran so quickly (i.e. without starting sbt and downloading stuff) they were the first in line to upload the cache ... of nothing 🙃 
Fixes https://github.com/http4s/http4s/issues/6360.

Only create scalafix job for 2.13

---

core/shared/src/main/scala/org/http4s/StaticFile.scala
tests/shared/src/test/resources/lipsum-symlink.txt
tests/shared/src/test/scala/org/http4s/StaticFileSuite.scala

Fixes https://github.com/http4s/http4s/issues/6363.

Follow links when accessing file attributes in `StaticFile`

---

core/shared/src/main/scala/org/http4s/Message.scala

I think these methods should contemplate `Entity[F]` rather than `Stream[F, Byte]`.

Fix `Request#productElement` and `Response#productElement`

---

docs/docs/entity.md

This only addresses the change `Stream[F, Byte]` -> `Entity` within Request/Response and definitely should be complemented at further iterations.

Tweak `Entity` docs

---

server/shared/src/main/scala/org/http4s/server/middleware/Throttle.scala
server/shared/src/test/scala/org/http4s/server/middleware/ThrottleSuite.scala

This PR implements the httpApp and httpRoutes shortcuts of the Throttle middleware. See #2402.

httpRoutes and httpApp shortcuts for Throttle middleware

---

client/shared/src/main/scala/org/http4s/client/middleware/Retry.scala
client/shared/src/test/scala/org/http4s/client/middleware/RetrySuite.scala
core/shared/src/main/scala/org/http4s/Message.scala

Closes #712. I've crossed my fingers that I correctly followed Ross's reasoning on the issue. Nevertheless, I'm open to taking rotten tomatoes.

Resubmit idempotent requests with only pure entities in `Retry` middleware

---

blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
server/shared/src/test/scala/org/http4s/server/middleware/TimeoutSuite.scala

Refactors the direct `race`s in favor of `GenTemporal` algebra.

Use `GenTemporal` for proceeding with timeouts

---

server/shared/src/test/scala/org/http4s/server/middleware/HSTSSuite.scala
server/shared/src/test/scala/org/http4s/server/middleware/HttpsRedirectSuite.scala
server/shared/src/test/scala/org/http4s/server/middleware/VirtualHostSuite.scala
server/shared/src/test/scala/org/http4s/server/staticcontent/FileServiceSuite.scala
tests/shared/src/test/scala/org/http4s/StaticFileSuite.scala

A teeny-weeny speed-up of tests running.

Use `parTraverse` in tests

---

build.sbt

This will now be set automatically to the javadoc.io unidoc link.
https://www.javadoc.io/doc/org.http4s/http4s-docs_2.13/0.22.13/org/http4s/index.html

Delete hard-coded Scaladoc url

---

core/js/src/main/scala/org/http4s/nodejs/ClientRequest.scala
core/js/src/main/scala/org/http4s/nodejs/IncomingMessage.scala
core/js/src/main/scala/org/http4s/nodejs/ServerResponse.scala

I initially intended to make these APIs public since they are helpful for integrating with serverless frameworks. After thinking more, I changed my mind.
Besides these interop APIs, there is essentially nothing else JS-specific in http4s, and I think that's great.
Furthermore, the only reason we need these interop APIs in http4s at all is to implement the Node.js scaffold server for the client testkit. I'd like to reserve the option to remove the need for them completely in the future: for example, by running the scaffold server as an external process via sbt (i.e., a testkit distributed as an sbt plugin).

Make Node.js interop APIs private

---

server/shared/src/main/scala/org/http4s/server/middleware/Timeout.scala
server/shared/src/test/scala/org/http4s/server/middleware/TimeoutSuite.scala

I think the uncancelable behavior is noteworthy because it could lead to some surprising effects on the user site. It's indisputable that it's the user's responsibility to check how their services produce effects. But still, I'm sure it's better to highlight that behavior. 
Also, I've added the test that proves my point about `Timeout` middleware behavior when dealing with uncancelable effects.

Highlight the uncancelable behavior in `Timeout` middleware scaladoc

---

server/shared/src/main/scala/org/http4s/server/middleware/Timeout.scala

These references in scaladoc look really monstrous. And their inlining doesn't work, at least in my $IDE.

Tweak `Timeout` middleware scaladoc

---

build.sbt
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala

The `readLoop` in the `ember-core` module made a use of fs2 Streams that was not necessary for the use-case at hand. In this use case: 
- There is no emitted outputs that the consumer may use to cut the stream processing.
- There were no interruptions that connected the flow of the stream to an outside event. 
- There were no resources acquired during the stream that had a limited nested scope.
- There was no chunking or re-chunking of outputs or intermediate values. The way the stream was constructed, it was just generating one output (in a singleton chunk) and immediately processing it, one by one. 
In this circumstances, fs2 Streams do not add any functionality, and takes some cognitive toll and a bit of memory cost. Instead, writing it as a tail-recursive `F[Unit]` operation fits the …

Ember Core: write readLoop without Streams.

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala

In this code, the use of `Alternative[Option]` can be replaced with an if-then-else statement. Furthermore, we can replace the for-comprehension with a simple flatMap and less inlining.
_Note_: most changes are whitespace.

Ember-Core - H2Client - Rewrite without alternative.

---

ember-core/shared/src/main/scala/org/http4s/ember/core/Encoder.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/EncoderSuite.scala

Fixes https://github.com/http4s/http4s/issues/6427
Around the repository there are different ways that empty responses are encoded. In some places the content length is set to 0, and in other places like the auth middleware, an empty response is returned with no headers set.
Here is a potential fix where an empty body with `content-length: 0` is always set when the status code allows a non-empty response and the header is not already set.
Something similar could probably also be done in the request encoding as well.

Encoding of response with empty body

---

build.sbt
server/shared/src/main/scala/org/http4s/server/middleware/Metrics.scala

- Extract local methods for main operations: starting the metric "timer", ending the metrics "timer". 
- Rename `MetricsRequestContext` to `MetricsEntry`, because they are not directly related to requests, and "context" is also used with "ContextRequest" and "ContextResponse", which can add confusion.

Server Metrics Middleware

---

docs/docs/json.md

Added a note that helped resolve a `circe` import error I encountered.
This was the solution proposed by armanbilge on Discord. In my case, I set up the project with `sbt new http4s/http4s.g8 --branch 0.23-scala3` and the import `import io.circe._` will work with Scala 3.1.0, but not 3.1.2. The proposed change allows the import to run.

Added note on possible circe import error in docs

---

server/shared/src/main/scala/org/http4s/server/Router.scala
server/shared/src/test/scala/org/http4s/server/RouterSuite.scala

The current implementation of `Router#define` from 0.23 differs from that we have at main. I think this was done accidentally in https://github.com/http4s/http4s/commit/8b148f48ae2c167f36d27f2b64a92bb638ca24ec#diff-7b0e93ead3858152f51e0f8ceb5dd1aec7c0eee85dd58a812e1192d204e7a059L42.

Fix regression of `Router#define`

---

server/shared/src/test/scala/org/http4s/server/RouterSuite.scala

[As we agreed](https://github.com/http4s/http4s/pull/6371#pullrequestreview-996021371), this is a backport of the Router's empty path case test.

Backport of `Router#define` test

---

.github/workflows/ci.yml
build.sbt

Sorry for the follow-up, realized I overlooked this subtlety. Occasionally the scoverage plugin will break for some otherwise valid code (like the `\r\n` thing). A PR could do this by mistake and we wouldn't find out till merge.
So actually, we _do_ want to run coverage for PRs, just to make sure it still works. We just don't want to upload the results!

Run coverage job for PRs, but don't upload results

---

ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
server/shared/src/main/scala/org/http4s/server/middleware/Caching.scala

Two subsequent calls of `Message#putHeaders` could be composed into one. It should bring itsy bitsy reducing allocations.

Compose multiple subsequent `Message#putHeaders` calls

---

docs/docs/upgrading.md

As discussed in https://github.com/http4s/http4s/pull/6460#issuecomment-1152525769. Confirmed that this works locally.
See also: https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#using-github

Point upgrade docs at scalafix published in series/0.22

---

core/src/main/scala/org/http4s/headers/Content-Disposition.scala
tests/src/test/scala/org/http4s/parser/ContentDispositionHeaderSuite.scala

As per RFC6266, Section 4.3, if `filename*` is defined, prefer that.  If not, try `filename`.
Kind of like #6475, but lossless.

Add filename property to Content-Disposition

---

core/shared/src/main/scala/org/http4s/ContentCoding.scala
core/shared/src/main/scala/org/http4s/MediaType.scala

This is the only missing `Ordering` I could find - all the other data types extend `Ordered`, which then allows deriving `Ordering` with implicit extension from `cats`
Closes #5017

Add Ordering for MediaRange

---

core/shared/src/main/scala/org/http4s/Uri.scala
laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
tests/shared/src/test/scala/org/http4s/PathSuite.scala

Fixes #5099 
This PR aims at making Uri.Path.merge compliant with RFC 3986 5.2.3

Make Uri.Path.merge compliant

---

client/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala

I honestly don't know why I set the LoggingHandler to INFO. It's too high for such a low level log. It spams a lot in `blaze`'s tests where we have logback set to INFO.

Set LoggingHandler in NettyTestServer to the default DEBUG level

---

server/shared/src/main/scala/org/http4s/server/middleware/Throttle.scala

replaces #6500 now targeting series/0.23 rather than main

fix typo in `Throttle` middleware `httpAapp->httpApp`

---

client/shared/src/main/scala/org/http4s/client/oauth1/oauth1.scala
client/shared/src/test/scala/org/http4s/client/oauth1/OAuthSuite.scala
server/shared/src/test/scala/org/http4s/server/middleware/ChunkAggregatorSuite.scala
server/shared/src/test/scala/org/http4s/server/staticcontent/FileServiceSuite.scala
tests/shared/src/test/scala/org/http4s/UriSpec.scala
tests/shared/src/test/scala/org/http4s/UrlFormSpec.scala
tests/shared/src/test/scala/org/http4s/headers/ForwardedSuite.scala
tests/shared/src/test/scala/org/http4s/multipart/MultipartParserSuite.scala
tests/shared/src/test/scala/org/http4s/parser/AcceptHeaderSpec.scala
tests/shared/src/test/scala/org/http4s/parser/AuthorizationHeaderSuite.scala
tests/shared/src/test/scala/org/http4s/parser/ForwardedHeaderSpec.scala
tests/shared/src/test/scala/org/http4s/parser/RangeParserSuite.scala
tests/shared/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
tests/shared/src/test/scala/org/http4s/parser/UriParserSuite.scala

This addresses the #1695 for tests only. Also, this PR brings some reduction of collections converting. That's why it targets 0.23. Apply the hide of whitespaces on review!

Smite `Seq` in tests

---

ember-core/shared/src/main/scala/org/http4s/ember/core/Parser.scala

Within the parser of `ember-core`, rewrites the `combineArrays` to
something that avoids some work.
- Not allocate, fill, and grow, an intermediaryArrayBuffer.
- Not allocate an array, immediately discarded, that is a copy of the Chunk.
- Maybe? avoid boxing brought by the use of a type-parametric API of `ArrayBuffer`, and deal directly with arrays of `Byte`.

Ember-Core: reimplement "combineArrays"

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala

Fixes #6549 
TLDR: Settings Acknowledgements waiting causes a bug on some very present implementations H2.
Long Story: 
Original Framing 
```
DEBUG - postman-echo.com:443 Write - Settings()
DEBUG - postman-echo.com:443 Read - Settings(SettingsMaxConcurrentStreams(128), SettingsInitialWindowSize(65536), SettingsMaxFrameSize(16777215))
DEBUG - postman-echo.com:443 Read - WindowUpdate(0,2147418112)
DEBUG - postman-echo.com:443 Write - Settings.Ack
DEBUG - postman-echo.com:443 Write - GoAway(identifier=0, lastStreamId=0, errorCode=FlowControlError, additionalDebugData=None)
```
As you see, the write for setting proceeds first. Ok, so now for the words in the spec.
```
The values in the SETTINGS frame MUST be processed in the order they
appear, with no other frame processing between values. …
```

H2 Settings Acknowledgments do not need to block progress

---

core/shared/src/main/scala/org/http4s/internal/BackendBuilder.scala

This addresses #5543. Though @bplommer has suggested deprecating it, I feel that for 1.0 we should remove it. Users could still do this on their side via `serverBuilder.resource.allocated`.

Remove `BackendBuilder#allocate`

---

core/shared/src/main/scala/org/http4s/internal/BackendBuilder.scala

This is a follow up to #6540.
Finally fixes #5543.

Deprecate `BackendBuilder#allocate`

---

core/shared/src/main/scala/org/http4s/Uri.scala

A micro-optimization, but `addSegment` can be used on the users' side heavily, so this could bring a positive impact (yes, a tiny one) to memory consumption.

Don't instantiate redundant `List` in `Path#addSegment`

---

docs/docs/middleware.md

Fixes #5086.
I did it very straightforwardly. If you have something to add, let me know.

Freshen up `Middleware` docs

---

core/shared/src/main/scala/org/http4s/Uri.scala
tests/shared/src/test/scala/org/http4s/UriSpec.scala

Fixes #6562.
Read this only with the hiding of whitespace changes in UI!

Don't override `endsWithSlash` when adding an empty `Path` segment

---

docs/changelog.md

The artifacts are already published due to https://github.com/typelevel/fs2/security/advisories/GHSA-2cpx-6pqp-wf35. Now we catch up the website.

Release v0.23.14

---

docs/changelog.md

The artifacts are already published due to https://github.com/typelevel/fs2/security/advisories/GHSA-2cpx-6pqp-wf35. Now we catch up the website.
Includes a forward-merge of https://github.com/http4s/http4s/pull/6568.

Release v1.0.0-M35 

---

build.sbt
ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-core/js/src/main/scala/org/http4s/ember/core/UtilPlatform.scala
ember-core/jvm/src/main/scala/org/http4s/ember/core/UtilPlatform.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/Util.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala

This fixes h2 on ember.js and achieves parity with http/1.1 on all platforms.

Set `serverNames` TLS parameter for ember h2

---

client/shared/src/test/scala/org/http4s/client/middleware/RetrySuite.scala
core/shared/src/main/scala/org/http4s/Entity.scala
core/shared/src/main/scala/org/http4s/EntityDecoder.scala
core/shared/src/main/scala/org/http4s/EntityEncoder.scala
core/shared/src/main/scala/org/http4s/Message.scala
core/shared/src/main/scala/org/http4s/multipart/Part.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/Encoder.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
examples/ember/src/main/scala/com/example/http4s/ember/EmberClientSimpleExample.scala
laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
server/shared/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
server/shared/src/test/scala/org/http4s/server/middleware/EntityLimiterSuite.scala
tests/shared/src/test/scala/org/http4s/EntityDecoderSuite.scala
tests/shared/src/test/scala/org/http4s/EntityEncoderSpec.scala
tests/shared/src/test/scala/org/http4s/MessageSuite.scala

**tl;dr** Because `ByteVector` is specialized for `Byte`, it has idiomatic APIs for byte manipulation and copy-free interop that `Chunk` lacks.
This is a follow-up to my comments in https://github.com/http4s/http4s/issues/5812. See there for more details, summary below:
1. IMHO a `ByteVector` the more idiomatic data structure for, well, bytes. `Chunk[Byte]` is kind of an FS2 thing.
2. `ByteVector` exposes useful ops specifically for byte manipulation, not available on `Chunk[Byte]`. I wanted this in:
https://github.com/typelevel/feral/pull/214#discussion_r882320272
3. `ByteVector` exposes better APIs for copy-free interop. I wanted this in:
https://github.com/http4s/http4s-jdk-http-client/pull/644#discussion_r882347645
4. Even though `ByteVector` does not subsume `Chunk`, many common …

Use `scodec.bits.ByteVector` for `Entity.Strict`

---

ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala

We've been hunting this down in Discord with @armanbilge and this seems to be the right thing to do :)
The problem: when connecting to a websocket endpoint served by ember, and then disconnecting from it (`ws.close()` in the browser), there is an exception thrown in the browser: 
```
WebSocket connection to 'ws://...' failed: Received a broken close frame containing a reserved status code.
```
Another client (Dark WebSocket terminal) also reports an abnormal closure: `Close status: 1006 (Abnormal Closure)`
After some digging, we realized we are sending back the close code that the client sends in originally while initiating the connection termination, which happens to be `1005` and is not allowed to be used by the endpoint:
```
1005 is a reserved value and MUST NOT be set as a status code …
```

Always respond to client close frame with 1000 "normal closure"

---

README.md
docs/docs/client.md
docs/docs/quickstart.md
docs/docs/service.md

Remove references to Scala 2.12 in docs

---

docs/versions.md

The version table currently suggests that 2.12 is supported and 2.13 is not for version 1.0

Fix 1.0 version table compatibility with 2.12 & 2.13

---

build.sbt
ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala

This is a fix for https://github.com/http4s/http4s/issues/6558.
The bug can be observed whenever a single `Chunk` of bytes contains more than one frame. In this case the current version decodes the first frame using `bufferToFrame`, emits it and recurses via `Pull.output1(value) >> go(next, remaining)`. But `go` will only continue when more data is read from the socket. This explains why sending messages "1", "2", "3" will only show "1", because the first chunk contains all three message. Messages "2" and "3" will only be decoded when further messages arrive, which might be never. The solution is simple: decode as many frames as possible from every chunk before recursing.

Parse all WebSocket frames in a `Chunk` in ember-server

---

client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/shared/src/test/scala/org/http4s/client/middleware/LoggerSuite.scala

Fixes https://github.com/http4s/http4s/issues/2951

Fix request logger to log in the case of no request body, when `logBody=true`

---

core/shared/src/main/scala/org/http4s/Uri.scala
tests/shared/src/test/scala/org/http4s/PathSuite.scala

Closes #6538
The actual fix would be along the lines of what was discussed [here](https://github.com/http4s/http4s/discussions/5930#discussioncomment-2997587), but we'll have to wait for [cats-uri](https://github.com/typelevel/cats-uri) for a definitive solution

Rewrite hashcode computation for `Uri.Path`

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/PseudoHeaders.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/h2/PsuedoHeadersSuite.scala
examples/ember/src/main/scala/com/example/http4s/ember/EmberServerH2Example.scala

So questions: 
1. How does Blaze deal with this?
2. Removing in the backend means it appears to be using chunked when logging, but is secretly not if h2 is used.
3. Overall it seems a bit like we have queued up nice helpers for a primarily http/1.1 world, but those helpers seem wrong with http2.

Ember H2 Connection Header Compliance

---

build.sbt
ember-core/shared/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/Parser.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/ParserSuite.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/StreamingParserSuite.scala

Don't backtrack in request/response prelude parsing for better performance.
Also resolves https://github.com/http4s/http4s/issues/6580 for 1.0.x

Don't backtrack in request/response prelude parsing

---

docs/docs/quickstart.md

Following the discussion on [here](https://github.com/http4s/http4s.g8/issues/249), I added a mention to Scala 3 branch in the documentation's quick-start guide.

Update quickstart guide to include Scala 3 branch

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala

Redo of #6525 in a series of commits, to make each change obvious, to attend @armanbilge 
comment in https://github.com/http4s/http4s/pull/6523#issuecomment-1179428961
Each commit is easier to review, specially if hiding whitespace changes.
________
In the `ember-core` package, in the H2Server, the `fromSocket` method,
we refactor the code to split the main expression, a for comprehension
in `Resource`, to extract a couple of methods in `F`:
- Initialising the H2Connection itself.
- Clear closed streams from the map of streams.
- Process a created stream, which includes handling push promises.
This is similar to recent PR #6523, and follows on previous PRs like #6425. 
_Note:_ Half of line changes are whitespace-only.

Ember Core - H2Server - Split for comprehension

---

client/shared/src/main/scala/org/http4s/client/middleware/Logger.scala
client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
client/shared/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
core/shared/src/main/scala/org/http4s/internal/Logger.scala
server/shared/src/main/scala/org/http4s/server/middleware/Logger.scala
server/shared/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
server/shared/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala

Simplifies type signatures for `org.http4s.internal.Logger`. For whatever reason it isn't package-private even though it's in the `internal` package, but it's binary-compatible though source-breaking so I think it's ok?

Simplify type signature for internal logger

---

core/shared/src/main/scala/org/http4s/headers/SourceMap.scala
tests/shared/src/test/scala/org/http4s/headers/SourceMapSuite.scala

It's yet another header from the https://github.com/http4s/http4s/issues/5010 list.

add SourceMap header

---

.scala-steward.conf

See:
- https://github.com/typelevel/log4cats/pull/679
- https://github.com/http4s/http4s/pull/6625

Pin slf4j to 1.x and cleanup

---

docs/docs/dsl.md

Add a small note at the paragraph that introduces right-associative path
matchers (`/:`) that they cannot be mixed with the left-associative
ones.

Add doc for mixing left- and right-associative

---

client-testkit/shared/src/main/scala/org/http4s/client/testkit/ClientRouteTestBattery.scala
ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerMtlsSuite.scala
ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
project/Http4sPlugin.scala
tests/jvm/src/main/scala/org/http4s/Http4sSuitePlatform.scala
tests/shared/src/main/scala/org/http4s/Http4sSuite.scala
tests/shared/src/main/scala/org/http4s/testing/DispatcherIOFixture.scala
tests/shared/src/test/scala/org/http4s/UriSpec.scala

At this point it is quite stable and brings many improvements we could benefit from, such as async resource fixtures (thanks to @danicheg for working on that in munit core :)

Update to munit 1.0.0-M6

---

ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala

This change is motivated by the I/O Integrated Runtime Concept in https://github.com/typelevel/cats-effect/discussions/3070 which proposes an alternate implementation of `Network[IO]`. There have also been discussions of a `Network` implementation based on [fs2-netty](https://github.com/typelevel/fs2-netty).
For Ember to be able to take advantage of such advances, we must expose the `Network[F]` constraint in the builder. Fortunately this is source-compatible, because an implicit `Network[F]` is always in scope for `Async[F]` which was already required.
See also how Skunk does it:
https://github.com/tpolecat/skunk/blob/14c756d68ba88da4415699bea388149c43e4e962/modules/core/shared/src/main/scala/Session.scala#L262
~~While looking at that, I notice Skunk actually only takes a `Concurrent` …

Expose `Network` constraint in ember builders

---

.github/workflows/ci.yml
build.sbt

This fixes the Scala Native CI (sorry). See https://github.com/typelevel/fs2/pull/2992 for additional detail.

Use ubuntu-22.04 in ci

---

docs/docs/auth.md
docs/docs/client.md
docs/docs/cors.md
docs/docs/csrf.md
docs/docs/dsl.md
docs/docs/entity.md
docs/docs/gzip.md
docs/docs/hsts.md
docs/docs/json.md
docs/docs/methods.md
docs/docs/middleware.md
docs/docs/service.md
docs/docs/static.md
docs/docs/streaming.md
docs/docs/testing.md
docs/docs/uri.md

This PR does a quick once over all our docs using mdoc to see if there are easy clean up wins by using `mdoc:silent`.
This main goal of this PR is to reduce unhelpful mdoc output.
So only minor modifications are being made to serve that goal.
There's certainly more work to do here, this is just a first small attempt to clean up low hanging fruit.
<details><summary>Example Screenshots From service.md</summary>
*Before:*
*After:*
</details>
<details><summary>Example Screenshots From lient.md</summary>
*Before:*
*After:*
</details>
---
**Edit:** This PR fixes a few other things unrelated to silencing output from IO values:
- [Fix CIRCE_VERSION ref in streaming.md](https://github.com/http4s/http4s/pull/6705/commits/21b67ccd157cbb665888b43475983bf837b2bdf3)
- [Remove old ContextShift mention …

Using `mdoc:silent` more liberally throughout docs

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala

Once https://github.com/typelevel/fs2/pull/2990 is released and we upgrade fs2 version, this operation should be significantly cheaper in many cases (or at worst: the same as before).
See also https://github.com/typelevel/jawn-fs2/pull/376

Call Chunk.toByteBuffer directly

---

core/shared/src/main/scala/org/http4s/headers/Cross-Origin-Resource-Policy.scala
laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
tests/shared/src/test/scala/org/http4s/headers/CrossOriginResourcePolicySuite.scala

- adds a model for the `Cross-Origin-Resource-Policy` header, following the [mozilla reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy)
- tests as well
- I looked at some other examples and they were adding the `checkAll` header laws test as well as explicit checks, but it kind of looked to me like those header laws would have already covered these explicit checks? Could anyone explain why we do both? 🙏🏻 
https://github.com/http4s/http4s/blob/d6e5f6ab0db674e857a0f4f4331655dddfc0f35a/tests/shared/src/test/scala/org/http4s/headers/HeaderLaws.scala#L33-L35
related to #5010

`Cross-Origin-Resource-Policy` header model

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/StreamForking.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/internal/StreamForkingSuite.scala

This is a backport of #6610 by @TimWSpence to 0.23 branch.

Make StreamForking resource safe in the face of cancelation

---

core/shared/src/main/scala/org/http4s/Uri.scala
tests/shared/src/test/scala/org/http4s/UriHostSuite.scala

Adds a `fromString` method to `org.http4s.Uri.Host`. While it is possible to get a `org.http4s.Uri.Host` from a `String` using `org.http4s.headers.Forwarded.Host.fromString` to get a `org.http4s.headers.Forwarded.Host` which itself has a `host` field of type `org.http4s.Uri.Host`, it felt less discoverable. This also bring `Host` in line with other objects in `org.http4s.Uri` which themselves have a convenient `fromString` method.

Add Uri.Host.fromString method

---

docs/docs/entity.md

follow up: #1694
Presupplied future has been deleted in 13527d6c320efd25800680a8fd841365dec7965e. Isn't it?
Thank you :)

docs: remove `Future[_]` from presupplied encoders

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala

- Add a procedural method `sendMessageBody`, that is commonly used by both `H2Client` and `H2Server`, (one for requests and the other for responses) to send the chunks of the body of the message. 
- Add another procedure `sendTrailerHeaders`, that also takes a message, and that extract the trailer headers and sends them through the stream.

Ember-Core: factor to H2Server loops from H2Client, H2Server.

---

client-testkit/jvm/src/main/scala/org/http4s/client/testkit/scaffold/RoutesToNettyAdapter.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/ParserSuite.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/TraversalSpec.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/internal/StreamForking.scala

Unlike "evalMap", the "foreach" method of Stream does not emit any outputs, so it is more suited for the cases where we just want to consume the stream inputs without passing them on.
Since it emits no outputs, it allocates fewer items, which is more efficient.

FS2 Streams: replace "evalMap" with "foreach".

---

core/shared/src/main/scala/org/http4s/Uri.scala
core/shared/src/main/scala/org/http4s/internal/CharPredicate.scala

```
[info] Benchmark                 (listSize)  Mode  Cnt  Score   Error  Units
[info] SizeCheckingBench.size            10  avgt    5  2.106 ± 0.008  ns/op
[info] SizeCheckingBench.size           100  avgt    5  2.105 ± 0.010  ns/op
[info] SizeCheckingBench.size          1000  avgt    5  2.103 ± 0.006  ns/op
[info] SizeCheckingBench.size         10000  avgt    5  2.101 ± 0.021  ns/op
[info] SizeCheckingBench.sizeIs          10  avgt    5  2.003 ± 0.016  ns/op
[info] SizeCheckingBench.sizeIs         100  avgt    5  2.003 ± 0.006  ns/op
[info] SizeCheckingBench.sizeIs        1000  avgt    5  2.014 ± 0.016  ns/op
[info] SizeCheckingBench.sizeIs       10000  avgt    5  2.012 ± 0.014  ns/op
```
So, yeah, this is a 5% improvement at max (tested on `List` by equality check with '1').

A bit more efficient size checking for `Seq` collections

---

circe/src/main/scala/org/http4s/circe/DecodingFailures.scala
client/shared/src/main/scala/org/http4s/client/oauth1/oauth1.scala
core/shared/src/main/scala/org/http4s/MessageFailure.scala
core/shared/src/main/scala/org/http4s/RequestCookieJar.scala
core/shared/src/main/scala/org/http4s/internal/CurlConverter.scala

```
[info] Benchmark                      (listSize)  Mode  Cnt  Score   Error  Units
[info] stringBuildingWithIterator             10  avgt    5  6.249 ± 0.014  ns/op
[info] stringBuildingWithIterator            100  avgt    5  6.252 ± 0.056  ns/op
[info] stringBuildingWithIterator           1000  avgt    5  6.241 ± 0.006  ns/op
[info] stringBuildingWithoutIterator          10  avgt    5  6.576 ± 0.103  ns/op
[info] stringBuildingWithoutIterator         100  avgt    5  6.599 ± 0.006  ns/op
[info] stringBuildingWithoutIterator        1000  avgt    5  6.584 ± 0.044  ns/op
```
A little tricky (not that tricky tbh) thing that brings a 5% performance improvement for string building.

A bit more efficient string building from `Seq` collections

---

ember-core/shared/src/main/scala/org/http4s/ember/core/Encoder.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/EncoderSuite.scala

This PR replays https://github.com/http4s/http4s/pull/6444 for the ember request encoder. Specifically, when the body is known (by reference equality) to be the `EmptyBody` i.e. an empty `Stream`, then a `Content-Length: 0` header is added and chunked transfer encoding is disabled. This relates to https://github.com/http4s/http4s/issues/4935, and possibly even fixes it.

Special-case `EmptyBody` in request encoder

---

core/shared/src/main/scala/org/http4s/Query.scala
core/shared/src/main/scala/org/http4s/UrlForm.scala

```
[info] Benchmark           (size)  Mode  Cnt      Score      Error  Units
[info] MapBench.map            10  avgt    5    238.153 ±   40.219  ns/op
[info] MapBench.map           100  avgt    5   6024.884 ±  409.198  ns/op
[info] MapBench.map          1000  avgt    5  59488.263 ±  243.845  ns/op
[info] MapBench.mapValues      10  avgt    5    318.889 ±    2.540  ns/op
[info] MapBench.mapValues     100  avgt    5   6222.427 ±  104.340  ns/op
[info] MapBench.mapValues    1000  avgt    5  64835.303 ± 2168.535  ns/op
```
Test results are bouncing a little but nonetheless show that we should get a 5-10% performance boost at least.

Use `map` instead of `mapValues` on `Map`s

---

core/shared/src/main/scala/org/http4s/util/Renderable.scala

The performance of `Writer#addList` shouldn't change, but fewer allocations is also fine.

Don't instantiate redundant `NonEmptyList` in `Writer#addList`

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/Shutdown.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala

Fixes https://github.com/http4s/http4s/issues/6780.

`Shutdown#trackConnection` should never be empty

---

client/shared/src/main/scala/org/http4s/client/middleware/Retry.scala
core/shared/src/main/scala/org/http4s/Header.scala
core/shared/src/main/scala/org/http4s/Headers.scala
core/shared/src/main/scala/org/http4s/internal/Logger.scala
tests/shared/src/test/scala/org/http4s/HeadersSpec.scala

```
[info] Benchmark                            (size)  Mode    Cnt      Score      Error  Units
[info] currentMkString                        10     avgt    5      653.514 ±   37.092  ns/op
[info] currentMkString                        100    avgt    5     6576.612 ±  907.011  ns/op
[info] currentMkString                        1000   avgt    5    58623.540 ± 1841.507  ns/op
[info] newMkString                            10     avgt    5      422.176 ±   12.110  ns/op
[info] newMkString                            100    avgt    5     4197.781 ±   15.698  ns/op
[info] newMkString                            1000   avgt    5    34725.574 ±  234.841  ns/op
```
This adds new methods for `Headers` for string building. Also, this brings 55-70% performance improvement and definitely should reduce …

More efficient string building from `Headers`

---

project/Http4sPlugin.scala
server/shared/src/main/scala/org/http4s/server/middleware/CORS.scala

Introduces a bunch of Scala-version specific `@nowarnX` annotation which map to a real `scala.annotation.nowarn` according to the table:
| Scala | 2.12 | 2.13 | 3 |
| -- | -- | -- | -- |
| `@nowarn2` | ✅ | ✅ | ☠️ |
| `@nowarn212` | ✅ | ☠️ | ☠️ |
| `@nowarn213` | ☠️ | ✅ | ☠️ |
| `@nowarn3` | ☠️ | ☠️ | ✅ |
Also this PR re-fixes https://github.com/http4s/http4s/pull/6750#discussion_r994977997 in a nicer and more generic way (hopefully). As well as the proposed annotations can be used in the future to address similar issues related to differences in Scalac warning detection/generation.
Basically it should allow to avoid inventing ad-hoc solutions every time and let us simply use a set of `nowarn` options that works for all current cross-build Scala versions in the project.
Also, Scala3 may …

Scala specific nowarnX annotations

---

docs/docs/integrations.md
docs/styles/styles.css

After many complaints and questions, I finally did something about it.
Here's the old page: https://http4s.org/v0.23/docs/integrations.html
This is an opinionated refactor: I specifically highlighted Ember, and dropped IMHO not-so-important information from the table so that it renders better.
I also dropped the Async Http client because it's not maintained, and the OkHttp client because [nobody cares enough to add a README](https://github.com/http4s/http4s-okhttp-client). And self-promoted my own projects 😇

Revamp the integrations page

---

client-testkit/js/src/main/scala/org/http4s/client/testkit/scaffold/ServerScaffold.scala
client-testkit/jvm/src/main/scala/org/http4s/client/testkit/scaffold/ServerScaffold.scala
client/js/src/main/scala/org/http4s/client/NodeJSClientBuilder.scala
project/Http4sPlugin.scala
server/jvm/src/main/scala/org/http4s/server/middleware/CSRF.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/Nonce.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeperF.scala
server/shared/src/test/scala/org/http4s/server/middleware/authentication/NonceFSpec.scala
tests/shared/src/main/scala/org/http4s/testing/DispatcherIOFixture.scala
tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala
tests/shared/src/test/scala/org/http4s/multipart/MultipartsSuite.scala

Cats Effect 3.4.0-RC2 includes significant changes to `Queue` semantics which are used in Ember and especially Ember H2.
Do we want to publish our own RC candidate against this?

Update to Cats Effect 3.4.0-RC2

---

core/shared/src/main/scala/org/http4s/HttpDate.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala

Arguments for `@deprecated` are mixed up, which gives a bit confusing warnings like this one:
```
scala> HttpDate.now
^
warning: method now in object HttpDate is deprecated (since Use HttpDate.current instead, this breaks referential transparency): 0.20.16
```

Fix some deprecation warning messages

---

build.sbt
circe/src/main/scala/org/http4s/circe/CirceInstances.scala
core/shared/src/main/scala/org/http4s/util/Renderable.scala

Adding a couple `lazy val`s allows the Scala.js linker to completely elide the `java.time` package, reducing size of generated JavaScript by ~ ~~30%~~ 20%. Bincompat got in the way a bit. Oh well.

Reduce JS size

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/StreamForking.scala

Ensures that the fiber is always started. This in turn guarantees that we will decrement the running counter and release the semaphore.

Fix resource leaks

---

core/shared/src/main/scala/org/http4s/EntityDecoder.scala
tests/shared/src/test/scala/org/http4s/ServerSentEventSpec.scala

Fixes https://github.com/http4s/http4s/issues/6694. There was a reason this did not exist and I made a stupid mistake when I added it in https://github.com/http4s/http4s/pull/6413. Woops 😅 
Long story short, it's completely broken, and there is no way to fix it. See explanation in https://github.com/http4s/http4s/issues/6694#issuecomment-1254100122.
Separately, we should consider adding something so we can support streaming decoders such as this one.

Deprecate event stream entity decoder

---

client/shared/src/main/scala/org/http4s/client/Client.scala
client/shared/src/test/scala/org/http4s/client/ClientSuite.scala

PR to address Ref comment in https://github.com/http4s/http4s/pull/6325#pullrequestreview-951279467

removed the Ref boolean

---

core/shared/src/main/scala/org/http4s/internal/CharPredicate.scala

I'm in favor of removing this method since it's in the `internal` package and isn't used in the repo, but... Mima beats on the hands since that's a public class anyway.

Mark method `CharPredicate.asMaskBased` as deprecated

---

client/shared/src/main/scala/org/http4s/client/middleware/Retry.scala
core/shared/src/main/scala/org/http4s/HttpDate.scala

This fixes an unsuspended `Instant.now()`

Use `Temporal#realTime` in client retry middleware

---

core/shared/src/main/scala/org/http4s/Uri.scala
tests/shared/src/test/scala/org/http4s/SegmentSuite.scala

Let me know if I've picked the wrong place for the test!

Fix for 6851 : Uri.Path.Segment can throw from its equals method

---

build.sbt
server/shared/src/main/scala/org/http4s/server/middleware/DefaultHead.scala

```
[info] Benchmark                                     Mode  Cnt      Score      Error   Units
[info] InterruptWhenBench.interruptWhenIOBench      thrpt    5  14981.354 ±   47.508  ops/ms
[info] InterruptWhenBench.interruptWhenStreamBench  thrpt    5  11910.674 ± 1005.696  ops/ms
```
```scala
def stream: fs2.Stream[IO, String] =
fs2.Stream.emit("foo").repeat
@Benchmark
def interruptWhenStreamBench: IO[Unit] =
stream.interruptWhen(fs2.Stream(true)).compile.drain
@Benchmark
def interruptWhenIOBench: IO[Unit] =
stream.interruptWhen(IO.pure[Either[Throwable, Unit]](Right(()))).compile.drain
```

Tweak body interrupting for better performance of `DefaultHead` Middleware

---

client-testkit/js/src/main/scala/org/http4s/client/testkit/scaffold/ServerScaffold.scala
client-testkit/jvm/src/main/scala/org/http4s/client/testkit/scaffold/package.scala
core/shared/src/main/scala/org/http4s/websocket/WebSocketHandshake.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
server/shared/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeperF.scala

A follow-up of the discussion https://github.com/http4s/http4s/pull/6855#pullrequestreview-1212613727.

Use cached value of `Right(())` to avoid allocations

---

bench/src/main/scala/org/http4s/bench/QueryBench.scala
core/shared/src/main/scala/org/http4s/Query.scala

This PR aims to make a model of `Query` more straightforward (and to retire the allocation of `Either`).
```scala
final class Query private (value: Either[Vector[KeyValue], String])
```
versus
```scala
sealed trait Query extends QueryOps with Renderable
object Query {
case object Empty extends Query 
final class Raw private[http4s] (value: String) extends Query
final class Parsed private[http4s] (value: Vector[KeyValue]) extends Query
}
```
It's a proposal, so I'm open to any comments on that.
Performance within fluctuation remained the same.
before
```
[info] Benchmark                        (size)   Mode  Cnt       Score       Error   Units
[info] QueryBench.filterParsedQuery          0  thrpt    5  101507.478 ±   419.039  ops/ms
[info] QueryBench.filterParsedQuery         10  thrpt …
```

Proposal: Change `Query` model

---

server/shared/src/main/scala/org/http4s/server/middleware/DefaultHead.scala

No one binary-compatibility ranger can't stop me from doing this refactoring in the 1.0 series 😉

Clean up `DefaultHead` middleware

---

docs/docs/client.md

The current return type of `Uri.fromString` in `client.md` docs is `Either[ParseFailure, Uri]`. But, actually return type is `ParseResult[Uri]`. This PR is fixes it.
https://github.com/http4s/http4s/blob/008602f534c82dda4cc79cd8d8add6a56c250da3/core/shared/src/main/scala/org/http4s/Uri.scala#L212
```scala
scala> import org.http4s.Uri
import org.http4s.Uri
scala> Uri.fromString(validUri)
val res0: org.http4s.ParseResult[org.http4s.Uri] = Right(https://my-awesome-service.com/foo/bar?wow=yeah)
scala> Uri.fromString(invalidUri)
val res1: org.http4s.ParseResult[org.http4s.Uri] =
Left(org.http4s.ParseFailure: Invalid URI: yeah whatever
^
expectation:
* must end the string)
```
---
Thank you :)

Update `Uri.fromString` return type in client docs

---

client/shared/src/main/scala/org/http4s/client/DefaultClient.scala
core/shared/src/main/scala/org/http4s/headers/Accept.scala

This PR tweaks `Accept` header constructions:
- in the `Parser` when we already have a `NonEmptyList`
- in `DefaultClient` when we can easily make a `NonEmptyList`

Tweak `Accept` usage to avoid variadic construction

---

core/shared/src/main/scala/org/http4s/internal/Logger.scala

A counterpart to #6880. Kudos to @armanbilge for finding this initially.
* throughput:
```
Benchmark                                  (size)  Mode  Cnt    Score     Error   Units
CurrentStringBuilding                        100  thrpt    5   95.480 ±   0.631  ops/ms
CurrentStringBuilding                       1000  thrpt    5   30.786 ±   0.392  ops/ms
CurrentStringBuilding                      10000  thrpt    5    4.903 ±   0.028  ops/ms
StreamToByteVectorStringBuilding             100  thrpt    5  166.562 ±   5.433  ops/ms
StreamToByteVectorStringBuilding            1000  thrpt    5   80.068 ± 106.562  ops/ms
StreamToByteVectorStringBuilding           10000  thrpt    5   17.376 ±   0.389  ops/ms
StreamToChunksToByteVectorStringBuilding     100  thrpt    5   96.616 ±   0.833  ops/ms …
```

Tweak stream compiling to hex string in `Logger`

---

core/shared/src/main/scala/org/http4s/Charset.scala
core/shared/src/main/scala/org/http4s/internal/Logger.scala

Sorry for not bringing benchmarks this time, but building a `String` from `Entity.Strtict` directly should have better performance for throughput/memory consumption than building a `Stream` and building a `String` from it.

Log a `Message` body considering the `Entity` model

---

build.sbt
js-artifact-size-test/src/test/scala/Main.scala

JS-Artifact: set header copyright to 2022

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

The stream generated by the call to unfoldEval emits requests-response pairs, but the downstream only uses the response to decide if it continues pulling from that stream. Thus we reduce what the stream emits.
This in turn triggers a lot of Scalafmt changes to the block. 
Reviewers may find it convenient to hide whitespace changes

Ember server reduce state

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala

_Not intended to actually merge into `update/series/0.23/vault-3.5.0`, the base should change when https://github.com/http4s/http4s/pull/6892 merges._
This PR simply uses the [new `contains` method](https://www.javadoc.io/doc/org.typelevel/vault_2.13/latest/org/typelevel/vault/Vault.html#contains(k:org.typelevel.vault.DeleteKey):Boolean) on `Vault` when checking for Http2PriorKnowledge.

Use Vault#contains to check for PriorKnowledge

---

flake.nix

The temurin package doesn't exist for all architectures, notably aarch64-darwin.  The temurin is for CI.  This is so users with Apple Silicon can build locally.

Use jdk8 in default devshell

---

build.sbt

We are seeing a lot of OOMs in JS CI lately. Let's see if this helps.

Try limiting Node.js heap size to 1GB

---

core/shared/src/main/scala/org/http4s/ProductIdOrComment.scala
core/shared/src/main/scala/org/http4s/headers/HeaderCompanion.scala
core/shared/src/main/scala/org/http4s/headers/Server.scala
core/shared/src/main/scala/org/http4s/headers/User-Agent.scala
core/shared/src/main/scala/org/http4s/internal/parsing/CommonRules.scala
docs/changelog.md
tests/shared/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

Merges and release notes.
I tried to pull out the last version of the user-facing dependency updates.  We don't have automation around that.

Post-0.23.17 cleanup

---

core/shared/src/main/scala/org/http4s/Charset.scala
core/shared/src/main/scala/org/http4s/HttpVersion.scala
core/shared/src/main/scala/org/http4s/Uri.scala
core/shared/src/main/scala/org/http4s/headers/Access-Control-Max-Age.scala
core/shared/src/main/scala/org/http4s/headers/Age.scala
core/shared/src/main/scala/org/http4s/headers/Content-Type.scala
core/shared/src/main/scala/org/http4s/headers/Sec-WebSocket-Version.scala
core/shared/src/main/scala/org/http4s/internal/CharPredicate.scala
scalafix-internal/input/src/main/scala/fix/GeneralLintersTest.scala
scalafix-internal/output/src/main/scala/fix/GeneralLintersTest.scala
scalafix-internal/rules/src/main/scala-2/fix/GeneralLinters.scala

Scala 2.13 creates the copy constructor with the same visibility as the primary constructor.  This is a good lint, but only pertinent through 2.12.

Remove nonValidatingCopyConstructor linter

---

bench/src/main/scala/org/http4s/bench/ChunkWriterBench.scala
core/shared/src/main/scala/org/http4s/internal/ChunkWriter.scala

* Throughput before changes:
```
Benchmark           (size)   Mode  Cnt      Score     Error   Units
appendSingleString     100  thrpt    5  21439.685 ± 814.071  ops/ms
appendSingleString    1000  thrpt    5   7990.988 ± 311.376  ops/ms
appendSingleString   10000  thrpt    5    762.789 ±  65.330  ops/ms
appendStringBatch      100  thrpt    5    366.361 ±  21.818  ops/ms
appendStringBatch     1000  thrpt    5     36.774 ±   0.392  ops/ms
appendStringBatch    10000  thrpt    5      3.120 ±   0.066  ops/ms
```
* Memory consumption before changes:
```
appendSingleString:·gc.alloc.rate.norm        100  avgt    5      464.018 ±     0.001    B/op
appendSingleString:·gc.alloc.rate.norm       1000  avgt    5     2272.061 ±     0.001    B/op
appendSingleString:·gc.alloc.rate.norm      10000  avgt …
```

Use `Chunk` builder instead of `Buffer` in `ChunkWriter`

---

core/shared/src/main/scala/org/http4s/headers/Server.scala
core/shared/src/main/scala/org/http4s/headers/User-Agent.scala
core/shared/src/main/scala/org/http4s/internal/parsing/CommonRules.scala

A user has reported a StackOverflowError initializing CommonRules.  This PR reduces stack consumption.
1. A parser that triggers it is made lazy so what isn't used can't hurt anyone.
2. The default depth is reduced, so it works on smaller-stack environments.
3. The default depth is referenced from a canonical constant in the relevant header instances.

Fix StackOverflowError initializing CommonRules

---

build.sbt

Because we are still seeing OOMs in CI 😕

Even less memory for Node.js

---

circe/src/main/scala/org/http4s/circe/CirceInstances.scala

As we explored in https://github.com/http4s/http4s/pull/6919, building `Chunk` from its builder should be faster than from anything else.

Use `Chunk` builder in `CirceInstances#streamedJsonArray`

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala

Fix connection hanging when response body stream fails. This was fixable by supplying a custom `onWriteFailure` that throws but the default behaviour was confusing.
Associated Discord discussion can be found [here](https://discord.com/channels/632277896739946517/839254871646404638/1065301202444763236).

Fix hanging when stream fails

---

server/shared/src/test/scala/org/http4s/server/middleware/BracketRequestResponseSuite.scala

A tiny readability improvement.

Refactor `Outcome` usage in `BracketRequestResponseSuite`

---

docs/docs/quickstart.md

Adds a handy list of a few dependencies in sbt format on the quickstart page.
Inspired by a user request in discord. I also like having these easily discoverable.

Add section with sbt dependencies to quickstart

---

core/shared/src/main/scala/org/http4s/metrics/MetricsOps.scala
tests/shared/src/test/scala/org/http4s/metrics/MetricsOpsSpec.scala

Some minor refactoring. _Review changes only with the hiding of whitespace._

Tweak `MetricsOps#classifierFMethodWithOptionallyExcludedPath`

---

core/shared/src/main/scala/org/http4s/EntityDecoder.scala

E.g. to append to an existing file.

Allow to customize flags for file decoders

---

build.sbt
client/jvm/src/main/scala/org/http4s/client/JavaNetClientBuilder.scala

`Sync` is sufficient, but making the change bincompatibly on `series/0.23` is not possible. Update: nevermind it was 😇 
Not sure how useful this is, but for example in our docs we _could_ use it to build a `Client[SyncIO]` that we can `unsafeRunSync()` without an implicit `IORuntime`. But that might be confusing.

`JavaNetClient` does not need `Async`

---

docs/adopters.md

`website/src/hugo/content/adopters.md` does not exist in `main` anymore.

Fix link to edit `adopters.md`

---

core/shared/src/main/scala/org/http4s/internal/package.scala
server/jvm/src/main/scala/org/http4s/server/middleware/CSRF.scala

An attendant PR to the merged https://github.com/http4s/http4s/pull/6984. 
As it was previously, the method from `scodec` needs some performance tweaks.
It'd be lovely if @mpilquist could do a miracle once again 🙏🏻 
But, this time the difference isn't that dramatic for real-world usage.
```
[info] DecodeHexBench.decodeHexHttp4s    1000  thrpt    5  154.654 ± 11.577  ops/ms
[info] DecodeHexBench.decodeHexHttp4s   10000  thrpt    5   13.714 ±  0.116  ops/ms
[info] DecodeHexBench.decodeHexHttp4s  100000  thrpt    5    1.524 ±  0.507  ops/ms
[info] DecodeHexBench.decodeHexScodec    1000  thrpt    5   81.527 ±  4.917  ops/ms
[info] DecodeHexBench.decodeHexScodec   10000  thrpt    5    3.923 ±  0.063  ops/ms
[info] DecodeHexBench.decodeHexScodec  100000  thrpt    5    0.425 ±  0.024  ops/ms
```

Use `ByteVector#fromHex` in `CSRF` Middleware

---

docs/changelog.md

One more RC round! This one included some subtle changes to `race` laws/semantics in CE.

Release v0.23.19-RC2

---

ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
ember-core/js/src/main/scala/org/http4s/ember/core/UtilPlatform.scala
ember-core/jvm/src/main/scala/org/http4s/ember/core/UtilPlatform.scala
ember-core/native/src/main/scala/org/http4s/ember/core/UtilPlatform.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala

Hi,
We are having issue using Ember client instead of Blaze client due to our custom certificat that needs both endpoint verification and TLS SNI disabled.
If we try with Java NET, the following succeeds with the commented line, or fails if uncommented:
```
val connection = new URL("https://my-endpoint.com").openConnection().asInstanceOf[HttpsURLConnection]
connection.setSSLSocketFactory(ourSslContext.getSocketFactory)
// connection.setHostnameVerifier((hostname, session) => true)
connection.setDoOutput(true)
connection.setRequestMethod("GET")
val br = new BufferedReader(new InputStreamReader(connection.getInputStream))
println(br.readLine())
```
Here is the error:
```
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: …
```

Add ability to disable SNI in Ember

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala

Fixes https://github.com/http4s/http4s/issues/7014.

Redirect `H2Connection.writeLoop` errors to logger

---

docs/changelog.md

Yes, another RC 😅 this one is just for us, no CE / FS2 bumps.
Our hands are tied with the RC, but arguably this makes sense anyway for the changes in https://github.com/http4s/http4s/pull/6980 and https://github.com/http4s/http4s/pull/7008.
Also, we are overdue for a merge into `main` I think ...

Release v0.23.19-RC3

---

build.sbt

We get this workaround for Scala Native from the `sbt-http4s-org` plugin.

Tweak `build.sbt`

---

docs/docs/integrations.md

https://github.com/http4s/http4s/blob/96428ee587edbd343226153faff8df871c93e12a/docs/docs/integrations.md?plain=1#L33
The old link does not work. Whereas https://jdk-http-client.http4s.org redirects to the latest release version automatically. So I think it should be a safe change.

Fix a broken link to JDKHttpClient in the docs

---

core/shared/src/main/scala/org/http4s/headers/Sec-WebSocket-Accept.scala
core/shared/src/main/scala/org/http4s/headers/Sec-WebSocket-Key.scala
core/shared/src/main/scala/org/http4s/internal/parsing/Rfc4648.scala
laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
tests/shared/src/test/scala/org/http4s/headers/SecWebSocketAcceptSuite.scala
tests/shared/src/test/scala/org/http4s/headers/SecWebSocketKeySuite.scala

Base64 contains uppercase and lowercase characters (A-Z, a-z), digits (0-9), and the "+" and "/" characters, and ends with 0 to 2 "=" characters. The previously used parser does not allow the "+" and "/" characters and does not check for "=" characters at the end.

Fix base64 parser for http headers Web-Socket-Key and Web-Socket-Accept

---

bench/src/main/scala/org/http4s/bench/QueryBench.scala
core/shared/src/main/scala/org/http4s/QueryOps.scala

- throughput
```
Benchmark                             (size)   Mode  Cnt      Score     Error   Units
QueryBench.withQueryParamParsedQuery       0  thrpt    5  26645.918 ± 365.286  ops/ms
QueryBench.withQueryParamParsedQuery      10  thrpt    5  24688.383 ±  81.462  ops/ms
QueryBench.withQueryParamParsedQuery     100  thrpt    5   2515.062 ±   5.276  ops/ms
QueryBench.withQueryParamParsedQuery    1000  thrpt    5    206.958 ±   0.536  ops/ms
QueryBench.withQueryParamRawQuery          0  thrpt    5  25385.754 ±  21.232  ops/ms
QueryBench.withQueryParamRawQuery         10  thrpt    5  23735.831 ± 638.432  ops/ms
QueryBench.withQueryParamRawQuery        100  thrpt    5   2511.501 ±   2.668  ops/ms
QueryBench.withQueryParamRawQuery       1000  thrpt    5    218.707 ±   1.387  ops/ms
```
- …

Tweak performance of `QueryOps#withQueryParam` 

---

server/shared/src/main/scala/org/http4s/server/Router.scala

This removes a redundant check that the prefix corresponds to the request's path. It's nothing impressive but a 10% improvement in throughput.

Tweak the `Router#translate`

---

build.sbt
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/Hpack.scala

1. use `ByteVector#toInputStream` and `ByteVectorOuputStream` for copy-free conversions
2. use `List.newBuilder` instead of `ListBuffer` (not sure if this makes a difference, but intent is clearer)
3. use `Mutex` instead of `Sempahore(1)` (performance is optimized and communicates intent)

`Hpack` optimizations

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala

Make the class constructor private, and extract an F-ectful
factory method that initialises the write block. 
-------

Ember-Core State - Extract factory method

---

build.sbt
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/h2/H2StreamSuite.scala

Fixes https://github.com/http4s/http4s/issues/7060.
An FS2 `Channel` replaces the `Queue` used for the `readBuffer`. A `Channel` offers two advantages for us:
1. It can be explicitly closed (this fixes the bug, will explain further inline).
2. It is optimized for single-consumer as a `Stream`, which is precisely our usecase.

Use `Channel` for H2 `readBuffer`

---

docs/changelog.md

Our first stable release in several months, which includes numerous bug fixes accumulated since v0.23.19-RC1. Let's get it out the door!

Release v0.23.19

---

docs/docs/server-middleware.md

Just a quick fix on the documentation #7117

fixes Wrong link in "Server Middleware" page in the docs #7117

---

docs/docs/dsl.md

Added more examples to the doc ( shortcut to create Responses)

---

core/shared/src/main/scala/org/http4s/ContextRoutes.scala

Added some useful constructors to ContextRoutes that existed on HttpRoutes.

Add missing constructors to ContextRoutes

---

docs/changelog.md

Ember H2 is broken without this patch.

Release v0.23.20

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala

More fixing following https://github.com/http4s/http4s/pull/7147. That fix had the right idea, it just needed to be applied in a couple other places.
Unfortunately we currently cannot exercise this case with ember client on `series/0.23`. Due to the limitations of the entity model it always sends the `endStream` on the body (instead of on the headers). However if we port https://github.com/http4s/http4s/pull/6752 to H2 then it would exercise this case and we could also do so on `main`.

Close H2 `readBuffer` on `headers.endStream`

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

Fixes https://github.com/http4s/http4s/issues/7149.
Ok, so I'm not entirely sold on this change. Masking errors seems like a world of pain when things go wrong in unexpected ways. Here's my thinking:
1. all errors _should_ already be reported through side-channels. So letting them leak to the unhandled error reporting just results in duplicate logging.
2. Random unhandled errors popping up is very unpopular. This issue is not the first time we've gotten complaints.
https://github.com/http4s/http4s/issues/7149
I did have one other implementation idea: after reporting an error through a side-channel, we could self-cancel the current fiber. Then, there would be no need to mask errors, and any errors that did appear would be legit. However, cancelation is rather drastic (unrecoverable) and …

Mask errors in Ember server `runConnection`

---

circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
client/js/src/main/scala/org/http4s/client/NodeJSClientBuilder.scala
core/shared/src/main/scala/org/http4s/TransferCoding.scala
core/shared/src/main/scala/org/http4s/Uri.scala
core/shared/src/main/scala/org/http4s/internal/package.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/PseudoHeaders.scala
laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
tests/shared/src/test/scala/org/http4s/SchemeSuite.scala
tests/shared/src/test/scala/org/http4s/TransferCodingSpec.scala

Follow up on #3442 and #7158. Fixes parts of #7031.
Replaced internal case insensitive implementation with `CIString`

Migrate `Uri.Scheme` and `TransferCoding` to `CIString`

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala

Use `MonadThrow` instead of `Sync` in `H2Client.RequestKey#getAddress`

---

.github/workflows/ci.yml
build.sbt

This is extremely annoying but the uploaded artifacts have gotten too big for CI 😢 I was finally able to publish v0.23.21 after disabling.

Disable artifact upload

---

core/shared/src/main/scala/org/http4s/Uri.scala
core/shared/src/main/scala/org/http4s/internal/package.scala

This removes some of the things mentioned in #7031.
I could also replace `hashLower` in the whole repo as suggested in the comment. This could be done by using CIString for `class TransferCoding` and `class Scheme` which would be correct according to RFC, but breaking.

Clear the internal package of unused/deprecated things

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/PseudoHeaders.scala
ember-core/shared/src/test/scala/org/http4s/ember/core/h2/PsuedoHeadersSuite.scala

RFC 7540 specifies query params must be included in the :path pseudo header, without this change, ember would just silently discard them.
Closes #7178

Include query params in http2 :path pseudo header

---

core/shared/src/main/scala/org/http4s/QueryOps.scala

This is a follow-up to #7106. Whatever we decide about changing the Queries API, this scaladoc is misleading, and we can fix it sooner.

Fix `QueryOps#setQueryParams` scaladoc

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

See also: https://github.com/typelevel/fs2/pull/3215
Running `sbt quicklint` gives off these:
```
[error] failed to generate semanticdb for E:\work\scala\http4s\ember-server\shared\src\test\scala\org\http4s\ember\server\EmberServerSuite.scala:
[error] java.lang.IllegalArgumentException: 5184 is not a valid offset, allowed [0..5179]
[error]         at scala.meta.internal.inputs.InternalInput.offsetToLine(InternalInput.scala:48)
[error]         at scala.meta.internal.inputs.InternalInput.offsetToLine$(InternalInput.scala:42)
[error]         at scala.meta.inputs.Input$File.offsetToLine(Input.scala:51)
[error]         at scala.meta.inputs.Position$Range.endLine(Position.scala:39)
[error]         at scala.meta.internal.inputs.package$XtensionPositionToRange$.toRange$extension(package.scala:47) …
```

Properly handle `NoSuchElementException` in `tlsSocket.applicationProtocol`

---

ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

When someone tries to make non-SSL connection to your SSL HTTP server you get this in your log:
```
[o.h.e.s.EmberServerBuilderCompanionPlatform] Request handler failed with exception
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:146)
at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:557)
at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
at …
```

Allow providing custom error handler when connection establishing fails.

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

Technically this is probably a small optimization—we can completely avoid calling the logging callback when trace logging is disabled.
But the real motivation is to work around the fact that on JS, TLS logging is not customizable unfortunately, it's either on-or-off.
https://github.com/typelevel/fs2/blob/d7f1b71a8d7badb8a7ef0a8a5468807f9e384358/io/js/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala#L77

Disable Ember server TLS logging more aggressively

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala

Chunk has a slightly more efficient traverse_ method than lists.

WebSocketHelpers.scala - Use Chunks

---

build.sbt
ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala

These can be deceptive in their current state - I had a URL with underscores, which org.http4s.Uri was happy with, but when I used it with ember client, ip4s.Uri was NOT happy with it, so I was getting a misleading "missing host" error, even though there was a host.

Improve error messages for MissingHost and MissingPort

---

server/shared/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
server/shared/src/test/scala/org/http4s/server/middleware/EntityLimiterSuite.scala

The current implementation is too strict—it's not always possible to know if a stream has ended without evaluating a "tail" effect. The new implementation begins evaluating the tail before deciding whether or not to raise an error.

Fix handling of streaming bodies in entity limiter

---

core/shared/src/main/scala/org/http4s/MediaType.scala

Scala Native has similar problems to Scala.js since both do whole program linking.
Disabling the MimeDB in Scala Native improves the binary size and linking time!
Here you see a comparison of linking a http4s hello world application in debug mode before and after the change:
<table>
<tr><th></th><th>Before</th><th>After</th></tr>
<tr><th>Binary size</th><td>~24.5 MB</td><td>~17.4 MB</td></tr>
<tr><th>Linking time</th><td>~19 seconds</td><td>~13 seconds</td></tr>
</table>
This makes it much more fun to build http4s applications with Scala Native! :)
Most credit goes to @keynmol who told me what MimeDB was and that it was excluded from Scala.js :)

Avoid linking MimeDB in Scala Native

---

core/shared/src/main/scala/org/http4s/Credentials.scala

This PR provides a fix for #7283 by replacing the existing `BasicCredentials.apply` constructor with `BasicCredentials.fromString` and using it in `BasicCredentials.unapply` to make pattern matching safe too.

Fixes #7283: make BasicCredentials constructor safe

---

core/shared/src/main/scala/org/http4s/headers/Cookie.scala
tests/shared/src/test/scala/org/http4s/parser/CookieHeaderSuite.scala

This updates the cookie header parser to handle zero or more spaces between semicolons, whereas the current code only handles a single space. For example, these are both currently invalid, but are considered valid with these changes:
```
Cookie: foo=bar;baz=quux
Cookie: foo=bar;  baz=quux
```
While this technically goes against the HTTP spec, I have seen it happen (and just had to fix a bug in production because of it 😅) and there seems to be precedent for going a little off spec, e.g. by [handling trailing semicolons in request cookies](https://github.com/http4s/http4s/blob/series/0.23/core/shared/src/main/scala/org/http4s/headers/Cookie.scala#L42) and by [handling zero or more spaces in `Set-Cookie` headers](https://github.com/http4s/http4s/blob/series/0.23/core/shared/src/main/scala/org …

Update request cookie parser to handle zero or more spaces between semicolons

---

ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala

Next FS2 upgrade will include the changes by @kamilkloch in https://github.com/typelevel/fs2/pull/3264 which could improve performance of this loop.

Ember-Core: Use optimised fs2 method in write Loop.

---

build.sbt
docs/docs/client-middleware.md
docs/docs/directory.conf

I hope using scala-cli in the domain sockets part is ok, I figure there's some chance of bitrot (because it's not an mdoc block) but I don't seem to be able to use ember server/client from here to make a self-contained example.
I don't mind the DestinationAttribute section existing but I could take it off if needed.

Add client middleware documentation

---

core/shared/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala

Hi, this PR implements a fix for https://github.com/http4s/http4s/issues/7262 by only catching errors related to decoding failures in `MultipartDecoder`.
Thanks!

Fix #7262: mulitpart decoder wrapping unwanted errors

---

ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala

Adds a warning log on startup for Ember clients & servers when timeouts have likely been misconfigured
Corresponds to similar logs on Blaze [Server](https://github.com/http4s/blaze/blob/b4c5565493feea1ea99a4ca19a364bd144d0d29b/blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala#L452C50-L460) and [Client](https://github.com/http4s/blaze/blob/b4c5565493feea1ea99a4ca19a364bd144d0d29b/blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala#L331-L349). As far as I understand, these warnings still apply (with the caveat that the Ember client has removed the specific `requestTimeout`, which can instead now be achieved using middleware)
In particular, reduces the risk of a user increasing `timeout` in the client and forgetting to update …

Add warning logs for misconfigured timeouts

---

ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/Defaults.scala
ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala

Fixes: [#7327 ](https://github.com/http4s/http4s/issues/7327)

Align the server and client idle timeouts in Ember

---

client-testkit/shared/src/main/scala/org/http4s/client/testkit/WSTestClient.scala
client-testkit/shared/src/test/scala/org/http4s/client/testkit/WSTestClientSuite.scala

Previously, `receive` was hanging when the connection closed, now it returns `None` as promised in the API.

Fix handling of connection closure in `WSTestClient`

---

docs/changelog.md

Let's ship the fix for that pesky warning in logs in ember-client.

Draft the `v0.23.25` release notes

---

.github/release.yml
.mergify.yml

We encountered this when releasing yesterday with the fix in the `client-testkit` done by @armanbilge.

Fix labelling PRs for the `client-testkit` module

---

docs/docs/dsl.md

Tiny PR that adds an example to the docs for how one might use the `OptionalMultiQueryParamDecoderMatcher`

Add OptionalMultiQueryParamDecoderMatcher Documentation

---

ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala

fixes #7356 
Prevent error logs when client closes connection during socket upgrade.

Log errors in `upgradeSocket`

---

core/shared/src/main/scala/org/http4s/internal/parsing/CommonRules.scala

remove deprecated `comment` parser from CommonRules

---

client/shared/src/main/scala/org/http4s/client/dsl/io.scala

It appears that this scaladoc is completely outdated. But it's intended to be frequently peeked at, so let's at least refresh it.

Fix the outdated code snippet in the client dsl scaladoc

---

docs/docs/auth.md

I removed the reference to the TSec library in the documentation as it seems like it is in the process of being deprecated. The original repo is archived and the fork https://github.com/davenverse/tsec has this in the readme: This software is in the process of finding its way out of your builds. This is maintained only for compatibility and security fixes. We hope you will work with others to find solutions to this space for the Scala community.
There is also:
- https://github.com/pac4j/http4s-pac4j
- https://github.com/profunktor/http4s-jwt-auth
A link to these could be useful, but they might grow stale like the TSec one, and it is probably not the responsibility of the http4s documentation to link to these?

Removed reference to TSec in documentation

---

core/shared/src/main/scala/org/http4s/h2/H2Keys.scala
ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
ember-server/js-jvm/src/test/scala/org/http4s/ember/server/EmberUnixSocketSuite.scala
ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
examples/ember/src/main/scala/com/example/http4s/ember/EmberClientH2Example.scala

This should rather live in http4s-client so more clients have a standard way to detect weather the request should be sent into http/2 prior knowledge land.
Had to put this into core, since H2Client lives in ember-core and should not depend on client.

Move ember H2Keys Http2PriorKnowledge key to core

---

client/shared/src/main/scala/org/http4s/client/DefaultClient.scala

Saw some unsafe calls:
- `NonEmptyList.fromListUnsafe`
- `m.head` where `m` is a `List`, not a `NonEmptyList`
that could be easily refactored to a safe call, and an opportunity to move some repeated code into a private function.

Small refactor to DefaultClient to remove unsafe calls and repeated code

---

core/shared/src/main/scala/org/http4s/websocket/protocolexceptions.scala

When an user sends `0x4` opcode to [websocket](https://github.com/http4s/http4s/blob/v0.23.26/examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala#L74-L81) following exception is printed:
```
[io-compute-8] ERROR o.h.e.s.EmberServerBuilderCompanionPlatform - WebSocket connection terminated with exception
org.http4s.websocket.ReservedOpcodeException: Opcode 4 is reserved for future use as per RFC 6455
at org.http4s.websocket.package$.makeFrame(package.scala:49)
at org.http4s.websocket.FrameTranscoder.bufferToFrame(FrameTranscoder.scala:187)
at org.http4s.ember.server.internal.WebSocketHelpers$.$anonfun$decodeFrames$3(WebSocketHelpers.scala:208)
at cats.ApplicativeError.catchNonFatal(ApplicativeError.scala:269)
at …
```

feat: suppress stack trace on protocol exceptions

---

core/shared/src/main/scala/org/http4s/multipart/Part.scala

`nameDecoded` and `filenameDecoded` have no error channel (aside from Option's `Unit`).  Instead of providing a function and an overly constrained error type, we just expose the name and filename as a Chunk of bytes and leave error handling to the caller.
The nullary and Charset based methods handle their own errors by using replacement characters and are unaffected.

Replace "*Decoded" Part methods with "*Bytes"

---

core/shared/src/main/scala/org/http4s/ResponseCookie.scala
tests/shared/src/test/scala/org/http4s/HeadersSpec.scala

I had trouble parsing a 'discard cookie' `Set-Cookie` header from Play Framework which specified a `Max-Age=0`.
Upon examination http4s ignores cookies with a Max-Age that doesn't contain the characters 1-9.  [RFC 6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.2.2) is murky on this point, specifying both non-zero digits in the syntax but also saying that zero or lower numbers should be parsed in the prose of section 5.2.2. I think it's safe to say that setting a `Max-Age=0` is common practice when invalidating a cookie.
The http4s client shouldn't then hide it from users in Responses by failing to parse, zero values should be permitted in the parser.

RFC: Cookies with `Max-Age=0` should be permitted

---

core/js/src/main/scala/org/http4s/nodejs/ClientRequest.scala
core/js/src/main/scala/org/http4s/nodejs/IncomingMessage.scala
core/js/src/main/scala/org/http4s/nodejs/ServerResponse.scala

[Arman](https://github.com/armanbilge) suggested changing the traits and objects from private to public so that they could be used in [Feral](https://github.com/typelevel/feral).
Ran `sbt quicklint` and no changes from the last commit on this branch.

Made traits and objects public for Node.js files

---

.github/workflows/ci.yml
build.sbt

series/0.23 is having trouble finding cachix after the latest flake update.  Speculating that getting on more current GitHub actions will help.

Fix bitrotten Nix actions

---

ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala

On JDK 17+, the exception has changed when a connection reset occured.
We have this stack trace :
java.io.IOException: Connection reset
at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(Unknown Source)
at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(Unknown Source)
at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(Unknown Source)
at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(Unknown Source)
at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
at delay @ …

Ember Client : Retry when connection reset on JDK 17+

---

core/shared/src/main/scala/org/http4s/internal/CurlConverter.scala

That should be a little better from a performance and memory consumption perspective.

Address the Entity model in `CurlConverter.requestToCurlWithBody`

---

core/shared/src/main/scala/org/http4s/metrics/CustomLabels.scala
core/shared/src/main/scala/org/http4s/util/SizedSeq.scala

After consuming the [latest SNAPSHOT](https://s01.oss.sonatype.org/content/repositories/snapshots/org/http4s/http4s-core_2.13/0.23.27-121-b8811f9-SNAPSHOT/) of `http4s` core, this `http4s-prometheus-metrics` [build](https://github.com/http4s/http4s-prometheus-metrics/actions/runs/10725779196/job/29744402752?pr=168) failed:
```
org.http4s.metrics.prometheus.PrometheusServerMetricsSuite:
==> X org.http4s.metrics.prometheus.PrometheusServerMetricsSuite.A http routes with a prometheus metrics middleware should register a 2xx response  0.039s java.lang.NullPointerException: null
at org.http4s.metrics.prometheus.Prometheus.createMetricsCollection(Prometheus.scala:344)
at org.http4s.metrics.prometheus.Prometheus.buildCustomMetricsOps(Prometheus.scala:131)
at …
```

Fix EmptyCustomLabels and SizedSeq0 singleton creation issue

---

core/shared/src/main/scala-2/org/http4s/LiteralSyntaxMacros.scala
tests/shared/src/test/scala/org/http4s/LiteralSyntaxMacrosSuite.scala

without the `_root_` in the uri macro, the added test fails to compile with `error: value http4s is not a member of String`
This issue was originally fixed in #741, but in the intervening years + refactors the `_root_` qualifier was dropped. I'm just re-adding it, and I'm adding it to all the literal macros just to be safe. 
fixes #704

Fix for Uri macro with `org` variable

---

docs/changelog.md

This is a maintenance release to fix scalafix processing exceptions in http4s modules.

prep for v0.23.29: update changelog

---

.scala-steward.conf

It seems we unintentionally brought an issue after the recent 0.23 -> main merge.

Fix Scala Steward config

---

ember-core/shared/src/test/scala/org/http4s/ember/core/h2/H2StreamSuite.scala

Follow up https://github.com/http4s/http4s/pull/7582
To follow the state transition in
https://httpwg.org/specs/rfc7540.html#StreamStates, client stream should start from idle state.
The original test is not wrong, but new one covers more scenarios for stream state transition, that would prevent bugs from sneaking into codebase in the future.

tidy: client stream should start from idle state

---

core/shared/src/main/scala/org/http4s/headers/X-Forwarded-Host.scala
tests/shared/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala

Alternative to #6979.
Partially addresses #5010.

Add `X-Forwarded-Host` header

---

server/shared/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
server/shared/src/main/scala/org/http4s/server/package.scala
server/shared/src/test/scala/org/http4s/server/middleware/EntityLimiterSuite.scala

Materializing my suggestions from https://github.com/http4s/http4s/pull/7602#issuecomment-2542072000

Respond with a 413 when raising an `EntityTooLarge` 

---

.github/workflows/ci.yml
project/Http4sPlugin.scala
project/plugins.sbt

So, here’s a 'maintenance paradox' — updating scala2 version to 2.13.16 requires `ch.epfl.scala:scalafix-testkit_2.13` to be published for 2.13.16, which version is currently 0.13. However, that scala2 version is supported in 0.14, which comes with the update of `sbt-http4s-org` to 0.17.7. But then, that update requires scala2 to already be at version 2.13.16 (as per the update of `ch.epfl.scala:scalafix-testkit_2.13`).
That's why this is present.

Update `Scala2` and `sbt-http4s-org`

---

docs/docs/quickstart.md

This is a follow up from https://github.com/http4s/http4s.g8/pull/438 where mill build tool support was added for Scala 2.x.

Document Scala 2.x mill giter8 template support
