http4s/http4s

- core/src/main/scala/org/http4s/headers/Content-Location.scala
- core/src/main/scala/org/http4s/parser/ContentLocationHeader.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- tests/src/test/scala/org/http4s/parser/ContentLocationHeaderSpec.scala
Another header modeled `Content-Location` which is basically the same as `Location`
> Model Content-Location header

- .github/workflows/ci.yml
- core/src/main/scala/org/http4s/parser/CookieHeader.scala
Check formatting in CI instead of just formatting.
> Check formatting in CI

- .github/workflows/ci.yml
- core/src/main/scala/org/http4s/parser/ContentLocationHeader.scala
I think this got changed back in a merge from 0.20.
> Use correct scalafmt check command

- server/src/main/scala/org/http4s/server/middleware/Logger.scala
> Fix logger json detection

- project/Http4sPlugin.scala
- website/src/hugo/content/changelog.md
Just the dependency bumps that were left behind in #3262.
> Release v0.20.21

- .mergify.yml
> Update mergify rules for Scala 2.12.11

- blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala
- client/src/main/scala/org/http4s/client/Client.scala
- client/src/test/scala/org/http4s/client/PoolManagerSpec.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExampleWithRedirect.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/ClientExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/ClientPostExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/MultipartClient.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/StreamClient.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Server.scala
- examples/docker/src/main/scala/com/example/http4s/Example.scala
- examples/jetty/src/main/scala/com/example/http4s/jetty/JettyExample.scala
- examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatExample.scala
- examples/tomcat/src/main/scala/com/example/http4s/tomcat/TomcatSslExample.scala
- project/Http4sPlugin.scala
- prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusClientMetricsSpec.scala
- prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusServerMetricsSpec.scala
Supersedes #3332, backported to series/0.21 with compilation fixes.
> Upgrade to cats-effect-2.1.3

- project/Http4sPlugin.scala
Corrects some simple oversights from #3341.
> More dependency cleanups

- website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
It's ugly to go this far back, but we don't have a mechanism of republishing the old sites.
The better solution to this would be to fetch some JSON published by master, but I don't know how to frontend.
> Update version dropdowns on site

- client/src/main/scala/org/http4s/client/Client.scala
> Remove unused Client.translate Bracket

- client/src/main/scala/org/http4s/client/middleware/Logger.scala
- server/src/main/scala/org/http4s/server/middleware/Logger.scala
Backport #3287. Also fix for client.
> Fix JSON detection in client and server Logger

- website/src/hugo/content/changelog.md
> Correct typo Depedency

- core/src/main/scala/org/http4s/EntityDecoder.scala
This was a good idea, and we should get it out sooner.
> Backport #3382: Use more efficient String Repr

- docs/src/main/tut/json.md
That hasn't been supported for a very long time.
> Drop mention of http4s-argonaut61

- build.sbt
I don't know if there are any for the `test->test`.
> Refer to SBT configs by constants

- build.sbt
> Don't remove -Ywarn-unused:imports from doc

- build.sbt
- project/Http4sPlugin.scala
I don't think this has been necessary for years.
> Remove YourKit JSP workaround

- build.sbt
> Remove snapshots resolver from core

- project/plugins.sbt
> Update sbt-mdoc to 2.2.0

- server/src/main/scala/org/http4s/server/middleware/HeaderEcho.scala
- server/src/test/scala/org/http4s/server/middleware/HeaderEchoSpec.scala
> Implement httpRoutes and httpApp constructors for HeaderEcho middleware

- core/src/main/scala/org/http4s/Method.scala
I am concerned that CI didn't catch this.
> Restore Method instance binary compatibility

- server/src/main/scala/org/http4s/server/middleware/ErrorAction.scala
- server/src/test/scala/org/http4s/server/middleware/ErrorActionSpec.scala
> Implement httpRoutes and httpApp constructors for ErrorAction middleware

- server/src/main/scala/org/http4s/server/middleware/DefaultHead.scala
- server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala
> Implement httpRoutes constructor for DefaultHead middleware

- core/src/main/scala/org/http4s/MimeDB.scala
You want constants? We've got constants.
> Regenerate MimeDB from IANA registry

- docs/src/main/mdoc/index.md
Related to https://github.com/http4s/http4s/issues/3260
> Update getting started

- core/src/main/scala/org/http4s/StaticFile.scala
- tests/src/test/scala/org/http4s/StaticFileSpec.scala
> Read directory fix series 21

- ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
New Logic Had Been Applied But Dead Code had been left. 
Put the request-line parsing before the header parsing.
> Ember Request Parser Improvements-  Remove Dead Code, Reorder

- client/src/main/scala/org/http4s/client/Client.scala
- Getting the effectful backends into a form they can be consumed by natchez is not simple. So I figure we should make it easier.
> Add Client.liftKleisli

- server/src/main/scala/org/http4s/server/middleware/HSTS.scala
- server/src/test/scala/org/http4s/server/middleware/HSTSSpec.scala
> Httproutes and httpapp for HSTS middleware

- server/src/main/scala/org/http4s/server/middleware/HttpsRedirect.scala
- server/src/test/scala/org/http4s/server/middleware/HttpsRedirectSpec.scala
> Implement httpRoutes and httpApp constructors for HttpsRedirect middleware

- .scalafmt.conf
- blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala
- blaze-core/src/main/scala/org/http4s/blazecore/util/CachingStaticWriter.scala
- blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
- blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala
- blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
- blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
- blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
- blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
- client/src/main/scala/org/http4s/client/JavaNetClientBuilder.scala
- client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
- client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
- okhttp-client/src/main/scala/org/http4s/client/okhttp/OkHttpBuilder.scala
- server/src/main/scala/org/http4s/server/middleware/CSRF.scala
- server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
- server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
- tests/src/test/scala/org/http4s/HttpDateSpec.scala
> Update to scalafmt-2.6.2, rerun scalafmtAll

- core/src/main/scala/org/http4s/headers/package.scala
> Fix deprecation warning message

- ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
- ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
Pushing Stuff Around for greater clarity of behavior, paving the way for connection reuse.
> Simplify Internal Ember Server Logic

- .github/workflows/ci.yml
- .github/workflows/release.yml
- project/Http4sPlugin.scala
- project/build.sbt
- project/plugins.sbt
> Upgrade to scala-2.12.12

- project/Http4sPlugin.scala
Catching up to things Scala Steward already sent to 1.0.
> Bump dependencies for 0.21.x

- project/Http4sPlugin.scala
- project/build.sbt
- project/plugins.sbt
Retargets #3704. #3695, #3698, #3696, #3688.
> Dependency bumps for 0.21

- docs/src/main/mdoc/integrations.md
Nuances like Proxy authentication are probably not in scope for an overview table.
> add proxy support column

- build.sbt
- project/Http4sPlugin.scala
- project/plugins.sbt
This is sufficient to start getting compilation errors in core. :tada:
> Dotty bootstrap

- blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
If we're not going to fix it let's stop failing builds on it.
[hangs head in shame]
> Skip flaky Insert a User-Agent header test

- .github/workflows/release.yml
- core/src/main/scala/org/http4s/FormDataDecoder.scala
- docs/src/hugo/layouts/single.html
- docs/src/main/mdoc/json.md
- ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
- website/src/hugo/content/adopters.md
- website/src/hugo/content/contributing.md
- website/src/hugo/layouts/partials/edit-button.html
- website/src/hugo/layouts/partials/edit-link.html
Updates some various references in comments and docs.  I already created the branch and reset all open PRs.
> Change default branch to main

- build.sbt
- project/Http4sPlugin.scala
- servlet/src/test/scala/org/http4s/servlet/Http4sServletRequestStub.scala
- servlet/src/test/scala/org/http4s/servlet/ServletIoSpec.scala
We use it in one test, and not to any great extent, and I'm tired of upgrading it.
Replaces #3786.
> Remove mockito from the build

- blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
> Skip another flaky blaze-client test

- core/src/main/scala/org/http4s/multipart/MultipartParser.scala
Should fix the build in #3790.
> Fix core compilation on Scala 2.12.12

- jetty-client/src/main/scala/org/http4s/client/jetty/ResponseListener.scala
> Remove failed request logging in JettyClient

- build.sbt
amazingly not much to do here
fixes #3843
> twirl on ce3

- build.sbt
scalatags seems to work out of the box 😄 
fixes #3842
> scalatags on ce3

- core/src/main/scala/org/http4s/HttpVersion.scala
Backport an insight from #3855 to parboiled2 while it's still here.
> Cache Rights of the common HttpVersions

- build.sbt
- project/Http4sPlugin.scala
> Update dependencies on series/0.21

- boopickle/src/test/scala/org/http4s/booPickle/BoopickleSpec.scala
- boopickle/src/test/scala/org/http4s/booPickle/BoopickleSuite.scala
- build.sbt
- project/Http4sPlugin.scala
- testing/src/test/scala/org/http4s/Http4sSuite.scala
This is a replay of #3852 on `series/0.21`
> Setup munit dependencies and make boopickle use munit

- project/plugins.sbt
> upgrading sbt-tpolecat to latest (v0.1.15)

- .github/workflows/ci.yml
- project/Http4sPlugin.scala
This is why some of our PRs haven't been building, except for locally.
> Build on pull requests to series/*

- core/src/main/scala/org/http4s/Uri.scala
- tests/src/test/scala/org/http4s/UriSpec.scala
> Fix rendering of URIs with colons

- .github/workflows/ci.yml
- core/src/main/scala/org/http4s/Header.scala
- core/src/main/scala/org/http4s/Headers.scala
- core/src/main/scala/org/http4s/HttpVersion.scala
- core/src/main/scala/org/http4s/Query.scala
- core/src/main/scala/org/http4s/Uri.scala
- core/src/main/scala/org/http4s/parser/QueryParser.scala
- project/Http4sPlugin.scala
- tests/src/test/scala/org/http4s/HeaderSpec.scala
- tests/src/test/scala/org/http4s/HeadersSpec.scala
- tests/src/test/scala/org/http4s/HttpVersionSpec.scala
- tests/src/test/scala/org/http4s/UriSpec.scala
- website/src/hugo/content/changelog.md
This had a non-trivial port of #3920.  I'd like to give @RafalSumislawski, @ashwinbhaskar, and @hamnis a chance to double check the URI part before we release 1.0.0-M8.
> Merge 0.21.12

- argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
- build.sbt
Replaced `Sync` with `Concurrent` for #3947
> ISSUE-3947 use concurrent instead of sync

- build.sbt
https://github.com/http4s/http4s/issues/3829
>  Enable implicit conversions

- build.sbt
- core/src/main/scala/io/chrisdavenport/vault/Key.scala
- core/src/main/scala/io/chrisdavenport/vault/Locker.scala
- core/src/main/scala/io/chrisdavenport/vault/Vault.scala
- project/Http4sPlugin.scala
- tests/src/test/scala/io/chrisdavenport/vault/KeyTests.scala
- tests/src/test/scala/io/chrisdavenport/vault/VaultSpec.scala
> Added a copy of vault to proceed with CE3 upgrade

- build.sbt
- project/Http4sPlugin.scala
The days are getting longer again!  Well, unless you live near @cquiroz.
> Winter solstice dependency bump

- build.sbt
- scala-xml/src/main/scala/scalaxml/ElemInstances.scala
> port scala xml to cats effect 3

- core/src/main/scala/org/http4s/Uri.scala
I don't understand this one, but we get 8 errors closer to Dotty support with it.
> Dotty can't find org.http4s.util._ imports in Uri

- core/src/main/scala-3/org/http4s/internal/CollectionCompat.scala
- core/src/main/scala/org/http4s/Uri.scala
- core/src/main/scala/org/http4s/metrics/MetricsOps.scala
- core/src/main/scala/org/http4s/parser/ForwardedHeader.scala
If we don't go with #4067, this is necessary, and it fixes several Dotty errors now.
> Collection compat 3

- project/build.properties
This is annoying as I flit from branch to branch.
> sbt-1.4.6 on 0.21.x

- circe/src/test/scala/org/http4s/circe/CirceSuite.scala
- client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
- client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala
We should try to use `unsafeRunSync` only at the end.
> Remove unsafe run sync

- client/src/test/scala/org/http4s/client/middleware/RetrySuite.scala
fix https://github.com/http4s/http4s/issues/4075
> enable retry suite

- tests/src/test/scala/org/http4s/ContentCodingSpec.scala
- tests/src/test/scala/org/http4s/QValueSpec.scala
- tests/src/test/scala/org/http4s/headers/AcceptCharsetSpec.scala
- tests/src/test/scala/org/http4s/headers/AcceptEncodingSpec.scala
- tests/src/test/scala/org/http4s/headers/AcceptLanguageSpec.scala
- tests/src/test/scala/org/http4s/parser/AcceptEncodingSpec.scala
- tests/src/test/scala/org/http4s/parser/AcceptHeaderSpec.scala
- tests/src/test/scala/org/http4s/parser/AcceptLanguageSpec.scala
> Remove uses of all QValue.q macro invocations

- project/Http4sPlugin.scala
This brings Scala-3.0.0-M3 support.
> Upgrade to log4s-1.10.0-M4

- project/Http4sPlugin.scala
Holding back jackson-databind and okio out of caution.
> metrics-4.1.17, play-json-2.9.2

- project/Http4sPlugin.scala
> jackson-databind-2.12.1

- servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala
Remove the blocking call to `dispatcher.unsafeRunSync` errorHandler that is used inside an `IO`.
The call to `dispatcher.unsafeRunSync` is kept only in the catch block of the `service` method.
> remove unsafeRunSync inside IO

- tests/src/test/scala/org/http4s/SchemeSpec.scala
- tests/src/test/scala/org/http4s/UriSpec.scala
Removes a couple lingering references to parboiled2.
> Shift specs to internal CharPredicate

- client/src/main/scala/org/http4s/client/Client.scala
- client/src/main/scala/org/http4s/client/DefaultClient.scala
- client/src/main/scala/org/http4s/client/middleware/GZip.scala
- client/src/main/scala/org/http4s/client/oauth1/oauth1.scala
- core/src/main/scala/org/http4s/Media.scala
- core/src/main/scala/org/http4s/internal/BackendBuilder.scala
- core/src/main/scala/org/http4s/util/package.scala
- ember-client/src/main/scala/org/http4s/ember/client/EmberClient.scala
- ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
- ember-core/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
- ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
- ember-core/src/main/scala/org/http4s/ember/core/Util.scala
- server/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
- server/src/main/scala/org/http4s/server/middleware/Caching.scala
- server/src/main/scala/org/http4s/server/middleware/EntityLimiter.scala
- server/src/main/scala/org/http4s/server/middleware/ErrorAction.scala
- server/src/main/scala/org/http4s/server/middleware/ErrorHandling.scala
- server/src/main/scala/org/http4s/server/middleware/Logger.scala
- server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
- server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
- testing/src/main/scala/org/http4s/testing/Http4sMatchers.scala
This works better with Scala 3's kind-projector.  Done here for branch alignment, necessary in series/0.22.
> Use MonadThrow, ApplicativeThrow, BracketThrow aliases

- ember-client/src/main/scala/org/http4s/ember/client/EmberClient.scala
- ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
- ember-client/src/test/scala/org/http4s/ember/client/internal/ClientHelpersSpec.scala
- project/Http4sPlugin.scala
Fix https://github.com/http4s/http4s/issues/4237
> port to typelevel keypool

- ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
- ember-core/src/test/scala/org/http4s/ember/core/ParsingSpec.scala
- ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
- ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
- examples/ember/src/main/scala/com/example/http4s/ember/EmberClientSimpleExample.scala
- project/Http4sPlugin.scala
Brought to you thanks to vim. Fixes https://github.com/http4s/http4s/issues/4232
It seems the build is flaky but this at least compiles
> Switch to org.typelevel.log4cats

- core/src/main/scala/org/http4s/HttpDate.scala
- core/src/main/scala/org/http4s/HttpVersion.scala
- core/src/main/scala/org/http4s/Method.scala
- core/src/main/scala/org/http4s/QValue.scala
- core/src/main/scala/org/http4s/Status.scala
- core/src/main/scala/org/http4s/Uri.scala
- core/src/main/scala/org/http4s/headers/Forwarded.scala
This PR addresses https://github.com/http4s/http4s/issues/3957
I standardized the RFC links to link to the html version and include the section title.
> Fix @see links in scaladoc

- dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardClientMetricsSuite.scala
- remove `println` on `0.21` branch
> #4215 Remove the printlns from the tests

- build.sbt
- client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
- client/src/main/scala/org/http4s/client/oauth1/oauth1.scala
- client/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
- core/src/main/scala/org/http4s/DecodeResult.scala
- server/src/main/scala/org/http4s/server/middleware/ErrorAction.scala
These are the necessary changes I wish weren't so.
> Compile http4s-client and http4s-server on 3.0.0-M2

- tests/src/test/scala/org/http4s/headers/AllowSuite.scala
@hamnis would be great if you could take a look? it should fix https://github.com/http4s/http4s/issues/4210
> add allow tests to cover some corner cases

- server/src/test/scala/org/http4s/server/middleware/ChunkAggregatorSuite.scala
> Explicit Arbitrary return type for transferCodingArbitrary

- servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
> Add call of GenericServlet init during Http4sServlet init

- testing/src/test/scala/org/http4s/Http4sSuite.scala
Makes it easier to originate test ports on series/0.21.
/cc @m-sp
> Backport TestScheduler and TestTimer from 0.22

- .github/workflows/ci.yml
- project/Http4sPlugin.scala
- project/plugins.sbt
> Bump sbt-http4s-org and cats-effect-testing

- core/src/main/scala-2.12/org/http4s/internal/CollectionCompat.scala
- core/src/main/scala-2.13/org/http4s/internal/CollectionCompat.scala
- core/src/main/scala-3/org/http4s/internal/CollectionCompat.scala
Closes https://github.com/http4s/http4s/issues/4313
> Deleted deprecated pairsToMultiParams

- project/Http4sPlugin.scala
> Upgrade to tomcat-9.0.43

- server/src/main/scala/org/http4s/server/middleware/CSRF.scala
- server/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeper.scala
Dotty doesn't like this, and Dotty is right.
> Advance cleanup of Dotty server warnings

- blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSuite.scala
- blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala
- blaze-server/src/main/scala/org/http4s/server/blaze/SSLContextFactory.scala
These cause warnings or errors in Dotty, and the fixes make better code even in 0.21.
> Dotty issues for blaze-client and blaze-server

- circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
- circe/src/test/scala/org/http4s/circe/CirceSensitiveDataEntityDecoderSpec.scala
- circe/src/test/scala/org/http4s/circe/CirceSuite.scala
These make Dotty sad and we want Dotty to be happy.
> Advance cleanup of Dotty circe warnings

- blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
- core/src/main/scala/org/http4s/Message.scala
- core/src/main/scala/org/http4s/Uri.scala
- project/Http4sPlugin.scala
- server/src/test/scala/org/http4s/server/middleware/ErrorActionSuite.scala
- servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
- tests/src/test/scala/org/http4s/MessageSuite.scala
- tests/src/test/scala/org/http4s/headers/ForwardedRenderersSuite.scala
- tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
There are some morally dubious `Option.get`s in here, but I don't think there are any new ones.
This ip4s release supports cats-effect-2 and lets us delete some things we inlined.  Many thanks to @mpilquist for taking our feedback.
> Upgrade to ip4s-2.0.0-M1

- project/Http4sPlugin.scala
There's no Dotty releases for scala-xml-1. Onward!
> Upgrade to scala-xml-2.0.0-M4

- core/src/main/scala-3/org/http4s/syntax/LiteralsSyntax.scala
- core/src/main/scala/org/http4s/headers/Forwarded.scala
- core/src/main/scala/org/http4s/headers/X-Forwarded-For.scala
I thought I did all these already, but I can't find them now.
> More core compilation fixes for 3.0.0-M3

- boopickle/src/test/scala/org/http4s/booPickle/BoopickleSuite.scala
> Explicit implicit types for boopickle

- blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
- circe/src/test/scala/org/http4s/circe/CirceSuite.scala
- dropwizard-metrics/src/main/scala/org/http4s/metrics/dropwizard/metrics.scala
- dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardClientMetricsSuite.scala
- dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardServerMetricsSuite.scala
- ember-client/src/main/scala/org/http4s/ember/client/EmberConnection.scala
- ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
- play-json/src/test/scala/org/http4s/play/PlaySuite.scala
- server/src/test/scala/org/http4s/server/middleware/DateSuite.scala
- server/src/test/scala/org/http4s/server/middleware/GZipSuite.scala
> Dotty progress

- core/src/main/scala/org/http4s/ResponseCookie.scala
- tests/src/test/scala/org/http4s/CookieSuite.scala
I don't recall seeing anybody use this.
> Deprecate the RequestCookieJar

- tests/src/test/scala/org/http4s/EntityEncoderSpec.scala
- tests/src/test/scala/org/http4s/UriSpec.scala
- tests/src/test/scala/org/http4s/UrlFormSpec.scala
merge forward might be bad, once it is merged I'll take care of it
> Munit port

- laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
- website/src/hugo/content/contributing.md
left overs worth backporting from my specs2 deletion branch
> fix urlformspec, update contrib

- core/src/main/scala/org/http4s/QValue.scala
- tests/src/test/scala/org/http4s/QValueSpec.scala
For https://github.com/http4s/http4s/issues/3949
Please let me know if using `unapply` is not a good idea.
> Add Hash and BoundedEnumerable instances for QValue

- ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
- ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
@rossabaker this fixes the compilation but I'm really not sure. I flatMap the `Resource[F, (SocketAddress[IpAddress], Stream[F, Socket[F]])]` twice and I don't think it's good.
But maybe it will help you.
> fix compilation

- project/Http4sPlugin.scala
Not the most focused commit, but we're in hustle mode.
> fs2-2.5.2, filter other update noise

- .github/workflows/ci.yml
- build.sbt
- client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
- ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
- examples/src/main/scala/com/example/http4s/ExampleService.scala
- project/Http4sPlugin.scala
- project/plugins.sbt
- scala-xml/src/main/scala/scalaxml/instances/ElemInstances.scala
- scalafix/build.sbt
- scalafix/project/build.properties
- scalafix/project/plugins.sbt
- scalatags/src/test/scala/org/http4s/scalatags/ScalatagsSuite.scala
- servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala
- servlet/src/main/scala/org/http4s/servlet/BlockingHttp4sServlet.scala
- tests/src/test/scala/org/http4s/HeadersSpec.scala
- tests/src/test/scala/org/http4s/Ipv4AddressSuite.scala
- tests/src/test/scala/org/http4s/Ipv6AddressSuite.scala
- tests/src/test/scala/org/http4s/MediaTypeSuite.scala
- tests/src/test/scala/org/http4s/MessageSuite.scala
- tests/src/test/scala/org/http4s/QValueSuite.scala
- tests/src/test/scala/org/http4s/multipart/MultipartSuite.scala
- tests/src/test/scala/org/http4s/parser/UriParserSuite.scala
this enables dotty M3. for rc1 we are still waiting on at least https://github.com/http4s/http4s/pull/4471 and https://github.com/typelevel/vault/pull/210
> Merge series v0.22 to main

- project/Http4sPlugin.scala
> play-json-2.10.0-RC2

- circe/src/main/scala/org/http4s/circe/CirceInstances.scala
- client/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
- core/src/main/scala/org/http4s/DecodeResult.scala
- core/src/main/scala/org/http4s/EntityDecoder.scala
- core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
- play-json/src/main/scala/org/http4s/play/PlayInstances.scala
- scala-xml/src/main/scala/scalaxml/ElemInstances.scala
- tests/src/test/scala/org/http4s/EntityDecoderSuite.scala
fixes https://github.com/http4s/http4s/issues/4268
> introduce new decodeResult builder

- project/Http4sPlugin.scala
Just cleans up some update noise.
> Scala 2.13.5: not on 0.21

- core/src/main/scala/org/http4s/headers/Accept-Charset.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- tests/src/test/scala/org/http4s/headers/AcceptCharsetSuite.scala
> Accept-Charset cleanup

- core/src/main/scala/org/http4s/headers/Accept-Patch.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- tests/src/test/scala/org/http4s/headers/AcceptPatchSuite.scala
- tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
> Migrate Accept-Patch header to new model

- client/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
- core/src/main/scala/org/http4s/headers/Accept.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- tests/src/test/scala/org/http4s/MediaTypeSuite.scala
- tests/src/test/scala/org/http4s/headers/AcceptHeaderSuite.scala
- tests/src/test/scala/org/http4s/parser/AcceptHeaderSpec.scala
> Accept header cleanup

- circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
- client/src/main/scala/org/http4s/client/middleware/FollowRedirect.scala
- client/src/main/scala/org/http4s/client/middleware/Logger.scala
- client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
- client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
- client/src/main/scala/org/http4s/client/middleware/Retry.scala
- server/src/main/scala/org/http4s/server/middleware/Logger.scala
- server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
- server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
> Move constants to header v2 to remove deprecated warnings

- core/src/main/scala/org/http4s/headers/Access-Control-Allow-Headers.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- tests/src/test/scala/org/http4s/headers/AccessControlAllowHeadersSpec.scala
- tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
> Access-Control-Allow-Headers header cleanup

- client/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
- core/src/main/scala/org/http4s/headers/Accept.scala
- tests/src/test/scala/org/http4s/parser/AcceptHeaderSpec.scala
> Accept header - more cleanup

- servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
There was some duplicate code in `Http4sServlet`. This PR removes it.
> Remove duplicate code

- blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
- blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
- core/src/main/scala/org/http4s/headers/Access-Control-Allow-Credentials.scala
- core/src/main/scala/org/http4s/headers/Date.scala
- core/src/main/scala/org/http4s/headers/ETag.scala
- core/src/main/scala/org/http4s/headers/Expires.scala
- core/src/main/scala/org/http4s/headers/Host.scala
- core/src/main/scala/org/http4s/headers/If-Match.scala
- core/src/main/scala/org/http4s/headers/If-Modified-Since.scala
- core/src/main/scala/org/http4s/headers/If-None-Match.scala
- core/src/main/scala/org/http4s/headers/If-Unmodified-Since.scala
- core/src/main/scala/org/http4s/headers/Last-Event-Id.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- tests/src/test/scala/org/http4s/HeaderSuite.scala
- tests/src/test/scala/org/http4s/headers/AccessControlAllowCredentialsSpec.scala
- tests/src/test/scala/org/http4s/headers/DateSuite.scala
- tests/src/test/scala/org/http4s/headers/ExpiresSuite.scala
- tests/src/test/scala/org/http4s/headers/IfModifiedSinceSuite.scala
- tests/src/test/scala/org/http4s/headers/LastEventIdSuite.scala
- tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
0 Access-Control-Allow-Credentials.scala
1 Date.scala
2 ETag.scala
3 Expires.scala
4 Host.scala
5 If-Match.scala
6 If-Modified-Since.scala
7 If-None-Match.scala
8 If-Unmodified-Since.scala
9 Last-Event-Id.scala
> port headers

- blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala
- core/src/main/scala/org/http4s/headers/Strict-Transport-Security.scala
- core/src/main/scala/org/http4s/headers/Transfer-Encoding.scala
- core/src/main/scala/org/http4s/headers/User-Agent.scala
- core/src/main/scala/org/http4s/headers/X-B3-Flags.scala
- core/src/main/scala/org/http4s/headers/X-B3-ParentSpanId.scala
- core/src/main/scala/org/http4s/headers/X-B3-Sampled.scala
- core/src/main/scala/org/http4s/headers/X-B3-SpanId.scala
- core/src/main/scala/org/http4s/headers/X-B3-TraceId.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
- tests/src/test/scala/org/http4s/headers/StrictTransportSecuritySuite.scala
- tests/src/test/scala/org/http4s/headers/TransferEncodingSuite.scala
- tests/src/test/scala/org/http4s/headers/ZipkinHeaderSuite.scala
- tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
partially address #4535
```
20 Strict-Transport-Security.scala
21 Transfer-Encoding.scala
22 User-Agent.scala
23 X-B3-Flags.scala
24 X-B3-ParentSpanId.scala
25 X-B3-Sampled.scala
26 X-B3-SpanId.scala
27 X-B3-TraceId.scala
```
> Header migration

- core/src/main/scala/org/http4s/DecodeResult.scala
fixes #4268
had this PR on my laptop lying around for a long time...
> Remove deprecated DecodeResult methods

- core/src/main/scala/org/http4s/headers/Access-Control-Allow-Credentials.scala
- tests/src/test/scala/org/http4s/headers/AcceptEncodingSuite.scala
- tests/src/test/scala/org/http4s/headers/AccessControlAllowCredentialsSpec.scala
- tests/src/test/scala/org/http4s/headers/AgeSuite.scala
- tests/src/test/scala/org/http4s/headers/AllowSuite.scala
- tests/src/test/scala/org/http4s/headers/ContentEncodingSuite.scala
- tests/src/test/scala/org/http4s/headers/ContentLengthSuite.scala
- tests/src/test/scala/org/http4s/headers/ContentTypeHeaderSuite.scala
- tests/src/test/scala/org/http4s/headers/DateSuite.scala
- tests/src/test/scala/org/http4s/headers/LinkSuite.scala
- tests/src/test/scala/org/http4s/headers/StrictTransportSecuritySuite.scala
reenable header laws and finish porting Access-Control-Allow-Credentials
> for a few headers more

- core/src/main/scala/org/http4s/headers/Set-Cookie.scala
- tests/src/test/scala/org/http4s/HeadersSpec.scala
Fixes warnings, reenables old test.
> Clean up HeadersSpec

- core/src/main/scala/org/http4s/MimeDB.scala
I obliterated some `v2.` last night, so it's as good a time as any to refresh it.
> Regenerate MimeDb

- server/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
- server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
- server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
> cleanup guaranteeCase usage

- .jvmopts
- tests/src/test/scala/org/http4s/EntityEncoderSpec.scala
should fix https://github.com/http4s/http4s/issues/4582
> Stabilize entity encoder spec

- tests/src/test/scala/org/http4s/DecodeSpec.scala
for example when we call flush at the of the stream for x-COMPOUND-TEXT charset on
jdk8 and the input stream ends in special control character (see
https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/CTEXT/ctext.html#Control_Characters)
This change relaxes the assertion on decoding result to make sure that
we only assert string content if the byte array is welformed and
accepted by nio's decoder
Fixes #4561
> Fix flaky test where decoding could throw IllegalStateException

- play-json/src/main/scala/org/http4s/play/PlayInstances.scala
More idiomatic implementation for ` Writes[Uri]` and `Reads[Uri] `
> PlayInstance - streamline Writes and Reads for Uri

- build.sbt
- core/src/main/scala-2/org/http4s/LiteralSyntaxMacros.scala
- core/src/main/scala-2/org/http4s/syntax/LiteralsSyntax.scala
- project/Http4sPlugin.scala
- tests/src/test/scala/org/http4s/LiteralSynxtaxMacrosSuite.scala
Closes #4600 
Picks off from https://github.com/http4s/http4s/pull/4616.
> Add and Use Literally 

- laws/src/main/scala/org/http4s/laws/discipline/EntityEncoderTests.scala
- laws/src/main/scala/org/http4s/laws/discipline/LawAdapter.scala
- project/Http4sPlugin.scala
- testing/src/test/scala/org/http4s/Http4sSuite.scala
> Migration to cats-effect-3.0.0-RC3

- build.sbt
- project/Http4sPlugin.scala
- project/plugins.sbt
Notably, cats-2.5.0, cats-effect-2.4.1, plus a bunch of internals.
> Upgrade lots of things

- project/Http4sPlugin.scala
Tired of watching it sputter.  Let's batch them.
> Cats-Effect 3.0.1 and friends

- blaze-client/src/test/scala-2.13/org/http4s/client/blaze/BlazeClient213Suite.scala
- client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
This is garbage, but we need to stop the bleeding and get the release out.
> Mark flaky test due to AHC

- core/src/main/scala/org/http4s/Message.scala
> Response is not a case class anymore

- okhttp-client/src/main/scala/org/http4s/okhttp/client/OkHttpBuilder.scala
- okhttp-client/src/test/scala/org/http4s/okhttp/client/OkHttpClientSuite.scala
- scalafix/build.sbt
- scalafix/input/src/main/scala/fix/RewritePackagesTests.scala
- scalafix/output/src/main/scala/fix/RewritePackagesTests.scala
- scalafix/rules/src/main/scala/fix/RewritePackages.scala
> Move okhttp client package

- blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSuite.scala
> Use a unique io runtime in BlazeServerSuite

- website/src/hugo/content/adopters.md
Add Wegtam GmbH in adopters list as well as g8 templates for web apps and tapir services.
> Add adopters

- blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
- blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala
- blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala
- core/src/main/scala/org/http4s/websocket/ReservedOpcodeException.scala
- core/src/main/scala/org/http4s/websocket/package.scala
- core/src/main/scala/org/http4s/websocket/protocolexceptions.scala
Resolves #2606.
Opening as a draft because I would like an initial review and some pointers on how (or if) to test this. I've only made changes to `core` and `blaze-server`. Do any of the other backends need adjusting?
> Distinguish between reserved and unknown frame opcodes

- build.sbt
- servlet/src/test/scala/org/http4s/servlet/AsyncHttp4sServletSuite.scala
I cannot seem to reproduce #2354.
> Add AsyncHttp4sServlet test suite

- core/src/main/scala/org/http4s/Header.scala
- tests/src/test/scala/org/http4s/HeadersSpec.scala
- tests/src/test/scala/org/http4s/QueryParamCodecSuite.scala
Cherry picking #4797 and #4626 from main (this will also fixes #3936)
> Backport from main

- build.sbt
- project/Http4sPlugin.scala
- project/build.properties
Supercedes #4788, #4800 and #4802
> Bump dependencies and fix sbt warnings

- project/Http4sPlugin.scala
> Update cats-parse to 0.3.3

- project/build.properties
Retarget of #4816 
Closes #4816
> Update sbt to 1.5.2

- blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
- blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala
- build.sbt
- project/Http4sPlugin.scala
> Read from an idle blaze-client connection to detect when server closes it

- docs/src/main/mdoc/testing.md
> added docs for Client.fromHttpApp 

- blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerParser.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/ProtocolSelector.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/SSLContextFactory.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/WSFrameAggregator.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/WebSocketDecoder.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/WebSocketSupport.scala
- blaze-server/src/test/scala/org/http4s/blaze/server/BlazeServerMtlsSpec.scala
- blaze-server/src/test/scala/org/http4s/blaze/server/BlazeServerSuite.scala
- blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
- blaze-server/src/test/scala/org/http4s/blaze/server/ServerTestRoutes.scala
- docs/src/main/mdoc/client.md
- docs/src/main/mdoc/json.md
- docs/src/main/mdoc/service.md
- docs/src/main/mdoc/static.md
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeSslExampleWithRedirect.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Server.scala
- examples/docker/src/main/scala/com/example/http4s/Example.scala
- scalafix/input/src/main/scala/fix/RewritePackagesTests.scala
- scalafix/output/src/main/scala/fix/RewritePackagesTests.scala
- scalafix/rules/src/main/scala/fix/RewritePackages.scala
Repackaging org.http4s.server.blaze -> org.http4s.blaze.server
Part of #2702
> Repackage server-blaze to blaze-server

- core/src/main/scala/org/http4s/multipart/MultipartParser.scala
Yak shaving for #2627. Introduces the `Event` ADT:
```scala
private[this] sealed trait Event
private[this] final case class PartStart(value: Headers) extends Event
private[this] final case class PartChunk(value: Chunk[Byte]) extends Event
private[this] final case object PartEnd extends Event
```
The actual parsing is factored out as a `Stream[F, Event]` (see `parseEvents`), decoupling it from handling part limits (`limitParts`) and building `Part`s (e.g. `partBodyFileStream`). This should allow us to examine and modify them in isolation.
One drawback of this encoding is that the assumed order of `Event`s is not encoded in types, so the logic concerned with building `Part`s has to handle some impossible situations. However, it's easy to show that `Event`s only come in the specified order - …
> Refactor MultipartParser

- jetty-server/src/test/scala/org/http4s/jetty/server/JettyServerSuite.scala
> Mark flaky test in JettyServerSuite

- website/src/hugo/static/_redirects
We still want to move off Netlify, but this corrects something in the interim.
> stable is v0.21, latest is 1.0

- SECURITY.md
0.20 is out. 0.22, 0.23, 1.0 are in.
> Update versions supported by security policy

- project/Http4sPlugin.scala
> Circe 0.14.0

- .github/workflows/ci.yml
- docs/src/main/mdoc/client.md
- docs/src/main/mdoc/cors.md
- docs/src/main/mdoc/csrf.md
- docs/src/main/mdoc/dsl.md
- docs/src/main/mdoc/entity.md
- docs/src/main/mdoc/gzip.md
- docs/src/main/mdoc/hsts.md
- docs/src/main/mdoc/json.md
- docs/src/main/mdoc/middleware.md
- docs/src/main/mdoc/service.md
- docs/src/main/mdoc/static.md
- docs/src/main/mdoc/streaming.md
- docs/src/main/mdoc/testing.md
- project/Http4sPlugin.scala
> Port documentation to 0.23

- core/src/main/scala/org/http4s/MimeDB.scala
- project/MimeLoader.scala
- project/build.sbt
And retain copyright notice
Closes #4896
> Use Ember client for mime loader

- docs/src/main/mdoc/client.md
- docs/src/main/mdoc/dsl.md
> Clean-up docs from cats-effect 2.0 things

- ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
Private, and just a parameter name, so I don't think it requires another RC.
> Fix typo: valiation -> validation

- .github/workflows/ci.yml
- build.sbt
- project/Http4sPlugin.scala
> Scala 2.12.14

- build.sbt
> Fix typo in build.sbt

- blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
- blaze-client/src/main/scala/org/http4s/client/blaze/BlazeConnection.scala
- blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
- blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientBase.scala
- blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSuite.scala
- blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala
Follow-up to infinite request body issues in #4815
It's a draft. It fixes the issue, but I need to clean up, and fix some tests, add some more tests, and probably do 100 other things.
> Fix blaze client handling of early responses

- project/plugins.sbt
> Update sbt-mdoc to 2.2.22

- project/build.sbt
> Update http4s-circe, http4s-ember-client to 0.22.0

- project/plugins.sbt
> Update logback-classic to 1.2.4

- project/Http4sPlugin.scala
- project/plugins.sbt
Mostly boring, ~~but we'll get Boopickle for Scala 3 now~~.
> Updates before 0.22.1

- docs/src/main/mdoc/dsl.md
Addresses https://github.com/http4s/http4s/issues/5006
> Add docs for MatrixVar

- website/src/hugo/content/changelog.md
The HTCPCP community demands it.
> Release v0.22.2

- client/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
- core/src/main/scala/org/http4s/EntityDecoder.scala
- core/src/main/scala/org/http4s/EntityEncoder.scala
- core/src/main/scala/org/http4s/Media.scala
- core/src/main/scala/org/http4s/Message.scala
- core/src/main/scala/org/http4s/ServerSentEvent.scala
- core/src/main/scala/org/http4s/StaticFile.scala
- core/src/main/scala/org/http4s/multipart/MultipartParser.scala
- core/src/main/scala/org/http4s/multipart/Part.scala
- ember-core/src/test/scala/org/http4s/ember/core/EncoderSuite.scala
- ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
- ember-core/src/test/scala/org/http4s/ember/core/TraversalSpec.scala
- ember-server/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/client/StreamClient.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/FileService.scala
- examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala
- project/Http4sPlugin.scala
- scala-xml/src/test/scala/scalaxml/ScalaXmlSuite.scala
- specs2/src/test/scala/org/http4s/Http4sSpec.scala
- testing/src/test/scala/org/http4s/Http4sSuite.scala
- tests/src/test/scala/org/http4s/DecodeSpec.scala
- tests/src/test/scala/org/http4s/MessageSuite.scala
- tests/src/test/scala/org/http4s/ServerSentEventSpec.scala
- tests/src/test/scala/org/http4s/multipart/MultipartParserSuite.scala
- tests/src/test/scala/org/http4s/multipart/MultipartSuite.scala
This work is mostly done on main, but after the files had moved, so it's mostly redone here.  The forward merge from this to main is going to be Not Fun.
> Upgrade to fs2-3.1.0

- website/src/hugo/content/changelog.md
> Release v0.23.1

- build.sbt
- ember-server/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
- ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
> ember server maxConcurrency -> maxConnections

- .jvmopts
I think it works better, but hard to know for sure. Maybe merge and let's try it out for a while?
> Try G1GC to help flaky Node.js ci

- website/jvm/src/hugo/content/contributing.md
- website/jvm/src/hugo/content/versions.md
- website/jvm/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
Fixes #5048 and also sneaks in some Scala.js promotion :)
> Update version status in website navbar

- build.sbt
- client/src/main/scala/org/http4s/client/oauth1/SignatureAlgorithm.scala
- client/src/main/scala/org/http4s/client/oauth1/oauth1.scala
- client/src/test/scala/org/http4s/client/oauth1/OAuthSuite.scala
- client/src/test/scala/org/http4s/client/oauth1/SignatureAlgorithmSuite.scala
- ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
- ember-client/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
- website/src/hugo/content/changelog.md
Basically #5064 ported forward to series/0.22, plus some scalafmt that got overlooked, I guess?
> Merge ember retry plus a reformat that hitched a ride

- server/src/main/scala/org/http4s/server/middleware/GZip.scala
- server/src/test/scala/org/http4s/server/middleware/GZipSuite.scala
Backport of https://github.com/http4s/http4s/pull/5056
> Backport to 0.22: Fix gzip on http 204

- core/src/main/scala/org/http4s/headers/Accept-Language.scala
- core/src/main/scala/org/http4s/headers/Content-Language.scala
- laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
- tests/src/test/scala/org/http4s/headers/AcceptLanguageSuite.scala
- tests/src/test/scala/org/http4s/parser/AcceptLanguageSuite.scala
https://github.com/http4s/http4s/issues/5069
Language-Accept parser having trouble with wild-card and more than one sub-tag
> Fix for #5069

- core/src/main/scala/org/http4s/EntityEncoder.scala
> Make encoders for File, Path, and InputStream implicit

- dsl/src/main/scala/org/http4s/dsl/Http4sDsl.scala
- dsl/src/main/scala/org/http4s/dsl/RequestDsl.scala
- dsl/src/main/scala/org/http4s/dsl/io.scala
- dsl/src/main/scala/org/http4s/dsl/request.scala
Conjecture: none of these should be vals.
> Restore binary compatibility of ->>

- dom-core/src/main/scala/org/http4s/dom/DomEntityEncoder.scala
- dom-core/src/main/scala/org/http4s/dom/package.scala
As promised in https://github.com/http4s/http4s/pull/5111#issuecomment-906907327. Still not perfect unfortunately!
> Undo scala-js-dom facade hacks

- project/Http4sPlugin.scala
> blaze-0.15.2

- project/plugins.sbt
> Various plugin updates

- project/Http4sPlugin.scala
A couple dependency bumps as the release train rolls on.
> munit-0.7.29, scodec-bits-1.1.28

- server/src/main/scala/org/http4s/server/middleware/CORS.scala
- server/src/test/scala/org/http4s/server/middleware/CORSSuite.scala
- website/src/hugo/content/changelog.md
#5144 merged forward to fix #5143
> Fix CORS preflight status, 0.23

- website/jvm/src/hugo/content/index.md
Put `.card` and `.card-body` elements into each column so that we get a bordered look.
| Current | Proposed |
| - | - |
| <img width="1437" alt="image" src="https://user-images.githubusercontent.com/4206232/133859343-566cc7e9-ad36-4932-b624-215daae14a2c.png"> | <img width="1435" alt="image" src="https://user-images.githubusercontent.com/4206232/133859301-b5e9b4cf-16cb-4669-aa04-57e7e7c73d56.png">
> Fix cards on landing page

- build.sbt
- project/Http4sPlugin.scala
Fixes https://github.com/http4s/http4s/issues/5231. @rossabaker can you confirm?
> Add JS timezone db for testing

- blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
> Mark blaze-client stats test as flaky

- tests/src/test/scala/org/http4s/multipart/MultipartParserSuite.scala
Removed printlns from MultipartParserSuite, fixes #5239
> Removed printlns from MultipartParserSuite

- website/jvm/src/hugo/content/contributing.md
Mention Node.js and yarn test dependencies and a few other minor improvements.
> Freshen contributing docs

- core/src/main/scala/org/http4s/QValue.scala
Contributing to issue #5017 
added `Ordering` instance to `QValue` class
> added Ordering instance to QValue Class

- client/shared/src/main/scala/org/http4s/client/middleware/DestinationAttribute.scala
Weakens `DestinationAttribute` constraint.
> Weaken DestinationAttribute constraint

- project/MimeLoader.scala
- project/build.sbt
This should unblock @jenshalm's plan to revamp the docs in https://github.com/http4s/http4s/discussions/5192#discussioncomment-1410456.
BTW I ran this locally and seemed to work fine 👍
> Update build project to use http4s 0.23

- core/src/main/scala/org/http4s/headers/Accept-Post.scala
- core/src/main/scala/org/http4s/internal/parsing/Rfc7230.scala
- core/src/main/scala/org/http4s/util/Renderable.scala
- laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
- tests/src/test/scala/org/http4s/headers/AcceptPostSuite.scala
> Add accept-post header model

- core/src/main/scala/org/http4s/HttpVersion.scala
- laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
Our arbitraries aren't as good as they ought to be.  I'll be gradually reforming them as we pass through the model.
> Improve Arbitrary[HttpVersion]

- website/src/hugo/content/changelog.md
Not a security release, but it's a bug fix, and it passed CI, and we have automation, so might as well.
> Release v0.21.30

- build.sbt
- core/shared/src/main/scala/org/http4s/HttpVersion.scala
- ember-client/js/src/main/scala/org/http4s/ember/client/internal/ClientHelpersPlatform.scala
- ember-server/js/yarn.lock
> Fix ci on main

- docs/src/main/mdoc/default.template.html
- website/src/hugo/content/versions.md
- website/src/hugo/static/templates/no-page-nav.template.html
I case you missed it, it has a live example of http4s in the browser! 😁 
https://http4s.github.io/http4s-dom
> Update all the urls to new http4s-dom site

- core/src/main/scala/org/http4s/headers/`Access-Control-Allow-Methods`.scala
> run scalafmt on series/0.22

- blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala
- boopickle/src/test/scala/org/http4s/booPickle/BoopickleSuite.scala
- build.sbt
- client/src/main/scala/org/http4s/client/oauth1/ProtocolParameter.scala
- client/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
- client/src/test/scala/org/http4s/client/middleware/FollowRedirectSuite.scala
- core/src/main/scala/org/http4s/Header.scala
- core/src/main/scala/org/http4s/headers/Forwarded.scala
- core/src/main/scala/org/http4s/internal/CharPredicate.scala
- core/src/main/scala/org/http4s/metrics/MetricsOps.scala
- dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/util.scala
- ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
- ember-server/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
- ember-server/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
- examples/docker/src/main/scala/com/example/http4s/Example.scala
- examples/src/main/scala/com/example/http4s/HeaderExamples.scala
- jetty-client/src/main/scala/org/http4s/jetty/client/ResponseListener.scala
- scalafix-internal/rules/src/main/scala-2/fix/GeneralLinters.scala
- server/src/main/scala/org/http4s/server/middleware/CORS.scala
- servlet/src/test/scala/org/http4s/servlet/Http4sServletRequestStub.scala
- tests/src/test/scala/org/http4s/FormDataDecoderSpec.scala
> Fix or exclude scalafix warnings

- blaze-server/src/test/scala/org/http4s/blaze/server/ServerTestRoutes.scala
This removes a redundant 'todo' in the `ServerTestRoutes`. It remained from the times when the `ServerTestRoutes.textPlain` was a `String`.
> Clean up `ServerTestRoutes`

- dsl/src/test/scala/org/http4s/dsl/PathInHttpRoutesSuite.scala
- website/src/hugo/content/contributing.md
I had plans to add it within #5591 but forgot.
> Add advice of using `assertEquals()` in the contributing guide

- build.sbt
> Publish http4s-scalatags for Scala 3

- build.sbt
- project/SiteConfig.scala
Closes #5452. A backport of the #5640.
> EPUB download of the docs for the `series/0.23`

- build.sbt
- project/SiteConfig.scala
Closes #5452. A backport of the #5642.
> EPUB download of the docs for the `series/0.22`

- .scala-steward.conf
> Pin scalatags to 0.10

- .github/workflows/ci.yml
- build.sbt
- dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardClientMetricsSuite.scala
- project/Http4sPlugin.scala
- project/plugins.sbt
- server/shared/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSuite.scala
> Merge 0.22 to 0.23

- build.sbt
> Clean up `build.sbt`

- core/shared/src/main/scala/org/http4s/Headers.scala
- core/shared/src/main/scala/org/http4s/headers/Trailer.scala
- laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
- project/Http4sPlugin.scala
- tests/shared/src/test/scala/org/http4s/headers/TrailerSuite.scala
> Merge `series/0.23` into `main`

- blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
- blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala
- client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
- project/Http4sPlugin.scala
- project/build.properties
- project/plugins.sbt
Propagates downstream changes.
> Merge `series/0.22` into `series/0.23`

- blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
- blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
- blaze-core/src/test/scala/org/http4s/blazecore/util/Http1WriterSpec.scala
- blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
- client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
- client/shared/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
- client/shared/src/test/scala/org/http4s/client/middleware/LoggerSuite.scala
- core/shared/src/main/scala/org/http4s/EntityEncoder.scala
- core/shared/src/main/scala/org/http4s/Message.scala
- core/shared/src/main/scala/org/http4s/StaticFile.scala
- core/shared/src/main/scala/org/http4s/multipart/MultipartEncoder.scala
- ember-core/src/main/scala/org/http4s/ember/core/Util.scala
- ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
- ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala
- ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/StreamUtils.scala
- examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/FileService.scala
- examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala
- laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
- server/shared/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
- server/shared/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
- server/shared/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
- specs2/src/test/scala/org/http4s/Http4sSpec.scala
- testing/shared/src/test/scala/org/http4s/Http4sSuite.scala
- tests/shared/src/test/scala/org/http4s/ServerSentEventSpec.scala
- tests/shared/src/test/scala/org/http4s/multipart/MultipartParserSuite.scala
- tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala
Removed a lot of unneeded `covary` calls, plus a couple of other minor tweaks
> Code cleanup (mostly variance-related)

- core/src/main/scala/org/http4s/Message.scala
> Fix scaladoc references to `io.chrisdavenport.vault` in the `series/0.22`

- core/src/main/scala/org/http4s/EntityEncoder.scala
- core/src/main/scala/org/http4s/Message.scala
Yet another scaladoc clean-up.
> Fix some scaladoc references to headers

- core/shared/src/main/scala/org/http4s/Entity.scala
This is the second slice of #4509.
> Convert Entity to an ADT with an empty case

- core/shared/src/main/scala/org/http4s/Entity.scala
- core/shared/src/main/scala/org/http4s/EntityEncoder.scala
I've merged `Empty` into `Strict` to avoid having two legal representations for a strict empty entity - any thoughts on this?
> Add Strict entity

- core/shared/src/main/scala/org/http4s/Entity.scala
- core/shared/src/main/scala/org/http4s/EntityEncoder.scala
Reverts http4s/http4s#5804 (I was too trigger-happy)
> Revert "Add Strict entity" pending further review

- client/shared/src/main/scala/org/http4s/client/middleware/Logger.scala
- client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
- client/shared/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
- core/shared/src/main/scala/org/http4s/internal/Logger.scala
- server/shared/src/main/scala/org/http4s/server/middleware/Logger.scala
- server/shared/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
- server/shared/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
> Simplify logger type signatures

- prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala
> Replace deprecated object in the imports

- build.sbt
- website/src/hugo/content/contributing.md
Intentionally boring.  I kept our docs in the conflicts, which were already on mdoc, which is the change that motivated this venture into antiquity.  This small diff should be quite easy to roll forward into the Branches That Actually Matter.
> Merge series/0.20 to series/0.21

- blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
This refactors some methods of the `Http1Connection` to simplify reasoning. Implementation, by and large, wasn't changed. Just decomposition was made more fine-grained and nested ifs replaced by pattern-matching.
> Refactor some `Http1Connection` methods

- website/src/hugo/content/adopters.md
> Added SurfsUp app

- server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
Extract logic to local methods.
> FileService Server Middleware: readability

- .scala-steward.conf
> Add scala-java-locales to steward ignores on main

- .scala-steward.conf
> Fix description for pinned CE2 dependencies

- .github/workflows/ci.yml
- project/Http4sPlugin.scala
- project/plugins.sbt
- scalafix/project/plugins.sbt
> Merge series/0.22 into series/0.23

- blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
- blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
- client/jvm/src/main/scala/org/http4s/client/JavaNetClientBuilder.scala
- client/shared/src/main/scala/org/http4s/client/Client.scala
- client/shared/src/main/scala/org/http4s/client/middleware/Metrics.scala
- ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
> Refactor some `Resource` usage

- server/shared/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
> Deprecate the `BracketRequestResponse#exitCaseToOutcome`

- ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerMtlsSuite.scala
- ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
- ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
- ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
- ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
- server/shared/src/test/scala/org/http4s/server/middleware/ErrorActionSuite.scala
This goes from https://github.com/http4s/http4s/pull/5889/files/518370fa1b660e1ffdc8e1916fcc9c61ae560968#diff-7e89a11f202c0194ac783e0af06c5d8c343e8576d09f76aaf9bd0dbb6b06e687
> Use `port` syntax

- .scala-steward.conf
> Fix scala-steward.conf syntax

- core/src/main/scala/org/http4s/EntityDecoder.scala
- core/src/main/scala/org/http4s/EntityEncoder.scala
Continuation of https://github.com/http4s/http4s/pull/5195
/cc @ChristopherDavenport
> Add EntityEncoder[F, ByteVector]

- .github/workflows/ci.yml
- build.sbt
Temporary, to deal with #5919.
> Revert "Enable snapshots for 0.22" (#5908)

- .scala-steward.conf
> Merge scalafmt-core forward from 0.22

- .github/release.yml
Fixes https://github.com/http4s/http4s/issues/5936 (I think)
> remove empty excludes from release notes config

- .github/release.yml
> Push behind-the-scenes label down the changelog

- .github/release.yml
- .scalafmt.conf
- website/src/hugo/content/changelog.md
This one's pretty trivial.  It will let us start with the release notes.
> Merge from 0.22

- .scala-steward.conf
> Ignore slf4j-api

- .scala-steward.conf
> Get http4s upgrades for build from 0.22

- client/src/main/scala/org/http4s/client/websocket/WSClient.scala
As discussed awkwardly late on #5520.
> Privatize web socket client pending concrete implementation

- docs/src/main/mdoc/static.md
This PR resolves https://github.com/http4s/http4s/issues/5823
> Update static content docs, fix deprecations

- server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
- server/src/test/scala/org/http4s/server/middleware/UrlFormLifterSuite.scala
Fixes #5989.  Backport of #5990.  All credit to @dfahritdinov.
> Respect URI locality in UrlFormLifter

- client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala
- docs/src/main/mdoc/auth.md
- docs/src/main/mdoc/cors.md
- docs/src/main/mdoc/csrf.md
- docs/src/main/mdoc/dsl.md
- docs/src/main/mdoc/entity.md
- docs/src/main/mdoc/gzip.md
- docs/src/main/mdoc/hsts.md
- docs/src/main/mdoc/json.md
- docs/src/main/mdoc/middleware.md
- docs/src/main/mdoc/service.md
- docs/src/main/mdoc/static.md
- docs/src/main/mdoc/testing.md
- dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
- ember-core/js/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
- ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Decompressor.scala
- ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/package.scala
- project/Http4sPlugin.scala
- server/shared/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
- server/shared/src/test/scala/org/http4s/server/RouterSuite.scala
- server/shared/src/test/scala/org/http4s/server/middleware/UrlFormLifterSuite.scala
- website/src/hugo/content/changelog.md
> Merge from 0.23.10

- website/src/hugo/content/changelog.md
> Release v1.0.0-M31

- client/src/main/scala/org/http4s/client/websocket/WSClient.scala
I'm also sneaking in a couple convenience methods to the high-level client.
> Add convenience methods to `WSConnectionHighLevel`

- website/src/hugo/content/versions.md
> Fresh up the version page

- .scala-steward.conf
Prevent further PRs like #6019.
> Merge Jetty forward from 0.22

- build.sbt
- project/plugins.sbt
- website/src/hugo/content/changelog.md
> Release v0.21.32

- build.sbt
- project/plugins.sbt
Hope not, but I don't want to be wrestling with it.
> Build tweaks in case there's another 0.21

- server/shared/src/main/scala/org/http4s/server/middleware/Caching.scala
Extract objects that do not change often or do not depend on the time.
> Caching Middleware - Small Rewrites

- core/src/main/scala/org/http4s/ResponseCookie.scala
- core/src/main/scala/org/http4s/internal/parsing/Cookies.scala
- tests/src/test/scala/org/http4s/headers/CookieSuite.scala
Backport of #6079.  All credit to @kailuowang.
> More tolerant cookie parsing

- blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala
This  is a follow-up from https://github.com/http4s/http4s/pull/6092#discussion_r821655262
> Add micro-opts for `CachingChunkWriter`

- docs/src/main/mdoc/integrations.md
I also changed the yes/no characters to the more colorful emoji to make it easier to visually distinguish. It looked really bad on the doc site with the plain squares
> Docs: ember supports websockets

- servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
Yet another micro-optimizations.
> Remove redundant draining of response body in `Http4sServlet` 

- server/shared/src/main/scala/org/http4s/server/middleware/ErrorHandling.scala
- Custom Recovery so we can expose a direct function folks can use rather than building their own, even if its not very complex
- Recovery Options - Both for all errors and for message failures allowing people the option to mix that in.
> Add Additional ErrorHandling Options

- .github/release.yml
Hopefully there aren't any more of these, but I've said that a few times already.
> Exclude series/0.21 from release notes

- client/shared/src/main/scala/org/http4s/client/Client.scala
This makes working with http4s nicer in projects using transformer types.
> Add OptionT Based Versions Of expectOption*

- site/src/main/mdoc/changelog.md
Need to land the plane sometime.  I expect another release train next week.
> Release v0.23.11

- ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
- ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
Backport of #5881 to series/0.21
> Support parsing response bodies without Content-Length in ember (0.21)

- website/src/hugo/content/changelog.md
> Release v0.21.33

- site/src/main/mdoc/versions.md
The changes to this page were too much for git to track, so it didn't properly merge this file and we lost some changes. Like messing up my http4s.js stuff 😝
> Restore changes to versions page on main

- core/shared/src/main/scala/org/http4s/HttpVersion.scala
- server/jvm/src/main/scala/org/http4s/server/middleware/CSRF.scala
Yet another attempt to push some clean-up.
> Remove deprecated things

- blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
- blaze-server/src/main/scala/org/http4s/blaze/server/WebSocketSupport.scala
- blaze-server/src/test/scala/org/http4s/blaze/server/ServerTestRoutes.scala
- circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
- core/src/main/scala/org/http4s/headers/Connection.scala
- ember-server/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
- server/src/main/scala/org/http4s/server/package.scala
- testing/src/test/scala/org/http4s/testing/ErrorReporting.scala
- tests/src/test/scala/org/http4s/ResponderSpec.scala
Let's save mem a bit and a few nanoseconds in allocations.
> Use predefined Close connection header

- core/src/main/scala/org/http4s/Message.scala
> Fix comment in org.http4s.Message.scala

- core/shared/src/main/scala/org/http4s/Message.scala
Fix some scaladoc regression of introducing `Entity`.
> Fix `Request`/`Response` scaladoc

- blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala
> Clean up `BlazeServerBuilder` scaladoc

- server/src/main/scala/org/http4s/server/middleware/authentication/DigestAuth.scala
- server/src/main/scala/org/http4s/server/middleware/authentication/Nonce.scala
- server/src/main/scala/org/http4s/server/middleware/authentication/NonceF.scala
- server/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeper.scala
- server/src/main/scala/org/http4s/server/middleware/authentication/NonceKeeperF.scala
Integrates `Random` into `DigestAuth` to avoid blocking.
> Integrate Random into DigestAuth

- .scala-steward.conf
Not a particularly challenging one.  Nothing much to see here.
> Get sbt-doctest from 0.22

- site/src/main/mdoc/further-reading.md
FS2 and The Official Guide (of FS2)
> Fixed Dead Links in further-reading.md

- blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala
To avoid nasty stacktraces when shutting down blaze.
> Use tryScheduling within IdleTimeoutStage

- .scala-steward.conf
Should have ci-skipped. Oh well.
> Ignore http4s-crypto updates on main

- ember-core/shared/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
Fixes an issue that can lead to excessive memory usage when decoding `Transfer-Encoding: chunked` responses with ember where the encoded chunks are significantly smaller than the read chunk size.
The current implementation uses an `Array[Byte]` to pass unconsumed data between iterations of the decoding loop defeating any structural sharing provided by `ByteVector`. For a read chunk of size `n` and an encoded chunk of size `k`, the stream will emit a `Chunk.byteVector` backed by an array of size `n` that addresses `k` bytes and then copy the remainder of the unaddressed `n - k` bytes into a new array for the next iteration. If `n` and `k` are close in size, this isn't that bad, but if `k` is significantly smaller, we end up with a lot of array copying. This effect is exacerbated in any …
> Avoid array copies when splitting chunks in ember chunked decoder

- .scala-steward.conf
> Update cats-parse from 0.22

- blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
> Tweak `async` usage in `Http1Connection`

- .scala-steward.conf
> Ignore `scala-xml` updates

- server/shared/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
Add a Scaladoc section to the object, with a link to the RFC standard
and a description of functionality.
Also, extract the post-processing logic to a private `aggregate`
function to leave `apply` as a mere `flatMapF`.
> Server - Chunk Aggregator Middleware: code and docs

- core/src/main/scala/org/http4s/multipart/Boundary.scala
- core/src/main/scala/org/http4s/multipart/Multipart.scala
`0.22.13` isn't released, so I think it's better to fix this.
> Fix deprecated since versions

- server/shared/src/main/scala/org/http4s/server/middleware/BodyCache.scala
That fits better with the new `Entity` model.
> Tweak `BodyCache#hasNoBody`

- client/src/main/scala/org/http4s/client/Client.scala
> Clarify connection lifecycle

- blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
This is a follow-up from https://github.com/http4s/http4s/pull/6266#issuecomment-1104014154
Also, this addresses the #6331.
> Roll back the #6254

- .scala-steward.conf
> Remove update ignorings in Scala Steward conf for the 0.23

- docs/versions.md
- project/Http4sSitePlugin.scala
This addresses the #6331.
I wonder should we update the series/0.22 branch too?
> Mark the 0.22 version as EOL at the website

- ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
That's what I get for waving my own changes through in https://github.com/http4s/http4s/pull/6036 🙃
> Fix test name

- build.sbt
- project/Http4sPlugin.scala
Fixes https://github.com/http4s/http4s/issues/5231. Properly this time :)
> Use UTC for JS tests, remove tzdb test dep

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
Incorporates logic of first `evalMapChunk` block, that of looking and acting on the `GoAway` frames, onto the second block.
> Ember-Core: merge evalMap blocks in writeLoop

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
We use the Chunk methods `indexWhere` and `splitAt` to avoid creating a full list. It also avoids converting back to `Chunk`.
> Ember-Core microptimisation: avoid lists

- core/shared/src/main/scala/org/http4s/multipart/Multiparts.scala
- tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala
- tests/shared/src/test/scala/org/http4s/multipart/MultipartsSuite.scala
0.23 follow-up to https://github.com/http4s/http4s/pull/6169.
> Use `ce.std.Random` for `Multiparts`

- .github/workflows/ci.yml
- build.sbt
Testing out some ideas for https://github.com/http4s/http4s/issues/6239.
> Publish internal scalafixes

- blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
- client/shared/src/main/scala/org/http4s/client/DefaultClient.scala
- ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClient.scala
This fixes #3707.
Credit to @ChristopherDavenport and @rossabaker for their work/discussion in #3708.
> Drain response body in `DefaultClient#defaultOnError`

- client/shared/src/test/scala/org/http4s/client/middleware/RetrySuite.scala
That speeds up tests running a little.
> Parallelize some requests in `RetrySuite`

- docs/adopters.md
Added On Air Entertainment to the list of http4s adopters.
> Add On Air Entertainment to list of adopters.

- blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
- client/shared/src/main/scala/org/http4s/client/Client.scala
- client/shared/src/main/scala/org/http4s/client/middleware/Retry.scala
- ember-client/shared/src/test/scala/org/http4s/ember/client/internal/ClientHelpersSuite.scala
- ember-core/shared/src/main/scala/org/http4s/ember/core/Encoder.scala
- laws/src/main/scala/org/http4s/laws/EntityEncoderLaws.scala
- server/jvm/src/main/scala/org/http4s/server/middleware/GZip.scala
- server/jvm/src/test/scala/org/http4s/server/middleware/GZipSuite.scala
- server/shared/src/test/scala/org/http4s/server/middleware/HSTSSuite.scala
- tests/shared/src/test/scala/org/http4s/ResponderSpec.scala
That's a not required refactoring, but clean-ups a little our codebase.
> Promote using of `Headers#contains`

- project/Http4sPlugin.scala
> Update to Cats Effect 2.5.5

- build.sbt
- circe/src/test/scala/org/http4s/circe/CirceSensitiveDataEntityDecoderSpec.scala
- circe/src/test/scala/org/http4s/circe/CirceSuite.scala
- project/Http4sPlugin.scala
Finishes what https://github.com/http4s/http4s/pull/6398 started :)
> Update to circe 0.14.2

- docs/changelog.md
> Sketch out the 0.22.13 release note

- core/shared/src/main/scala/org/http4s/EntityDecoder.scala
- tests/shared/src/test/scala/org/http4s/ServerSentEventSpec.scala
All the pieces were already here, including a test, so not sure why this wasn't already exposed.
> Add `EntityDecoder[EventStream]`

- project/Http4sPlugin.scala
Not sure what the long-term plans are, but FTR it would be very easy to whip up an http4s-steward. See: https://github.com/armanbilge/diy-steward
> Update to Vault 3.2.1

- .github/workflows/steward.yml
Uses organization secrets and the [typelevel-steward](https://github.com/apps/typelevel-steward) app.
> Add a Scala Steward workflow

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
The last part of the `fromSocket` is just a loop to keep the "connection" open until the state in `stateRef` is closed. This was implemented with a Pull and streams, but it can be written as a one-line self-recursive loop.
> Ember-Core H2Server: replace pull with a recursive function

- server/shared/src/main/scala/org/http4s/server/middleware/Throttle.scala
The `takeToken` method uses the Ref.access method, which yields a setter. The setter yields `true` if it can set the value, or `false` if it could not, perhaps because of a concurrent write. In the latter case, the method has to re-try.
Currently, that recursion goes through emitting an Option and `flatMap`. This commit changes that to a direct recursive call.
> Throttle Server middleware: use recursion

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
Also, logic can be written as for comprehension.
> Ember-Core H2Server: extract method to send initial request

- ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
The use of `>>` and guard from Alternative type-class can be replaced with basic if-then-else Scala construct.
> Ember-Client: no Alternative

- .scala-steward.conf
> Ignore cats updates on main

- docs/changelog.md
> Release v0.22.14

- docs/docs/quickstart.md
- Added sample curl command in quickstart.md
> Add sample curl command to quickstart.md

- server/shared/src/main/scala/org/http4s/server/middleware/Caching.scala
This is a pretty minor thing, just some TF-guys would be happy.
> Relax `server.middleware.Caching` constraints

- core/shared/src/main/scala/org/http4s/Uri.scala
> Add `Host#fromIp4sHost` method

- docs/changelog.md
A few things were more behind-the-scenes.
> Release note tweaks for v0.23.13

- ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala
- Reduce some `Pipe` methods to extract the logic as functions on the effect `F`. 
- Replace some calls to `through` with calls to Stream methods.
- Fuse the `encodeFrame` with the `write` method into a `writeFrame` function, that avoids building a new finite in-memory stream for each frame.  
_Note:_ half the diff is whitespace.
> Ember-Server: WebSocketHelper rewrite / optimisation

- docs/docs/json.md
Basically the same issue as https://github.com/http4s/http4s.g8/issues/278, which leads to questions in Discord :) the combination of `Resource` and `IO` works just fine here.
> Don't use `Stream` in JSON client example

- docs/changelog.md
Not current with series/0.23, but looks current with 0.23.13.
> Release v1.0.0-M34

- .github/workflows/update-flake.yml
Completely my bad, the changes in https://github.com/http4s/http4s/pull/6498 needed the action to be updated to latest 😅
> Update to update-flake-lock v10

- docs/adopters.md
> Add Hireproof to adopters

- docs/docs/testing.md
> Remove references to `HttpService` in `testing.md`

- core/shared/src/main/scala/org/http4s/Uri.scala
- docs/docs/middleware.md
- tests/shared/src/test/scala/org/http4s/UriSpec.scala
> 0.23 -> main

- ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
- server/shared/src/main/scala/org/http4s/server/websocket/WebSocketBuilder2.scala
- server/shared/src/test/scala/org/http4s/server/websocket/WebSocketBuilderSuite.scala
> WebSocketBuilder2: make constructor public

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
- examples/ember/src/main/scala/com/example/http4s/ember/EmberServerH2Example.scala
causes errors for some implementations namely curl and chrome. 
Full Context Here
https://discord.com/channels/632277896739946517/632286375311573032/1004832231719710790
> Ember H2 - Do not respond to WindowUpdate with Ping

- docs/docs/client.md
Scala 2.11 is something from times when we were young and wild.
> Tweak client page

- client/shared/src/main/scala/org/http4s/client/middleware/GZip.scala
- client/shared/src/test/scala/org/http4s/client/middleware/GZipSuite.scala
- core/shared/src/main/scala/org/http4s/MediaType.scala
- server/js/src/main/scala/org/http4s/server/middleware/GZipPlatform.scala
- server/jvm/src/main/scala/org/http4s/server/middleware/GZipPlatform.scala
- server/shared/src/main/scala/org/http4s/server/middleware/GZip.scala
- server/shared/src/test/scala/org/http4s/server/middleware/GZipSuite.scala
> Cross-compile `GZip` middlewares for JS

- docs/changelog.md
Also merges in the release notes for v0.23.15.
> Release v1.0.0-M36

- .scala-steward.conf
> Ignore case-insensitive updates on main

- client/shared/src/main/scala/org/http4s/client/middleware/Logger.scala
- server/shared/src/main/scala/org/http4s/server/middleware/Logger.scala
> Default redactHeadersWhen to include any header with "token" #6186

- client/shared/src/main/scala/org/http4s/client/Client.scala
- client/shared/src/test/scala/org/http4s/client/ClientSyntaxSuite.scala
> Deprecate some methods in `Client`

- docs/changelog.md
Needs https://github.com/http4s/http4s/pull/6661 then off to the races 🚀
> Release 0.23.16

- .scala-steward.conf
> Ignore keypool updates on main

- build.sbt
Yeah, ok, not a great look 😅 teething pains until I figure out how to simplify some of this stuff.
> Setup linking paths for OpenSSL on macOS

- docs/contributing.md
As is the title. One of the code blocks is missing syntax highlight.
Thank you :)
> apply syntax highlighting to code blocks in `contributing.md`

- .scala-steward.conf
> Ignore epollcat updates on main

- docs/adopters.md
Added scala-k8s library to libraries in the adopters page.  
By the way, Thanks for the great work!
> Added scala k8s to libraries in the adopters page

- .github/workflows/ci.yml
- build.sbt
... because GHA just pulled the rug out from under our feet 😡 
- https://github.com/actions/runner-images/issues/6283
> Invoke brew via full path

- docs/versions.md
- project/Http4sSitePlugin.scala
> Promote Scala Native support on homepage

- .github/workflows/ci.yml
- build.sbt
- flake.lock
- flake.nix
> Provide a dev shell per Java version

- .github/workflows/ci.yml
- .github/workflows/update-flake.yml
- build.sbt
- flake.lock
- flake.nix
Following from https://github.com/http4s/http4s/pull/6724#issuecomment-1264555194.
> Use Nix for CI

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
Redo of #6523, in a series of small-step commits. 
__________ 
Small refactor of the code in the `fromSocket` method of the `H2Client` class, for creating and starting up an `H2Connection`. Splits long code of the `for` comprehension (in Resource) into a set of auxiliary methods in `F`. 
Each of the auxiliary methods operates at the level of the "F" effect, and they are only lift to a `Resource` for the purposes of background running.
Initialising the `H2Connection` object is done in a separate method. Instead of accessing the components from the variables in the for loop, the other auxiliary methods access them
through the `H2Connection` fields themselves.
> Ember-Core / H2Client /  fromSocket: split for comprehension.

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
Further to the procedural decomposition from #6613, we extract the processing of "Push Promises" as a separate procedure (function with `F[Unit]` return).
> Ember-Core H2Server: Extract "fulfill push promises" procedure.

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
- Extract method `checkLengthOf`, used in both branches.
- Extract method `attribute`, abstracted on the Message. 
- Extract method `trailWith`.
> H2Stream - changes and code rewrites.

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
Since `streamCreationLock.permit` is itself a functional value, it should not be a problem to share it from the connection.
> Ember-Core H2Server: get streamCreationLock from H2Connection

- ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
Add `withAdditionalSocketOptions` to `EmberServerBuilder`
> Add withAdditionalSocketOptions to EmberServerBuilder

- core/shared/src/main/scala/org/http4s/Status.scala
There is no more `scalastyle` 🥲
> Rm redundant comments in `Status`

- .scala-steward.conf
> Ignore munit updates on main

- docs/contributing.md
- docs/docs/quickstart.md
- Updates contributing guide to refer to Discord and correct SBT commands.
- Updates some text in the quickstart page to align with template update PRs:
- https://github.com/http4s/http4s.g8/pull/294
- https://github.com/http4s/http4s.g8/pull/293
> Cleanup quickstart and contributing pages

- client/shared/src/main/scala/org/http4s/client/middleware/GZip.scala
`Async` -> `MonadCancelThrow` + `Compression`
> Relax constraints for client gzip middleware

- docs/getting-help.md
- docs/landing.template.html
I want off Elon's ride, and nobody else wanted on.
> Close Twitter

- server/shared/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
Fixes #5240 
I have tested the fix on Windows and Linux, and it works.
> Fixes resourceServiceBuilder to work on Windows

- client/js/src/main/scala/org/http4s/client/NodeJSClientBuilder.scala
- flake.nix
Node.js 18 is the current LTS.
> Use Node.js 18 in devshell/CI

- docs/docs/integrations.md
Add http4s-netty to integrations page
> Add http4s-netty to integrations

- docs/docs/integrations.md
To promote it a little bit more in its early days ;)
> Add fs2-data to integrations docs page

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
Compact the calls to `traverse` and `parTraverse` on a single branch, the one with push enabled and any push promises in the response.
> Ember-Core: simplify logic for push promises.

- client-testkit/jvm/src/main/scala/org/http4s/client/testkit/scaffold/NettyTestServer.scala
Just an old one that never merged forward.
> Merge 0.22 -> 0.23

- flake.nix
Not a scintillating one, but I'm blocked without it.
> Merge 0.23 -> main

- core/src/main/scala/org/http4s/headers/User-Agent.scala
- core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
- core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
- core/src/main/scala/org/http4s/parser/SimpleHeaders.scala
- website/src/hugo/content/changelog.md
This was manually released.  Giving CI a chance.
> Post v0.21.34 cleanup

- core/src/main/scala/org/http4s/ProductIdOrComment.scala
- core/src/main/scala/org/http4s/headers/HeaderCompanion.scala
- core/src/main/scala/org/http4s/headers/Server.scala
- core/src/main/scala/org/http4s/headers/User-Agent.scala
- core/src/main/scala/org/http4s/internal/parsing/Rfc7230.scala
- docs/changelog.md
- flake.lock
- tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
Release notes and checking the manually-released fixes.
> Cleanups after v0.22.15

- docs/changelog.md
> Release v0.23.18

- docs/docs/client.md
- docs/docs/dsl.md
- docs/docs/json.md
Use Request(...) directly instead of using the DSL like Post(...), Get(...)
> Phase out the client DSL in the docs

- circe/src/test/scala/org/http4s/circe/CirceSensitiveDataEntityDecoderSpec.scala
- project/Http4sPlugin.scala
- project/build.sbt
Reverts http4s/http4s#6965
See https://github.com/circe/circe/issues/2089.
> Revert "Update circe-core, circe-generic, ... to 0.14.4 in series/0.23"

- docs/docs/quickstart.md
Follow-up to https://github.com/http4s/http4s/pull/6963#discussion_r1100664745. Adapted from similar documentation in Cats Effect.
https://github.com/typelevel/cats-effect#getting-started
> Clarify module choices in quickstart docs

- core/shared/src/main/scala/org/http4s/HttpDate.scala
- core/shared/src/main/scala/org/http4s/headers/Deprecation.scala
- core/shared/src/main/scala/org/http4s/headers/Sunset.scala
- laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
- tests/shared/src/test/scala/org/http4s/headers/DeprecationSuite.scala
- tests/shared/src/test/scala/org/http4s/headers/SunsetSuite.scala
For [Issue 6960](https://github.com/http4s/http4s/issues/6960)
> Add Deprecation and Sunset Headers

- .github/workflows/ci.yml
- build.sbt
Annoying that we don't get automated updates for these ...
Anyway, CI is completely busted. In case anybody noticed 😛
> Update nix and cachix actions

- ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala
> Handle EndOfStream error in Ember WebSocket server

- docs/docs/included-server-middleware.md
- docs/docs/middleware.md
- docs/docs/server-middleware.md
- server/shared/src/main/scala/org/http4s/server/middleware/HttpMethodOverrider.scala
- server/shared/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
Initial draft for https://github.com/http4s/http4s/issues/3652
I'm requesting general feedback on the format and will add comments in specific parts of the document.
> Middleware documentation

- core/shared/src/main/scala/org/http4s/MediaType.scala
> Add application/graphql media type

- docs/docs/error-handling.md
Some documentation for a beginner who wants to know how to get told about the exceptions his questionable code is throwing (*cough).
I did the best I could based off this hint, but I am by no means an expert.
https://discord.com/channels/632277896739946517/632286375311573032/1068542135739097209
> Document ErrorAction middleware

- server/shared/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
- server/shared/src/test/scala/org/http4s/server/middleware/BracketRequestResponseSuite.scala
> Fix semantic merge conflicts following #6305

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
_Note_ most line changes are whitespace.
> Ember-Core H2Connection: extract "WriteChunk" auxiliary function.

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
In the core of H2Stream extract a method "cancelWith" that,
when the stream is cancelled, completes all deferreds with 
a left (error case) of a CancellationException.
-------
> Ember-Core H2Stream - Extract "cancelWith" method.

- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
If an `F` procedure is tail-recursive, as in it has to end with a recursive call to the same method (in a flatMap), then we cannot use a for comprehension, since that rewrites it to a  `map` call and thus is no longer a tail-recursive call.
-------
> Ember-Core / H2Stream / sendData: for-comp is not tail-recursive.

- build.sbt
- client-testkit/shared/src/main/scala/org/http4s/client/testkit/WSTestClient.scala
- client-testkit/shared/src/test/scala/org/http4s/client/testkit/WSTestClientSuite.scala
- core/shared/src/main/scala/org/http4s/websocket/WebSocketContext.scala
- core/shared/src/main/scala/org/http4s/websocket/WebSocketFrame.scala
> add WSTestClient builder from HttpApp

- docs/changelog.md
> Fix release date

- core/shared/src/main/scala/org/http4s/headers/Upgrade-Insecure-Requests.scala
- core/shared/src/main/scala/org/http4s/headers/`Upgrade-Insecure-Requests`.scala
- laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
- tests/shared/src/test/scala/org/http4s/headers/UpgradeInsecureRequestsSuite.scala
Adds `Upgrade-Insecure-Requests` as part of #5010 .
Let me know what can be improved.
> Add `Upgrade-Insecure-Requests` header model

- docs/adopters.md
Simple Link and Company name update.
> Update Jack Henry - adopters.md

- ember-core/shared/src/main/scala/org/http4s/ember/core/Util.scala
This makes things a bit more concise.
> Use `ClockOps` in `Util#readWithTimeout`

- docs/changelog.md
The fix in the last patch didn't quite take. But this time, I think we got it 😇
> Release v0.23.21

- ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
- ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
This contains
* backport of https://github.com/http4s/http4s/pull/7167 to 0.23-series
* fixes https://github.com/http4s/http4s/issues/7108
* other things from https://github.com/http4s/http4s/pull/7170
> A bunch of tweaks to `ClientHelpers`' methods

- tests/shared/src/test/scala/org/http4s/DecodeSpec.scala
- tests/shared/src/test/scala/org/http4s/UriSuite.scala
❗ review only with hiding whitespaces applied
> Use `Assertions#assume` in tests

- docs/changelog.md
More Ember fixes in this release.
> Release v0.23.22

- docs/changelog.md
> Release v1.0.0-M40

- client/shared/src/main/scala/org/http4s/client/middleware/CookieJar.scala
Hi!
Addresses #6519. 
Happy to discuss if I didn't get the point - the feature would be pretty useful for me.
> expose cookies in the CookieJar middleware

- docs/changelog.md
Ember optimizations and bug fixes.
> Release v0.23.23

- core/shared/src/main/scala/org/http4s/headers/Content-Transfer-Encoding.scala
- core/shared/src/main/scala/org/http4s/multipart/Part.scala
- laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
- tests/shared/src/test/scala/org/http4s/headers/ContentTransferEncodingSuite.scala
fixes #6793
I had a shot at modeling the header. 
As this is a first for me feedback is very welcome. Especially I was not sure whether to model it using CIString or not (RFC states it is case insensitive).
> Model Content-Transfer-Encoding header

- core/shared/src/main/scala/org/http4s/Message.scala
- core/shared/src/main/scala/org/http4s/internal/CurlConverter.scala
- core/shared/src/main/scala/org/http4s/internal/PosixQuoting.scala
- tests/shared/src/test/scala/org/http4s/MessageSuite.scala
Extends initial implementation in #3113 with a quoted body
> Add asCurlWithBody

- docs/changelog.md
We didn't land all the open PRs (sorry!), but there's a lot of good changes in here that have accumulated for months.
> Release v0.23.24

- docs/changelog.md
> Add note about cats-parse to 0.23.24 changelog

- docs/code-of-conduct.md
I resigned my moderator positions in Typelevel and affiliates a long time ago, and this listing fell through the cracks.
> Ross is not a moderator

- docs/docs/error-handling.md
> Push error handling docs through mdoc

- .github/release.yml
`release.yml` is a little bit outdated, some modules have been moved to separate repos.
> Refactor `release.yml`

- core/shared/src/main/scala/org/http4s/internal/CharPredicate.scala
> remove unused deprecated method asMaskBased

- client/shared/src/main/scala/org/http4s/client/dsl/io.scala
- docs/changelog.md
- ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
- ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
- ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
- flake.lock
No conflicts, but I haven't tried to build it.
> Merge 0.23.26 -> main

- client/shared/src/main/scala/org/http4s/client/middleware/History.scala
- client/shared/src/test/scala/org/http4s/client/middleware/HistorySuite.scala
> #6521 History client middleware

- docs/changelog.md
> Prepare v0.23.27

- docs/versions.md
Some minor up-to-date updates.
> Tweak the 'versions' page

- core/js/src/main/scala/org/http4s/nodejs/ServerResponse.scala
> Minor optimization in ServerResponse

- docs/changelog.md
There's a lot pending and we'll do another one soon, but we're long past due.
> Prepare release v0.23.28

- RELEASING.md
Polished up some notes from our call today working through the http4s release. Do these make sense?
> notes on how to put together a v0.23.xx release

- docs/changelog.md
It'd be ideal to make the forty-second release milestone an ultimate one.
> Draft the `v1.0.0-M42` release notes

- .scala-steward.conf
> Ignore http4s-scalafix-internal updates

- .github/workflows/ci.yml
- .scala-steward.conf
- client/shared/src/test/scala/org/http4s/client/middleware/CookieJarSuite.scala
- core/shared/src/main/scala-2.13/org/http4s/LiteralSyntaxMacros.scala
- core/shared/src/main/scala/org/http4s/EntityTag.scala
- core/shared/src/main/scala/org/http4s/headers/Forwarded.scala
- core/shared/src/main/scala/org/http4s/headers/Link.scala
- core/shared/src/main/scala/org/http4s/internal/parsing/Rfc3986.scala
- docs/changelog.md
- ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
- ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala
- ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala
- flake.lock
- project/Http4sPlugin.scala
- project/build.properties
- project/plugins.sbt
- scalafix-internal/rules/src/main/scala-2/fix/UseLiteralsSyntax.scala
- server/shared/src/main/scala/org/http4s/server/middleware/Throttle.scala
- server/shared/src/test/scala/org/http4s/server/middleware/HttpsRedirectSuite.scala
- tests/shared/src/test/scala/org/http4s/LiteralSyntaxMacrosSuite.scala
the only conflicts I had to resolve were 
- the changelog
- the scala versions in `project/HttpPlugin.scala`
but then I had to push a fix to remove an unused import from a test suite that hasn't been touched in years. I'm not sure what has changed there?
> merge v0.23.29 -> main

- RELEASING.md
I missed this part in the process yesterday
> update 1.0.0-Mxx releasing guide re ancillary releases

- docs/docs/dsl.md
- state the support of flag query parameters
- add a short example
- add a note regarding the syntax
- fixes #7489
> Add documenation for FlagQueryParamMatcher.

- docs/docs/multipart.md
> Simplify form example

- docs/changelog.md
I tried to use `[ci-skip]` but it didn't work
> Prep for v1.0.0-M44: update changelog

- docs/docs/testing.md
Easier to read, more in-line with the rest of the docs.
> Update 'his/her' to 'their'

- .github/workflows/ci.yml
- build.sbt
The value we get from this is not worth the risk.
> Remove Cachix

- flake.nix
> Build with the current Node.js in Nix
